### ISSUE TITLE
Runtime upgrade/extrinsic scheduling

### ISSUE THREAD

**Issue by drewstone** [paritytech/subport#1]
It seems useful for future networks that developers are able to schedule the process of upgrades that occur. At the moment it isn't clear what ordering runtime upgrade are processed (maybe they follow the ordering of their position in the `construct_runtime!` call and maybe not).

Having a way to schedule which modules will run their on_runtime_upgrade hook sounds nice to have especially given it would allow chains, like Edgeware, to catch up to substrate master without jumping through so many hoops.

**Comment by joepetrowski** [comment]
We do have a scheduler incoming, will this help?
https://github.com/paritytech/substrate/pull/5412

**Comment by drewstone** [comment]
At first glance I do not think so @joepetrowski. I'm talking specifically about ordering `on_runtime_upgrade` calls once a new upgrade is pushed. Say if I want the `on_runtime_upgrade` in the balances module to explicitly go before the one in the system module or any others.

**Comment by joepetrowski** [comment]
Ah, I see what you mean. Yeah, `on_runtime_upgrade` executes in the order of pallets declared in `construct_runtime`. If you wanted to execute something out of order you may have to do two separate upgrades.

**Comment by NukeManDan** [comment]
@drewstone is this still an issue? If so, please reopen this 🙏🏼

As far as I can tell, there is no plans for such an integration, but if you wanted to bring this up on https://github.com/paritytech/substrate , the core dev team may be able to comment on alternatives and may even try to make this possible.
