### ISSUE TITLE
Migrating existing chain into a parachain to connect with Polkadot

### ISSUE THREAD

**Issue by ultra-pool** [paritytech/subport#100]
Im wanting to bring a project over to DOT. But the doc's are lacking about how to bring a chain onto DOT. Needing a chain like DOT staking and prefunded wallet for swamping over current users of the project. Is there any doc's on how to do this? Any stuff im finding is for the testnet which has wallets prefunded. Thank you.

**Comment by ultra-pool** [comment]
Thank you @bkchr I hope ill be able to get my project over here soon.

**Comment by ultra-pool** [comment]
@bkchr Can you reach out to any Dev's to help. Thank you. I would like to move on with this project.

**Comment by jimmychu0807** [comment]
Hi @ultra-pool, I don't think there is a straight answer to this, and will depend on what features your chain is currently offering. When you say bringing over to DOT, do you mean you will not have your own native chain token but using DOT instead on your chain, or you want to use [Substrate framework](https://substrate.dev) to build your chain? Would you need to connect your chain to the broader [Polkadot network](https://polkadot.network/), or it will be a standalone chain?

On one hand, you could explore what Substrate offer technically by porting some of your current key features to it. On the other hand, if you are thinking about how to port the your existing production chain over to Substrate and how to perform the migration, I can connect you to our ecosystem manager and he will be able to give you more details and what to look out for. [Contact me in Element](https://app.element.io/#/user/@jimmychu0807:matrix.parity.io).

**Comment by ultra-pool** [comment]
I would like to have the project on its own chain so others can build tokens and dapps on our chain. Using substrate as the main core. It offers everything i need for our project.

One of the main things i would need a main account from the start to be able to swap our current communities coins. 

@jimmychu0807

**Comment by jimmychu0807** [comment]
This issue is being taken care of in another channel. Closing this.
