### ISSUE TITLE
Why blocks are not finalized in instant-seal mode?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#102]
Recently I have implemented the Instant-Seal feature  https://substrate.dev/recipes/kitchen-node.html#instant-seal-consensus in my application. Here is code https://github.com/ayushmishra2005/substrate-barcode-scanner/blob/master/node/src/service.rs It is working fine as expected. Block is getting created when a new transaction comes in. 

However, block finalization process has been stopped. Please see the below screenshot. 5 blocks are created but none has been finalized. 

![image](https://user-images.githubusercontent.com/1575561/109138471-680af580-7780-11eb-943a-39f6d6a3dfa2.png)

If I purge chain and start node without instant-sealing, the finalization process starts along with empty blocks. 

Can someone please help me, what I am missing in instant-seal mode?

**Comment by ayushmishra2005** [comment]
@shawntabrizi Could you please help me with this issue?

**Comment by al3mart** [comment]
Hey, first of all I had no access to your repo, so I could not check how did you implemented it.

But, at first glance I would recommend to have a look at the RPC part https://substrate.dev/recipes/custom-rpc.html#the-manual-seal-rpc .
Also, reading through the recipe I felt that all the time talks about creation of blocks, not finalization, I can be wrong here, but was just my feeling, would like some double check on this.

**Comment by ayushmishra2005** [comment]
@al3mart I have updated the link. It should be accessible now. Could you please check?

**Comment by al3mart** [comment]
Any luck with that RPC ? @ayushmishra2005  :)

**Comment by ayushmishra2005** [comment]
@al3mart I went through https://substrate.dev/recipes/custom-rpc.html#the-manual-seal-rpc. But it looks like, with manual-seal, I have to hit RPC to finalize block, which I really don't want. 
When I execute my application without `instant-seal` mode:
`./target/release/node-template --dev`
Everything works fine. Block creation, finalization etc..

I want same behavior when I run with `instant-seal` mode without creating empty blocks. Empty blocks have stopped creating. But Finalization is not working.

**Comment by Gauthamastro** [comment]
> @al3mart I went through https://substrate.dev/recipes/custom-rpc.html#the-manual-seal-rpc. But it looks like, with manual-seal, I have to hit RPC to finalize block, which I really don't want.
> When I execute my application without `instant-seal` mode:
> `./target/release/node-template --dev`
> Everything works fine. Block creation, finalization etc..
> 
> I want same behavior when I run with `instant-seal` mode without creating empty blocks. Empty blocks have stopped creating. But Finalization is not working.

@ayushmishra2005 This might help https://www.crowdcast.io/e/substrate-seminar/13

**Comment by ayushmishra2005** [comment]
Thanks @Gauthamastro I will take a look

**Comment by ayushmishra2005** [comment]
> > @al3mart I went through https://substrate.dev/recipes/custom-rpc.html#the-manual-seal-rpc. But it looks like, with manual-seal, I have to hit RPC to finalize block, which I really don't want.
> > When I execute my application without `instant-seal` mode:
> > `./target/release/node-template --dev`
> > Everything works fine. Block creation, finalization etc..
> > I want same behavior when I run with `instant-seal` mode without creating empty blocks. Empty blocks have stopped creating. But Finalization is not working.
> 
> @ayushmishra2005 This might help https://www.crowdcast.io/e/substrate-seminar/13

@al3mart @Gauthamastro In this video, @jimmychu0807 talked about this pull request https://github.com/paritytech/substrate/pull/6951. But this PR was never merged.  I don't see heartbeat and cooldown feature in the current Substrate implementation https://github.com/paritytech/substrate/blob/master/client/consensus/manual-seal/src/lib.rs

Currently, a hardcoded value false is set in `finalize` param. 

https://github.com/paritytech/substrate/blob/master/client/consensus/manual-seal/src/lib.rs#L244

**Comment by al3mart** [comment]
You could fork the pallet and set the `finalize` param to true and use your own pallet. That should get the finalization going

**Comment by ayushmishra2005** [comment]
Thanks @al3mart . It works like a charm.

**Comment by karanchopraa** [comment]
@ayushmishra2005 could u plz brief me how u resolve this issue, as i unable to understand it properly by the above chat.

**Comment by ayushmishra2005** [comment]
@karanchopraa You can copy this https://github.com/ayushmishra2005/substrate-barcode-scanner/tree/master/client/consensus/manual-seal. You may face compilation issue because of Substrate version. But it would fix this issue.
