### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/subport#103]
<img width="1280" alt="Screen Shot 2021-02-25 at 11 51 56 AM" src="https://user-images.githubusercontent.com/62865359/109187420-e6a36b00-775f-11eb-976e-eb39a45bd0cf.png">
I'm currently following this tutorial: 
 https://www.shawntabrizi.com/substrate-collectables-workshop/#/0/running-a-custom-node

I'm getting the error above after entering this command : 
./scripts/build.sh

**Comment by NukeManDan** [comment]
@J-Cook-jr that tutorial is quite dated, and you are building substrate v1, we are now on v3 😉 
Instead, please try getting a node built from the tutorials here: https://substrate.dev/tutorials/ and build on top of the template node to follow along with that. 

If you have further issues, please reopen this and we can address it after you have given it a good go on a working base node template v3.

**Comment by J-Cook-jr** [comment]
Thanks Dan, I'm new to developing with substrate. I did successfully build
and launch the v3 node by following along with the substrate node-template
repo. I also connected the front end template to the node. I'm having a
great experience so far experimenting with substrate and I greatly
appreciate the resources.

I'm trying to specifically build a NFT marketplace. Do you know of any up
to date substrate tutorials I can follow for building an NFT platform?
Thanks in advance!
