### ISSUE TITLE
Question: How to subscribe to Babe slot notifications from RPC?

### ISSUE THREAD

**Issue by rg3l3dr** [paritytech/subport#109]
`sc_consensus_babe::BabeWorker` exposes `slot_notification_stream()`. We would like to hook this into the RPC, such that a client can subscribe to slot notifications via web sockets. It is not clear how, or if it is even possible, to do this, since `BabeWorker` is only returned from `start_babe()`, which appears to require that background tasks (which include the RPC) have already been spawned; whereas it would seem that `slot_notification_stream()` would need to somehow have already been passed to `rpc_extension_builder` first. 

For context, we are exploring whether it is possible to use Babe as a template for a proof-of-space consensus blockchain we are preparing to implement in Substrate. Our protocol, Subspace, is also based on Ourobouros Praos, but instead of evaluating a VRF at each slot, we evaluate a disk-based "plot" for a valid proof-of-space. This requires a separation between the client and farmer which would then communicate over the RPC, similar to how geth and ethhash are implemented. 

While we could simply implement a parallel timing loop on the farmer, this is undesirable, as we also need the epoch data and to be assured that we are in-fact on the head of the longest-chain, which would require maintaining a parallel light-client implementations within the farmer. 

Additionally, we need to implement a return path, such that the the farmer would be able to return a solution result over the RPC after each notification (conceptually similar to VRF evaluation result). However, it is also not clear how to do this in the current implementation of Babe. 

Thanks!

**Comment by rg3l3dr** [comment]
We have implemented a work around by running a second Web Socket Server within the Babe worker, that exposes `notify_slot` as a subscription and awaits `proof_requests` from the farmer. This RPC based evaluation of the plot replaces the VRF evaluation used by default in Babe. 

Here is the [RPC code](https://github.com/subspace/substrate-stencil/blob/smoke-test-built-in-rpc/client/consensus/babe/src/rpc_server.rs) and here is where it hooks into [`claim_slot`](https://github.com/subspace/substrate-stencil/blob/15db483f5336e4b556cec892e3bb4384042736f6/client/consensus/babe/src/lib.rs#L530-L557).

If anyone has any ideas for a more canonical solution, that leverages the way `slot_notification_stream` works, we would love to hear it.

Thanks!

**Comment by bkchr** [comment]
So I tried the following:

```
diff --git a/bin/node/cli/src/service.rs b/bin/node/cli/src/service.rs
index 80561a78a..fd5d57bb6 100644
--- a/bin/node/cli/src/service.rs
+++ b/bin/node/cli/src/service.rs
@@ -234,24 +234,6 @@ pub fn new_full_base(
        let telemetry_span = TelemetrySpan::new();
        let _telemetry_span_entered = telemetry_span.enter();
 
-       let (_rpc_handlers, telemetry_connection_notifier) = sc_service::spawn_tasks(
-               sc_service::SpawnTasksParams {
-                       config,
-                       backend: backend.clone(),
-                       client: client.clone(),
-                       keystore: keystore_container.sync_keystore(),
-                       network: network.clone(),
-                       rpc_extensions_builder: Box::new(rpc_extensions_builder),
-                       transaction_pool: transaction_pool.clone(),
-                       task_manager: &mut task_manager,
-                       on_demand: None,
-                       remote_blockchain: None,
-                       network_status_sinks: network_status_sinks.clone(),
-                       system_rpc_tx,
-                       telemetry_span: Some(telemetry_span.clone()),
-               },
-       )?;
-
        let (block_import, grandpa_link, babe_link) = import_setup;
 
        (with_startup_data)(&block_import, &babe_link);
@@ -285,6 +267,24 @@ pub fn new_full_base(
                task_manager.spawn_essential_handle().spawn_blocking("babe-proposer", babe);
        }
 
+       let (_rpc_handlers, telemetry_connection_notifier) = sc_service::spawn_tasks(
+               sc_service::SpawnTasksParams {
+                       config,
+                       backend: backend.clone(),
+                       client: client.clone(),
+                       keystore: keystore_container.sync_keystore(),
+                       network: network.clone(),
+                       rpc_extensions_builder: Box::new(rpc_extensions_builder),
+                       transaction_pool: transaction_pool.clone(),
+                       task_manager: &mut task_manager,
+                       on_demand: None,
+                       remote_blockchain: None,
+                       network_status_sinks: network_status_sinks.clone(),
+                       system_rpc_tx,
+                       telemetry_span: Some(telemetry_span.clone()),
+               },
+       )?;
+
        // Spawn authority discovery module.
        if role.is_authority() {
                let authority_discovery_role = sc_authority_discovery::Role::PublishAndDiscover(
```

And this compiles fine. Not sure why you think that the RPC needs to be build before BABE?

**Comment by nazar-pc** [comment]
We were starting with https://github.com/kaichaosun/substrate-stencil, but now I see the order is not required, which makes sense and will work this way.
I guess we were looking too narrowly before, thanks!
