### ISSUE TITLE
problem running node template provided docker.sh. LLVM missing

### ISSUE THREAD

**Issue by billtlee** [paritytech/subport#113]
Hi,

I just started playing with Substrate and saw in the read me that I can run it in docker.  I am following this tutorial: https://substrate.dev/docs/en/tutorials/create-your-first-substrate-chain/ and cloned the repo to my mac.  Then I ran ./scripts/docker_run.sh.  Towards the end, I got the following errors:

sccache: Compiler killed by signal 9
error: could not compile `wasmtime-environ`.

Caused by:
  process didn't exit successfully: `sccache rustc --crate-name wasmtime_environ --edition=2018 /var/www/node-template/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-environ-0.19.0/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 -Cembed-bitcode=no --cfg 'feature="parallel-compilation"' --cfg 'feature="rayon"' -C metadata=45fd8ca1ee3ddbe6 -C extra-filename=-45fd8ca1ee3ddbe6 --out-dir /var/www/node-template/target/release/deps -L dependency=/var/www/node-template/target/release/deps --extern anyhow=/var/www/node-template/target/release/deps/libanyhow-cd4125385d1eabff.rmeta --extern base64=/var/www/node-template/target/release/deps/libbase64-23616c0f34aab9ce.rmeta --extern bincode=/var/www/node-template/target/release/deps/libbincode-91b014b4ae57ebdb.rmeta --extern cfg_if=/var/www/node-template/target/release/deps/libcfg_if-f1d9cca014e2299a.rmeta --extern cranelift_codegen=/var/www/node-template/target/release/deps/libcranelift_codegen-1cfea581dab0cda6.rmeta --extern cranelift_entity=/var/www/node-template/target/release/deps/libcranelift_entity-e39ae3947299cbeb.rmeta --extern cranelift_frontend=/var/www/node-template/target/release/deps/libcranelift_frontend-bad74fb87d31c680.rmeta --extern cranelift_wasm=/var/www/node-template/target/release/deps/libcranelift_wasm-34b34de56ba5f34b.rmeta --extern directories=/var/www/node-template/target/release/deps/libdirectories-5fbb7c6822fcc8d8.rmeta --extern errno=/var/www/node-template/target/release/deps/liberrno-8ffee3b16677ecc7.rmeta --extern file_per_thread_logger=/var/www/node-template/target/release/deps/libfile_per_thread_logger-eba33bfeb73cc68c.rmeta --extern indexmap=/var/www/node-template/target/release/deps/libindexmap-7a2d724823396830.rmeta --extern libc=/var/www/node-template/target/release/deps/liblibc-bd1988fe34bc15a3.rmeta --extern log=/var/www/node-template/target/release/deps/liblog-9d7469c2b2154aa8.rmeta --extern more_asserts=/var/www/node-template/target/release/deps/libmore_asserts-7a38f0d70f2531ae.rmeta --extern rayon=/var/www/node-template/target/release/deps/librayon-a5a15c81960eff18.rmeta --extern serde=/var/www/node-template/target/release/deps/libserde-c25df2ef907f6b24.rmeta --extern sha2=/var/www/node-template/target/release/deps/libsha2-1fc6048a4bb6e519.rmeta --extern thiserror=/var/www/node-template/target/release/deps/libthiserror-8cd09edb0721a4a8.rmeta --extern toml=/var/www/node-template/target/release/deps/libtoml-b00dfe9eb27e13f7.rmeta --extern wasmparser=/var/www/node-template/target/release/deps/libwasmparser-76407b521907c109.rmeta --extern zstd=/var/www/node-template/target/release/deps/libzstd-e7e0d4b76c74f0ce.rmeta --cap-lints allow -L native=/var/www/node-template/target/release/build/zstd-sys-40e50ebc67268a67/out` (exit code: 254)
warning: build failed, waiting for other jobs to finish...
error: build failed

Does anyone know what might be causing this and how to solve it?  Thanks!

**Comment by billtlee** [comment]
Shouldn't the dependencies be in the docker image?  Do I need to install the dependencies on the host or the image?  I am a bit confused.  I am under the assumption that I don't need to install the dependencies on the host if running with Docker.  Isn't that the whole point of using docker?

**Comment by NukeManDan** [comment]
@billtlee I am inquiring as to if our base image is mos configured somehow, the shell script just wraps a docker compose command for the dockerfile in the root dir of the template. In the meantime, possibly try this with an alpine or Ubuntu base image and install on top of it as the devhub instructs.

**Comment by billtlee** [comment]
@NukeManDan Thanks for getting back!  I have tried a lot of things to get it up and running but still no luck.  The latest is, I have added a Dockerfile:

FROM rust:latest as builder
RUN apt-get update && apt-get install -y cmake pkg-config libssl-dev git build-essential clang libclang-dev curl
RUN rustup default stable
RUN rustup update nightly
RUN rustup update stable
RUN rustup target add wasm32-unknown-unknown --toolchain nightly
WORKDIR /var/www/node-template
COPY . .
RUN cargo build --release

FROM debian:buster-slim
WORKDIR /var/www/node-template
COPY --from=builder /var/www/node-template .
CMD ["./target/release/node-template", "--dev"]

And modified docker-compose.yml to:

services:
  dev:
    build: .
    container_name: node-template
    working_dir: /var/www/node-template
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/node-template/.cargo
    volumes:
      - .:/var/www/node-template

But it's still not building.  I am at a lost and am just about to give up...

**Comment by billtlee** [comment]
Here is the error I got:

The following warnings were emitted during compilation:

warning: couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
warning: set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
warning: c++: fatal error: Killed signal terminated program cc1plus
warning: compilation terminated.

error: failed to run custom build command for `librocksdb-sys v6.11.4`

Caused by:
  process didn't exit successfully: `/var/www/node-template/target/release/build/librocksdb-sys-1e8e90f42a461442/build-script-build` (exit code: 1)
  --- stdout
  cargo:warning=couldn't execute `llvm-config --prefix` (error: No such file or directory (os error 2))
  cargo:warning=set the LLVM_CONFIG_PATH environment variable to the full path to a valid `llvm-config` executable (including the executable itself)
  cargo:rerun-if-changed=rocksdb/
  TARGET = Some("x86_64-unknown-linux-gnu")
  OPT_LEVEL = Some("3")
  HOST = Some("x86_64-unknown-linux-gnu")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  DEBUG = Some("false")
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  CXX_x86_64-unknown-linux-gnu = None
  CXX_x86_64_unknown_linux_gnu = None
  HOST_CXX = None
  CXX = None
  CXXFLAGS_x86_64-unknown-linux-gnu = None
  CXXFLAGS_x86_64_unknown_linux_gnu = None
  HOST_CXXFLAGS = None
  CXXFLAGS = None
  CRATE_CC_NO_DEFAULTS = None
  CARGO_CFG_TARGET_FEATURE = Some("fxsr,sse,sse2")
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/cache/cache.o" "-c" "rocksdb/cache/cache.cc"
  exit code: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/cache/clock_cache.o" "-c" "rocksdb/cache/clock_cache.cc"
  exit code: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/cache/lru_cache.o" "-c" "rocksdb/cache/lru_cache.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/cache/sharded_cache.o" "-c" "rocksdb/cache/sharded_cache.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/arena_wrapped_db_iter.o" "-c" "rocksdb/db/arena_wrapped_db_iter.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/blob/blob_file_addition.o" "-c" "rocksdb/db/blob/blob_file_addition.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/blob/blob_file_garbage.o" "-c" "rocksdb/db/blob/blob_file_garbage.cc"
  exit code: 0
  exit code: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/blob/blob_file_meta.o" "-c" "rocksdb/db/blob/blob_file_meta.cc"
  exit code: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/blob/blob_log_format.o" "-c" "rocksdb/db/blob/blob_log_format.cc"
  exit code: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/blob/blob_log_reader.o" "-c" "rocksdb/db/blob/blob_log_reader.cc"
  exit code: 0
  exit code: 0
  exit code: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/blob/blob_log_writer.o" "-c" "rocksdb/db/blob/blob_log_writer.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/builder.o" "-c" "rocksdb/db/builder.cc"
  exit code: 0
  exit code: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/c.o" "-c" "rocksdb/db/c.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/column_family.o" "-c" "rocksdb/db/column_family.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/compacted_db_impl.o" "-c" "rocksdb/db/compacted_db_impl.cc"
  exit code: 0
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/compaction/compaction.o" "-c" "rocksdb/db/compaction/compaction.cc"
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/compaction/compaction_iterator.o" "-c" "rocksdb/db/compaction/compaction_iterator.cc"
  cargo:warning=c++: fatal error: Killed signal terminated program cc1plus
  cargo:warning=compilation terminated.
  exit code: 1
  running: "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/compaction/compaction_job.o" "-c" "rocksdb/db/compaction/compaction_job.cc"
  exit code: 0
  exit code: 0
  exit code: 0
  exit code: 0
  exit code: 0

  --- stderr
  error: 'rustfmt' is not installed for the toolchain 'stable-x86_64-unknown-linux-gnu'
  To install, run `rustup component add rustfmt`
  Failed to run rustfmt: Internal rustfmt error (non-fatal, continuing)


  error occurred: Command "c++" "-O3" "-ffunction-sections" "-fdata-sections" "-fPIC" "-m64" "-I" "rocksdb/include/" "-I" "rocksdb/" "-I" "rocksdb/third-party/gtest-1.8.1/fused-src/" "-I" "snappy/" "-I" "." "-Wall" "-Wextra" "-std=c++11" "-Wno-unused-parameter" "-msse2" "-msse4.1" "-msse4.2" "-mpclmul" "-DSNAPPY=1" "-DNDEBUG=1" "-DHAVE_SSE42=1" "-DHAVE_PCLMUL=1" "-DOS_LINUX=1" "-DROCKSDB_PLATFORM_POSIX=1" "-DROCKSDB_LIB_IO_POSIX=1" "-o" "/var/www/node-template/target/release/build/librocksdb-sys-9e55a52787789a16/out/rocksdb/db/column_family.o" "-c" "rocksdb/db/column_family.cc" with args "c++" did not execute successfully (status code exit code: 1).


warning: build failed, waiting for other jobs to finish...
error: build failed
ERROR: Service 'dev' failed to build : The command '/bin/sh -c cargo build --release' returned a non-zero code: 101

**Comment by billtlee** [comment]
Is it possible to have an already compiled docker image of the substrate-template?

**Comment by NukeManDan** [comment]
@billtlee sorry for the delay in reply - have you seen the https://playground.substrate.dev/ ?

Playground templates can be started on a local machine (`docker` must be available). [Here is how](https://github.com/paritytech/substrate-playground/#cli)

The precompiled node template image is [built here](https://github.com/paritytech/substrate-playground/blob/ba53a20ad6e4bf9d6b29019de6fce94785fc4d94/.github/workflows/event-template-updated.yml) and [pushed here](https://github.com/substrate-developer-hub/substrate-node-template/blob/master/.github/workflows/build-push-template.yml)

Also if you are using an M1 ARM chip Macbook - you likely will run into issues. See more on help [here](https://vikiival.medium.com/run-substrate-on-apple-m1-a2699743fae8)

Please reopen / open a new issue if you run into further problems here 🙏🏼
