### ISSUE TITLE
Contract Pallet

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/subport#116]
I'm currently working on the "Add a pallet" tutorial on the substrate website using the node-template. I've successfully imported the contracts pallet  crate. However, after following the instructions for adding the contracts-pallet to the runtime and running "SKIP_WASM_BUILD=1 cargo check -p node-template-runtime", I get errors. Please help. 

Thanks!

<img width="1280" alt="Screen Shot 2021-03-03 at 12 51 59 PM" src="https://user-images.githubusercontent.com/62865359/109849411-59f52300-7c1f-11eb-9896-360222f5f88c.png">

**Comment by J-Cook-jr** [comment]
When you say fall back to v2.0.1. Are you referring to the node-template or the contracts-pallet?

**Comment by NukeManDan** [comment]
To clarify, you need to be following [this tutorial](https://substrate.dev/docs/en/tutorials/add-contracts-pallet/) to add contracts, not the standard add a pallet. Note that using substrate v3 might cause problems, [this PR](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/875) guides you to use v2.0.1 to avoid issues

**Comment by J-Cook-jr** [comment]
1. Thanks @ NukeManDan. Just for my own Clarity, I should be using v2.0.1 node-template?

2.If this is the case, then what is v3.0.0 and why does the substrate dev website advise users to clone v3.0.0?

3. I noticed there is also a "Node" repo as well... Is that a good place to get the updated code? 
4. 
Please clarify, this would make my journey a lot smoother. I've been recking my brain for the past few days. Thanks!

**Comment by J-Cook-jr** [comment]
Also, I am using v3.0.0. Is there a way to downgrade back to v2.0.1 or do I just start over by cloning  v2.0.1?

**Comment by NukeManDan** [comment]
I would start fresh for this case, as it is easier for just starting out with tutorials :) 

v3 of substrate tutorials are in the works, but you don't need to wait :grin:

**Comment by J-Cook-jr** [comment]
One more question.... Where do I reference v2.0.1 code?  I switched the repos branch to v2.0.1, but when I checked the cargo.toml file I saw all dependencies were labeled v2.0.0

**Comment by J-Cook-jr** [comment]
I found the solution, Thanks!
