### ISSUE TITLE
When use sp_core::Pair in custom pallet, building program will get the error: no `Pair` in the root

### ISSUE THREAD

**Issue by zhiquan911** [paritytech/subport#117]
In my pallet, I use `ed22519` crypto to verify signature, like this code:

```rust
use sp_core::{Pair, ed25519};

let flag = ed25519::Pair::verify_weak(&sig, &msg, &pk);

```

I have tested it in `tests.rs` successfully. But when I cargo build node, I got like this:

```log

  error[E0432]: unresolved import `sp_core::Pair`
     |
  30 | use sp_core::{Pair, ed25519};
     |               ^^^^ no `Pair` in the root

  error[E0433]: failed to resolve: could not find `Pair` in `ed25519`
      |
  252 |             let flag = ed25519::Pair::verify_weak(&sig, &msg, &pk);
      |                                 ^^^^ could not find `Pair` in `ed25519`


```

**Comment by bkchr** [comment]
Hint: `Pair` is only available on `std`. There is the `Verify` trait when you just want to verify a signature.

**Comment by zhiquan911** [comment]
> Hint: `Pair` is only available on `std`. There is the `Verify` trait when you just want to verify a signature.

How do I use `Verify` trait? Are there any examples to see?

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/blob/master/primitives/runtime/src/generic/unchecked_extrinsic.rs#L132

Not sure what you want to see. This is relative easy.

**Comment by zhiquan911** [comment]
@bkchr Thank you very much. I have solved the problem.

**Comment by salman01zp** [comment]
@zhiquan911  how did you resolve this?

**Comment by bkchr** [comment]
@salman01zp you can not use `Pair` from the runtime. You need to use `Verify` trait for example.
