### ISSUE TITLE
how start a private network

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/subport#12]
i use alpaha4, but when i use the command"build-spec --chain local > customSpec.json",  the json file is different from alpha3.  how can i do for start my private network(many node)

**Comment by JoshOrndorff** [comment]
Can you say what is different about your chainspec from your expectations?

Did you know we have a tutorial for starting a private network with alpha.6? https://www.substrate.io/tutorials/start-a-private-network/v2.0.0-alpha.6

**Comment by danforbes** [comment]
Closing due to lack of response.
