### ISSUE TITLE
Balance Stays Zero

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/subport#120]
```await api.query.system.account('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY')``` returns ```{
  nonce: '0',
  consumers: '0',
  providers: '0',
  data: { free: '0', reserved: '0', miscFrozen: '0', feeFrozen: '0' }
}```  and  ```await api.query.system.account('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY')```
returns ```{ free: '0', reserved: '0', miscFrozen: '0', feeFrozen: '0' }``` with the following genesis.json 
```
    "palletBalances": {
      "balances": [
        [
          "5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY",
          1152921504606846976
        ],
```
using the substrate node template ```3.0.0```
I've tried to use the balances pallet instead of the system pallet to store the balances but still
The balance stays zero with the following as well
```
    const keyring = new Keyring({ type: 'sr25519' });
    const alice = keyring.addFromUri('//Alice');
    console.log(alice.toJson());
    const bob = keyring.addFromUri('//Bob');
    const aliceBalance = await api.query.balances.account(alice);
    console.log(aliceBalance.toHuman());
    const bobBalance = await api.query.balances.account(bob);
    console.log(bobBalance.toHuman());
    await api.tx.balances.forceTransfer(alice, 1, bob);;
    const aliceBalance2 = await api.query.balances.account(alice);
    console.log(aliceBalance2.toHuman());
    const bobBalance2 = await api.query.balances.account(bobBalance);
    console.log(bobBalance2.toHuman());
```

**Comment by noahsalvadordenjo** [comment]
Just a guess, but if i replace it with 32byte i have the following error
```UnhandledPromiseRejectionWarning: Error: FATAL: Unable to initialize the API: createType(AccountId):: Cannot construct unknown type 32byte``` So what should AccountId be?

**Comment by kianenigma** [comment]
why are you overriding it in the first place? just let it be the default. 

'32byte' was not a type name, that's why what you did doesn't work.

**Comment by noahsalvadordenjo** [comment]
Then i have the following error ```REGISTRY: Error: Unknown type passed to AccountId constructor```

**Comment by shawntabrizi** [comment]
@noahsalvadordenjo I have no custom types at all to make my node connect to the javascript. What else have you changes in your node? Where can we see code?

**Comment by noahsalvadordenjo** [comment]
https://github.com/noahsalvadordenjo/foschorgeschet

**Comment by shawntabrizi** [comment]
Then you should not be using any of those custom types.

Balance is not `u64`, AccountId is not `Vec<u8>`

**Comment by kianenigma** [comment]
Your node has default types. If you don't pass anything to the constructor of the API and let it use the default types it will work, as shawn showed.  

Please reopen if you had further issues.

**Comment by noahsalvadordenjo** [comment]
I've removed Balance and AccountId from the registry but still i have the following error 
```REGISTRY: Error: Unknown type passed to AccountId constructor```

**Comment by shawntabrizi** [comment]
When running your node, please go to:

https://polkadot.js.org/apps/#/?rpc=ws://localhost:9944

This will connect to your local node. From there, you should see that everything is working as shown above. If you have errors locally it is because you set up your projects incorrectly. You should provide a [Minimal, Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example) to show us how you ran into your error, not just post one error message with no context.

**Comment by noahsalvadordenjo** [comment]
I tried that but still here's my evidence
https://drive.google.com/file/d/1J1-m_BsjAZFuzD44SzM8E71udTzp6HCC/view?usp=sharing
