### ISSUE TITLE
Contract-Pallet

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/subport#123]
Is v3.0.0 contract compatible with v3.0.0 node-template? Last week I was told to fallback to v2.0.1 node-template  in order to import the contracts-pallet. This worked for me and I was able to successfully import and build everything with no issues. However, there isn't much clarity when it comes down to actually deploying ink! smart contracts to the local blockchain I have running on the v2.0.1 node-template . When I submitted an issue in the ink! repo about this, I was told that ink! v3.0.0-rc3 should work with the latest version of substrates node-template. From what I understand the latest version of the substrate node-template is v3.0.0. However, like I said before, the v3.0.0 contract-pallet for v3.0.0 node-template was not ready for use at the time. Is it ready now? If it isn't, can someone please clarify which  version of these components actually are currently working. I'm simply trying to build a blockchain that allows smart contracts to be deployed on it. Thanks!

**Comment by NukeManDan** [comment]
All versions are working - so long as you **don't mix major version numbers** of specific projects. That is what [semver](https://semver.org/) is meant to address.  There is an active effort to get devhub docs updated to _substrate_ 3.0.0 [here](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues?q=is:issue+is:open+sort:updated-desc+label:v3-tutorial-update) - so version hopping should not be an issue very soon. 

ink! versioning is _seporate_ from substrate, so you need to look at the [compatability](https://github.com/paritytech/ink/releases/tag/v3.0.0-rc3) in the release notes for ink! on what substrate dependencies are expected.

**Comment by NukeManDan** [comment]
solved (for now) in #124
