### ISSUE TITLE
Contract-pallet

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/subport#124]
@NukeManDan , last week when I tried importing the contract-pallet v3.0.0 into substrate-node-template v3.0.0 I ran into errors. In order to get this to work, you told me to fallback to substrate-node-template v2.0.1 and contract-pallet v2.0.1 . This solution did work until I started working with ink! 3.0 smart contracts..lol... Has there been any changes since then?  Is contract-pallet 3.0 ready to be used with substrate-node-template v3.0? And will this work with ink! 3.0 smart contracts?Does ink! 3.0 have anything to do with the contract-pallet I import into substrate-node-template? Please clear this up for me. Thanks!

**Comment by NukeManDan** [comment]
> ## ANNOUNCEMENT
> Currently many users are facing incompatibility issues using ink! 3.0-rc3 with Substrate 3.0 including the contracts-pallet 3.0 when trying to interact with their smart contracts via the Canvas UI. This is due to a missing adjustment for smart contract instantiation introduced in the most recent contracts-pallet version 3.0. The issue is on top of our priority list and we try to resolve it asap.
In the meantime please use the Polkadot JS Apps interface since it already has support for the new contracts-pallet instantiation APIs.

https://matrix.to/#/#ink:matrix.parity.io

https://matrix.to/#/#ink-announcements:matrix.parity.io
