### ISSUE TITLE
Backing off claiming new slot for block authorship: finality is lagging. 

### ISSUE THREAD

**Issue by Daelon02** [paritytech/subport#127]
Hi everyone, we have a little problem.
When we trying add new validator, we have a this error 
` Backing off claiming new slot for block authorship: finality is lagging. `

**Comment by NukeManDan** [comment]
@Daelon02 please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) 🙏🏼

**Comment by NukeManDan** [comment]
@Daelon02 just checking in, is this still an issue? Please do provide more details as the last post asked 🙏🏼 
If not, please close this issue.

**Comment by Daelon02** [comment]
Ohh, sorry, my fault) We all repair)
