### ISSUE TITLE
Substrate runtime use with wasmi / wasmtime 

### ISSUE THREAD

**Issue by apiscerena** [paritytech/subport#128]
I'm interested in wasm-based blockchain VM, and want to know wasmi's mechasim. 
Does the substrate runtime use wasmi? Are there any related docs?

**Comment by bkchr** [comment]
CC @danforbes @NukeManDan

**Comment by NukeManDan** [comment]
Hey @apiscerena - great questions and I would love to see docs made on this topic! 🤩 I have not personally explored this subject before, but happy to get the ball rolling! I have complied a few docs for you to review, let us know where you decide to start developing tutorials/docs when you do! 😁 

Here is a [search of all wasm references](https://substrate.dev/rustdocs/v3.0.0/sc_service/index.html?search=wasm) in substrate as a start.

The [runtime interface](https://substrate.dev/rustdocs/v3.0.0/sp_runtime_interface/index.html) lets you connect your wasm and/or native runtume to the host substrate node - the [wasm runtime interface](https://substrate.dev/rustdocs/v3.0.0/sp_wasm_interface/index.html) sets [**executors**](https://substrate.dev/rustdocs/v3.0.0/sc_executor/index.html) that take calls and execute them in the runtime and has good docs to review about their use. IIUC  `executor <> runtime <> node` is the high-level modularization, and thus you are able to select the runtime using the correct connectors on both sides.  

[The Wasm builder](https://substrate.dev/rustdocs/v3.0.0/substrate_wasm_builder/index.html) is a tool that integrates the process of building the WASM binary of your project into the main cargo build process.

## wasmi
- [embedded API in substrate](https://substrate.dev/rustdocs/v3.0.0/wasmi/index.html)
- [executor docs](https://substrate.dev/rustdocs/v3.0.0/sc_executor_wasmi/index.html)
- [docs](https://paritytech.github.io/wasmi/wasmi/index.html)
- [source](https://github.com/paritytech/wasmi)

## wasmtime
- [embedded API in substrate](https://substrate.dev/rustdocs/v3.0.0/wasmtime/index.html)
- [executor docs](https://substrate.dev/rustdocs/v3.0.0/sc_executor_wasmtime/index.html)
- [Runtime library support for Wasmtime](https://substrate.dev/rustdocs/v3.0.0/wasmtime_runtime/index.html)
- [site](https://wasmtime.dev/)
- [docs](https://docs.wasmtime.dev/)
- [source](https://github.com/bytecodealliance/wasmtime)

**Comment by NukeManDan** [comment]
@adibhanna checking in here: did this info help? Are you interested in working on docs outlining this at all? 😁 🙏🏼 
Happy to support you in any way you need

**Comment by apiscerena** [comment]
Thanks for your documentation lists @NukeManDan. I really appreciate it.
I'm reading these docs and Substrate source code recently. Actually, I wanna firstly start with "How the Wasmtime is Integrated into Substrate Framework". So, I'm trying to go review the codebase and figure out how many problems need to be solved, such as gas metering, indeterministics of supported programming language, sandbox, etc. 

I don't know if there are some docs about these questions?  If not, I'm afraid that codebase is the only way to sort these out?

**Comment by NukeManDan** [comment]
The resources I provided are the best we have at the moment AFAIK RE: WASM integrations. I would reach out to those committing code (find them with git blame) about specific questions and under the pretense that you want to create docs, they may be open to discussing this more with you 😁 🤞🏼

**Comment by apiscerena** [comment]
Wonderful. Thank you! @NukeManDan

**Comment by NukeManDan** [comment]
Closing this here to move to https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/issues/955
