### ISSUE TITLE
Block producing stopped after upgrading through wasm

### ISSUE THREAD

**Issue by qc16** [paritytech/subport#13]
i did upgrade the chain as the follow steps:
1.Tracked substrate new version
2.Changed my own runtime logic,including modifing storage field, storage key hasher and so on
3.Changed the spec version and impl_version
4.Built a runtime wasm blob file and node binary file
5.Stopped old nodes and restarted the nodes through new binary file
6.Using sudo system.setCode to update runtime
After i finished all these steps, the chain stopped to produce block after a short while.Am i right to upgrade runtime online as so?Or what are the correct steps?

**Comment by JoshOrndorff** [comment]
Can you provide a little more information?

1. What versions (tag or commit hash) did you use for the two runtimes?

2. Were block still produced after step 5?

3. Were _any_ blocks produced after the runtime upgrade? If so how many?

4. What node are you using? Is the code available to look at?

5. What error messages do you see from you node or your UI?

**Comment by danforbes** [comment]
Closing due to lack of response.
