### ISSUE TITLE
pallet_collective set members not found in the module or Config

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/subport#130]
Hi there i would like to use the pallet collevtives set_member function, how do i do that if i can't find it in the module neither the config?

**Comment by shawntabrizi** [comment]
What do you mean by:

> can't find it in the module neither the config

Can you elaborate with specific examples, screenshots, etc...

**Comment by noahsalvadordenjo** [comment]
This is what i mean with module https://drive.google.com/file/d/1cFMAta9kFuMNshq6VD49ENgRWFi_-ctw/view?usp=sharing and this is what i mean with config https://drive.google.com/file/d/1cFMAta9kFuMNshq6VD49ENgRWFi_-ctw/view?usp=sharing 
For example to set the validators with pallet session you need to overwrite the config right?

**Comment by noahsalvadordenjo** [comment]
Got it it's defined in Call https://drive.google.com/file/d/1dkHl-nMtVRBxMyQHxxJ7cpausPRj_OgS/view?usp=sharing but how do we use call?

**Comment by NukeManDan** [comment]
@noahsalvadordenjo all of these drive files are access restricted, did you need further support?

**Comment by shawntabrizi** [comment]
I also cannot access the files in your drive. Please upload code to a Github GIST or a picture directly on this platform.

**Comment by noahsalvadordenjo** [comment]
this is what i mean with config
![config](https://user-images.githubusercontent.com/22356457/111518250-2f928200-8756-11eb-9c58-c43ab81c79e5.png)
this is what i mean with call
![call2](https://user-images.githubusercontent.com/22356457/111518278-36b99000-8756-11eb-93d5-2c9a5225622d.png)
this is what i mean with module
![module](https://user-images.githubusercontent.com/22356457/111518307-3c16da80-8756-11eb-9618-276496aaf8b9.png)
How do we use call functions in our pallet?

**Comment by NukeManDan** [comment]
Have you checked out the [add a pallet tutorail](https://substrate.dev/docs/en/tutorials/add-a-pallet/)?
This covers details on how to configure the interface of Nicks to your runtime that should guide you on the patterns you need to implement your pallet in your runtime.

**Comment by shawntabrizi** [comment]
To update the members in this pallet, you want to use the `ChangeMembers` trait which implements this functionality:

https://github.com/paritytech/substrate/blob/master/frame/collective/src/lib.rs#L792

For an example, you can see how the election-phragmen module calls this trait: https://github.com/paritytech/substrate/blob/af998b20151cf08d0757a0c4d040be9438197cdd/frame/elections-phragmen/src/lib.rs#L186

**Comment by noahsalvadordenjo** [comment]
So the docs tell me the following "The membership can be provided in one of two ways: either directly, using the Root-dispatchable function set_members, or indirectly, through implementing the ChangeMembers. The pallet assumes that the amount of members stays at or below MaxMembers for its weight calculations, but enforces this neither in set_members nor in change_members_sorted." Does the pallet_multisig has a trait to implement? How do we use Call in the second way?
