### ISSUE TITLE
Node Template v.3.0.0

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/subport#131]
Can anyone help me out with this issue:

https://github.com/substrate-developer-hub/substrate-node-template/issues/156#issue-833051447

**Comment by NukeManDan** [comment]
@J-Cook-jr please do not spam our issues with requests. Please be patient as we get through requests. It's ok to ask for help in the technical chat.

**Comment by J-Cook-jr** [comment]
My apologies @NukeManDan Dan, I thought I posted the first issue in the wrong repo.

**Comment by NukeManDan** [comment]
No worries 😁 
Next time, this is the right repo for substrate support to get help!
Checkout the readme here for details on the best way to get help 😀 

https://github.com/paritytech/subport/

**Comment by JudeWH** [comment]
@J-Cook-jr I'm also seeing the same warnings after installing dependencies and I was wondering if you were able to resolve this issue? Does it matter if the front-end template was cloned from within the node template?

**Comment by NukeManDan** [comment]
@JudeWH see the issue we moved this to: substrate-developer-hub/substrate-node-template#156
