### ISSUE TITLE
Offline nodes node are not slashed and can still be select as validator

### ISSUE THREAD

**Issue by kaigedong** [paritytech/subport#133]
Hi, I create one test net use substrate 2.0 bin/node. And I have created 8 node to claim to be validator. And the max validator count is 4. So 4 validators have top staked token are selected as validator.
But when I make one selected validator offline, next era it can still be selected as validator. Did I missed any step or configuration?

**Comment by kianenigma** [comment]
Did you also try and wait for another era? The effect of them going offline might become visible after 1 era. 

@andresilva I can't find the issue, but I believe you worked on a similar bug recently.

**Comment by andresilva** [comment]
@kianenigma https://github.com/paritytech/polkadot/issues/2088

Due to session buffering the validator might already have been picked for the next session. This is on my TODO list.

**Comment by kaigedong** [comment]
> Did you also try and wait for another era? The effect of them going offline might become visible after 1 era.
> 
> @andresilva I can't find the issue, but I believe you worked on a similar bug recently.

Yes, I waited for several eras, and the offline validator still be selected as validator.

**Comment by kaigedong** [comment]
> @kianenigma [paritytech/polkadot#2088](https://github.com/paritytech/polkadot/issues/2088)
> 
> Due to session buffering the validator might already have been picked for the next session. This is on my TODO

**Comment by andresilva** [comment]
It's also likely that the validators were set to be "invulnerable" in which case they are not affected by slashing. This is a configuration that exists by default on the development/testing chains.

**Comment by kaigedong** [comment]
> It's also likely that the validators were set to be "invulnerable" in which case they are not affected by slashing. This is a configuration that exists by default on the development/testing chains.

Thank you!
