### ISSUE TITLE
Grandpa finalization not working after import-blocks command

### ISSUE THREAD

**Issue by inodelisia** [paritytech/subport#134]
I have a Testnet with 4 standard nodes that act as validators. I've exported some blocks (using export-blocks command) and tried to create a fork using import-blocks (I've used this approach because I want to revert the chain to a certain block height, even if the block were already finalized), the fork created is producing new blocks but I didn't managed to restart finalization  (I've used the same keys, I've restarted the nodes after inserting the keys into the keystore, also tried to author_rotatekeys, noteFinalityStalled, with no result. It seems stuck at Round(1) on Grandpa roundstate.

**Comment by andresilva** [comment]
Use the RPC endpoint `grandpa_roundState` on each node to figure out what their local view of the protocol is: are nodes on the same round? are nodes on the same set_id? who is missing votes?

**Comment by NukeManDan** [comment]
@inodelisia checking in here - can you provide more info as requested? Ideally a [minimal reproducable example](https://stackoverflow.com/help/minimal-reproducible-example) so we can support you. If you solved this, can you let us know what did the trick?
