### ISSUE TITLE
how to get account history transactions by rpc

### ISSUE THREAD

**Issue by johnsonsuncrypto** [paritytech/subport#135]

**Comment by kianenigma** [comment]
You mean get all the transactions of an account? 

- You need a node running with --pruning=archive
- Use [`chain_getBlock()`](https://polkadot.js.org/docs/substrate/rpc/#getblockhash-blockhash-signedblock) RPC to get a single block, check the `.extrinsics` for signed transactions coming from your account of interest. 
- Get the parent hash from header, repeat step 2 until you are satisfied. 

There's no custom RPC for this.

**Comment by johnsonsuncrypto** [comment]
ok tks
