### ISSUE TITLE
pallet_balances::Event::Deposit is unused

### ISSUE THREAD

**Issue by KalitaAlexey** [paritytech/subport#136]
Hello. I see that pallet_balances has Event::Deposit and its documentation states it's for fees, but it's not used and currently there is no way to see how much fee a transaction did cost.

**Comment by bkchr** [comment]
CC @joepetrowski

**Comment by joepetrowski** [comment]
Sure, it is used: https://github.com/paritytech/polkadot/blob/f89020dafeec01f949b42e7d3257b5840be47f96/runtime/common/src/impls.rs#L35

You can calculate how much a transaction cost from the state/tx params at the time of execution, see e.g. https://github.com/paritytech/substrate-api-sidecar/blob/b8e8292af976b512255df08e3d62bea4d59a8c92/src/services/blocks/BlocksService.ts#L442

**Comment by KalitaAlexey** [comment]
I see so it's expected for users of pallet_balances to deposit this event.
I think it's inconsistent with other events.
Thanks.
