### ISSUE TITLE
How to export chainspec from already running node?

### ISSUE THREAD

**Issue by ashi20192020** [paritytech/subport#137]
We have built a custom blockchain on top of substrate, & we started the node few months back without generating the chainSpec file. Later we got to know that we should generate the chainSpec file & use that every time we want to start the new node, so we generated the new chainSpec file. But we cant use this chainSpec, since it has different block hash than the one we are already running, so we are getting the error saying node which we are trying connect with as boot node is at different chain than we expect it to be. 
I am getting below error

`Bootnode with peer id xxx is on a different chain (our genesis: 0x6913…c3c3 theirs: 0x9be3…54d6)`

Is there any solution for this scenario? Can we export chainspec from already running node, so that we can use it while starting new node?

**Comment by NukeManDan** [comment]
The chainspec file should be passed to all nodes from the original node. There are non-determinism issues in generating this file. See the last note in [the private network tutorial](https://substrate.dev/docs/en/tutorials/start-a-private-network/customspec) for more on this. 

You likely need to perform a [Re-Genesis](https://github.com/paritytech/substrate/issues/7458) if you somehow lost this file, and generate a new chain-spec that you then embed into the node's source for others to make sure they get the right one.
