### ISSUE TITLE
pallet-evm for version 3.0.0 

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/subport#138]
For v3.0.0, which version of pallet-evm should I install?
I think the max version of pallet-evm is 2.0.1 and it fails.

```
cargo check -p node-template-runtime

error: failed to select a version for `parity-util-mem`.
    ... required by package `sp-core v2.0.0`
    ... which is depended on by `pallet-evm v2.0.1`
    ... which is depended on by `node-template-runtime v3.0.0 (/Users/mac/Documents/Substrate/inverse-node/runtime)`
    ... which is depended on by `node-template v3.0.0 (/Users/mac/Documents/Substrate/inverse-node/node)`
versions that meet the requirements `^0.7.0` are: 0.7.0
```

**Comment by NukeManDan** [comment]
The evm has migrated to the `frontier` project:

https://github.com/paritytech/frontier/blob/master/frame/evm/Cargo.toml has v3, but no tag for this (yet)

https://crates.io/crates/pallet-evm has not been updated to v3 - will report, you can use the git repo specified in your cargo for the mean time though

**Comment by NukeManDan** [comment]
@bkchr is anything needed to hand over access to let frontier release `pallet-evm` from now on the evm on crates.io?

**Comment by NukeManDan** [comment]
right now crates has the wrong metadata and show Basti and Ben as owners
![image](https://user-images.githubusercontent.com/35669742/113194319-3c1ade00-921e-11eb-9135-5fe3d1d1a759.png)

**Comment by gnunicorn** [comment]
> right crates.io has the wrong metadata and shows @gnunicorn as owner

it also shows paritytech-core-devs... the frontier can overwrite it, whenever they have a release ready.

**Comment by NukeManDan** [comment]
@frankli-dev https://crates.io/crates/pallet-evm (3.0.0) and https://crates.io/crates/pallet-ethereum (1.0.0) are now updated and ready to pull into your deps! 🎉

**Comment by frankli-dev** [comment]
Thank you @NukeManDan
