### ISSUE TITLE
how to set custom types according to the substrate  based coins. (mine is PIRL)

### ISSUE THREAD

**Issue by cetindogu** [paritytech/subport#139]
>i can't transfer my coins from local node https://polkadot.js.org/apps/?rpc=ws%3A%2F%2F127.0.0.1%3A9944#/explore 
> my node is PIRL 2.0 coin validator (i have installed pirl2.0 node on my local pc, and waited for syncing)
> PIRL coin source code is -> https://github.com/pirl/pirl-2_0
i got this error
![image](https://user-images.githubusercontent.com/7325611/113366334-89539880-9361-11eb-91b5-6584351a80ba.png)
need help, where is no developer for now. so i need to learn how to succeed to transfer via latest
https://github.com/polkadot-js/apps
developer said to me "add custom types" 
but i dont know how to add make custom types json to add it.
do i have to inspect all source codes? and then find custom types. then create a json??
isnt there any easy way? 
please help me, and give info for me to find a solution.

**Comment by shawntabrizi** [comment]
@cetindogu take a look at the solutions presented here: https://polkadot.js.org/docs/api/FAQ#the-node-returns-a-could-not-convert-error-on-send

**Comment by cetindogu** [comment]
Thank you @shawntabrizi , it worked after i set the custom type json (julien, @masterdubs, pirl coin developer, have given me this json


{ 
"Address": "AccountId",
"LookupSource": "AccountId",
  "Account": {
    "nonce": "U256",
    "balance": "U256"
  },
  "Transaction": {
    "nonce": "U256",
    "action": "String",
    "gas_price": "u64",
    "gas_limit": "u64",
    "value": "U256",
    "input": "Vec<u8>",
    "signature": "Signature"
  },
  "Signature": {
    "v": "u64",
    "r": "H256",
    "s": "H256"
  },
  "Keys": "SessionKeys5"
}

**Comment by kl3eo** [comment]
The same types worked for the @polkadot/api
