### ISSUE TITLE
[question] Parity ether and substrate compatibility inquiry

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/subport#14]
As a sidechain, I am currently using parity ether poa below link. Is it compatible with substate and parity ether? I am wondering if it is possible to use the substrate chain offchain worker to get data through http request from a specific site, then confirm the block and send the data to the parity ether main chain. I would appreciate it if you could tell me how to do it. If you have an example source, it would be okay if you let me know.

- link : https://github.com/openethereum/wiki/blob/master/Demo-PoA-tutorial.md

**Comment by HCastano** [comment]
By default neither of these chains are "compatible" with each other. You need to do a bit of work on each chain to get them to understand what the other is saying.

Consider this simplified example where you want to send a Substrate transaction to an Ethereum PoA chain. From the Ethereum PoA side of things you'd need a smart contract which accepts Substrate transactions. These transactions could be submitted through an external service which performs a call to an Ethereum node. The smart contract could then "transform" them into Ethereum transactions (into maybe an ERC20 token `transfer()`). Through a bit of work Ethereum now understands Substrate, even though it doesn't understand it natively.

Getting back to your original use case. You can have something like this:

`Substrate -> Offchain Worker -> Website -> Substrate -> External Service -> Ethereum`

The external service could subscribe to your Substrate node, listening for the transactions it wants to relay, and then make a call to Ethereum. This could be a call to a smart contract you have set up to do something with the data from Substrate.

**Comment by puffanddmx** [comment]
Thanks for the reply. I know that the parity ether poa itself supports solidity to be compatible with Ethereum, but is it impossible to directly communicate with other substrates by modifying the wasm of the parity ether poa itself?
