### ISSUE TITLE
How can I judge and prompt the JS client that the incoming type is wrong in the substrate?

### ISSUE THREAD

**Issue by imstar15** [paritytech/subport#140]
Hi, I want to ask a question. I wrote a pallet with a module function defined in it, and the parameter is vec<u8>. I use the polkadot.js library to send a request to call this function, and I should pass in a js string. But for testing, I passed 123 of type number. Substrate parsed me out as [0,0,...], and the array was all 0s. How can I ensure that the parameters passed by the client are of the correct type? If the correct type is not passed in, can I prompt the client with an error?

**Comment by NukeManDan** [comment]
In general strings should should not be included in your runtime. Instead, raw SCALE encoded bits are suggested (as a `Vec<u8>` UTF8 encoded characters) Here is [how and why](https://stackoverflow.com/questions/65348505/runtime-building-string-not-found-in-this-scope). In the case that you are not doing this already

The API auto-decorates [types](https://polkadot.js.org/docs/api/start/types.basics) but you must (for now) directly inform the api of any [custom or extended types](https://polkadot.js.org/docs/api/start/types.extend). It _should_ help guard against improper encoding/decoding. 

You can and should also create checks for the right types **before you call the API** in js as needed, as apposed to replying on the node to do that for you.

**Comment by imstar15** [comment]
Thank you for your answer!
