### ISSUE TITLE
Why tokens.transfer is asking for transaction fee with ORML 0.4.0 and Substrate 3.0.0 

### ISSUE THREAD

**Issue by ashi20192020** [paritytech/subport#141]
I am using ORML tokens pallet for one of my applications. Earlier I was using **ORML 0.3.2** and **Substrate 2.0**. Below is Runtime configuration of `pallet_transaction_payment` and `orml:token`

```
parameter_types! {
	pub const TransactionByteFee: Balance = 0;
}

impl pallet_transaction_payment::Trait for Runtime {
	type Currency = Balances;
	type OnTransactionPayment = ();
	type TransactionByteFee = TransactionByteFee;
	type WeightToFee = IdentityFee<Balance>;
	type FeeMultiplierUpdate = ();	
}

impl tokens::Trait for Runtime {
	type Event = Event;
        type Balance = Balance;
	type Amount = i64;
	type CurrencyId = i64;
        type OnReceived = ();
        type WeightInfo = ();
}
```
With the above configuration, I was able to transfer without any transaction fee. Recently I have updated my application with  ORML 0.4.0 and Substrate 3.0.0. Below is Runtime configuration:

```
parameter_types! {
	pub const TransactionByteFee: Balance = 0;
}

impl pallet_transaction_payment::Config for Runtime {
	type OnChargeTransaction = CurrencyAdapter<Balances, ()>;
	type TransactionByteFee = TransactionByteFee;
	type WeightToFee = IdentityFee<Balance>;
	type FeeMultiplierUpdate = ();
}

impl tokens::Trait for Runtime {
	type Event = Event;
        type Balance = Balance;
	type Amount = i64;
	type CurrencyId = i64;
        type OnReceived = ();
        type WeightInfo = ();
}
```
As you can see, there is no change in the `token` configuration but in `pallet_transaction_payment`, `Currency` got replaced by `OnChargeTransaction`. As a result, it started asking for transaction fee. 

![image](https://user-images.githubusercontent.com/81686485/113476142-324fdf80-9497-11eb-8c1d-e56e801cb56e.png)

Can someone please help me to understand and fix this?

**Comment by NukeManDan** [comment]
Let's keep the conversation over on ORML https://github.com/open-web3-stack/open-runtime-module-library/issues/433#issuecomment-812848200
