### ISSUE TITLE
How can I transfer all the DOT to my another account

### ISSUE THREAD

**Issue by zeusxs** [paritytech/subport#142]
I have five account on polkadot, and they all have a little bit DOT，but when I transfer(close keep alive switch) the DOT, it alway tell me that Exception balances.keepalive, what should I do? If I leave 1 DOT on account, I lost 4 DOT？

**Comment by shawntabrizi** [comment]
To transfer the full balance using Polkadot JS Apps, you simply need to adjust the toggles like in this image:

![Uploading image.png…]()

**Comment by zeusxs** [comment]
> To transfer the full balance using Polkadot JS Apps, you simply need to adjust the toggles like in this image:
> 
> <img alt="image" width="1060" src="https://user-images.githubusercontent.com/1860335/113502690-22cfa580-952e-11eb-85b7-a4a660c17cac.png">
I dont't find toggles like you, and it has something different

![image](https://user-images.githubusercontent.com/30338668/113503029-03527000-9562-11eb-8dc4-d18d61a9947b.png)

**Comment by zeusxs** [comment]
![image](https://user-images.githubusercontent.com/30338668/113503148-85db2f80-9562-11eb-8682-d4d64ba5d21b.png)

English Version

**Comment by shawntabrizi** [comment]
@zeusxs it means that you are using your account in some way where you cannot transfer the full balance. For example if you have some lock on your account or some reserved balance.

Maybe you have a identity registered, you are staking, you are voting, etc... Whatever it is, you need to undo those things.

**Comment by zeusxs** [comment]
> @zeusxs it means that you are using your account in some way where you cannot transfer the full balance. For example if you have some lock on your account or some reserved balance.

Thanks a lot, I check my account , and three of them transfer successfully. only one accound(I check no identity registered, no staking, no voting) still have this problem. Is there any RPC method that I can query my account state

**Comment by zeusxs** [comment]
![image](https://user-images.githubusercontent.com/30338668/113535904-4b779e00-9607-11eb-80b6-fb470e0a8a87.png)

![image](https://user-images.githubusercontent.com/30338668/113535739-d99f5480-9606-11eb-81d7-3d6a4e0b700a.png)

**Comment by shawntabrizi** [comment]
@zeusxs please dont open another issue. Just post your address and we can look to see what the issue might be.

**Comment by zeusxs** [comment]
> @zeusxs please dont open another issue. Just post your address and we can look to see what the issue might be.
This is my address: 123dYiYNBwu4Wy8FjPuz259e5zhfiFWxdFcPqEm1e8YsAMs8
Thank you very much~

**Comment by shawntabrizi** [comment]
@zeusxs please try calling `staking > withdraw unbonded` again

**Comment by shawntabrizi** [comment]
The problem here is likely because of the `session > set_keys` call you made, but its not exactly clear to me how to fix it.

**Comment by zeusxs** [comment]
> The problem here is likely because of the `session > set_keys` call you made, but its not exactly clear to me how to fix it.
> 
> Will need more time to investigate

Yeah, I used `session->set_keys` to set session key, but the server which run polkadot binary program is stop now, maybe I should set a new session key, and use `session->purge_key`

**Comment by shawntabrizi** [comment]
@zeusxs i think that is reasonable. Also remember things in the session pallet take a full session to take effect.

**Comment by zeusxs** [comment]
I try to made RPC method(`session->purge_key`). The exception(noAssociatedValidatorId) happened. does it means that My accound is clear successfully? But I still can't transfer all DOT. I think maybe I meet a bug .

**Comment by shawntabrizi** [comment]
@zeusxs I have opened an issue ^

We will continue to investigate. There is not much that can be done for the moment. Sorry about that.

**Comment by zeusxs** [comment]
nice for you!, I just feel sad about my 1 DOT~, Ha Ha Ha

**Comment by shawntabrizi** [comment]
If we can find a bug, I will make sure to open a tip for you for more than 1 DOT for reporting this bug to us :)

**Comment by shawntabrizi** [comment]
@zeusxs We saw that the first thing you tried to do was become a  validator. To your knowledge, did that work?

**Comment by shawntabrizi** [comment]
@zeusxs We found the issue. Basically the `purge_keys` command was checking to see if you were a validator, and only allowing you to clean up your keys if that is the case.

Before you cleaned up your keys, you stopped becoming a validator, so you were not able to call `purge_keys` successfully.

We will make a PR to remove this check (which is really not needed), and it will allow you to call `purge_keys` successfully, and clean up the reference counter on your account.

**Comment by zeusxs** [comment]
Here is my address, 123dYiYNBwu4Wy8FjPuz259e5zhfiFWxdFcPqEm1e8YsAMs8

**Comment by shawntabrizi** [comment]
Are you a programmer? you might be interested to make a PR to solve the issue I opened here ^^

And it would solve your issue too :)

**Comment by zeusxs** [comment]
> Are you a programmer? you might be interested to make a PR to solve the issue I opened here ^^
> 
> And it would solve your issue too :)

actually I'm a programer, but I'm not familiar with Rust language. So it maybe diffcult for me to solve this issue

**Comment by kianenigma** [comment]
For further investigation, the track of changes of the account of subject is: 

```
Ref count changed at 4481265 from 1,3 to 1,1: https://polkascan.io/polkadot/transaction/0x7047b0f320df7146a47ec38c096d336d7faddd085b7e569ab7ab832098cb8954
Ref count changed at 4064067 from 1,0 to 1,3: https://polkascan.io/polkadot/transaction/0x95f087f3ab7c2d6c04855e2191c44879d989f7aeb670b9dfa8d044d9e8a95c30
Ref count changed at 4064046 from 0,0 to 1,0: https://polkascan.io/polkadot/transaction/0xbff2d68117582173ab572c4dea2ab946836357fa25a01935f901f60c4c430b8f

```

**Comment by zeusxs** [comment]
Have this bug been solved?  I still can't transfer my DOT and calling purgeKey remain fail
