### ISSUE TITLE
I can't transfer all the DOT to another account

### ISSUE THREAD

**Issue by zeusxs** [paritytech/subport#144]
I can't transfer all DOT to another account(It must be leave 1DOT)，balances.keepalive Exception always report when I send DOT.

**Comment by kianenigma** [comment]
The reason is literally in the name of your transaction `balances.**keepalive**`. If you are sure about killing your account and know what you are doing, go to the [`extrinsic`](https://polkadot.js.org/apps/#/extrinsics) tab, and submit a normal `transfer` manually.

**Comment by shawntabrizi** [comment]
@zeusxs if you need more assistance, you will ultimately need to share your address so we can look at the state of your account.
