### ISSUE TITLE
error[E0046]: not all trait items implemented, missing: `successful_origin`

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#149]
While running `cargo +nightly build --release --features runtime-benchmarks`, I am getting this

```
error[E0046]: not all trait items implemented, missing: `successful_origin`
875 | / impl<
876 | |     O: Into<Result<RawOrigin<AccountId, I>, O>> + From<RawOrigin<AccountId, I>>,
877 | |     AccountId: Default,
878 | |     I,
...   |
891 | |     }
892 | | }
    | |_^ missing `successful_origin` in implementation
    |
    = help: implement the missing item: `fn successful_origin() -> OuterOrigin { todo!() }`
```

Can someone help me to fix this?

**Comment by JesseAbram** [comment]
came across this with @kianenigma. Seems like some benchmark was not implemented that should have been , fixed it by adding 	'polkadot-service/runtime-benchmarks' to the features of the node's Cargo.toml [file](https://github.com/paritytech/statemint/blob/master/node/Cargo.toml#L219)

**Comment by kianenigma** [comment]
yeah your def. missing some `some-crate/std` somewhere.

**Comment by kianenigma** [comment]
Also, please provide further information: 

>  running cargo +nightly build --release --features runtime-benchmarks

Running this command on what code base and on which commit exactly?

**Comment by ayushmishra2005** [comment]
> came across this with @kianenigma. Seems like some benchmark was not implemented that should have been , fixed it by adding 'polkadot-service/runtime-benchmarks' to the features of the node's Cargo.toml [file](https://github.com/paritytech/statemint/blob/master/node/Cargo.toml#L219)

Thanks @JesseAbram It worked

**Comment by jimmychu0807** [comment]
Encountered this problem today. Need to read the error message to see which pallet is giving the `` missing: `successful_origin` ``, and then add the corresponding `<pallet>/runtime-benchmarks` in the runtime **Cargo.toml** `runtime-benchmarks = [...]` block.

**Comment by rlaferla** [comment]
I am seeing this with `xcm-builder`.  What should I change to fix it?

```
  error[E0046]: not all trait items implemented, missing: `try_successful_origin`
     --> /home/test/.cargo/git/checkouts/polkadot-4038f27d5e4ea2e8/097ffd2/xcm/xcm-builder/src/origin_conversion.rs:247:1
      |
  247 | / impl<RuntimeOrigin: OriginTrait + Clone, Conversion: Convert<RuntimeOrigin, MultiLocation>>
  248 | |     EnsureOrigin<RuntimeOrigin> for EnsureXcmOrigin<RuntimeOrigin, Conversion>
      | |______________________________________________________________________________^ missing `try_successful_origin` in implementation
      |
      = help: implement the missing item: `fn try_successful_origin() -> Result<OuterOrigin, ()> { todo!() }`
```
