### ISSUE TITLE
[Question] Any code snipped how to call Smart Contract from within Offchain Worker?

### ISSUE THREAD

**Issue by evgeny-s** [paritytech/subport#152]
Hey, guys. 
I'm currently trying to implement Off-chain worker which sends some specific data to the Smart Contract.
I took [this](https://github.com/paritytech/substrate/tree/master/frame/example-offchain-worker) as a starting point.
I was able to send a signed transaction as described in this example, but I need to send a signed transaction to the specific Smart Contract. 
Could you please share some directions or even code snippets to achieve this? 

Thanks in advance.

**Comment by al3mart** [comment]
Based on this documentation https://substrate.dev/rustdocs/v3.0.0/pallet_contracts/enum.Call.html#variant.call you should be able to send any call to your contracts.

**Comment by evgeny-s** [comment]
@al3mart , thanks.
Could you maybe please provide steps on how to inject keys to offchain-worker to be able to sign transactions. 
Currently, I'm trying to send a signed transaction but get [this](https://github.com/paritytech/substrate/blob/master/frame/example-offchain-worker/src/lib.rs#L424) error. 
Tried to insert keys via RPC call `author` -> `insertKeys`, no success.
Any other options here?

Thanks.

**Comment by evgeny-s** [comment]
> @al3mart , thanks.
> Could you maybe please provide steps on how to inject keys to offchain-worker to be able to sign transactions.
> Currently, I'm trying to send a signed transaction but get [this](https://github.com/paritytech/substrate/blob/master/frame/example-offchain-worker/src/lib.rs#L424) error.
> Tried to insert keys via RPC call `author` -> `insertKeys`, no success.
> Any other options here?
> 
> Thanks.

This was fixed. Need to provide correct key type, which provided in the offchain-worker.  
Thanks!

**Comment by evgeny-s** [comment]
> Based on this documentation https://substrate.dev/rustdocs/v3.0.0/pallet_contracts/enum.Call.html#variant.call you should be able to send any call to your contracts.

Would be great to see:
* How to instantiate contract instance to be able to call it
* How to specify contract ABI
* How to specify contract public key

**Comment by al3mart** [comment]
Thanks for the feedback, much appreciate it

**Comment by evgeny-s** [comment]
Still no success on it.

**Comment by evgeny-s** [comment]
BTW, was able to call it like this:
```
let contract_addr_str = b"5Fay3QQH2S4wXqCQdhZAS2bWrqvdbVmq77jb2M7seNDqjz1G";
				let contract_addr = contract_addr_str.to_vec();
				let mut contract_addr = &contract_addr[..];
				let contract_addr = <<T::CT as frame_system::Trait>::Lookup as StaticLookup>::Source::decode(&mut contract_addr).unwrap();

				let input = [
					// the selector
					0xCA,
					0xFE,
					0xBA,
					0xBE,
					0,
					0,
					0,
					0,
				];

				pallet_contracts::Call::call(
					contract_addr,
					0u32.into(),
					10_000_000_000,
					input.to_vec()
				)
```


But for some reason, `contract_addr` was not applied. Do you guys have any other options how to call SC by the address?

**Comment by NukeManDan** [comment]
I would ask this explicitly in the [ink matrix chat](https://matrix.to/#/#ink:matrix.parity.io) - you can link this issue there to get explicit support from the SC tooling pros 😁

**Comment by evgeny-s** [comment]
Thanks, will do.
