### ISSUE TITLE
[Question] Signing application for mobile devices

### ISSUE THREAD

**Issue by BenWhiteJam** [paritytech/subport#153]
Question regarding Subkey, is there a reference in terms of what implementations/languages are available as well as references to examples for mobile devices?

Found these repos so far:
- Go: https://github.com/vedhavyas/go-subkey
- Py: https://github.com/zatoichi-labs/py-subkey
- Java Client: https://github.com/emeraldpay/polkaj
- Java API: https://github.com/polkadot-java/api

I wonder about implementations in regards to Swift / Objective-C / Kotlin / Dart?

**Comment by emostov** [comment]
From what I understand parity-signer uses some one off Rust crypto for signing. @Slesarew, @TarikGul  or @maciejhirsz might know more?

Not sure if this is up to date, but last time I checked it is shipped from NPM as [react-native-substrate-sign](https://www.npmjs.com/package/react-native-substrate-sign)

**Comment by Slesarew** [comment]
Almost correct; the libs were just moved into the Signer, I'm not sure if they will be supported as standalone (I'll try to), but they'll certainly be slightly out of sync. ed25519 is not finished in either version though so it's not exactly very good reference.

Nevertheless, the Subkey part there is literally copypasted from Substrate code and that's just compiled into good old C FFI. The Substrate codebase is the reference in a sense.

Also some wasm-built Rust code could be found in https://github.com/paritytech/wasm-utils, it's pretty complete but using it elsewhere is complicated.
