### ISSUE TITLE
Question about Aura Reward

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/subport#155]
In the substrate POA aura + granpa base, can we know which part of the document is referred to the logic that rewards the block generation?

**Comment by NukeManDan** [comment]
There is no block rewards _intrinsic_ to your block production and finalization. In the templates for testing, these are not configured. This is intended: you can configure a block reward for _any_ consensus you decide on. You can select a reward scheme an add it as a pallet to your runtime, like [pallet_staking](https://substrate.dev/rustdocs/v3.0.0/pallet_staking/).

As an example, you can see how BABE configures a mock runtime that sets an empty [staking reward here](https://github.com/paritytech/substrate/blob/master/frame/babe/src/mock.rs#L203), you could configure this instead to whatever you so choose. 

And further GRANDPA has a mock example [here as well](https://github.com/paritytech/substrate/blob/master/frame/grandpa/src/mock.rs#L209)

As AURA is based on permissioned authority, it doesn't make much sense to reward explicitly for this behavior. See the [tests cases in Arua's source](https://github.com/paritytech/substrate/blob/master/client/consensus/aura/src/lib.rs#L710-L781) for a lead on how you might incorporate rewards.
