### ISSUE TITLE
Error while registering a parachain to local relaychain. FailedToConvertParameter validate_transaction 

### ISSUE THREAD

**Issue by frankli-dev** [paritytech/subport#156]
I'm following this cumulus workshop https://substrate.dev/cumulus-workshop/#/en/3-parachains/2-register

- https://github.com/paritytech/polkadot (master branch)
- https://github.com/substrate-developer-hub/substrate-parachain-template (master branch)

When I submit the sudo, it fails
![image](https://user-images.githubusercontent.com/51565705/115489626-7f1f0e80-a22a-11eb-8b94-503a5458e78b.png)

`crowdloan.create
1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: Some(Error { cause: Some(Error { cause: None, desc: "Not enough data to fill buffer" }), desc: "Could not decode `Call::create.2`" }), desc: "Could not decode `Call::Crowdloan.0`" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: Some, Error { cause: Some, Error { cause: None, desc: \"Not enough data to fill buffer\" }, desc: \"Could not…
`

**Comment by NukeManDan** [comment]
You _must_ use the commits specified for types to be handled for you, as stated in the workshop. The commit is referenced there.

**Comment by icodezjb** [comment]
I had a similar problem.
Using the wrong or outdated polkadot.js types via polkadot.js.org.
Resolved it by cleaning and configuring the correct type
