### ISSUE TITLE
Consensus Error on Private Chain Tutorial After Upgrading to alpha.8

### ISSUE THREAD

**Issue by danforbes** [paritytech/subport#16]
I recently upgraded our tutorials to alpha.8 and encountered an error that was logged to the command line when I was following the steps of [the tutorial to start a private chain](https://github.com/substrate-developer-hub/tutorials/blob/master/tuts/start-a-private-network/v2.0.0-alpha.7/customchain.md):
`2020-05-15 16:05:54 Encountered consensus error: CannotSign([88, 111, 68, 26, 64, 196, 73, 49, 116, 34, 235, 87, 110, 210, 180, 172, 173, 48, 31, 26, 239, 99, 33, 149, 142, 20, 160, 177, 129, 23, 83, 58], "An unknown keystore error occurred: No such file or directory (os error 2)")
`

I notice this error after starting the second node. Both nodes report an error of the same form, albeit with different values in the `CannotSign` array. Despite the errors, I still see the nodes finalizing blocks after inserting keys and restarting the nodes. I've gone through the steps of the tutorial a few times and deleted `/tmp/node0*` between each pass, so I'm pretty sure the error is reproducible and not user error.

**Comment by JoshOrndorff** [comment]
This is not your mistake. The aura authoring engine is broken. I opened https://github.com/paritytech/substrate/issues/6052 for it.

I would have moved this, but I saw the riot post first.
