### ISSUE TITLE
How to create a local account?

### ISSUE THREAD

**Issue by liudonghao** [paritytech/subport#160]
I'm trying to fectch and parse some json data from the external world inside OCW, then organize those data as parameters passed to a function inside a smart contract. The problem I came across is that it cannot sign:
```
let signer = Signer::<T, T::AuthorityId>::any_account();
		if !signer.can_sign() {
			debug::error!("No local accounts available. Consider adding one via `author_insertKey` RPC.");
		}
```
so, I use Postman to try to create a local account using below json via posting on localhost:9933, but it doesn't work:
```
{
    "jsonrpc": "2.0",
    "method": "author_insertKey",
    "params": ["aura","seed phrase","0x1000000000000000000000000000000000000000000000000000000000000001"],
    "id": 1
}
```

**Comment by NukeManDan** [comment]
Based on the [example here](https://github.com/paritytech/substrate/blob/master/frame/example-offchain-worker/src/lib.rs) and the [RPC source for the call you are invoking](https://github.com/paritytech/substrate/blob/60eb0c69fa264dd758c91e3d81ac68ef75036b8e/client/rpc/src/author/mod.rs#L97-L109)

- These are the [key types](https://github.com/paritytech/substrate/blob/60eb0c69fa264dd758c91e3d81ac68ef75036b8e/primitives/core/src/crypto.rs#L1157-L1183) substrate supports. You are likely after `acco` as the type
- Here are the [docs on the RPC call](https://polkadot.js.org/docs/substrate/rpc#insertkeykeytype-text-suri-text-publickey-bytes-bytes) 
  - You need to set the correct parameters, your example should fail as the seed is not correct, and the public key doesn't match. 
  - Here is an example I used the embedded `key` sub-command in the node to generate:
     ```
     Secret phrase `inmate try anxiety track clarify knock border clog daring adjust afraid dizzy` is account:
     Secret seed:      0xfef6a204d5ff3cc44649cc741d1b73406e60134827c88cab3df6a788f84d5743
     Public key (hex): 0x0cdbc665dfe9a241b1d917675c5778f939070c033864d9d523474c06a7a7276e
     Account ID:       0x0cdbc665dfe9a241b1d917675c5778f939070c033864d9d523474c06a7a7276e
     SS58 Address:     5CMZidaVNXwt8hZR9Au1JaxMdq92WiXGVjo818E8BpbFn1so
     ```
     Running a node template:
     ```
     ./target/release/node-template --dev --base-path /tmp/node
     ```
    And the call that can insert this:
    ```
    curl -H "Content-Type:application/json" -d '{"jsonrpc":"2.0","id":1,"method":"author_insertKey","params": ["acco","inmate try anxiety track clarify knock border clog daring adjust afraid dizzy","0x0cdbc665dfe9a241b1d917675c5778f939070c033864d9d523474c06a7a7276e"]}' http://127.0.0.1:9933
    ```
    Will return:
    
    
- Do you expose RPC ports for this with `--unsafe-rpc-external` when running your node?

**Comment by NukeManDan** [comment]
Checking in @liudonghao - need more support here? If so , let's reopen the issue.
