### ISSUE TITLE
error[E0609]: no field `__rip` on type `__darwin_arm_thread_state64`

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#162]
Getting below error while running `cargo build --release` after updating cargo.  My code is here https://github.com/ayushmishra2005/substrate-barcode-scanner and I am using Substrate 3.0.0

```
error[E0609]: no field `__rip` on type `__darwin_arm_thread_state64`
   --> /Users/ayushkumarmishra/.cargo/registry/src/github.com-1ecc6299db9ec823/wasmtime-runtime-0.22.0/src/traphandlers.rs:169:44
    |
169 |                     (*cx.uc_mcontext).__ss.__rip as *const u8
    |                                            ^^^^^ unknown field
    |
    = note: available fields are: `__x`, `__fp`, `__lr`, `__sp`, `__pc` ... and 2 others

error: aborting due to previous error

For more information about this error, try `rustc --explain E0609`.
error: could not compile `wasmtime-runtime`

```

Can someone please help me to fix this?

**Comment by NukeManDan** [comment]
Did you do a blanket `cargo update`? This is expected to break substrate based projects in this way 😬

**Comment by ayushmishra2005** [comment]
> Did you do a blanket `cargo update`? This is expected to break substrate based projects in this way 😬

Yes @NukeManDan   I did `cargo update`. What should I have done? and What should I do now to fix this?

**Comment by NukeManDan** [comment]
only update the [precise packages](https://doc.rust-lang.org/cargo/commands/cargo-update.html#examples) you need: `cargo update -p foo --precise 1.2.3`

Revert your commit to before this update, and update just the packages you need and troubleshoot from there if needed for any dependency issues.
