### ISSUE TITLE
Substrate 3.0, archive-node failed to sync at the block right after a runtime upgrade

### ISSUE THREAD

**Issue by sergeibadass** [paritytech/subport#164]
My runtime (Hammer) is developed based on Substrate 3.0. I have done two forkless runtime upgrades and the block production continues just fine. But when I boot an archive node connecting to my substrate chain, an error happen when the synchronization reaches the second runtime update checkpoint. 

"Checking Inherents failed: timestamp set in block doesn't match slot in seal. 

![image](https://user-images.githubusercontent.com/76840075/117663235-01b83f80-b1d3-11eb-95df-28c202de67b7.png)

I Have tried reverted to the last finalized block and sync again but it does not work.

Could anyone help?

Fact sheet: 
done two forkless updates:
- spec 100 to 101 at block 586648
- spec 101 to 102 at block 1013074

block interval: 3s
block producing: babe + grandpa. but forced the era update to None so the community wont change.

block browser: https://explorer.spanner.network/?rpc=wss%3A%2F%2Fspannerchain.ddns.net%2Fhammer#/explorer/query/586648

**Comment by sergeibadass** [comment]
It seems that this PR (https://github.com/paritytech/substrate/pull/8124) fixes this problem by removing the inherent assertion logic. It is released after substrate 3.0. any quick fix? @NukeManDan

**Comment by sergeibadass** [comment]
Update: i revert back to the native runtime of spec 100 and sync successfully. The problem is native runtime spec 102 fail to verify the blocks but the wasm-based verification can.

**Comment by NukeManDan** [comment]
Sorry for not getting in here sooner to support! Glad you solved this @sergeibadass - please let me know if I can help further.
