### ISSUE TITLE
Pallet treasury

### ISSUE THREAD

**Issue by Daelon02** [paritytech/subport#165]
Hello, how many tokens can be kept in the treasury at least? We have accelerated the burning, and it shows that there are 10,000 tokens in the treasury

**Comment by Daelon02** [comment]
We use default substrate genesis config

**Comment by thiolliere** [comment]
AFAICT the treasury account can spend all its fund until the minimum balance (i.e. existential deposit).

**Comment by NukeManDan** [comment]
@Daelon02 - please let me know if you ended up finding what you needed, and if so leave some tips for others here?

We can reopen if you are able to provide more info about what you are having issues around specifically.
