### ISSUE TITLE
bug in release version

### ISSUE THREAD

**Issue by samuelpereira** [paritytech/subport#168]
Hi, 

I have installed by tag v3.0.0 and also release, and always get v2.0.0 its a "version" or I'm actually using v3.0.0 ?

cargo install --force subkey --git https://github.com/paritytech/substrate --tag release
    Updating git repository `https://github.com/paritytech/substrate`
  Installing subkey v2.0.0 (https://github.com/paritytech/substrate?tag=release#49a4103f)
    Updating crates.io index

Thanks,

**Comment by NukeManDan** [comment]
The latest subkey version is 2.0.1, not on crates.io, but on the repo itself: https://github.com/paritytech/substrate/blob/master/bin/utils/subkey/Cargo.toml#L3

you can install it like this: https://substrate.dev/docs/en/knowledgebase/integrate/subkey

Not all parts of substrate follow the same release tag. We use semver, only updating on _breaking_ changes for each crate.
