### ISSUE TITLE
Node template not available in the playground ide

### ISSUE THREAD

**Issue by andropixels** [paritytech/subport#169]
Not able to start the node on the playground ide for substrate ...
The following error  popsup.

Error: Service(Client(Backend("IO error: While lock file: /home/playground/.local/share/node-template/chains/dev/db/LOCK: Resource temporarily unavailable")))

**Comment by al3mart** [comment]
Sessions in the playground live for a limited time, I wonder if you have surpassed that limit as I am not able to reproduce the error.
Playground is working as usual for me.

**Comment by al3mart** [comment]
If this issue is still relevant, please feel free to reopen it back.
