### ISSUE TITLE
Question about Forkless Upgrade

### ISSUE THREAD

**Issue by MyronFanQiu** [paritytech/subport#17]
I knew that for pallet-runtime, substrate would build both native runtime and wasm runtime to achieve forkless upgrade. This is fantastic. 

Besides pallet-runtime, in the node-template, node would rely on some substrate client dependencies such as sc-network, sc-service, sc-executor and sc-consensus. If I built a blockchain based on alpha6 version, for example. Months later, I want to upgrade the dependencies to rc2. Would it casue hard fork for my blockchain?

Is there some suggestions and best practice for such scenario?

**Comment by JoshOrndorff** [comment]
In general, changing the logic in the non-runtime part of your node can cause a fork (hard or soft depending on how the logic changes). In practice, most of the changes that are introduced are backward compatible and will not cause a fork. Afterall, Polkadot and Kusama are always running latest Substrate, and they are not forking. After we release version Substrate 2.0, our crates will follow semantic versioning, so you will know which updates are compatible and which aren't.

**Comment by MyronFanQiu** [comment]
> In general, changing the logic in the non-runtime part of your node can cause a fork (hard or soft depending on how the logic changes). In practice, most of the changes that are introduced are backward compatible and will not cause a fork. Afterall, Polkadot and Kusama are always running latest Substrate, and they are not forking. After we release version Substrate 2.0, our crates will follow semantic versioning, so you will know which updates are compatible and which aren't.

Thanks for your reply. Good to know!
