### ISSUE TITLE
Parachain blocks are not getting finalized 

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#171]
I was following https://substrate.dev/cumulus-workshop and tried to connect parachain template wth relay chain.

Everything is working fine as per the tutorial. But I noticed one thing that parachain was able to produce blocks but blocks were not getting finalized.

Parachain:
![image](https://user-images.githubusercontent.com/1575561/119778439-29065080-bee5-11eb-9844-45860367c880.png)

Is there any specific reason for that? On the other hand, I can see block finalization in relaychain. 

Relaychain:
![image](https://user-images.githubusercontent.com/1575561/119778474-34f21280-bee5-11eb-8c8e-4c2d1f9fb941.png)

**Comment by ayushmishra2005** [comment]
I can see block finalization log in console but not in UI. Is this expected behavior?

**Comment by NukeManDan** [comment]
Are you using the correct ui at the commit specified?

**Comment by NukeManDan** [comment]
Try again with the latest updates to the workshop (just about to be published: https://github.com/substrate-developer-hub/cumulus-workshop/pull/68)

Please reopen if you can't get this working - remember to use the right commits all around and wait for the epoch change as noted!
