### ISSUE TITLE
about nonce problem

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/subport#172]
i did the several transactions requests with very fast time, i got the below error.
are there any way that i can do the cover with multi transactions with fast way , cuz of the below error , it is hard to transfer multi transactions with the fast time ?

**Comment by al3mart** [comment]
Batching transactions can help you going https://substrate.dev/rustdocs/v3.0.0-monthly-2021-05/pallet_utility/pallet/struct.Pallet.html#method.batch

Also, having a look at https://github.com/paritytech/sub-flood can give you new ideas too

**Comment by puffanddmx** [comment]
thanks any way
