### ISSUE TITLE
Can we do version downgrade through forkless runtime upgrade?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#176]
Is it possible to downgrade the version through forkless runtime upgrade?

**Comment by ayushmishra2005** [comment]
https://substrate.dev/rustdocs/v3.0.0-monthly-2021-05/frame_system/struct.LastRuntimeUpgradeInfo.html#method.was_upgraded

**Comment by thiolliere** [comment]
the call: `set_code` will check if the code can be set using https://substrate.dev/rustdocs/v3.0.0-monthly-2021-05/frame_system/pallet/struct.Pallet.html#method.can_set_code
Thus it will fail if spec_name doesn't match and spec version doesn't increase.

The call: `set_code_without_checks` will not check anything and set the code instead, thus setting a code without a different spec name or a decreasing spec version is accepted.
AFAICT from the runtime point of view then next block should use the new code without issues, but there might be some stuff I'm not aware of in the client.

Then in the next block the `on_runtime_upgrade` logic (as defined by pallets `on_runtime_upgrade` and `OnRuntimeUpgrade` given to [`Executive`](https://substrate.dev/rustdocs/v3.0.0-monthly-2021-05/frame_executive/struct.Executive.html) is executed only if [was_upgraded](https://substrate.dev/rustdocs/v3.0.0-monthly-2021-05/frame_system/struct.LastRuntimeUpgradeInfo.html#method.was_upgraded) is successful, meaning spec_name changed or version increased

**Comment by thiolliere** [comment]
But I wonder what is the usecase ? In case you want to downgrade the runtime, why not publishing a new runtime with an increased version and the old code ?

**Comment by ayushmishra2005** [comment]
> But I wonder what is the usecase ? In case you want to downgrade the runtime, why not publishing a new runtime with an increased version and the old code ?
Great thanks I think this would be best option.
