### ISSUE TITLE
How to set STASH amount in staking chain_spec configuration

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#179]
I am experimenting with staking. I am getting below error

<img width="908" alt="120600000-dccb8b00-c465-11eb-9c02-b825bda957f2" src="https://user-images.githubusercontent.com/1575561/120659864-65691c00-c4a4-11eb-8e62-26c6166dc979.png">

When I checked UI console, I found this

![image](https://user-images.githubusercontent.com/1575561/120660438-f63ff780-c4a4-11eb-9134-276fc4a98e94.png)

After changing `STASH` https://github.com/paritytech/substrate/blob/v3.0.0/bin/node/cli/src/chain_spec.rs#L275 amount, it started working. I am not able to relate to it. What is the correct way to set this amount? and why I am getting the above error?

Can someone please help me to understand this?

**Comment by NukeManDan** [comment]
Define "relate to it"? What are you trying to set? 
Are you modifying anything on the v3 node other than this value?

**Comment by ayushmishra2005** [comment]
@NukeManDan With this value https://github.com/paritytech/substrate/blob/v3.0.0/bin/node/cli/src/chain_spec.rs#L245, its working fine.

However when I changed it to


const ENDOWMENT: u128 =1_000_000_000_000_000_000_000_000_0_u128;
const TASH: u128 = ENDOWMENT / 1000;

it stopped working. If I reduce one more zero(1_000_000_000_000_000_000_000_000_u128), it works. 

@NukeManDan Could you please help me to understand this?

**Comment by ayushmishra2005** [comment]
Sorry @NukeManDan I should have explained it better. Its not related to u128. I recorrected my comment. please review https://github.com/paritytech/subport/issues/179#issuecomment-854725096

Regarding your other questions:

Node is compiling and running fine. It's also producing blocks. It's just that I am not able to open the staking module due to these parameters https://github.com/paritytech/subport/issues/179#issuecomment-854725096.

**Comment by ayushmishra2005** [comment]
@NukeManDan After spending lot of time on debugging, I found that there is an issue with UI compatibility. Its working fine with https://github.com/polkadot-js/apps/tree/v0.91.2 but not with the latest polkadot-js version.

**Comment by NukeManDan** [comment]
@ayushmishra2005 glad you found the problem.


https://github.com/polkadot-js/apps/issues/5468
