### ISSUE TITLE
No interface is provided to query transactions

### ISSUE THREAD

**Issue by wjy19990622** [paritytech/subport#18]
ℹ want query transactions by using transactions hash, but no public interface was found. what can i do?

**Comment by JoshOrndorff** [comment]
Polkadot JS Apps is a separate (but related) project from Substrate. It is housed on github at https://github.com/polkadot-js/apps

It does offer an interface for viewing extrinsic (basically transaction) details for _recent_ blocks. You can see it by going to the "Explore" tab and clicking on a block number.

You're correct that Apps does not offer a UI for querying arbitrary transactions in the history of the chain. That is the job of a block explorer. In the Substrate ecosystem, a good block explorer is polkascan. If you just want to use polkascan, you can see it at https://polkascan.io/. If you're building something yourself, they have lots of useful code at https://github.com/polkascan

**Comment by danforbes** [comment]
@wjy19990622 I hope these responses were helpful! Please let us know if you have additional questions.
