### ISSUE TITLE
Aura validator not generating blocks:  "ignoring digests not meant for us" in logs

### ISSUE THREAD

**Issue by Gauthamastro** [paritytech/subport#180]
I am trying to start a private testnet consisting of two validators: Alice and one other validator.

*chain_spec.rs has initial validator set as given below*

```
authority_keys_from_seed("Alice"),
authority_keys_from_seed("rabbit when hundred because during expect miracle illegal make alarm grunt crunch"),
```

I followed this tutorial [here](https://substrate.dev/docs/en/tutorials/start-a-private-network/customchain) to insert the session keys and restart the nodes, but even after that, blocks are not finalizing, and only Alice is generating blocks, and the other validator is showing logs as shown below

![Capture](https://user-images.githubusercontent.com/17110878/120753569-fd104e00-c528-11eb-9072-7795eb880e21.JPG)

What am I doing wrong? and what does this Ignoring digest not meant for us mean?

**Comment by hoanglamhuynh** [comment]
this is an exact copy of https://github.com/paritytech/subport/issues/180
are you the author?

Author: NukeManDan
