### ISSUE TITLE
Upgrading Polkadot Node

### ISSUE THREAD

**Issue by J-Cook-jr** [paritytech/subport#181]
I'm using 0.8.30 and I would like to update it to the latest release. Can someone walk me through the steps of doing this? Thanks!

**Comment by NukeManDan** [comment]
Updating what software(s) in particular? The typical process for a custom chain that needs to update breaking changes is to:
1. clone and checkout the old version of the repo
2. Perform a git squash merge with the target version (possibly just to the next release, and in steps from there untill the new target is reached)
3.  look for changes in the relevant files that are applicable for your customize code
4. update your cargo dependancides to the correct version on your code (via crates.io if published, or to the branch/tag on a git repo (github typically)) 
5. Update your cargo.lock dependancies as needed but **NOT everything!** - just what is needed via `cargo update -p foo --precise 1.2.3`
5. map the changes needed from the squash merge to your custom code
6. `do while not compiling {squish bugs}`

Let me know if you need further support or if that flow is not clear. 🙏🏼
