### ISSUE TITLE
How to fetch transaction fee through query

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#182]
I am able to fetch the current balance through https://polkadot.js.org/docs/api/examples/promise/read-storage-at

I transferred x amount from Alice to Bob. After a successful transaction, A has a previous balance - x amount - y fee.

I want to fetch this y fee.

**Comment by al3mart** [comment]
You want to use the calls in this section https://polkadot.js.org/docs/substrate/rpc#payment

**Comment by ayushmishra2005** [comment]
Thanks @al3mart

**Comment by emostov** [comment]
Those linked RPCs give estimates - which are ok as long as you don't need exact accounting. For anyone that needs exact fees for accounting options I know of are:

- dryRun extrinsic at exact block where it was included (the most versatile): https://polkadot.js.org/docs/substrate/rpc/#dryrunextrinsic-bytes-at-blockhash-applyextrinsicresult
- calc crate, which does arithmetic in rust and used in `/blocks` endpoint of sidecar to give exact `partialFee`: https://github.com/paritytech/substrate-api-sidecar/tree/master/calc

These will give the exact fee the tx used after it was included. Note the calc crate only supports a few specific runtime while dryRun should support much more runtimes.

**Comment by ayushmishra2005** [comment]
@emostov I am trying to hit dry_run using below query

```
const blockHash = '0xf487de8813810f4c4bac9e7a5ece4cf3fb9594eb7687cb1d7fd1f3dbeb8273c8';
const { block } = await api.rpc.chain.getBlock(blockHash);


const result = await api.rpc.system.dryRun(block.extrinsics[1].toHex(), blockHash);
console.log('Result:', JSON.stringify(result.toHuman()));
```

I am getting the below error

`Result: {"Err":{"Invalid":{"Stale":null}}}`

Please let me know if I am missing anything.
