### ISSUE TITLE
How to manually installl the subkey tool?

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/subport#184]
After running the following command `` `curl https://getsubstrate.io -sSf | bash -s -- --fast```
Ubuntu on windows run into the following 
```
Skipped cargo install of 'substrate' and 'subkey'
You can install manually by cloning the https://github.com/paritytech/substrate repo,
and using cargo to install 'substrate' and 'subkey' from the repo path.
Run source ~/.cargo/env now to update environment
```

How to install it manually?

**Comment by NukeManDan** [comment]
Use WSL https://substrate.dev/docs/en/knowledgebase/getting-started/

**Comment by noahsalvadordenjo** [comment]
Already ran and reopend terminal 
```cargo install --force subkey --git https://github.com/paritytech/substrate --version 2.0.1 --locked```
