### ISSUE TITLE
How to modify `Total Issuance` on-chain?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#186]
Would it be possible to change total issuance on-chain?

<img width="872" alt="Screenshot 2021-06-16 at 5 17 21 PM" src="https://user-images.githubusercontent.com/1575561/122213708-da861980-cec6-11eb-8815-cb5c804ad0fa.png">

**Comment by shawntabrizi** [comment]
Yes, you issue or burn tokens.

https://crates.parity.io/frame_support/traits/tokens/currency/trait.Currency.html

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/1860335/122220665-73f20300-cea8-11eb-879a-2ad1ea715766.png">

**Comment by ayushmishra2005** [comment]
@shawntabrizi Could you please share any example for reference?

**Comment by shawntabrizi** [comment]
Just look at any use of the `Currency` trait in Substrate or Polkadot.
