### ISSUE TITLE
`TotalIssuance` is not decreased

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#187]
As per this comment https://github.com/paritytech/substrate/blob/ede9bc19e883005d6bb71f325f13c90e03cea9c2/frame/balances/src/lib.rs#L275 `TotalIssuance` should get decreased after altering `FreeBalance` and `ReservedBalance` .

But it is increasing rather than decreasing. Please help me to understand this. Is this an issue?

**Comment by shawntabrizi** [comment]
@ayushmishra2005 total issuance is a tracker of how much total balance is in your system across all the users.

The total issuance will only decrease if you reduce the free / reserved balance of an existing account.

If you instead give an account new funds, the total issuance will obviously increase.

**Comment by ayushmishra2005** [comment]
@shawntabrizi 

I have a scenario, 

Suppose Total Issuance is 100 units.

I created a new account `Test`. I used `Balances.set_balance` to set 10 units as its free balance.

Now total issuance is showing as 110 units, which is expected.

If I delete that `Test` account, the total issuance should be back to 100 units. But this is not happening. Total Issuance is still showing as 110 Unit.

I don't know whether its a bug or expected behavior. I don't know whether its a polkadot.js UI issue.

How could I reduce total issuance, if someone increased it by mistake by following above steps?

**Comment by shawntabrizi** [comment]
What does "delete" that account mean.

**Comment by ayushmishra2005** [comment]
@shawntabrizi 

I reframed my comment. Please check again https://github.com/paritytech/subport/issues/187#issuecomment-863179457. By `delete` I meant, `Forget This Account`. 

<img width="1404" alt="Screenshot 2021-06-18 at 11 40 39 AM" src="https://user-images.githubusercontent.com/1575561/122514801-24d3db80-d02a-11eb-8cec-f28ebbc87391.png">

**Comment by shawntabrizi** [comment]
Forget this account does not actually do anything on the blockchain.

it is just the front-end javascript removing the private keys of the account from your cache.

If you call `set_balance` and set a users balances to all 0, then you will see the decrease.

**Comment by ayushmishra2005** [comment]
@shawntabrizi 

Could you please reopen the issue? I haven't got the answer. I know that  `set_balance` would increase/decrease _total issuance_.

Here is what I am trying to explain:

1) Supposed I created a new account `TEST` and used `set_balance` to set 10 UNITS in its balance. This increased _total issuance_.

2) I removed this new account `TEST` using `Forget This Account`. Now I don't see this account in browser.

3) Now I want to reduce _total issuance_ by 10 UNITS, which I added to the above _TEST_ account. Since this account is not visible so I couldn't set its balance back to ZERO.

How could I reduce _total issuance_ by 10 UNITS now? The only option is to set the balance of existing accounts, which I didn't touch. This is not the good approach.

I want to reduce those 10 UNITS from _total issuance_, which I set in the newly added `TEST` account by mistake and couldn't set to ZERO back because I removed this new account `TEST` using `Forget This Account`. 

Please help me to fix this.

**Comment by shawntabrizi** [comment]
You can go into the blockchain storage explorer and query `System > Accounts` to see all the accounts with some balance in your system.

Then you can find your TEST account address and delete it using `set_balance`

**Comment by ayushmishra2005** [comment]
@shawntabrizi 

As I mentioned above, once I click _Forget This Account_ for TEST account, it gets disappeared/removed from everywhere. I don't see it in _System > Accounts_. 

If It was still there, I would have set its balance. But unfortunately, after clicking `Forget This Account`, I can't find it anywhere.

**Comment by shawntabrizi** [comment]
<img width="949" alt="image" src="https://user-images.githubusercontent.com/1860335/122552726-901fac80-d02e-11eb-89b3-98688ea63a13.png">

With the "include option" turned off will return all the accounts in your blockchain.

You should be able to find the account you want there.

You should review how to query the storage of your blockchain: https://www.shawntabrizi.com/substrate/transparent-keys-in-substrate/

**Comment by ayushmishra2005** [comment]
This is AWESOME @shawntabrizi .  This is what I was looking for. Great Thanks.
