### ISSUE TITLE
how to use substrate in c/c++ ?

### ISSUE THREAD

**Issue by cSingleboy** [paritytech/subport#190]
like title ....

**Comment by shawntabrizi** [comment]
Substrate is a Rust framework, so there really isn't a way.

Between the Substrate Node and the Runtime, there is a Wasm abstraction, and technically, this Wasm could be generated from C/C++ code, but this would be very advance and a lot of work, and not really something anyone has achieved yet.

**Comment by baidang201** [comment]
if you find polkadot c++ host, there are a c++ project https://github.com/soramitsu/kagome

Kagome is a Polkadot Host (former Polkadot Runtime Environment) developed by Soramitsu and funded by Web3 Foundation grant.

**Comment by shawntabrizi** [comment]
Its not quite "substrate" though. It is a "Polkadot Runtime Environment" which is not an extensible blockchain development framework, but a specific client for running a polkadot node using C++

But yeah, a good resource for sure 👍
