### ISSUE TITLE
How `return`s are getting calculated on `Staking>>Targets`

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#192]
How `return`s are getting calculated on `Staking>>Targets`?

<img width="1406" alt="Screenshot 2021-06-24 at 6 21 16 PM" src="https://user-images.githubusercontent.com/1575561/123265782-06357f00-d519-11eb-82a7-c839057a354f.png">

**Comment by NukeManDan** [comment]
calculation: https://github.com/polkadot-js/apps/blob/8a95b1a93b21cfd3a7cc0a24e1e08cb5022dc391/packages/react-hooks/src/useInflation.ts#L36

found in that page here: https://github.com/polkadot-js/apps/blob/d91bdcd191e7ca703fc7618188ab4a9a62763879/packages/page-staking/src/Targets/index.tsx
