### ISSUE TITLE
What should be staking `REWARD_CURVE` value for a standalone chain?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#193]
What should be staking `REWARD_CURVE` value for a standalone chain? In Polkadot, it is mentioned that if there's no parachains, then this is 75% staked : 25% float. What does this mean?

https://github.com/paritytech/polkadot/blob/master/runtime/polkadot/src/lib.rs#L381-L392

![image](https://user-images.githubusercontent.com/1575561/123285161-700a5480-d52a-11eb-835d-ad2ba3c935be.png)

**Comment by NukeManDan** [comment]
The high level details are here: https://wiki.polkadot.network/docs/learn-staking/#inflation
more details: https://w3f-research.readthedocs.io/en/latest/polkadot/overview/2-token-economics.html

You must evaluate your tokenomics for your solo chain to see what makes most sense, per your configuration.
