### ISSUE TITLE
Can we do `Forkless-Upgrade` on server using locally created WASMs?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#197]
Can we do `Forkless-Upgrade` on server using locally created WASMs? or we should always create WASM on server bootnode?

Would there be any impact or harm of doing that?

**Comment by NukeManDan** [comment]
Reply from an element that you asked this in as well:

>It doesn't matter.
>The proposed WASM file will be used by all of your collators/validators.
>Something to consider is that after doing the forkless upgrade, you should copy the binary you built to all the validators and bootnodes so they can have the latest non-runtime changes.
