### ISSUE TITLE
How to use try-runtime???

### ISSUE THREAD

**Issue by Irish-bee** [paritytech/subport#198]
hello,guys! How to use try-runtime?  Could you please write a doc about it?

**Comment by shawntabrizi** [comment]
@Irish-bee there is a video presentation here: https://www.crowdcast.io/e/substrate-seminar/41

**Comment by sacha-l** [comment]
WIP [here](https://github.com/substrate-developer-hub/substrate-developer-hub.github.io/pull/1056) and some how-to guides to follow 😃
