### ISSUE TITLE
How to debug in pallet benchmark

### ISSUE THREAD

**Issue by AsceticBear** [paritytech/subport#199]
![image](https://user-images.githubusercontent.com/11801722/124235923-714e0980-db48-11eb-9409-4008f24bbc78.png)

I am writing pallet benchmark tests and want to print the caller info here. Can somebody help me figure out why can not output the caller?

**Comment by NukeManDan** [comment]
Stupid question: what is the return type of `caller` and does it implement the `Debug` trait?

**Comment by AsceticBear** [comment]
Thanks for your reminder. Use `--execution native` solve this problem. 

```rs
#[cfg(feature = "std")]
impl std::fmt::Display for AccountId32 {
	fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
		write!(f, "{}", self.to_ss58check())
	}
}

impl sp_std::fmt::Debug for AccountId32 {
	#[cfg(feature = "std")]
	fn fmt(&self, f: &mut sp_std::fmt::Formatter) -> sp_std::fmt::Result {
		let s = self.to_ss58check();
		write!(f, "{} ({}...)", crate::hexdisplay::HexDisplay::from(&self.0), &s[0..8])
	}

	#[cfg(not(feature = "std"))]
	fn fmt(&self, _: &mut sp_std::fmt::Formatter) -> sp_std::fmt::Result {
		Ok(())
	}
}
```
