### ISSUE TITLE
Pallet-staking

### ISSUE THREAD

**Issue by Daelon02** [paritytech/subport#200]
Hi, where i can set a minimum bond value?

**Comment by NukeManDan** [comment]
https://github.com/paritytech/substrate/blob/cf4e320398cf3b8ef8a2c240d7495c25b3b73b08/frame/staking/src/lib.rs#L972-L978

This is set in the chain-spec for genesis typically. 
https://github.com/paritytech/substrate/blob/c6240ce90083f9e8db94b6c33f81297c11534ea0/frame/staking/src/lib.rs#L1269
