### ISSUE TITLE
why my peer count is so low?

### ISSUE THREAD

**Issue by gitloverr** [paritytech/subport#203]
hi everyone,

I have a two polkadot node and it versions are 0.9.5 and 0.9.7 . but peer count of nodes seems 3 or sometimes 4. why so low this count. I checked on telemetry the other nodes status, they have ~ 30-50 peers?

Why my nodes isn't ? what should I do for increase my peer count?

thank you

**Comment by NukeManDan** [comment]
There are breaking changes requiring an update to 0.9.8 to sync with other nodes. You must update
https://github.com/paritytech/polkadot/releases/tag/v0.9.8

**Comment by gitloverr** [comment]
hi @NukeManDan ,

I started also polkadot 0.9.8 , it has same problem.

Version: `polkadot 0.9.8-3a10ee63c-x86_64-linux-gnu`

Peer status:
 `
{
  "health": {
    "peers": "1",
    "isSyncing": false,
    "shouldHavePeers": true
  }
}
`

how do I solve this issue? Please open this issue again...

thank you

**Comment by NukeManDan** [comment]
Can you elaborate on your system setup and node configuration?

**Comment by gitloverr** [comment]
hi @NukeManDan ,

I used both binary and docker image for 0.9.8 and I started those nodes has same problem. (on both CentOS 8 and 7 machines ) Is there any point you want to learn?

thank you

**Comment by NukeManDan** [comment]
Yes:
- your system setup (cpu, ram, OS) 
- your network (are you in a cloud host? What bandwidth do you have? What ports are available?)
- the exact call you using to launch (flags and such for the CLI)

**Comment by NukeManDan** [comment]
Please open again with more info if you still need help 🙏🏼

**Comment by gitloverr** [comment]
hi @NukeManDan,

my peers decreased then synced:

**while syncing**

`
```
{
  "health": {
    "peers": "45",
    "isSyncing": true,
    "shouldHavePeers": true
  }
}
```
`

**after syncing**

{
  "health": {
    "peers": "1",
    "isSyncing": false,
    "shouldHavePeers": true
  }
}

why so?

my machine: 

**OS: Centos7
RAM: 8GB
CPU:  1.70GHz 1 CORE**

**Comment by decentration** [comment]
@gitloverr Docker is causing my lowered peer count https://github.com/paritytech/subport/issues/291
