### ISSUE TITLE
Get `event_count` failed in test.rs

### ISSUE THREAD

**Issue by AsceticBear** [paritytech/subport#206]
![image](https://user-images.githubusercontent.com/11801722/126334524-c696e3b3-f375-45da-b03e-cb64dcbc67fd.png)

I am trying to calculate event numbers, but the result is not right, any idea about this?

**Comment by AsceticBear** [comment]
Solved: `ext.execute_with(|| System::set_block_number(1));` The TestExternalities block number must large than 0.

**Comment by shawntabrizi** [comment]
Yes. This is a little bit of an unfortunate easter egg.

We turn off events on block 0 because we don't want a million events in the genesis block when starting a chain.

**Comment by AsceticBear** [comment]
@shawntabrizi  Is it possible to catch the event in my own pallets? As I see, `event_count()`, `events()` .... all belongs to System.  A example like `MyPallet::event_count()`?

**Comment by shawntabrizi** [comment]
events is just a storage item, and `deposit_event` is just implemented here:

https://github.com/paritytech/substrate/blob/master/frame/system/src/lib.rs#L1233

So you can write whatever code you want that will satisfy this
