### ISSUE TITLE
Bootnode with peer id `1#################################Pb` is on a different chain (our genesis: 0x2f....…75cb theirs: 0x....…58bd) 

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#208]
I am running a validator on local using the below command and trying to connect a node running on a different server. 

./target/release/myapplication \
  --validator \
  --base-path ~/chain-base/node-X1 \
  --chain ./node/chain_def_server.json \
  --name "Local - Validator X1" \
  --port 30334 \
  --rpc-port 9934 \
  --ws-port 9945 \
  --telemetry-url 'wss://telemetry.polkadot.io/submit/ 0' \
  --unsafe-ws-external \
  --unsafe-rpc-external \
  --bootnodes /ip4/1.111.111.111/tcp/30333/p2p/1#################################Pb \
  --rpc-cors=all \
  --rpc-methods=Unsafe

I am getting the below log on the console:

```
2021-07-26 09:57:47 Bootnode with peer id `1#################################Pb` is on a different chain (our genesis: 0x2f....…75cb theirs: 0x....…58bd)    
2021-07-26 09:57:50 💤 Idle (0 peers), best: #0 (0x2f....…75cb), finalized #0 (0x2f....…75cb), ⬇ 11.5kiB/s ⬆ 5.2kiB/s    
2021-07-26 09:57:55 💤 Idle (0 peers), best: #0 (0x2f....…75cb), finalized #0 (0x2f....…75cb), ⬇ 5.0kiB/s ⬆ 0.7kiB/s 
```

I followed this solution https://stackoverflow.com/a/66555306/1714250 and copied chain spec from server. I am running validator with the same chain-spec, which server node is using.

Please let me know what I am missing here.

**Comment by BCarlaYap** [comment]
Hi@ayushmishra2005, I had the same problem as you.
I used the raw chain spec json file though:
```
./target/release/node-template build-spec --chain=customSpec.json --raw --disable-default-bootnode > customSpecRaw.json
```

**Comment by ayushmishra2005** [comment]
> Hi @ayushmishra2005, I had the same problem as you.
> I used the raw chain spec json file though:
> 
> ```
> ./target/release/node-template build-spec --chain=customSpec.json --raw --disable-default-bootnode > customSpecRaw.json
> ```
@BCarlaYap Did this fix the issue?

**Comment by BCarlaYap** [comment]
> > Hi @ayushmishra2005, I had the same problem as you.
> > I used the raw chain spec json file though:
> > ```
> > ./target/release/node-template build-spec --chain=customSpec.json --raw --disable-default-bootnode > customSpecRaw.json
> > ```
> 
> @BCarlaYap Did this fix the issue?

For me, yep. it's found here: https://substrate.dev/docs/en/tutorials/start-a-private-network/customspec

I hope it works for you

**Comment by ayushmishra2005** [comment]
@BCarlaYap Unfortunately it's not working for me

**Comment by BCarlaYap** [comment]
Oh no...
@ayushmishra2005 can you try purging node-X-1? so that the genesis blocks are the same for both?
then connect again to the boot node...

**Comment by ayushmishra2005** [comment]
@BCarlaYap I already did that. But it's not working. 

One more thing, I want to mention here. The server was deployed at v1.0.0 and later, it has been upgraded to v3.0.0.

On local, I checked out to v3.0.0 directly>> Created fresh build>> and from there I am trying to run the validator.

Do you think I am missing something here?

**Comment by ayushmishra2005** [comment]
Can someone please help on this issue?

**Comment by NukeManDan** [comment]
https://substrate.dev/docs/en/tutorials/start-a-private-network/customspec
> **A critical note:** A single person should create the chain spec and share the resulting customSpecRaw.json file with their fellow validators.

Did you do this?

**Comment by ayushmishra2005** [comment]
@NukeManDan my server is running with chain_def_server.json. I downloaded the same on local. Do I still need to convert into the raw spec?

**Comment by BCarlaYap** [comment]
@ayushmishra2005 can you show what's inside your `chain_def_server.json` ? 
If you take a look again in the tutorial, it said **_raw_**, meaning your json file should look something like:
```json
{
  "name": "Development",
  "id": "dev",
  "chainType": "Development",
  "bootNodes": [],
  "telemetryEndpoints": null,
  "protocolId": null,
  "properties": null,
  "consensusEngine": null,
  "lightSyncState": null,
  "genesis": {
    "raw": {
      "top": {...},
      "childrenDefault": {}
    }
  }
}

```

**Comment by ayushmishra2005** [comment]
@BCarlaYap Yes, Its raw.


```
{
  "name": "Mainnet",
  "id": "mainnet",
  "chainType": "Live",
  "bootNodes": [
    "/ip4/1.111.111.111/tcp/30333/p2p/1#################################Pb"
  ],
  "telemetryEndpoints": [
    [
      "/dns/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F",
      0
    ]
  ],
  "protocolId": "abc-mainnet",
  "properties": {
    "tokenDecimals": 18,
    "tokenSymbol": "ABC"
  },
  "forkBlocks": null,
  "badBlocks": null,
  "consensusEngine": null,
  "lightSyncState": null,
  "genesis": {
    "raw": {
      "top": {
        "0x#######5": "0x0000"
      },
      "childrenDefault": {}
    }
  }
}
```

**Comment by NukeManDan** [comment]
Have you tried to purge the chain and start again from Genesis? Do confirm the chain spec is the same bitwise to be sure. 

You could [check the hash](https://askubuntu.com/questions/61826/how-do-i-check-the-sha1-hash-of-a-file) to be sure.

Both nodes are now using the latest version starting from no previous state?

**Comment by ayushmishra2005** [comment]
@NukeManDan Yes, I already purged chain. 

I checked the hash of file on server and local. They are same.

Server Response:

`sha1sum /home/chain_def.json`

`bd4######################2c0  /home/chain_def.json`

Local Machine Response:

`shasum node/chain_def.json`

```
perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
        LC_ALL = (unset),
        LC_CTYPE = "en_IN.UTF-8",
        LANG = (unset)
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
bd4######################2c0  node/chain_def.json
```

**Comment by NukeManDan** [comment]
It is unclear what the issue is then. I do notice the name of the file is different from your original post, just to double check that is right.

You mentioned you used two different versions of the node, I suggest you build the same code on both machines to try again, and if the same architecture, try the binary from one to be used on both. 

Are you using the same CLI flags for both?

**Comment by ayushmishra2005** [comment]
> It is unclear what the issue is then. I do notice the name of the file is different from your original post, just to double check that is right.
> 
> You mentioned you used two different versions of the node, I suggest you build the same code on both machines to try again, and if the same architecture, try the binary from one to be used on both.
> 
> Are you using the same CLI flags for both?

@NukeManDan please ignore file name. I am using same file on server and local. As I mentioned in above comment, hash is same for both files(One is on server, another one, which I downloaded on local from server).


Regarding your suggestion `You mentioned you used two different versions of the node, I suggest you build the same code on both machines to try again, and if the same architecture, try the binary from one to be used on both.`: Unfortunately, I can't try this on the production server.

What do you mean by `same CLI flags`?

**Comment by NukeManDan** [comment]
> What do you mean by same CLI flags?
The exact command you use to start your nodes, like discussed [here](https://substrate.dev/docs/en/tutorials/start-a-private-network/alicebob#alice-starts-first)

> One more thing, I want to mention here. The server was deployed at v1.0.0 and later, it has been upgraded to v3.0.0.
> On local, I checked out to v3.0.0 directly>> Created fresh build>> and from there I am trying to run the validator.

If you are still running substrate v1 client for a node, it is not going to be compatible with v3 nodes AFAIK. You likely need to access (or otherwise request) this server to update.

**Comment by ayushmishra2005** [comment]
@NukeManDan Yes, I am using same CLI flags on local, which are being used on server.

Server node was deployed on v1 and later it has been upgraded to v3 through forkless upgrade. On local, I directly checked out to v3 and build the node.

**Comment by NukeManDan** [comment]
The client is the issue. There are breaking changes in the node between versions. You must update more than just the runtime, and install this new software for v3.

Any code changes outside your runtime folder (in your node folder) can cause breaking changes that require a node client update.

Your original issue is likely due to a breaking change in how the chainspec is read.

**Comment by ayushmishra2005** [comment]
Sorry, @NukeManDan for the delay in my response. 

I couldn't understand your above comment. Neither I can nor I can ask to do any update/change on server. Please let me know what should I try on local.

**Comment by ayushmishra2005** [comment]
> The client is the issue. There are breaking changes in the node between versions. You must update more than just the runtime, and install this new software for v3.
> 
> Any code changes outside your runtime folder (in your node folder) can cause breaking changes that require a node client update.
> 
> Your original issue is likely due to a breaking change in how the chainspec is read.

Hey, @NukeManDan I just want to confirm my understanding. Are you suggesting that

1) I should update all validators with the latest code.

2) Regenerate Chain_spec on main boot node, transfer that file to all validators and restart all validators with new chain_spec
?

**Comment by NukeManDan** [comment]
@ayushmishra2005 is this still a problem? Circling back to this if needed, after you do attempt the generation of and passing around of the chainspec from both the old node, and the new ones to all new nodes.
