### ISSUE TITLE
There isn't exist a standard way to change the ss58 address format to another like Bech32

### ISSUE THREAD

**Issue by sinitcin** [paritytech/subport#210]
Hey guys! I spent 2 weeks managing this task but it seems doesn't work at all.

**Comment by NukeManDan** [comment]
I think we talked about your needs previously. Can you link and quote that here?

**Comment by sinitcin** [comment]
> I think we talked about your needs previously. Can you link and quote that here?

Hi Dan, yes we talk about this in the Matrix. Today later I'll send the details.

**Comment by sinitcin** [comment]
1. Implement Public struct:

```rust
#[derive(Clone, Encode, Decode, PassByInner, MaxEncodedLen)]
pub struct Public(pub [u8; COMPRESSED_PUBKEY_LEN]);
...
impl TraitPublic for Public 
```

The Public struct should have the possibility to create from Bech32 p2wpkh and p2wsh, phrase, Private compressed key and from Ss58, is it?
2. Implement SecretKey analogously.
3. Implement Pair:

```rust
/// A key pair.
#[cfg(feature = "full_crypto")]
#[derive(Clone)]
pub struct Pair {
    public: PublicKey,
    secret: SecretKey,
}#[cfg(feature = "full_crypto")]
impl TraitPair for Pair {
...
```

4. Implement Bech32Codec analogously like Ss58Codec:

```rust
/// Key that can be encoded to/from SS58.
///
/// See <https://github.com/paritytech/substrate/wiki/External-Address-Format-(SS58)#address-type>
/// for information on the codec.
pub trait Ss58Codec: Sized + AsMut<[u8]> + AsRef<[u8]> + Default {
```

5. Add an implementation Bech32Codec for AccountId32

```rust
impl Bech32Codec for AccountId32 {}
```

6. Implement AddressMapping trait:

```rust
pub struct HashedAddressMapping;impl AddressMapping<AccountId32> for HashedAddressMapping {

fn into_account_id(address: H160) -> AccountId32 {
    let mut data = [0u8; 32];
    data[0..20].copy_from_slice(&address[..]);
    AccountId32::from(Into::<[u8; 32]>::into(data))
  }
}
```
And the structure be like:

```rust
pub struct AccountInfo {
    pub address: H160,
    pub account_id: AccountId32,
    pub private_key: H256,
}
```

But I'm newby in the Substrate and probably I'm wrong guys!

**Comment by sinitcin** [comment]
Any thoughts guys?
