### ISSUE TITLE
Facing Issue in Adding Instant-seal on Substrate V2 code.

### ISSUE THREAD

**Issue by PankajMUI** [paritytech/subport#211]
I have a code which is working on substrate V2. Now i am adding the Instant-seal to it. 
The code is building fine.
But when i am doing the transection It is giving me the Error.
Error:
`1010: Invalid Transection: Inability to pay some fees , eg. account balance is too low`

**Comment by NukeManDan** [comment]
You need funds in the account submitting the extrinsic. Are you using prefunded accounts? The node template --Dev flag includes a few. They are set in your chainspec file.

**Comment by PankajMUI** [comment]
Yeah the funds is available in the account(the chainspec file is same as previous).

**Comment by NukeManDan** [comment]
I am not familiar with instant seal, but I think you need to configure your chain spec differently. It may be leading to an issue here .

What are you using to issue transactions? Api? Apps ui? Other?

**Comment by NukeManDan** [comment]
@PankajMUI please reopen this issue if you still need support 🙏🏼
