### ISSUE TITLE
BABE + GRANDPA (0 blocks are finalized)

### ISSUE THREAD

**Issue by true-eye** [paritytech/subport#213]
I run a testnet with three nodes. (one bootnode & two full nodes). based on BABE + GRANDPA.
Right now, it produces blocks but 0 blocks are finalized.

For bootnode,
`/home/ubuntu/test-node --alice --chain=/home/ubuntu/customSpecRaw.json --validator --telemetry-url wss://telemetry.polkadot.io/submit/ 0`

For fullnode,
`/home/ubuntu/test-node --chain=/home/ubuntu/customSpecRaw.json --rpc-cors=all --bootnodes /ip4/3.7.55.131/tcp/30333/p2p/xxx --telemetry-url wss://telemetry.polkadot.io/submit/ 0`

I'm not sure why it doesn't finalize blocks. Please help me.

Note: As I provide `--alice` flag for bootnode. Does this mean I don't need to insert keys using RPC, right? What about fullnodes?

**Comment by bkchr** [comment]
Where is `customSpecRaw` coming from? Are you sure that you configured grandpa correctly?

**Comment by NukeManDan** [comment]
@true-eye still need support? If so, please re-open this issue (or just comment here)
