### ISSUE TITLE
Regarding the participation of archive nodes in the staking workflow 

### ISSUE THREAD

**Issue by gokulsan** [paritytech/subport#216]
Hello Everyone,

I have a question on Polkadot archive nodes and their possible role in a staking workflow. Can archive nodes participate in the staking workflow for an NFT platform built on Polkadot Substrate Pallets.

**Comment by NukeManDan** [comment]
Archive nodes are normal nodes that retain all block history. Thus you can do anything a normal node could do, with the addition of directly accessing historical state. Staking is not related to node operations, or applications build on top of a substrate network.

**Comment by gokulsan** [comment]
Thank you so much for answering the question on GitHub and StackOverflow. However it is not yet explaining why archive nodes cannot participate in the staking. If the archive nodes cannot participate in the staking process, it could be a reason for slashing attack from their side.  This would make them the perfect reason for the nothing at stake scenario. As Archive Nodes are very powerful they can unleash nothing at stake attack.

**Comment by NukeManDan** [comment]
I don;t think what you are saying here makes any sense. Do you mean _validators_ cannot be archive nodes? This is not the case. Why do you think this?
