### ISSUE TITLE
Sandwich Attacks & Front Running Attacks from Adversarial Archive Nodes

### ISSUE THREAD

**Issue by gokulsan** [paritytech/subport#217]
Hello Everyone,

Could you please advise me if there are threat vectors from archive nodes such as front running attacks, sandwich attacks and nothing at stake attacks as they are quite powerful interms of the infrastructure and information architecture. How do we prevent scenarios when they become byzantine and become powerful and practical adversaries.

**Comment by NukeManDan** [comment]
Define an archive node for me? I do not see how this is at all related to attacks on a network.

**Comment by NukeManDan** [comment]
Please add more context here so I can help, for now I am closing the issue.
