### ISSUE TITLE
cross chain

### ISSUE THREAD

**Issue by Sunyangyang12** [paritytech/subport#230]
Thanks for your reply, Is there a tutorial on how to build a cross-chain project based on polkadot about Ethereum and Bitcoin (or Fabric) ?

**Comment by al3mart** [comment]
What  I think you might be looking for is what we name Bridges. There is not tutorials yet on them, but you can find a talk on that topic in this [crowdcast](https://www.crowdcast.io/e/substrate-seminar/12)
