### ISSUE TITLE
error: failed to select a version for the requirement crypto-mac = "^0.7"

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#231]
I am getting below error while compiling code with Substrate 3.0.0
```

ayushkumarmishra@Ayushs-MacBook-Pro node % cargo build --release              
    Updating crates.io index
error: failed to select a version for the requirement `crypto-mac = "^0.7"`
candidate versions found which didn't match: 0.11.1, 0.11.0, 0.10.1, ...
location searched: crates.io index
required by package `hmac v0.7.0`
    ... which is depended on by `hmac-drbg v0.2.0`
    ... which is depended on by `libsecp256k1 v0.3.4`
    ... which is depended on by `sc-executor v0.9.0`
    ... which is depended on by `datahighway v3.0.5 (/Users/ayushkumarmishra/workspace/node/node)`
       
```
Please help me to fix this.

**Comment by ayushmishra2005** [comment]
also I want to add crypto-mac 0.7.0 has been deleted here https://crates.io/crates/crypto-mac/versions

**Comment by ltfschoen** [comment]
crypto-mac 0.7.0 has been added back to https://crates.io/crates/crypto-mac/versions
latest Substrate commit is building again

**Comment by al3mart** [comment]
I guess we can close this issue then, feel free to open it again if this is still relevant.

**Comment by ltfschoen** [comment]
note that this issue is related to this Substrate issue https://github.com/paritytech/substrate/issues/9633
