### ISSUE TITLE
error: failed to select a version for `snow`.

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#232]
```
error: failed to select a version for `snow`.
    ... required by package `libp2p-noise v0.29.0`
    ... which is depended on by `libp2p v0.34.0`
    ... which is depended on by `sc-authority-discovery v0.9.0`
versions that meet the requirements `^0.7.1` are: 0.7.2, 0.7.1

all possible versions conflict with previously selected packages.

  previously selected package `snow v0.7.1`
    ... which is depended on by `libp2p-noise v0.29.0`
    ... which is depended on by `libp2p v0.34.0`
    ... which is depended on by `sc-authority-discovery v0.9.0`

```

I am getting this error while compiling my substrate code. Can someone please help me to fix this?

**Comment by al3mart** [comment]
Resetting your Cargo.lock might help

**Comment by ayushmishra2005** [comment]
@al3mart I am getting above error after executing below commands:

```
cargo clean
git stash
rm -rf Cargo.lock 
cargo build --release
```

**Comment by ltfschoen** [comment]
it appears to be related to dependencies being removed from crates.io https://crates.io/crates/snow/versions

**Comment by NukeManDan** [comment]
@ltfschoen looks like your mentioned PR above solved this? If not, let's reopen.

**Comment by NukeManDan** [comment]
I am working on another project with this error. _Keep_ the lock file, and update snow (7.3 was [yanked](https://crates.io/crates/snow/versions))

```
cargo update -p snow --precise 0.7.2
```

This got my build working.
