### ISSUE TITLE
Bridging

### ISSUE THREAD

**Issue by timo-cmd2** [paritytech/subport#233]
Hello everyone 👋🏻

**Your work with Substrate is so freaking awesome ❤️ Keep this up!**

I am currently working on a parachain-based NFT token and was just wondering if you could use/interact with the Substrate from other host-languages such as C++ or Golang. Do such bridges exist?

Thanks for your support 

Best regards

Timo Sarkar

**Comment by NukeManDan** [comment]
If you are looking for _client_ libraries to talk to your node, checkout https://github.com/substrate-developer-hub/awesome-substrate - there are a few langs to choose from. If you are looking for a node implementation, https://github.com/ChainSafe/gossamer/ is a Polkadot impl in go, not a full substrate compliant node though. Could be used as a reference :)
