### ISSUE TITLE
Why 'multisig signatory' is not showing while authorizing multisig transaction?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#234]
Steps:

1) I created 3 accounts on parity singer and imported them in Rococo testnet

![image](https://user-images.githubusercontent.com/1575561/132278863-8d6312af-4ccd-4863-bd9a-ed143809cba4.png)

2) I created a multi-sig account and transfer some funds.

![image](https://user-images.githubusercontent.com/1575561/132279303-5da16d61-87bc-4355-aa41-db4c49ec42bd.png)

3) I created an account on browser locally and tried to transfer some funds from mulsig account.

![image](https://user-images.githubusercontent.com/1575561/132279081-1affce06-0fff-4d25-b74e-63976094da5e.png)

4) I should see 'multisig signatory' option on this next screen but this is not happening.

![image](https://user-images.githubusercontent.com/1575561/132279103-b31df766-43a0-4fe6-94db-b04e0b513ffb.png)

Please let me know if I am missing something.

**Comment by NukeManDan** [comment]
https://wiki.polkadot.network/docs/learn-accounts#example-with-polkadotjs has a detailed walkthrough on this and https://www.youtube.com/watch?v=ZJLqszvhMyM&list=PLOyWqupZ-WGuAuS00rK-pebTMAOxW41W8&index=26 is an explainer video to review as well.

You need to set the threshold and specific accounts to be included. How did you configure the multisig exactly?

**Comment by ayushmishra2005** [comment]
@NukeManDan Yes, I followed https://www.youtube.com/watch?v=ZJLqszvhMyM&list=PLOyWqupZ-WGuAuS00rK-pebTMAOxW41W8&index=27 except account creation part, which I created through Parity signer.

please find below the steps, which I followed 

1) I created 3 accounts on Paraity signer and imported them in Rococo testnet 

![image](https://user-images.githubusercontent.com/1575561/132432756-d803f9d1-57d9-457c-82cb-92565a51d361.png)

2) Created Multi Sig account

![image](https://user-images.githubusercontent.com/1575561/132432995-04582b20-4791-4f03-8821-968e6bfbcbc8.png)

3) Transferred 10 ROC to multisig account and Created an account locally

![image](https://user-images.githubusercontent.com/1575561/132433177-219bfa6f-31d7-4edd-a5dd-2a408d645732.png)

4) Tried to transfer 10 ROC from multisig account to local account

![image](https://user-images.githubusercontent.com/1575561/132433378-00c990da-a11a-44d4-bffc-05c0814bc832.png)

But not getting  'multisig signatory' option on this next screen

![image](https://user-images.githubusercontent.com/1575561/132433409-c299b309-13ce-47bc-82bb-f8109db3a065.png)

Even If I submit `Sign and Submit`, it keeps loading. Please let me know if I have missed any step.

**Comment by NukeManDan** [comment]
Are you able yo create a multisig with in app accounts and or via the extension and the correct modal appears? 

Have you tried to use the extrinsics tab to manually step through the process and are blocked there as well?

**Comment by ayushmishra2005** [comment]
`Are you able yo create a multisig with in app accounts and or via the extension and the correct modal appears?`. =>


No @NukeManDan I didn't try to create multisig with app accounts. I was trying with Parity Signer accounts because this is my usecase. 

I will try and let you know.


`Have you tried to use the extrinsics tab to manually step through the process and are blocked there as well?` No I haven't tried this. Let me try.

**Comment by ayushmishra2005** [comment]
@NukeManDan Unfortunately this is also not working with app accounts.

1) I created 3 apps accounts >> created multisig with threshold 2 >> transfer some fund to new multisig from one of app account >> tried to transfer fund from multisig to new app account : I am facing same issue.

![image](https://user-images.githubusercontent.com/1575561/132452469-e2a77309-0b21-4bf1-b158-57bd7c8d95dd.png)


2) I also tried to transfer through extrinsic but I am not getting `multisig` option in extrinsic. It should be there as per this video https://www.youtube.com/watch?v=ZJLqszvhMyM&list=PLOyWqupZ-WGuAuS00rK-pebTMAOxW41W8&index=27

![image](https://user-images.githubusercontent.com/1575561/132452855-2c61050d-6f9b-44bb-9ffd-6d0316ae90ad.png)

It looks like I have limited access to ROCOCO testnet. 

Could you try it from your end?

**Comment by NukeManDan** [comment]
So it turns out that Rococo doesn't presently have the multisig pallet included ([look here](https://github.com/paritytech/polkadot/blob/master/runtime/rococo/src/lib.rs)). That is why this is failing to bring up the right modal/work. 

I would expect the UI _not_ to have this capability displayed if the pallet isn't included. As there is no real need for it on Rococo, I don't expect it to be included. If you like, adding this to a fork is an option for local testing, and we can ask upstream if Rococo in production can have it included.
