### ISSUE TITLE
how can i Pass arguments to off-chain worker by cli

### ISSUE THREAD

**Issue by baidang201** [paritytech/subport#236]
i  had seen <Pass arguments to off-chain worker by rpc> in https://github.com/paritytech/substrate/issues/3912, but i need init done when substrate node start up. 
Do you have any good idea?

i try parse custom cmd param in client/cli/src/commands/run_cmd.rs  and  use "sc_service::{ config::Configuration};" save param. but when i try to use sc-service in bin/node-template/runtime,
it report 
```
use sc_service::{ config::Configuration};
     |     ^^^^^^^^^^ use of undeclared crate or module `sc_service`
```

the bin/node-template/runtime/Cargo.toml added content is 
```
sc-service = { version = "0.9.0", default-features = false, path = "../../../client/service", optional = true}

std = [
  "sc-service",
]
```

**Comment by NukeManDan** [comment]
If this is still an issue, please let me know and we will reopen it. It could make a handy doc if you have source to reference for this too :pray: 
Others may be interested in the same patterns.
