### ISSUE TITLE
Timestamp pallet `set` extrinsic fails in polkadot.js

### ISSUE THREAD

**Issue by VargSupercolony** [paritytech/subport#238]
Hello subport,

I have an issue with `api.tx.timestamp.set` extrinsic not working in polkadot.js when trying to use it in integration test context.
Basically, I want to mock the behavior of advancing the block and block time, just in the test environment. The extrinsic call fails, because it's an `inherent` and cannot be just sent with `signAndSend()`. 

Please find the minimum reproducible example here: https://github.com/VargSupercolony/timestamp-in-tests-for-ink

**Comment by NukeManDan** [comment]
Closing as we let this one slip @VargSupercolony - SO sorry! :sob: will not have this happen again for you!
Any hints we should leave from the PR that referenced this above?

**Comment by VargSupercolony** [comment]
Well, this hasn't been solved yet. The current architecture of Substrate does not allow for dispatching the `tx.timestamp.set` extrinsic, as it *must* be dispatched from the inherent origin (inserted by the block author). As for the PR, please see the comment & the context: https://github.com/Supercolony-net/openbrush-contracts/pull/47#discussion_r745532864 . This comment mentions the issue in the integration test context, which I described in my original issue.

What I would like to know is if it's somehow possible to advance the block number/block time directly by interacting with the node via polkadot.js API. The example is there to show how I see it being used.

**Comment by WookashWackomy** [comment]
@VargSupercolony did you find any workarounds for that? That functionality (of advancing block time/number) is somehow crucial when it comes to e2e testing contract functions that rely on the time passing by.

The only idea I had is to hoist calls to `Self::env().block_timestamp()` and create proxy methods where one implementation would retrieve the timestamp (a regular call) and the second one pass the timestamps from arguments (specifically for tests - the methods would be guarded with `Ownable`-like attribute (from openbrush), so the method is available only in e2e tests
