### ISSUE TITLE
Not able to generate parachain Genesis state

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#239]
I am getting below error while hitting this command `./target/release/datahighway-collator export-genesis-state --parachain-id 20XX > parachain/para-20XX-genesis`

```
ayushkumarmishra@Ayushs-MacBook-Pro node % ./target/release/datahighway-collator export-genesis-state --parachain-id 2005 > parachain/para-2005-genesis
thread 'main' panicked at 'AuRa authorities empty, maybe wrong order in `construct_runtime!`?', /Users/ayushkumarmishra/.cargo/git/checkouts/cumulus-59522f43471fa161/fd80849/pallets/aura-ext/src/lib.rs:96:13
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Here is my runtime https://github.com/DataHighway-DHX/node/blob/make_compatible_with_kusama/runtime/src/lib.rs

Please let me know what I am missing and in which order, I should keep Aura in `construct_runtime!`

**Comment by NukeManDan** [comment]
(From Element chat)
> Please try following the order from here. https://github.com/substrate-developer-hub/substrate-parachain-template/blob/6589adf6885f382f38a8cfed081fc948397be325/runtime/src/lib.rs#L453
Dan Shields
note the extra syntax, some modules are numbered explicitly:
```rust
// Create the runtime by composing the FRAME pallets that were previously configured.
construct_runtime!(
	pub enum Runtime where
		Block = Block,
		NodeBlock = generic::Block<Header, sp_runtime::OpaqueExtrinsic>,
		UncheckedExtrinsic = UncheckedExtrinsic,
	{
// -- snip --
		ParachainSystem: cumulus_pallet_parachain_system::{Pallet, Call, Config, Storage, Inherent, Event<T>, ValidateUnsigned} = 20,

		ParachainInfo: parachain_info::{Pallet, Storage, Config} = 21,

		Balances: pallet_balances::{Pallet, Call, Storage, Config<T>, Event<T>} = 30,

		Aura: pallet_aura::{Pallet, Config<T>},
		AuraExt: cumulus_pallet_aura_ext::{Pallet, Config},
// -- snip --
```

**Comment by ayushmishra2005** [comment]
@NukeManDan Issue was in chain_spec where I was passing no authority in aura. I fixed it. Thanks for looking into it.
