### ISSUE TITLE
How to list all the parachains in a Polkadot network?

### ISSUE THREAD

**Issue by kebab-mai-haddi** [paritytech/subport#240]
Is it possible to list all the parachains in a given network? The [documentation](https://wiki.polkadot.network/docs/build-parachains-rococo) for test-network for parachains states that we can select the desired parachain from the dropdown. I want to do the same thing from the backend using Rust but I am not sure what the cli command is (if I am running the Polkadot node) or a rust function that exists in the source code of Polkadot that lists all the parachains.

**Comment by shawntabrizi** [comment]
All the parchains currently onboarded to a relay chain can be found in a storage item here: https://github.com/paritytech/polkadot/blob/master/runtime/parachains/src/paras.rs#L320

```
	/// All parachains. Ordered ascending by `ParaId`. Parathreads are not included.
	#[pallet::storage]
	#[pallet::getter(fn parachains)]
	pub(super) type Parachains<T: Config> = StorageValue<_, Vec<ParaId>, ValueQuery>;
```

So you can query this storage item to get a vector of those ParaIds.

Depending on what your scenario is, this may or not may not be enough information for you. For example, this does not tell you anything about their RPC endpoints or anything like that if you are trying to build a user interface. Those things are mostly tracked off chain.
