### ISSUE TITLE
Not able to generate chain_spec 

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#242]
I am getting below error after following https://substrate.dev/cumulus-workshop/#/en/1-prep/2-chain-spec?id=generate-a-plain-chain-spec. I am using Mac M1.

```
ayushkumarmishra@Ayushs-MacBook-Pro polkadot % ./target/release/polkadot build-spec --chain rococo-local --disable-default-bootnode > rococo-custom-2-plain.json
zsh: illegal hardware instruction  ./target/release/polkadot build-spec --chain rococo-local  > 

```
Can someone help me to fix this?

**Comment by ayushmishra2005** [comment]
@NukeManDan Its not solved yet. Could you please reopen it?

**Comment by NukeManDan** [comment]
Did you try the steps outlined?

**Comment by ayushmishra2005** [comment]
Yes @NukeManDan It worked after following below steps 

```
rustup install stable-aarch64-apple-darwin
rustup default stable-aarch64-apple-darwin
```
