### ISSUE TITLE
Why `ExistentialDeposit` is different in Substrate Parachain Template and Substrate Node Template?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#246]
Why `ExistentialDeposit` is different in Substrate Parachain Template and Substrate Node Template?
https://github.com/paritytech/substrate/blob/polkadot-v0.9.9/bin/node-template/runtime/src/lib.rs#L235 and 

https://github.com/substrate-developer-hub/substrate-parachain-template/blob/polkadot-v0.9.9/runtime/src/lib.rs#L251

What is more ideal?

**Comment by NukeManDan** [comment]
The ED is whatever you believe is economically viable for your network to prune "dust" accounts. There is not generic "ideal" here, but requires you to decide, and monitor that the intended effects are happening.

Start here to decide this for yourself: https://wiki.polkadot.network/docs/build-protocol-info#existential-deposit
