### ISSUE TITLE
Error Connecting to Substrate { "isTrusted": true }

### ISSUE THREAD

**Issue by ytytgo** [paritytech/subport#248]
I want to deploy a node and frontend on an AWS server but it fails.
ubuntu 20.04.

Get the node up and running,
./target/release/node-template --dev --tmp  --ws-external
or
./target/release/node-template --dev tmp --ws-external --rpc-external --rpc-cors=all --base-path db/node2 --ws-port 9944

Frontend is also up and running,
yarn start

also change ip to specific VM's ip
$ vi src/config/development.json
  "PROVIDER_SOCKET": "ws://52.40.22.xxx:9944"

When I access to 
52.40.22.xxx:8000

 I get

Error Connecting to Substrate
{ "isTrusted": true }
....

Using the exact same code in my local environment (m1 osx), it succeeded.

Don't I need a place to put 0.0.0.0 somewhere?

**Comment by NukeManDan** [comment]
This is likely simply a too slow network and a too restrictive node AWS instance. For reference: 
https://docs.substrate.io/v3/concepts/weight/
> Substrate defines one unit of weight as one picosecond of execution time, that is 1012 weight = 1 second, or 1,000 weight = 1 nanosecond, on fixed reference hardware (Intel Core i7-7700K CPU with 64GB of RAM and an NVMe SSD).

This is overkill for just running a simple node without many pallets. But try a minimum of 8 GB RAM and a few cores to see if that resolves the issues.
