### ISSUE TITLE
how can i  Reproduce  1,500 TPS in substrate benchmark test with multi  validator node

### ISSUE THREAD

**Issue by baidang201** [paritytech/subport#249]
https://twitter.com/gavofyork/status/1270025498580656134?lang=en

![image](https://user-images.githubusercontent.com/3405789/136767456-c25e61d7-dd93-4921-bbc5-eee83c54fef0.png)

**Comment by shawntabrizi** [comment]
I believe this tool was used: https://github.com/NikVolf/sub-bench

**Comment by baidang201** [comment]
thx
