### ISSUE TITLE
Should we use this format ` Vec<(AccountId, AccountId, GrandpaId, AuraId, ImOnlineId, AuthorityDiscoveryId)>`, or only `Vec<AuraId>` for `initial_authorities`  in the chain specification for a Parachain, where the 1st and 2nd elements of the tuple would represent the Stash and Controller keys for controlling its funds

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#250]
Should we use this format ` Vec<(AccountId, AccountId, GrandpaId, AuraId, ImOnlineId, AuthorityDiscoveryId)>`, or only `Vec<AuraId>` for `initial_authorities` in `testnet_genesis` function?

https://github.com/substrate-developer-hub/substrate-parachain-template/blob/master/node/src/chain_spec.rs#L128

**Comment by NukeManDan** [comment]
`AuraId` = https://github.com/substrate-developer-hub/substrate-parachain-template/blob/master/runtime/src/lib.rs#L36

> not sure if the collator needs the Grandpa session key since the relay chain validator is the one that finalises the blocks.

Right, it does not.

> the collators' set (and their nominators) are selected to produce blocks with a valid set of transactions based on their stake in the network, and part of each block reward goes to the collator that produced the block, who then shares it with the nominators. collators also get stashed if they misbehave
>
> so why shouldn't parachain collators need to have both a Stash and Controller session key?

The devhub parachain template uses no slashing, it is pure vanilla `aura-extention` https://github.com/paritytech/cumulus/blob/master/pallets/aura-ext/src/lib.rs#L17-L34 
you are confusing concepts with a BABE & GRANDPA configuration that this is not.

`initial_authorities` needs to map from the `ChainSpec::from_genesis(...)` correctly and it is up to you to set and read things properly for your configuration. AFAIK The order is not important, so long as you map them correctly.

Another example: https://github.com/paritytech/polkadot/blob/dcccd9671191f54831b6b0d9c44170d0eb184700/node/service/src/chain_spec.rs#L296

One idea about collator selection for sovereign chains you might get a lot from: https://www.youtube.com/watch?v=e_Yj7NUlYwQ&list=PLp0_ueXY_enX6S5sogeo7GHD1BXTLj5Xr&index=22
