### ISSUE TITLE
Regarding HotStuff consensus implementation on Substrate Framework

### ISSUE THREAD

**Issue by gokulsan** [paritytech/subport#252]
Hello Substrate Team,

I am looking for any existing implementation of HotStuff consensus algorithm on Substrate Framework. Is it compatible with the Grandpa / Babe / Proof of Existence consensus algorithms. Request your kind guidance in this regard.

**Comment by NukeManDan** [comment]
Looked briefly at HotStuff, AFAIK there is no work being done on this within the Substrate ecosystem, If you do find or work on something, please add it! Here:
https://github.com/substrate-developer-hub/awesome-substrate/
