### ISSUE TITLE
How should I check whether my chain is compatible with Polkadot?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#255]
1) I am preparing our parachain for Polkadot auction. Earlier I prepared my codebase to make it compatible with Kusama. I believe the same codebase would work for Polkadot except adding chain_spec config for `Westend` testnet and `Polkadot`. Please let me know if I am missing anything.

2) How should I check whether my chain is compatible with Polkadot? 

According to me, below is the list 

- [ ] Test registering parachain locally with locally running relay chain as mentioned in https://docs.substrate.io/tutorials/v3/cumulus/start-relay/

- [ ] Follow the same steps mentioned in https://github.com/substrate-developer-hub/cumulus-workshop/blob/master/en/6-rococo-registration/1-register.md to register parachain on Westend

Is there anything else I should check for Polkdaot compatibility?

3) Currently I am using Polkadot0.9.10. Do I need to update it to Polkadot 0.9.11?

**Comment by NukeManDan** [comment]
1. https://github.com/substrate-developer-hub/substrate-parachain-template/blob/master/node/src/chain_spec.rs#L76 you have to configure this and also setup a chainspec for production, not `dev` or `local`
2. You should test against `polkadot` (not westend) running in `--chain <dev|local|staging>` using `polkadot-launch` as described in the tutorial and as _stressed_ you must test the against the same version running on the network you are targeting. At the time of writing that is 0.9.11 at a minimum for collators, and 0.9.12 for validators. 

### Please also review: https://docs.substrate.io/how-to-guides/v3/parachains/pre-launch/
