### ISSUE TITLE
Error: Input("Relay chain argument error: Invalid input: `rococo-dev` only supported with `rococo-native` feature enabled.")

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#257]
Here is code https://github.com/DataHighway-DHX/node/blob/make_compatible_with_kusama/node/src/command.rs#L47

When I am trying to hit this command `./target/release/datahighway-collator --alice --collator --tmp --chain dev`, I am getting below error

```
2021-10-27 18:44:58 ⛓  Native runtime: datahighway-parachain-1 (datahighway-parachain-0.tx1.au1)    
Error: Input("Relay chain argument error: Invalid input: `rococo-dev` only supported with `rococo-native` feature enabled.")
```

I also tried to remove `rococo` word after seeing this code https://github.com/paritytech/polkadot/blob/v0.9.10/cli/src/command.rs#L116 but that didn't make any difference.

I have followed https://github.com/substrate-developer-hub/substrate-parachain-template/tree/polkadot-v0.9.10 and here is my codebase 

https://github.com/DataHighway-DHX/node/tree/make_compatible_with_kusama.

I am getting same error in `Substrate Parachain Template` as well.

**Comment by NukeManDan** [comment]
There is no `--dev` mode for collators presently: https://github.com/paritytech/cumulus/issues/483
You must run a testnet as described here: https://docs.substrate.io/tutorials/v3/cumulus/start-relay/
