### ISSUE TITLE
How to upgrade between substrate versions?

### ISSUE THREAD

**Issue by imstar15** [paritytech/subport#259]
I built a test chain myself, based on monthly-2021-05, I want to compile the new polkadot-v0.9.10 code of substrate and upgrade the chain.

However, after submitting the wasm file, an error message was printed on the command line, and the upgrade failed.

```
Unable to author block in slot 545079636,. `can_author_with` returned: Failed to get runtime version at `BlockId::Hash(0x66b27ca005e0f393ddddf3fa886f24619b8cc67d3b1b5efe6215e442143eee6c)` and will disable authoring. Error: VersionInvalid("RuntimeConstruction(Instantiation(\"Instantiation: Export ext_crypto_secp256k1_ecdsa_recover_compressed_version_2 not found\"))") Probably a node update is required!
```

How should I upgrade correctly?

I tested the upgrade from the original versions of various Substrate. Here are my test results:

1 monthly-2021-05 -> monthly-2021-06: upgrade success!

2 monthly-2021-05 -> monthly-2021-07, monthly-2021-06 -> monthly-2021-07: upgrade failed!
```
Unable to author block in slot 545112786,. `can_author_with` returned: Failed to get runtime version at `BlockId::Hash(0x6c3dc988e17b4b4f303079a0089b6cafc0ee3d1dd51e577ef18363fbf75f9410)` and will disable authoring. Error: VersionInvalid("RuntimeConstruction(Instantiation(\"Instantiation: Export ext_trie_blake2_256_verify_proof_version_1 not found\"))") Probably a node update is required!
```
3 monthly-2021-05 -> polkadot-v0.9.10, monthly-2021-05 -> monthly-2021-10, monthly-2021-07 -> polkadot-v0.9.10: upgrade failed!
```
Unable to author block in slot 545079636,. `can_author_with` returned: Failed to get runtime version at `BlockId::Hash(0x66b27ca005e0f393ddddf3fa886f24619b8cc67d3b1b5efe6215e442143eee6c)` and will disable authoring. Error: VersionInvalid("RuntimeConstruction(Instantiation(\"Instantiation: Export ext_crypto_secp256k1_ecdsa_recover_compressed_version_2 not found\"))") Probably a node update is required!
```
4 polkadot-v0.9.10 -> monthly-2021-10: upgrade success!

**Comment by NukeManDan** [comment]
Can you provide your codebase and point to PRs moving between versions? I can point to a few things in there. I am confused why you are moving between monthly and Polkadot tags - are you building a solo-chain? **Parachains are only expected to be stable on Polkadot tags.** 

Here is an example where we update the parachain template: https://github.com/substrate-developer-hub/substrate-parachain-template/pull/73

Here is my "cheat sheet" to update manually between **specific tagged releases of Polkadot**:
_Pro tip: use [https://www.gitkraken.com/](https://www.gitkraken.com/) for easy code review!_

- checkout the correct cumulus commit the template uses (before any changes)
    - checkout a temporary new branch (that has HEAD at this commit)
    - look in the template cargo.lock get their cumulus commit, ensure it matches what you have
- do a squash merge with commit on target latter commit
    - `git merge --squash <commit>`
    - review the diff for this merge, make changes as needed
    - mostly can ignore changes that don't live in the template there (or other reference parachain like statemine)
    - Some things won't be needed for you, so do consider what changes you are applying carefully

**Comment by irsal** [comment]
We are in the process of moving the functionality from our blockchain (built off of substrate-node-template) to a parachain. Hence why we're moving from monthly to the polkadot versions. 

Here is our PR: https://github.com/OAK-Foundation/OAK-blockchain/pull/23

**Comment by irsal** [comment]
We can close this out, @imstar15. We figured out we needed to upgrade our standalone nodes to the new client.

**Comment by imstar15** [comment]
Thank you, I closed it.
