### ISSUE TITLE
Query the node interface document

### ISSUE THREAD

**Issue by simpleshark** [paritytech/subport#26]
I want to make a DOT wallet. Is there a node interface document that allows me to generate addresses, transfer money, query transaction records, and so on?

**Comment by danforbes** [comment]
Substrate-based chains expose an RPC server that can be used to interact with them as you describe. The most common family of libraries for doing that at this time is [Polkadot JS](https://github.com/polkadot-js/). You can learn more about Polkadot JS RPC calls here https://polkadot.js.org/api/start/api.rpc.html and here https://polkadot.js.org/api/substrate/rpc.html.
