### ISSUE TITLE
ERC721 smart contract deployment issue

### ISSUE THREAD

**Issue by aaku1234** [paritytech/subport#260]
system.extrinsic failed others deploying smart contract .Following this github code for ERC721 https://github.com/allanperlee/Nftoken

**Comment by NukeManDan** [comment]
Please report issues and seek support with `ink` on their repos and element channels
-  https://github.com/paritytech/ink-docs
- https://matrix.to/#/#ink:matrix.parity.io

And specifically for this one, why not open an issue on _that repo_ :wink:
