### ISSUE TITLE
about the polkadot transaction mempool

### ISSUE THREAD

**Issue by gitloverr** [paritytech/subport#262]
hi everyone,

I would like to check transaction mempool of my node for pending transactions or signed but unbroadcast transactions to blockchain... How can I check the mempool for polkadot transactions? is there any way?

thank you

**Comment by NukeManDan** [comment]
The "mempool" is unique to each node, for Substrate based chains like Polkadot, this is the [transaction pool](https://docs.substrate.io/v3/concepts/tx-pool/)

- You can query a specific node for it's pending extrinsics: https://polkadot.js.org/docs/substrate/rpc#pendingextrinsics-vecextrinsic
- You may also look to [sidecar](https://github.com/paritytech/substrate-api-sidecar/) and the `/node/transaction-pool` endpoint: https://paritytech.github.io/substrate-api-sidecar/dist/
