### ISSUE TITLE
+5 days era

### ISSUE THREAD

**Issue by xxxvik-xakerxxx** [paritytech/subport#265]
I created an action on my test network, while I already had a crowdloan auction was completed now the ending period is going on, but my era has become 5 days longer, is this a normal process for the network and should it be so (reading the documentation, I found no explanation this process)

**Comment by NukeManDan** [comment]
Please provide more detail - what does "my era has become 5 days longer" mean exactly?

**Comment by xxxvik-xakerxxx** [comment]
> Please provide more detail - what does "my era has become 5 days longer" mean exactly?

it's just that the era for some reason has ceased to close, I don't understand why its term is just growing now (is it connected with the fact that 1 of the validators is not working at the moment)
