### ISSUE TITLE
Why `Developer` tab got removed from parachain's Settings?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#269]
I was doing local testing by connecting with local relay chain. I was able to connect with relaychain as parachain. Parachain was also producing blocks.

However  I am not able to execute extrinsic because of Polkadot JS issue. 

I just checked this tab got removed from all live and testnet parachains's settings. 

It's visible only under solochain. Because of this issue, I am not able to import custom types and hence not able to perform any extrinsic. 

This is a blocker and I can not proceed due to this issue. 

<img width="1804" alt="Screenshot 2021-11-10 at 4 45 46 PM" src="https://user-images.githubusercontent.com/1575561/141104544-62cbb9ca-a492-427d-b35c-eb772d0e8235.png">

**Comment by Loaki07** [comment]
would like to know where the custom types have to be added for the respective chain

**Comment by NukeManDan** [comment]
### https://github.com/paritytech/substrate/pull/8615

All chains including this change in substrate no longer need to manually set custom types :tada:
I highly recommend moving to a version no less than this. This is _required_ for parachain use,  it was included as of 0.9.11
https://github.com/substrate-developer-hub/substrate-parachain-template/blame/70b63ad47a0255c667c6b3329fce92bebb369b3a/pallets/template/Cargo.toml#L16

If you need this dev tab for older versions, run a local older version of the apps UI that includes it. It is _never_ a blocker if you run the version matching the cumulus tutorial guide's one. You can see the history of tested ones here in the 1st page history:
https://github.com/substrate-developer-hub/substrate-docs/commits/main/v3/tutorials/09-cumulus/a-start-relay/index.mdx

**Comment by ayushmishra2005** [comment]
@NukeManDan I upgraded codebase to 0.9.11 and also implemented https://github.com/substrate-developer-hub/substrate-parachain-template/blame/70b63ad47a0255c667c6b3329fce92bebb369b3a/pallets/template/Cargo.toml#L16 in all pallets to fix compilation issue.

Parachain is also able to connect with local relaychain and producing blocks.

Are you suggesting to test my upgraded parachain(0.9.11) with older version of PolkadotJs.apps?

**Comment by NukeManDan** [comment]
No I am saying you no longer need custom types. Try it ;)

**Comment by ayushmishra2005** [comment]
@NukeManDan Its not working. I have opened new issue https://github.com/paritytech/subport/issues/271. Please see and let me know if I am missing anything
