### ISSUE TITLE
Security hardening for a custom blockchain built with substrate framework

### ISSUE THREAD

**Issue by gokulsan** [paritytech/subport#270]
Hello Team,

How can we ensure the security of a custom blockchain built using substrate framework from attack vectors like Distributed Denial of Service attack or Nothing at Stake Attack or other attack vectors. Is it entirely dependent on the security of the consensus algorithm and cryptographic libraries being used. Is it always required to use a trusted execution environment like SGX hardware enclave. I am still learning substrate framework in detail. Sorry if this question is very trivial.

**Comment by NukeManDan** [comment]
Food for thought: 
https://docs.substrate.io/v3/concepts/weight/
https://docs.substrate.io/v3/concepts/tx-pool/
https://docs.substrate.io/v3/advanced/cryptography/
https://wiki.polkadot.network/docs/build-pdk
https://w3f.github.io/parachain-implementers-guide/protocol-overview.html
https://wiki.polkadot.network/docs/learn-comparisons

**Comment by NukeManDan** [comment]
also: https://integritee.network/
