### ISSUE TITLE
Could not decode `MultiSignature`, variant doesn't exist

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#271]
This related to #269 

@NukeManDan As you mentioned here, after introducing `scale-info`, We don't need to add custom types since `Settings>>Developer` got removed from polkadot js apps. 

I tried to execute extrinsic after connecting with local relaychain. My parachain is able to connect with relay chain and able to produce blocks but not able to perform extrinsic.

I am getting below error on UI console:

`submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Runtime error: Execution failed: ApiError(FailedToConvertParameter { function: "validate_transaction", parameter: "tx", error: Error { cause: None, desc: "Could not decode `MultiSignature`, variant doesn't exist" } }): RuntimeApi, Execution failed: ApiError, FailedToConvertParameter { function: \"validate_transaction\", parameter: \"tx\", error: Error { cause: None, desc: \"Could not decode `MultiSignature`, variant doesn't exist\" } }`

<img width="1434" alt="Screenshot 2021-11-11 at 6 14 28 PM" src="https://user-images.githubusercontent.com/1575561/141301444-6e84764a-f7aa-46a5-9003-4ab4fdcf8d3e.png">

<img width="1434" alt="Screenshot 2021-11-11 at 6 14 35 PM" src="https://user-images.githubusercontent.com/1575561/141301534-98b1b2ce-564e-4bca-bbf2-5ef4a302cde5.png">

**Comment by NukeManDan** [comment]
What branch are you working on here to inspect? https://github.com/DataHighway-DHX/node/branches
I see substrate V3 used in master, that will not work with this.

Have you derived `TypeInfo` fir all your pallets? [example here](https://github.com/paritytech/substrate/pull/8615/files#diff-9acae09f48474b7f0b96e7a3d66644e0ce5179464cbb0e00671ad09aa3f73a5fR30)
```rust
#[derive(Clone, Encode, Decode, Eq, PartialEq, RuntimeDebug, MaxEncodedLen, TypeInfo)]
pub struct SomeStorageStruct<Balance, AccountId, DepositBalance> {...}
```

**Comment by ayushmishra2005** [comment]
Hi @NukeManDan Sorry I forgot to give branch name. Here is branch https://github.com/DataHighway-DHX/node/tree/polkadotv0.9.11

Please see here example https://github.com/DataHighway-DHX/node/blob/polkadotv0.9.11/pallets/roaming/roaming-accounting-policies/src/lib.rs#L52. I have made the same changes at all corresponding places. 


Without this `TypeInfo` change, pallets won't get compiled. I followed this PR https://github.com/substrate-developer-hub/substrate-parachain-template/pull/80 to update it to polkadot 0.9.11.

**Comment by ayushmishra2005** [comment]
@NukeManDan did you get a chance to look into it?

**Comment by NukeManDan** [comment]
have you tried using an older version of the apps ui?
more info here
https://github.com/substrate-developer-hub/substrate-docs/issues/583

**Comment by ayushmishra2005** [comment]
@NukeManDan I didn't try with older version. Lets assume it would work with older version with custom type definition but at the end we have to use latest UI https://polkadot.js.org/apps/#/explorer.

What is the solution to make it work with latest version of UI?

**Comment by NukeManDan** [comment]
ensure you have the updated client and runtime that have scale info. clear you browser cache and cookies for the ui on all versions (if you have accounts setup, back them up first of course!)

**Comment by ayushmishra2005** [comment]
@NukeManDan I did the same. I started local relay chain using https://docs.substrate.io/tutorials/v3/cumulus/start-relay/. I am able to connect my parachain. Parachain is also able to produce block.

I deleted browser cache and cookies from Chrome and Firfox but still facing same issue.
