### ISSUE TITLE
Is it possible to attach extra info to the block that is sent to other nodes?

### ISSUE THREAD

**Issue by nazar-pc** [paritytech/subport#274]
I am looking for a way to attach a piece of optional data to the block that is sent to other nodes. The data is optional, but will help other nodes to verify the block much quicker.

**Comment by NukeManDan** [comment]
Sorry for the delay! Maybe here:
https://docs.substrate.io/v3/runtime/macros/#pallethooks with on_initialize, on_finalize and on_runtime_upgrade that could be used to trigger explicit events... but if it's optional you likely want to have this with OCWs https://docs.substrate.io/v3/concepts/off-chain-features/

Example: https://github.com/paritytech/substrate/tree/master/frame/examples/offchain-worker

**Comment by nazar-pc** [comment]
I don't need events or anything in runtime, I need to augment information sent alongside block contents when it is gossiped through the network.
