### ISSUE TITLE
what is the different content between polkadot-v0.9.12 and  ”4.0.0-dev”?

### ISSUE THREAD

**Issue by baidang201** [paritytech/subport#276]
4.0 substrate develop version = “4.0.0-dev” is base https://crates.io/search version manager system，  it may be packet a commit hash code and upload to crates.io，what is the different content between polkadot-v0.9.12 and  ”4.0.0-dev”，What is the  4.0.0-dev update strategy?

is it 4.0.0-dev commit hash equ laster polkadot-v0.9.x?

**Comment by NukeManDan** [comment]
4.0.0-dev = crate version for substrate - this is not locked and floats on `master` upstream
polkadot-v0.x = branch or tag used for polkadot releses that is fixed in the git history, it (for the moment) uses  4.0.0-dev cargo deps
