### ISSUE TITLE
What is the process to become eligible  for crowdloan for a parachain?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#279]
Crowdloans are a way for projects to fundraise for a parachain slot on the Polkadot network. As I can see from PolkadotJsApps, One can contribute from here https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpub.elara.patract.io%2Fpolkadot#/parachains/crowdloan for a parachain.

I just wanted to know how could be a parachain listed on this page? 

According to me if any parachain tries to get registered as parathread, that parachain would be listed on this page and anyone can contribute from there. Please let me know if I am missing something.

or do we need to integrate any crowdloan related pallet in parachain?

**Comment by al3mart** [comment]
As you say, crowdloans are a tool for teams to be competitive in the slot auctions.

To open a crowdloan you will need:

1) Reserve a paraId
2) Register a parathread (upload wasm + state for it)
3) Now you will be able to open a crowdloan for a slot.

For more info please check [this link](https://wiki.polkadot.network/docs/learn-crowdloans#starting-a-crowdloan-campaign), as always, feel free to try this type of things in a local network to make sure all the concepts are well understood.
