### ISSUE TITLE
Clarifications for setting up Custom Rococo Staging Network 

### ISSUE THREAD

**Issue by decentration** [paritytech/subport#280]
hi im working on setting up a custom rococo staging network. I am planning to document the workflow as a how-to, which gets into slightly more nitty gritty than the "start a private network" [tutorial.](https://docs.substrate.io/tutorials/v3/private-network/#launch-your-private-network) It would be great to get some clarity about the session keys part. 

I have 3 validators containing 7 different types of session keys, grandpa, imOnline, authorityDiscovery, etc... the spec was loaded from a customised version of `rococo-native` staging testnet in `node/service/src/chain_spec.rs` file. I have a few questions:

1. Do i need to make 21 key inserts before I start to produce blocks?
1. Where do I find the types of calls to make and the parameter names (such as "gran" for grandpa)?
1. Is there a faster way than to curl RPC calls?
1. Can i add more validators even though only 3 are coded into the chain spec, or is 3 the minimum?
1. Is every key provided a minimum required necessity? Whats minimum requirement?
1. Why are there 2 x AccountIds for each validator?
1. How can i do this better? Or am i creating testnet staging network correctly?

Below is the session part of my chain spec json:

```json
"session": {
          "keys": [
            [
              "5DvXwFVJAhuzMEdQmFsfzCGL1CDUqVJc6nDHyxDqYoSqUE18",
              "5DvXwFVJAhuzMEdQmFsfzCGL1CDUqVJc6nDHyxDqYoSqUE18",
              {
                "grandpa": "5GboBX4hqNVopiBQVsXWAw3SzD5dpKxqjK3iDA38GPxJEi6w",
                "babe": "5HTALD3kTwmDHNKEKxsquepU56Quzq59xKGmhksekpcF3C5T",
                "im_online": "5D7DGQNjk5gAwatPSMf555VB1W8UCq1sQomHX2eRwiLqhc4t",
                "para_validator": "5D7DGQNjk5gAwatPSMf555VB1W8UCq1sQomHX2eRwiLqhc4t",
                "para_assignment": "5D7DGQNjk5gAwatPSMf555VB1W8UCq1sQomHX2eRwiLqhc4t",
                "authority_discovery": "5D7DGQNjk5gAwatPSMf555VB1W8UCq1sQomHX2eRwiLqhc4t",
                "beefy": "KWBh8XBfoyenpdXN5qY1deY6tpkN2Hvw4skhERZRi2neimHBR"
              }
            ],
            [
              "5D2KWHBa7X2RRt8zGhwmuXxa4KE4ofTGCY4nYg8W6MKxV523",
              "5D2KWHBa7X2RRt8zGhwmuXxa4KE4ofTGCY4nYg8W6MKxV523",
              {
                "grandpa": "5FUibppET3z3SRqbfgGAzMTRUgBcdVzWw2Kv9pCsQLd6qsp8",
                "babe": "5HTALD3kTwmDHNKEKxsquepU56Quzq59xKGmhksekpcF3C5T",
                "im_online": "5D2KWHBa7X2RRt8zGhwmuXxa4KE4ofTGCY4nYg8W6MKxV523",
                "para_validator": "5D2KWHBa7X2RRt8zGhwmuXxa4KE4ofTGCY4nYg8W6MKxV523",
                "para_assignment": "5D2KWHBa7X2RRt8zGhwmuXxa4KE4ofTGCY4nYg8W6MKxV523",
                "authority_discovery": "5D2KWHBa7X2RRt8zGhwmuXxa4KE4ofTGCY4nYg8W6MKxV523",
                "beefy": "KW3FkcrJAy6Z5ysiRQupzvP4dcwfSnJCBwjtGsSsgcBwhapCv"
              }
            ],
            [
              "5GZ7Qq9XCwtCPvUVg6Bg13TpZn9z64kapADgXPj5JJk716oz",
              "5GZ7Qq9XCwtCPvUVg6Bg13TpZn9z64kapADgXPj5JJk716oz",
              {
                "grandpa": "5EX7Uw8VbNgDtdEbTa3rGVkR7VsGcPoFpFfPYs4iexyKVw72",
                "babe": "5HTALD3kTwmDHNKEKxsquepU56Quzq59xKGmhksekpcF3C5T",
                "im_online": "5GZ7Qq9XCwtCPvUVg6Bg13TpZn9z64kapADgXPj5JJk716oz",
                "para_validator": "5GZ7Qq9XCwtCPvUVg6Bg13TpZn9z64kapADgXPj5JJk716oz",
                "para_assignment": "5GZ7Qq9XCwtCPvUVg6Bg13TpZn9z64kapADgXPj5JJk716oz",
                "authority_discovery": "5GZ7Qq9XCwtCPvUVg6Bg13TpZn9z64kapADgXPj5JJk716oz",
                "beefy": "KWDc8ncrJx3NtMFeKxNMGpqU1FrnJTR2Yf1aqFdxNRP2ihJex"
              }
            ]
          ]
        },
        "grandpa": {
          "authorities": []
        },
        "imOnline": {
          "keys": []
        },
        "authorityDiscovery": {
          "keys": []
        },
```

**Comment by JoshOrndorff** [comment]
@NukeManDan  and @sacha-l can probably help a lot more than I can, but I'll take a crack anyway. These answers are not exhaustive, but should point you in the right direction and clear up some of the conceptual things.

The chain spec snippet you quoted is indeed the main thing you have to change. But there are probably others. For example, if you add more validators, you may also need to give them tokens.

Now let's try to tackle your questions in order.

1. You can make 21 different keys, and that will work fine. But you don't need to. Any session keys that use the same crypto types can share the same keys. You can see that happening already in the snippet you posted. Most session keys are sr25519 and can share. Grandpa is different, it is ed25519. It can share a seed with the others, but the keys will be different. From the looks of your snippet, beefy may use different crypto too, but I'm not familiar with beefy.
2. https://github.com/paritytech/substrate/blob/de6033a2aa4f0191877200516fbc2655399faa4b/primitives/core/src/crypto.rs#L984-L1010
3. There are some alternative options, but I'm not sure they are faster. Basically the two options are
  * Use RPC calls. You can do this with Curl, or also with the Apps ui, or another tools of your choice
  * Use the `polkadot key insert` command. To learn more run `polkadot key --help`.
4. You can add validators in either of two ways:
  * Modify the spec file to include all of the ones you want right from the get go. I'd recommend this if you know you'll want more
  * Start the chain with only 3 validators, and add the rest later through extrinsics. See the polkadot staking docs on how to go this route.
5. You can gt by without some of the session keys, but I wouldn't recommend starting that way. Doing so will just leave doubts in your mind and potentially lead to other weird errors. The Babe key is most critical, but I relly would recommend just including them all at least until you get something working.
6. They are technically AccountId and ValidatorId. But in Polkadot they are configured to be the same. Just leave them like that.
7. You're on the right track.

**Comment by decentration** [comment]
Hi @JoshOrndorff, your input was extremely helpful, thanks a lot, you are very awesome :) I am now producing and finalizing blocks. I made individual rpc calls for the aforementioned session keys. 

I have a couple of questions:

1. If i want to allow many validators, but started with only three in the chain-spec file, will that work fine? How does that work?
1. I noticed that there is another way to generate keys via `author_rotateKeys`:

``` 
curl http://127.0.0.1:9933 \
-H "Content-Type:application/json;charset=utf-8" \
-d '{ "jsonrpc":"2.0", "id":1, "method":"author_rotateKeys" }'; 
```
What is the difference between doing it this way and using subkey generate, and then making `author_insertKey` calls? Are they different depending on the type of validation, or are they interchangeable?

**Comment by JoshOrndorff** [comment]
`author_rotateKeys` is a wonderful RPC call, and you should use it whenever you can. A classic use case for that RPC is having a validator change its session keys after a chain is live.

However, it is not easy to use `rotateKeys` before starting the chain, because you will need to know the keys in advance in order to put them in your chain spec file.

**Comment by decentration** [comment]
@JoshOrndorff currently I have produced 70870 blocks for my babe/grandpa Rococo staging network. But block production had stopped as i was fiddling with adding a new validator, as well as starting the process of transferring everything to Docker. 

```
2021-12-09 15:32:30 🎁 Prepared block for proposing at 70879 [hash: 0xb3120a1998afdb09962bc05823489126b25dbe1105fece713c06a27a9470a3dc; parent_hash: 0xb986…2d95; extrinsics (2): [0x04a3…708b, 0x69a6…46c1]]    
2021-12-09 15:32:30 🔖 Pre-sealed block for proposal at 70879. Hash now 0xff10905158b4f213752bf822f6948630958d5fe0891df35de412082c0596bc6e, previously 0xb3120a1998afdb09962bc05823489126b25dbe1105fece713c06a27a9470a3dc.    
2021-12-09 15:32:30 Error with block built on 0xb98672463aaa5b729362c629ec6966a87fe709f6c941781abed449f449332d95: ClientImport("Unexpected epoch change")    
2021-12-09 15:32:33 💤 Idle (2 peers), best: #70878 (0xb986…2d95), finalized #70876 (0xeaf1…f0b3), ⬇ 1.8kiB/s ⬆ 1.8kiB/s    
2021-12-09 15:32:36 🙌 Starting consensus session on top of parent 0xb98672463aaa5b729362c629ec6966a87fe709f6c941781abed449f449332d95    
2021-12-09 15:32:36 🎁 Prepared block for proposing at 70879 [hash: 0x8b659fa55018f7c4669a8f3d0f73705076065fae2d4a1e530ad7730fcfeadfdc; parent_hash: 0xb986…2d95; extrinsics (2): [0x8614…a67d, 0x69a6…46c1]]    
2021-12-09 15:32:36 🔖 Pre-sealed block for proposal at 70879. Hash now 0xe36742f60f2b75478db1071d398fb891e46fc53281381bc203819ece65764ac3, previously 0x8b659fa55018f7c4669a8f3d0f73705076065fae2d4a1e530ad7730fcfeadfdc.    
2021-12-09 15:32:36 Error with block built on 0xb98672463aaa5b729362c629ec6966a87fe709f6c941781abed449f449332d95: ClientImport("Unexpected epoch change")   
```
From checking previous issues about this it mentions to wait an epoch is ```pub const EPOCH_DURATION_IN_SLOTS: BlockNumber = 1 * HOURS;```

I stopped all validators, waited at least an hour and then restarted but still had the above epoch error. 

I did notice in prior issues people refer to reverting blocks. I tried to revert blocks by running `./target/release/polkadot revert --chain ./specs/rococo-pop-art.json --pruning=archive 100`, but got `2021-12-09 11:37:42 Error with block built on 0xb98672463aaa5b729362c629ec6966a87fe709f6c941781abed449f449332d95: ClientImport("Unexpected epoch change")`

I believe this to be a rite of passage when dealing with babe, if you have any insights or sanity checklist for dealing with that would be awesome!

**Comment by decentration** [comment]
it seems from reading this it is quite a challenge https://github.com/paritytech/substrate/issues/4464

i assume a hard spoon is taking the state and porting it to a new chain

**Comment by NukeManDan** [comment]
https://substrate.stackexchange.com/ could be a good place to resurface some of this for some rep :grin:
