### ISSUE TITLE
half of the validation nodes go offline

### ISSUE THREAD

**Issue by transxask** [paritytech/subport#282]
What if half of the validation nodes go offline for some reason and the final block cannot be generated

**Comment by NukeManDan** [comment]
Nov 23 12:29:02.059  WARN 💔 Error importing block 0x9424295f8479fdf6e2d85ac5f073179777ea9d7837e2d1ba1cd37f34e17625de: Err(UnknownParent) 

This suggests you are missing state possibly network wide if all nodes are unable to find the parent :thinking: 
I suggest you restart all nodes, see what behavior is happening then on the verbose logs, and move from there. If it's a local testnet, likely best to start from scratch.

I apologize for the delay! Still an issue? Let's open this up again.
