### ISSUE TITLE
Pallet for enabling peer to peer messaging between authenticated users

### ISSUE THREAD

**Issue by gokulsan** [paritytech/subport#284]
Hello Substrate Team,

Could you please help me to know if there a reference pallet from substrate framework for enabling peer to peer messaging between authenticated users.

**Comment by NukeManDan** [comment]
Sorry for the delay in reply!
I would suggest looking at https://docs.substrate.io/tutorials/v3/permissioned-network/ - the node-authorization pallet would likely be a reasonable start to something like you propose. But... a "blockchain based general messaging platform" in general is a tried and fraught example of a use case this is very likely misguided. Please do consider the application logic very carefully. here is a primer to start the right thoughts moving:
https://docs.substrate.io/v3/runtime/storage/#what-to-store

Best of luck in your R&D :grin:
