### ISSUE TITLE
Dynamically call methods of other pallets as callback functions

### ISSUE THREAD

**Issue by en** [paritytech/subport#29]
I am trying to implement a pallet (we call it pallet-handler here), which is similar to a firewall plus a dispatcher.

This pallet receives external extrinsic and dispatches the messages to specific pallets for execution.

Other pallets dynamically register themselves to the pallet-handler and the pallet-handler dispatches messages
according to the registered rules.

Here is a pseudo-code:

pallet-handler:
```
decl_storage! {
	trait Store for Module<T: Trait> as Handler {
		// A map that records what kind of messages the pallet is interested in.
		Rules: map hasher(blake2_128_concat) u32 => PALLET_A_OR_PALLET_B;
	}
}

decl_module! {
	pub struct Module<T: Trait> for enum Call where origin: T::Origin {
		fn register(origin, message_type: u32, SOME_PALLET: ???) {
			ensure_root(origin)?;
			Rules::insert(message_type, SOME_PALLET);
		}

		fn dispatch(origin, message_type: u32, data: Vec<u8>) {
			ensure_root(origin)?;
                        let PALLET = Rules::get(message_type);
                        let result = PALLET::callback(data);
                        // ...
		}
	}
}
```
Pallet A:
```
decl_module! {
	pub struct Module<T: Trait> for enum Call where origin: T::Origin {
		fn callback(origin, data: Vec<u8>) {
			ensure_root(origin)?;
                        // ...
		}
	}
}
```
Pallet B:
```
decl_module! {
	pub struct Module<T: Trait> for enum Call where origin: T::Origin {
		fn callback(origin, data: Vec<u8>) {
			ensure_root(origin)?;
                        // ...
		}
	}
}
```
For example, register(1, PALLET_A) and register(2, PALLET_B) are called,  then the handler receives a message of type 1, so the message will be dispatched to pallet A.

How should I design the storage of pallet-handler to achieve this goal?

**Comment by bkchr** [comment]
Maybe @gautamdhameja can you help you here a little bit? :)

**Comment by gautamdhameja** [comment]
You can do this using a `SignedExtension`, by looking at the `CallMetadata`. This will allow you to filter/pre-process the extrinsic before you send it forward to the corresponding pallet.
Here's an example - https://github.com/gautamdhameja/substrate-rbac/blob/master/src/lib.rs#L226

**Comment by en** [comment]
Thanks, @gautamdhameja 
The example of access control is very helpful. For the problem of module callback, I currently use a workaround like this:
https://github.com/cdot-network/ibc-demo/blob/f81149af2b1fc6b19e155b537b49c6bf3e88985b/runtime/src/lib.rs#L45
