### ISSUE TITLE
how to get the public key of the caller (origin) of an extrinsic function

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#290]
i created an extrinsic function called my_func, and called it using 
```
    assert_ok!(MyTestModule::my_func(
        Origin::signed(account_1_account_id.clone()),
        account_1_public_key.clone(),
    ));

```

where i'm passing as the 2nd argument an account public key for Alice as shown below of type _Vec<u8>_, and i thought the way to convert it to type _u64_ so I could use it as  _T::AccountId_ (https://paritytech.github.io/substrate/monthly-2021-09+1/node_primitives/type.AccountId.html) was to use _Decode::decode..._ as shown below, and i'm using that account_1_account_id as the 1st argument.
```
const ALICE_PUBLIC_KEY: &[u8] = &[212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125];

let account_1_public_key: Vec<u8> = ALICE_PUBLIC_KEY.clone().into();
let account_1_account_id: u64 = Decode::decode(&mut account_1_public_key.as_slice().clone()).ok().unwrap();
```
when i run the test,  it calls _my_func_ extrinsic function as shown successfully, signed by Alice's account
```
pub fn my_func(origin: OriginFor<T>, sender_public_key: Vec<u8>) -> DispatchResult {
    let _sender = ensure_signed(origin)?;
    let account_public_key = _sender.encode();
    log::info!("account_public_key: {:?}", account_public_key.clone());
    log::info!("sender_public_key: {:?}", sender_public_key.clone());
    ...

```

but if i try to convert the signed origin _sender into its public key _Vec<u8>_ using _sender.encode(), then the output is _[212, 53, 147, 199, 21, 253, 211, 28]_ 

but Alice's public key that we provided in sender_public_key variable is actually [_212, 53, 147, 199, 21, 253, 211, 28, 97, 20, 26, 189, 4, 169, 159, 214, 130, 44, 133, 88, 133, 76, 205, 227, 154, 86, 132, 231, 165, 109, 162, 125]._

my goal is to find out the public key (32 element vector Vec<u8>) that corresponds to the account that actually calls the extrinsic my_func (i.e. the value of the origin argument ), because i want to check inside the function my_func  whether the public key that calls the function is a whitelisted public key that is stored in the database on-chain

but i haven't figured out how to do that, and i don't understand why running _sender.encode() is returning an 8 element vector instead of an 32 element vector for the public key?

**Comment by NukeManDan** [comment]
Please open a post on https://substrate.stackexchange.com/ if you are still looking for support! We can triage from there. Be sure to search there first for similar issues / errors. And add more context please, there is a bit too little to get started here.
