### ISSUE TITLE
Docker not peering with Docker nodes, but peering with non-Docker ones.

### ISSUE THREAD

**Issue by decentration** [paritytech/subport#291]
I have 3 validators, but only one validator (the non-docker validator) shows the 2 other peers. The other 2 docker validators only show one peer, which are both with the non-docker validator.

**Validator 1 (non-docker)**
`2021-12-10 14:34:00 💤 Idle (2 peers), best: #0 (0x5c45…01bb), finalized #0 (0x5c45…01bb), ⬇ 96 B/s ⬆ 24 B/s`

**Validator 2 (docker)**
`2021-12-10 14:36:17 💤 Idle (1 peers), best: #0 (0x5c45…01bb), finalized #0 (0x5c45…01bb), ⬇ 49 B/s ⬆ 44 B/s`

**Validator 3 (docker)**
`2021-12-10 14:36:47 💤 Idle (1 peers), best: #0 (0x5c45…01bb), finalized #0 (0x5c45…01bb), ⬇ 0 ⬆ 12 B/s`

Commands:

non-docker:
```
./target/release/polkadot --base-path /tmp/relay/newnode01 --chain ./specs/rococo-pop-art.json --port 30333 --ws-port 9944 --rpc-port 9933 --validator --name MyNode01
```

docker:

```
docker run --rm -it decentration/pop-art:v0.9.14 polkadot --chain /specs/rococo-pop-art.json --port 30334 --ws-port 9945 --rpc-port 9934 --validator --name Decentration02 --bootnodes /ip4/134.122.101.173/tcp/30333/p2p/12D3KooWMUjKWixBU6kv8iqcAvRq12DEQhKeJgsWJ8YPcMaCsC3y
```

in my Dockerfile i have exposed these ports:
`EXPOSE 30333-30343 9933-9960 8080 300`

has anyone had this behaviour where peers only show for non-docker validators? How can i fix?

**Comment by decentration** [comment]
```
CONTAINER ID   IMAGE                          COMMAND                  CREATED              STATUS              PORTS                                                                                                                                                                                                NAMES
9500c9454400   decentration/pop-art:v0.9.14   "/usr/local/bin/polk…"   About a minute ago   Up About a minute   300/tcp, 8080/tcp, 9933/tcp, 134.122.101.173:9934->9934/tcp, 9935-9944/tcp, 9946-9960/tcp, 134.122.101.173:9945->9945/tcp, 30333/tcp, 30335-30343/tcp, 134.122.101.173:30334->30334/tcp              magical_austin
7d669bc9f46d   decentration/pop-art:v0.9.14   "/usr/local/bin/polk…"   5 minutes ago        Up 5 minutes        300/tcp, 8080/tcp, 9933-9934/tcp, 134.122.101.173:9935->9935/tcp, 9936-9945/tcp, 9947-9960/tcp, 134.122.101.173:9946->9946/tcp, 30333-30334/tcp, 30336-30343/tcp, 134.122.101.173:30335->30335/tcp   optimistic_gould
```

**Comment by decentration** [comment]
@NukeManDan do you have an idea about Dockerized nodes that only peer with non-docker nodes and what the issue could be?

**Comment by justinFrevert** [comment]
@decentration can you share the relevant code w/ `Dockerfile`s or `docker-compose.yml`s?

**Comment by decentration** [comment]
@justinFrevert 

```Dockerfile
FROM paritytech/ci-linux:production as builder

LABEL description="This is the build stage for polkadot. Here we create the binary."

ARG PROFILE=release
WORKDIR /polkadot

COPY . /polkadot/
#RUN  fallocate -l 1G /swapfile

RUN rustup uninstall nightly
RUN rustup install nightly
RUN rustup update nightly
RUN rustup target add wasm32-unknown-unknown --toolchain nightly
RUN cargo clean
RUN cargo update
#RUN cargo +nightly-2021-11-01 check 
RUN cargo build --release

# ===== SECOND STAGE ======

FROM debian:buster-slim
LABEL description="This is the 2nd stage: a very small image where we copy the polkadot binary."
ARG PROFILE=release
COPY --from=builder /polkadot/target/$PROFILE/polkadot /usr/local/bin
COPY ./specs/ /specs/
RUN apt update && apt install -y ca-certificates 
RUN useradd -m -u 1000 -U -s /bin/sh -d /polkadot polkadot && \
	mkdir -p /polkadot/.local/share && \
	mkdir /data && \
	chown -R polkadot:polkadot /data && \
	ln -s /data /polkadot/.local/share/polkadot && \
	rm -rf /usr/bin /usr/sbin

USER polkadot
#EXPOSE 30333-30343 9933-9960 8080 300
VOLUME ["/data"]

CMD ["/usr/local/bin/polkadot"]
```

I tried both exposing ports from Dockerfile, and trying without exposing and instead exposing from the docker run command, i tried both -p and -P. i tried explicitly adding ip and host -p ip:port:host.

**Comment by justinFrevert** [comment]
@decentration it likely falls outside the scope of this support team. Our fault for not catching it sooner, so we'll give some pointers and help route you in the right direction.

You should check out [Docker Networking](https://docs.docker.com/network/) to look over any possible issues that may be affecting connectivity of your nodes. It's likely the issue lies here, while our support is focused on Substrate.

Since you're trying to run polkadot itself as a validator, you should check out the polkadot validator lounge for these common issues https://app.element.io/#/room/#polkadot-validator-lounge:matrix.org.
