### ISSUE TITLE
Why `IdentityFee<Balance>` of `pallet_transaction_payment` was replaced with `WeightToFee` on Polkadot0.9.11?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#293]
I just updated my codebase to Polkadot 0.9.11.  I was following Substarte Parachain Template. I found that the value of `WeightToFee`  got changed.
https://github.com/substrate-developer-hub/substrate-parachain-template/blob/polkadot-v0.9.11/runtime/src/lib.rs#L359

I just wanted to know:-

1) why it was changed?
2) How should I set value of `WeightToFeePolynomial`? Should I keep it same as parachain template

https://github.com/substrate-developer-hub/substrate-parachain-template/blob/polkadot-v0.9.11/runtime/src/lib.rs#L139-L140

**Comment by NukeManDan** [comment]
1. See the blame history for the PRs that are involved for details for _why_. 
- https://github.com/paritytech/cumulus/blame/ccf18114326287aedb6906b42c74ed4829c99022/parachain-template/runtime/src/lib.rs#L361

2. You must implement this in your runtime: https://paritytech.github.io/substrate/master/frame_support/weights/trait.WeightToFeePolynomial.html
- https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/src/lib.rs#L292
