### ISSUE TITLE
Why `AVERAGE_ON_INITIALIZE_RATIO` value was reduced to 5 in polkadot 0.9.11

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#294]
I just updated my codebase to Polkadot 0.9.11. I was following Substarte Parachain Template. I found that `AVERAGE_ON_INITIALIZE_RATIO` value was reduced to 5 in polkadot 0.9.11. In earlier version, it was 10.

What was the reason for that?

**Comment by NukeManDan** [comment]
Please see the blame history for this item in Cumulus, the template is derived from there. 
Also you very very much need to be on 0.9.12 at a minimum at the time of writting, and 0.9.14 is about to be release. Upgrades are critical.
