### ISSUE TITLE
Exported method AuraApi_slot_duration is not found

### ISSUE THREAD

**Issue by cgroeschel** [paritytech/subport#295]
This seems to be related to https://github.com/paritytech/substrate/issues/4172 just that we can't really purge the DB and instead need to find a way to get the node running on existing DB if possible at all.

Our working branch is here: https://github.com/DataHighway-DHX/node/tree/0575116484fbd6c4b3be47929b62f02b46e57062

**Comment by vasylenko-yevhen** [comment]
@cgroeschel hey there. We're currently facing similar issue in the process of migration to new substrate version. Did you manage to overcome this issue?
