### ISSUE TITLE
New nodes always disconnect to all other nodes before fully sync

### ISSUE THREAD

**Issue by SotaTek-ThinhPhung** [paritytech/subport#298]
HI substrate team, We built our chain with Substrate FRAME (v3.0.0). When we tried to test tps, a single validator (Node A) is disconnected with other nodes. We cleared Node A' data and restarted it. At the start, It synced data normally and connected with other peers, but when the process almost synced done, Node A disconnected with all other nodes again. We thinked it is banned by other nodes and we used new machine (Node B) to join network, but node B had the same problem. It only synced about 120k blocks while about 130k blocks are finalized, after that it disconnected with all other peers. We checked log of all nodes, but nothing is useful. Now, other nodes (which already in chain) is still working and producing block, but new nodes no longer can join, all of new nodes only sync about 120k/130k blocks, after that they disconnect to all other nodes. Please give us some hint for this situation! We do not get something useful from logs. We tried telnet and it connected therefore It's not networking problem. Thanks for any help!

**Comment by NukeManDan** [comment]
Sorry this was missed! If this issue is ongoing, please try with logs enabled at trace level for your network `--log=sc-network=trace` I believe. We can repoen this with more detail on https://substrate.stackexchange.com/
