### ISSUE TITLE
How  can we apply firewall on pallet calls?

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#299]
I have a helper pallet. Other pallets interact with this helper pallet to access some functionality. Can we put firewall on this pallet calls to limit how much different pallets can spend to how much was allocated to them?

**Comment by shawntabrizi** [comment]
You need to elaborate your question. If you can program it, you can do it with substrate, so not sure what kind of response you are looking for here.

**Comment by ayushmishra2005** [comment]
@shawntabrizi Can we limit or control number of calls to a pallet from other pallets?

**Comment by shawntabrizi** [comment]
Pallets at a high level are all a single piece of software, so there is no specific way to set a limit. But of course you can create APIs where pallets identify themselves, then you keep a counter, and stop accepting calls once a limit is reached.

**Comment by ayushmishra2005** [comment]
Thanks @shawntabrizi . Could you please guide how to create APIs where pallets identify themselves

**Comment by shawntabrizi** [comment]
Every pallet implements the `PalletInfo` trait: https://crates.parity.io/frame_support/traits/trait.PalletInfo.html

```
pub trait PalletInfo {
    fn index<P: 'static>() -> Option<usize>;
    fn name<P: 'static>() -> Option<&'static str>;
}
```

So you just need to pass that information from the pallet to where you want to track.

**Comment by NukeManDan** [comment]
This may be a good fit to post on https://substrate.stackexchange.com/ if you wanted :)
