### ISSUE TITLE
any plan for Substrate/Polkadot to integrate with Rosetta

### ISSUE THREAD

**Issue by rayeaster** [paritytech/subport#30]
https://www.rosetta-api.org/
https://github.com/coinbase/rosetta-specifications

**Comment by danforbes** [comment]
@rayeaster apologies for the extremely delayed response. We do not necessarily have any plans, per se, but we are aware of Rosetta and I personally think it's a very worthwhile effort. I am going to close this Issue, but please let me know if you'd like to help by implementing some Substrate/Rust/Rosetta integrations :rocket:
