### ISSUE TITLE
How the value of `VERSION_DISCOVERY_QUEUE_SIZE` is determined as 100

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#300]
How the value of `VERSION_DISCOVERY_QUEUE_SIZE` https://github.com/paritytech/polkadot/blob/v0.9.13/runtime/polkadot/src/lib.rs#L1439 is determined as 100?

**Comment by NukeManDan** [comment]
Please open a post on https://substrate.stackexchange.com/ if you are still looking for support! We can triage from there. Be sure to search there first for similar issues / errors.
