### ISSUE TITLE
How should we determine value of `candidacy_bond`

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#301]
How should we determine value of [		candidacy_bond](https://github.com/substrate-developer-hub/substrate-parachain-template/blob/971fc22076c9f366cdb1e2262c36ea925809b37b/node/src/chain_spec.rs#L191)

**Comment by NukeManDan** [comment]
Please open a post on https://substrate.stackexchange.com/ if you are still looking for support! We can triage from there. Be sure to search there first for similar issues / errors. Adding more of a stand alone q is best as well, not needing to link to another site to answer :pray:
