### ISSUE TITLE
This sdk haved transferAll Method ? or only have transferKeepAlive and transfer methods ?

### ISSUE THREAD

**Issue by alisivandiy** [paritytech/subport#304]
Im just saw transferKeepAlive and transfer methods ! ,
anybody know about this ?

**Comment by al3mart** [comment]
The extrinsic [`transfer_all`](https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L401) is available at balances pallet along those ones you have mentioned.
