### ISSUE TITLE
Pallet-EVM with Substrate 4.0.0

### ISSUE THREAD

**Issue by flupine** [paritytech/subport#306]
Hello !

I want to install pallet-evm on my substrate 4.0.0 chain, but I haven't found any relevant resources to use it with subtrate 4.0.0 because there is lot of changes between substrate 3.0.0 and 4.0.0 have you ever managed to use pallet-evm on this version ? If so, do you have any resources to give me?

**Comment by NukeManDan** [comment]
Please open a post on https://substrate.stackexchange.com/ if you are still looking for support! We can triage from there. Be sure to search there first for similar issues / errors.
matching versions is paramount FYI.
