### ISSUE TITLE
Wrong transferrable value

### ISSUE THREAD

**Issue by Tore19** [paritytech/subport#31]
Two validator accounts, initial state is:

Total: 350,000
Locked: 349,990(Vesting, will unlock gradually after 1 month)
Bonded: 300,000
Initial transferrable: 10

After a few eras, I made a payout(100 tokens were transferred to them to set an identity, so the reserved value is 100):

![image](https://user-images.githubusercontent.com/10955745/92682612-59ac5700-f363-11ea-83fc-0dc25faf1807.png)

I got 704.296 rewards and the reward destination is "Staked", so the bonded value is 300,704.296 now.

But why the transferrable value is 718.371? I think it should be 14.075 (718.371 - 704.296), because 704.296 rewards were already bonded.

If the transferrable value is 718.371, it means I can use the rewards(704.296) now and they are also bonded. Is that a problem?

**Comment by NukeManDan** [comment]
@Tore19 is this still an issue? If so, please reopen this 🙏🏼
