### ISSUE TITLE
Not able to make a bid to win a parachain slot

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#310]
I am following these instructions https://docs.substrate.io/tutorials/v3/cumulus/rococo/ to register https://github.com/DataHighway-DHX/DataHighway-Parachain as parachain on rococo.

I registered a para id 2026 and submitted as parathread. Its onboarded now

![image](https://user-images.githubusercontent.com/1575561/152301689-73161a46-cca3-42f8-86d3-ea8b9001a653.png)
  According to this https://docs.substrate.io/tutorials/v3/cumulus/rococo/#parachain-slot-auction, `Only fully-onboarded Rococo parathreads are eligible to bid in a Rococo parachain slot auction.` I should see the bidding option. But its not visible.
  
  
![image](https://user-images.githubusercontent.com/1575561/152301893-a9826bfd-ac45-4e8f-b809-9d2b96c86033.png)

Can we apply for crowdloan directly https://docs.substrate.io/tutorials/v3/cumulus/rococo/#crowdloans and skip auction?

How can we win the parachain slot?

**Comment by al3mart** [comment]
There is no bidding system on Rococo, as there are no auctions in place.

At the moment the on boarding is done manually.
