### ISSUE TITLE
Application Application VersionInvalid RuntimeConstruction

### ISSUE THREAD

**Issue by 99Kies** [paritytech/subport#311]
release polkadot v0.9.13 
![image](https://user-images.githubusercontent.com/45918704/152492592-801666de-da75-4439-87f3-346726330cfd.png)
I encountered an error when upgrading my parallel chain.
`Error: Service(Application(Application(VersionInvalid("RuntimeConstruction(Other(\"host doesn't provide such function: env:ext_pairing_bls12_377_add_version_1\"))"))))`
I don't know how to locate this problem, can someone help?

**Comment by bkchr** [comment]
https://github.com/paritytech/substrate/blob/7cb0e76b847a49e2a9227e0c039bcbb335c83309/bin/node/executor/src/lib.rs#L28

here you see how to add extra host functions.

**Comment by 99Kies** [comment]
@bkchr But here I have exactly the same example as above, but there is a problem.
![image](https://user-images.githubusercontent.com/45918704/152640565-3baad2ca-6bf1-4cda-b6d9-4599c73fb452.png)
![image](https://user-images.githubusercontent.com/45918704/152640579-a1fd286f-273e-453d-902b-116cbe8595a8.png)

**Comment by bkchr** [comment]
`bls12_377_add` where have you added this function to the host functions?

**Comment by 99Kies** [comment]
> `bls12_377_add` where have you added this function to the host functions?

![image](https://user-images.githubusercontent.com/45918704/152915491-59c47a37-6a06-48df-bc70-368d3c164b23.png)

On `Pallets` and `Primitives`, there are information about these functions, do you mean thatI have to delete them?

**Comment by 99Kies** [comment]
@bkchr I found the location of the function that reported the error. in `primitives::io::Pairing`.

**Comment by bkchr** [comment]
This is your own function or whatever. This doesn't exist in Substrate

**Comment by 99Kies** [comment]
@bkchr I solved the problem, thank you for your guidance!
