### ISSUE TITLE
Why set_balnace error but total issuance still changed?

### ISSUE THREAD

**Issue by xtony77** [paritytech/subport#312]
substrate v3.0.0
pallet-balances v3.0.0
pallet-sudo v3.0.0

`system_account`
```
data: {
    free: 1.0000 DOT
    reserved: 0
    miscFrozen: 1.0000 DOT
    feeFrozen: 0
}
```

`sudo_sudo` and `balances_set_balance`
```
newFree: 0,
newReserved: 0
```

I test the `sudo_sudo` and `balances_set_balance` on the local side, the error message I got was `ConsumerRemaining`, I guess the reason for the failure is that the miscFrozen balance is 1, so I can't set newFree to 0, but the total issuance still changed, why?

**Comment by shawntabrizi** [comment]
@xtony77 thanks for reporting this.

It was a bug, and is being fixed by: https://github.com/paritytech/substrate/pull/10826

Can you please share your Polkadot or your Kusama address, and I will open a treasury tip for finding this :)

**Comment by xtony77** [comment]
Ok, thinks.
16RzEcgXVzXXn2gEQbqqp74Pw7MJSb7PKtz29BhVZmpXBKRn

**Comment by shawntabrizi** [comment]
<img width="1673" alt="image" src="https://user-images.githubusercontent.com/1860335/153158765-7eee31ae-b64f-4db0-a7ad-506fe9c976d3.png">

The tip should resolve when other council members vote for it. Thanks!
