### ISSUE TITLE
About cross-chain pallet `cumulus-ping` occur `Bad origin`

### ISSUE THREAD

**Issue by VegeBun-csj** [paritytech/subport#318]
Hi, i have a question about a example pallet called [`cumulus-ping`](https://github.com/paritytech/cumulus/blob/master/polkadot-parachains/pallets/ping/src/lib.rs).I put it in my runtime.
Ok, i have start a local relaychain with rococo.And i have start two parachain(2000 and 3000) which use same wasm code and different genesis state.I registered 2000 and 3000 in my local rococo, and create a two-way channel between two chain.And i execute `extrinsic` in `developer` bar. i choose `ping-pong` pallet method `start`. wait a little, i got an error "Bad origin".
So i have some question that in polkadot-v0.9.8.Polkadot-js exists a `sudo` bar in `developer` bar. But in this polkadot-v0.9.16, it's missing.So, how can i address this error? 
Code link is this: https://github.com/VegeBun-csj/Proof-Chain

**Comment by VegeBun-csj** [comment]
> the error code is obviously, `BadOrigin` means your origin account is wrong:
> 
> https://github.com/paritytech/cumulus/blob/364a88f1dd0cbe22fd9e9f2b56da01972901ab15/polkadot-parachains/pallets/ping/src/lib.rs#L163-L165
> 
> https://github.com/paritytech/cumulus/blob/364a88f1dd0cbe22fd9e9f2b56da01972901ab15/pallets/xcm/src/lib.rs#L171-L178

OK, thanks. But i have configured the barrier in my parachain runtime, the code is :
```rust
match_type! {
	pub type SpecParachain: impl Contains<MultiLocation> = {
		// 当前上一级中继链下的parachain 2000
		MultiLocation {parents: 1, interior: X1(Parachain(2000))} |
		// 当前上一级中继链下的parachain 3000
		MultiLocation {parents: 1, interior: X1(Parachain(3000))}
	};
}
pub type Barrier = (
	TakeWeightCredit,
	AllowTopLevelPaidExecutionFrom<Everything>,
	AllowUnpaidExecutionFrom<ParentOrParentsExecutivePlurality>,
	// ^^^ Parent and its exec plurality get free execution
	AllowUnpaidExecutionFrom<SpecParachain>,
);
```
this configuration of Barrier is correct?
And my account is an account of  parachain 2000 when i start a cross chain tx in parachain2000

**Comment by al3mart** [comment]
`BadOrigin` thrown by [this line](https://github.com/paritytech/cumulus/blob/6af1dd5f6f3d3a8f333ec9f0540d442e26df7ec1/polkadot-parachains/pallets/ping/src/lib.rs#L121)

Meaning that `start` extrinsic needs to be called by root, thing that you can do by submitting a SUDO call with the SUDO account.

Polkadot.js apps is fairly smart, and it will show you tabs depending on the available features for the accounts loaded, so if you cannot see SUDO tab, that means that you have not a SUDO account loaded in the application.

Your error has nothing to do with the configuration of your barriers.
