### ISSUE TITLE
[Parachain] Could not find the header of the genesis block in the database!

### ISSUE THREAD

**Issue by 99Kies** [paritytech/subport#323]
network: rococo live
<img width="739" alt="image" src="https://user-images.githubusercontent.com/45918704/158636735-7d34b8ed-a63c-40de-9d5e-eaa20b19e646.png">

**Comment by 99Kies** [comment]
@bkchr I haven't solved the problem yet.

**Comment by bkchr** [comment]
I did not close the issue, I just moved it to the place where it belongs. Here you will get better help.

**Comment by 99Kies** [comment]
i fixed it.
