### ISSUE TITLE
V2.0.0 p2p connection not compatible with RC3

### ISSUE THREAD

**Issue by mikiquantum** [paritytech/subport#33]
We are in the process of upgrading our chain to v2.0.0 released. 
We were able to successfully upgrade to 2.0.0-rc6 from alpha.3, and since we saw that the official 2.0 release was out we thought to give it a go.

Since we have to make a two step upgrade node first and then runtime due to all the changes between these two versions, we had to have a hybrid network for a little bit using bootnodes in RC3, so old nodes (alpha3) and new ones (rc6) could still communicate to each other until we execute the runtime upgrade.
After RC3 the `--legacy-network-protocol` was removed, so we had to use that version for the bootnodes (closest compatible to RC6).
Now have been trying to use instead of RC6, the latest released v2.0.0, and since there has been changes on the libp2p version seems like it cannot connect anymore with older nodes (RC3 ones).

I can see in the logs:
```
Sep 24 08:27:13.701 DEBUG Handler(PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw")) => Endpoint Dialer { address: "/ip4/127.0.0.1/tcp/30335" } open for custom protocols.
Sep 24 08:27:13.701 DEBUG External API <= Open(PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw"))
Sep 24 08:27:13.701 DEBUG Connected 12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw
Sep 24 08:27:13.701 DEBUG New peer with known best hash 0x4249…c6e2 (571).
Sep 24 08:27:13.701 DEBUG Negotiated: Received confirmation for protocol: /substrate/flvs/6
Sep 24 08:27:13.702 DEBUG Successfully applied negotiated protocol
Sep 24 08:27:13.702 DEBUG Received no longer supported legacy request from PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw")
Sep 24 08:27:13.702 DEBUG External API => Disconnect PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw")
Sep 24 08:27:13.702 DEBUG PSM <= Dropped(PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw"))
Sep 24 08:27:13.702 DEBUG Handler(PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw")) <= Disable
Sep 24 08:27:13.702 DEBUG PSM => Connect(PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw")): Enabling connections.
Sep 24 08:27:13.702 DEBUG Handler(PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw")) <= Enable
Sep 24 08:27:13.702 DEBUG Report 12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw: -2147483648 to -2147483648. Reason: Unsupported protocol, Disconnecting
Sep 24 08:27:13.702 DEBUG PSM => Drop(PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw")): Disabling connections.
Sep 24 08:27:13.702 DEBUG Dropped TCP connection to 127.0.0.1:30335
Sep 24 08:27:13.702 DEBUG Handler(PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw")) <= Disable
Sep 24 08:27:13.702 DEBUG Connection Connected { endpoint: Dialer { address: "/ip4/127.0.0.1/tcp/30335" }, info: PeerId("12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw") } closed: Handler(Handler(A(A(A(A(A(A(Legacy(ConnectionKillError)))))))))
Sep 24 08:27:13.702 DEBUG Libp2p => Connection (ConnectionId(TaskId(36)),Dialer { address: "/ip4/127.0.0.1/tcp/30335" }) to 12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw closed.
Sep 24 08:27:13.702 DEBUG External API <= Closed(12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw)
Sep 24 08:27:13.702 DEBUG Libp2p => Disconnected(12D3KooWL7zjphsMraXk4pMwR5eJiuYCjtybvLAXqXbDQNbK8oiw): Was disabled.
```

Is there any way that we could (easily) fix the incompatibility, without downgrading the libp2p version?

Otherwise we might have to stick to RC6 and schedule a future upgrade to v2.0.0 as soon as all the nodes in the network have been upgraded.

Thanks in advance

**Comment by danforbes** [comment]
@mikiquantum I asked around a bit and it sounds like the two-step approach you are describing is what others are taking as well. I will leave this Issue open; please keep us posted on your progress and let us know if you have any questions.

**Comment by mikiquantum** [comment]
Thanks for the heads up @danforbes . I will give an update here as soon as we start moving the upgrade up.

**Comment by NukeManDan** [comment]
@mikiquantum I _think_ is this not still an issue? If so, please reopen this 🙏🏼
