### ISSUE TITLE
Importing account from the mnemonic generated a different account address using polkadot.js browser UI

### ISSUE THREAD

**Issue by adibart** [paritytech/subport#335]
I lost the setup for polkadot.js account in my browser. When I recovered the account using my 12 seed mnemonic, it recovered the account with a different address.

I can't access any of my crowdloan funds as the account identifier has now [changed.[](url)](url)

**Comment by NukeManDan** [comment]
https://support.polkadot.network/support/home is where you can find help, github is not a place to receive end user support. I suggest reading through guides there, and trying to contact the support email if no luck. 

Best of luck!
