### ISSUE TITLE
Rococo Slot Request

### ISSUE THREAD

**Issue by ncodespot** [paritytech/subport#336]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Kylin

### Parachain Name

KylinTest

### ParaID

3012

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-3012-genesis.txt](https://github.com/paritytech/subport/files/8416960/para-3012-genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-3012-wasm.txt](https://github.com/paritytech/subport/files/8416964/para-3012-wasm.txt)

### (Optional) Upload your Chain Specification

[rococo-public-parachain-3012-plain.txt](https://github.com/paritytech/subport/files/8416989/rococo-public-parachain-3012-plain.txt)

### Anything else we should know?

We just want to test the public rococo testnet deployment process

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding in aprox 1h 20'
