### ISSUE TITLE
Rococo slot request from Litentry

### ISSUE THREAD

**Issue by Kailai-Wang** [paritytech/subport#337]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Litentry

### Parachain Name

litentry-rococo

### ParaID

2106

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://github.com/litentry/litentry-parachain/releases/download/v0.9.5/rococo-genesis-state

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/litentry/litentry-parachain/releases/download/v0.9.5/rococo-genesis-wasm

### (Optional) Upload your Chain Specification

https://github.com/litentry/litentry-parachain/blob/release-v0.9.5/node/res/chain_specs/rococo.json

### Anything else we should know?

paraId on rococo is matching Litmus now (2106)

### Register your Rococo parachain details for `polakdot-js/apps`

https://github.com/polkadot-js/apps/pull/7287
https://github.com/polkadot-js/apps/pull/7325

**Comment by al3mart** [comment]
It would be very handy if you build your rococo runtime for the same paraId than in Kusama, do you have anything blocking you from doing that ?
If that is not the case I would appreciate if you can update the issue with the new build :)

**Comment by Kailai-Wang** [comment]
No problem, I'll change the ID to 2106 and rebuild it.
I'll update the thread later.

**Comment by Kailai-Wang** [comment]
Hi @al3mart, now it should be rebuilt with paraId 2106. Tests with rococo-local looked good.

**Comment by al3mart** [comment]
Onboarding in aprox 1h 50'

**Comment by Kailai-Wang** [comment]
We'd like to have a state rollback to block number #1700000 for our parachain on rococo

I note down the steps that I have down:
- stop all instances (rpc nodes, collators)
- backup DB from rpc node (archive node)
- on rpc node:
   `./litentry-collator export-state --chain=rococo --pruning=archive -- 170000 > rococo-170000.json`
   `./litentry-collator export-genesis-state --chain=./rococo-170000.json > rococo-170000-genesis-state`
   `./litentry-collator export-genesis-wasm --chain=./rococo-170000.json > rococo-170000-genesis-wasm`
- perform `export-state` step on all nodes (to rollback the DB)
- adjust the startup parameter to use `rococo-1700000.json` as bootstrap chain spec

I have attached the rococo-170000-genesis-state and rococo-170000-genesis-wasm as zip file.

[rococo-170000-genesis.zip](https://github.com/paritytech/subport/files/8774755/rococo-170000-genesis.zip)

**Comment by al3mart** [comment]
I am concerned about the chain parameter here:
` ./litentry-collator export-state --chain=rococo --pruning=archive -- 170000 > rococo-170000.json`
Is that chain spec pointing to rococo the relay, or it happens that the chain spec that you are using is called `rococo` ?
What we are looking here is to export the state from the parachain side, not the relay state.

**Comment by Kailai-Wang** [comment]
> I am concerned about the chain parameter here: ` ./litentry-collator export-state --chain=rococo --pruning=archive -- 170000 > rococo-170000.json` Is that chain spec pointing to rococo the relay, or it happens that the chain spec that you are using is called `rococo` ? What we are looking here is to export the state from the parachain side, not the relay state.

Hi @al3mart ,thanks for being attentive :)
Yea it represents the [parachain chain spec](https://github.com/litentry/litentry-parachain/blob/release-v0.9.7/node/src/command.rs#L107), not the relaychain, we were just lazy to invent a new single-word for our parachain on rococo :)

With that being said, the state should be correctly exported. Please go ahead and reset the head state to `rococo-170000-genesis-state`, I've already adapted it to use the new chain spec.

**Comment by al3mart** [comment]
New artifacts have been pushed

**Comment by Kailai-Wang** [comment]
Thanks a lot, much appreciated!

**Comment by NicoMorganParity** [comment]
Hello @Kailai-Wang,
Can you please share with us your Parachain Manager Account.
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.

**Comment by Kailai-Wang** [comment]
> Hello @Kailai-Wang, Can you please share with us your Parachain Manager Account. A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.

Hey Nico thanks for reaching out!

Here's the rococo account: `5ELWo1HLSAGUrjwcvcCB1HcDb8XMmh4SouLW6oRkR64JMK69`, however I'm not sure if it was the account which registered the parachain (or if we registered it on our own at all)
