### ISSUE TITLE
Rococo Slot Request

### ISSUE THREAD

**Issue by Bart2048** [paritytech/subport#338]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

BartTech

### Parachain Name

Bart Testnet

### ParaID

3013

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-3013-genesis-bart.txt](https://github.com/paritytech/subport/files/8419151/para-3013-genesis-bart.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-3013-wasm-bart.txt](https://github.com/paritytech/subport/files/8419154/para-3013-wasm-bart.txt)

### (Optional) Upload your Chain Specification

[bart-rococo.txt](https://github.com/paritytech/subport/files/8419161/bart-rococo.txt)

### Anything else we should know?

test the public rococo parachain

### Register your Rococo parachain details for `polakdot-js/apps`

skip this step

**Comment by al3mart** [comment]
Onboarding in aprox 1h 30'
