### ISSUE TITLE
Dolphin 2084

### ISSUE THREAD

**Issue by ghzlatarev** [paritytech/subport#339]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Manta Network

### Parachain Name

Dolphin

### ParaID

2084

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[dolphin-testnet-2084-state.zip](https://github.com/paritytech/subport/files/8464251/dolphin-testnet-2084-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[dolphin-testnet-2084-wasm.zip](https://github.com/paritytech/subport/files/8464216/dolphin-testnet-2084-wasm.zip)

### Anything else we should know?

Can we start a HRMP channel with parachain ID 2000

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Already onboarded

**Comment by al3mart** [comment]
Pushing initial state again

**Comment by ghzlatarev** [comment]
Thanks.

**Comment by ghzlatarev** [comment]
Can we restore from block #99117 wss://anjie.rococo.dolphin.engineering
