### ISSUE TITLE
Rococo Slot Request

### ISSUE THREAD

**Issue by F3Joule** [paritytech/subport#340]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Dappforce

### Parachain Name

Subsocial

### ParaID

3015

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-3015-rococo-genesis.txt](https://github.com/paritytech/subport/files/8468353/para-3015-rococo-genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-3015-rococo-wasm.txt](https://github.com/paritytech/subport/files/8468354/para-3015-rococo-wasm.txt)

### Anything else we should know?

Test the HRMP with Acala

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding in aprox 1h 40'
