### ISSUE TITLE
Rococo Slot Request

### ISSUE THREAD

**Issue by ygit1** [paritytech/subport#342]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

ydot

### Parachain Name

ymint

### ParaID

3018

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-3018-genesis.zip](https://github.com/paritytech/subport/files/8476503/para-3018-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-3018-wasm.zip](https://github.com/paritytech/subport/files/8476504/para-3018-wasm.zip)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y para ID...

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding in about 1h
