### ISSUE TITLE
Rococo Slot prolongation Request

### ISSUE THREAD

**Issue by F3Joule** [paritytech/subport#344]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Dappforce

### Parachain Name

Subsocial

### ParaID

3015

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-3015-rococo-genesis.txt](https://github.com/paritytech/subport/files/8488710/para-3015-rococo-genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-3015-rococo-wasm.txt](https://github.com/paritytech/subport/files/8488712/para-3015-rococo-wasm.txt)

### Anything else we should know?

We need a few more days to finish our testing. Then we'll get long-term slot. But for now we please for prolongation.

### Register your Rococo parachain details for `polakdot-js/apps`

- [X] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7374

**Comment by al3mart** [comment]
```
{
  manager: 5GjP491LcTa71ZhTBbwp3Eda3xauBX8ESunEsQq3KCQPaz4r
  periodBegin: 28
  periodCount: 3
  lastLease: 28
  leaseCount: 1
}
```
For what I see, you should be onboarded again in the next batch. These onboarding/offboardings are automated by the [assigned_slots](https://github.com/paritytech/polkadot/blob/master/runtime/common/src/assigned_slots.rs) pallet.

In the meantime I could suggest running rococo_local on your side and keep on testing in there.
