### ISSUE TITLE
Rococo Long Term Slot Request

### ISSUE THREAD

**Issue by Bart200c** [paritytech/subport#346]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

PichiuNetwork

### Parachain Name

Pichiu Rococo Testnet

### ParaID

2102

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[pichiu-2102-genesis.txt](https://github.com/paritytech/subport/files/8497274/pichiu-2102-genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[pichiu-2102-wasm.txt](https://github.com/paritytech/subport/files/8497279/pichiu-2102-wasm.txt)

### (Optional) Upload your Chain Specification

[pichiu-rococo-parachain-2102-raw.json.txt](https://github.com/paritytech/subport/files/8497281/pichiu-rococo-parachain-2102-raw.json.txt)

### Anything else we should know?

We want to launch an XCM channel with community parachains.

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding happening in aprox 1h 50'

**Comment by Bart200c** [comment]
My mistake. The genesis dose not match the para_id 2102, need help to para clean and new genesis para init. Thanks a lot! @al3mart 

New genesis:
[pichiu-2102-genesis.txt](https://github.com/paritytech/subport/files/8519430/pichiu-2102-genesis.txt)
[pichiu-2102-wasm.txt](https://github.com/paritytech/subport/files/8519431/pichiu-2102-wasm.txt)
[pichiu-rococo-parachain-2102-raw.json.txt](https://github.com/paritytech/subport/files/8519434/pichiu-rococo-parachain-2102-raw.json.txt)

MD5 (2102/pichiu-2102-genesis) = 7eb933ee8956bbec0242ff0c52e3db2d
MD5 (2102/pichiu-2102-wasm) = 182a330869d9328c4e3e3342dfa969f2
MD5 (2102/pichiu-rococo-parachain-2102-raw.json) = 939e29032a14fee27ab4eb1d014f7938

**Comment by al3mart** [comment]
Sure thing!

**Comment by Bart200c** [comment]
Hi @al3mart, Need help updating the relaychain code. 

[pichiu_runtime.compact.compressed.wasm.txt](https://github.com/paritytech/subport/files/8680475/pichiu_runtime.compact.compressed.wasm.txt)

Because of a wrong upgrade(set_code), the relaychain codeHash is different from parachain codeHash

New codeHash: 6479f047278bf800d77ed8606346e7ecd0cb3485acc3713047827074c5e1e5a4
![image](https://user-images.githubusercontent.com/103230129/168109838-4bbb23ce-5641-46cb-ba7d-d40057b3c942.png)

Relaychain wrong codeHash: 
![image](https://user-images.githubusercontent.com/103230129/168109594-e49d4ff3-6fda-4383-80ae-5220ce32e21a.png)
