### ISSUE TITLE
Rococo Slot Request

### ISSUE THREAD

**Issue by F3Joule** [paritytech/subport#348]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Dappforce

### Parachain Name

SubsocialX (SoonSocialX on Rococo)

### ParaID

2100

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-2100-genesis.txt](https://github.com/paritytech/subport/files/8521792/para-2100-genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-2100-wasm.txt](https://github.com/paritytech/subport/files/8521794/para-2100-wasm.txt)

### (Optional) Upload your Chain Specification

https://github.com/dappforce/subsocial-parachain/blob/f3/rococo/node/res/soonsocial.json

### Anything else we should know?

Since this parachain is started, we can stop 3015, which was requested to obtain short term slot.

I will appreciate if you'll reserve 2100 para id for this account: `5GjP491LcTa71ZhTBbwp3Eda3xauBX8ESunEsQq3KCQPaz4r`

### Register your Rococo parachain details for `polakdot-js/apps`

- [X] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7374

**Comment by al3mart** [comment]
Onboarding as a parathread now. Once this is complete I will trigger the parachain onboarding

**Comment by al3mart** [comment]
Onboarding happening in 1h 12'
