### ISSUE TITLE
Genshiro parachain slot

### ISSUE THREAD

**Issue by muctep-dehuc** [paritytech/subport#349]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Equlibrium

### Parachain Name

Genshiro

### ParaID

2024

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[state.txt](https://github.com/paritytech/subport/files/8531349/state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[wasm.txt](https://github.com/paritytech/subport/files/8531352/wasm.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y para ID...

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Registering your parathread right now

**Comment by al3mart** [comment]
Onboarding happening in aprox 2h
