### ISSUE TITLE
Centrifuge Rococo Temporary Slot for XCM Testing

### ISSUE THREAD

**Issue by mikiquantum** [paritytech/subport#350]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Centrifuge

### Parachain Name

Altair Testnet Temp 0

### ParaID

2088

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[xcm-altair-dev.txt](https://github.com/paritytech/subport/files/8535254/xcm-altair-dev.txt)

### Upload your Validation Code (genesis runtime Wasm)

[parachain_altair_runtime-aa467c6.compact.compressed.txt](https://github.com/paritytech/subport/files/8535259/parachain_altair_runtime-aa467c6.compact.compressed.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y para ID...

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Registering parathread right now

**Comment by al3mart** [comment]
Short term slot assigned, you should be onboarding on the coming rotation
