### ISSUE TITLE
Rococo Slot Request

### ISSUE THREAD

**Issue by abhath-labs** [paritytech/subport#351]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Bitgreen

### Parachain Name

BitgreenRococo

### ParaID

3024

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-2000-genesis.zip](https://github.com/paritytech/subport/files/8551749/para-2000-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-2000-wasm.zip](https://github.com/paritytech/subport/files/8551751/para-2000-wasm.zip)

### Register your Rococo parachain details for `polakdot-js/apps`

- [X] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7441

**Comment by al3mart** [comment]
you genesis and head are called `para-200-*` are they built for the same paraId than the one you are requesting to be onboarded on ?

**Comment by abhath-labs** [comment]
yes they are for 3024, just kept the default filename

**Comment by al3mart** [comment]
Your para will get onboarded on the next rotation

**Comment by abhath-labs** [comment]
Thanks, unfortunately the chain is not producing blocks. No specific error, just repeats importing block1.
Should we create another paraId and try again or share an updated wasm/genesis to reset?
