### ISSUE TITLE
Integrittee Parachain seems to have lost it's slot

### ISSUE THREAD

**Issue by SBalaguer** [paritytech/subport#352]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Integritee

### Parachain Name

Integritee

### ParaID

1003

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

It's already on chain.

### Upload your Validation Code (genesis runtime Wasm)

It's already on chain

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y para ID...

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
1h 13' mins to onboarding

**Comment by brenzi** [comment]
pardon: the ParaID is correct, but the team is wrong: this is encointer's parachainz. but all good no need to do anything
