### ISSUE TITLE
t0rn slot

### ISSUE THREAD

**Issue by chiefbiiko** [paritytech/subport#353]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

t3rn

### Parachain Name

t0rn

### ParaID

3333

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[t0rn.genesis.txt](https://github.com/paritytech/subport/files/8556183/t0rn.genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[t0rn.wasm.txt](https://github.com/paritytech/subport/files/8556191/t0rn.wasm.txt)

### (Optional) Upload your Chain Specification

[t0rn.raw.json.txt](https://github.com/paritytech/subport/files/8556202/t0rn.raw.json.txt)

### Anything else we should know?

We would love to keep the slot for as long as possible.

### Register your Rococo parachain details for `polakdot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7443

**Comment by MaciejBaj** [comment]
thanks @al3mart

**Comment by al3mart** [comment]
Short term granted, you should be onboarding on the next rotation

**Comment by MaciejBaj** [comment]
perfect, all working fine!
