### ISSUE TITLE
Rococo temp slot request

### ISSUE THREAD

**Issue by abhath-labs** [paritytech/subport#354]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Bitgreen

### Parachain Name

BitgreenRococo

### ParaID

3029

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[rococo-bitgreen-3029-genesis.zip](https://github.com/paritytech/subport/files/8565116/rococo-bitgreen-3029-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[rococo-bitgreen-3029-wasm.zip](https://github.com/paritytech/subport/files/8565112/rococo-bitgreen-3029-wasm.zip)

### (Optional) Upload your Chain Specification

[rococo-bitgreen-3029-raw.json.zip](https://github.com/paritytech/subport/files/8565205/rococo-bitgreen-3029-raw.json.zip)

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by abhath-labs** [comment]
We made some changes to the parachain code that we think should fix the issue with #351, please remove the parachain from slot 3204 and onboard us in the new slot 3029. Thanks

**Comment by al3mart** [comment]
Should onboard in next rotation
