### ISSUE TITLE
eth json rpc 

### ISSUE THREAD

**Issue by slashramin** [paritytech/subport#355]
when I call this method :
```
{
    "jsonrpc": "2.0",
    "id": "1",
    "method": "eth_accounts",
    "params": [
    ]
}
```
response is :
``` 
{
    "jsonrpc": "2.0",
    "error": {
        "code": -32601,
        "message": "Method not found"
    },
    "id": "1"
}
```
why this is happening to me?
in documentation polkadot supports eth but when I call like document I got this error

**Comment by al3mart** [comment]
I find https://substrate.stackexchange.com a much better place for this type of question.
Please, open a question in stackexchange as it has more visibility and your doubts might be useful for other devs.
Thanks.
