### ISSUE TITLE
Mangata <3 Roccoco: long-lasting slot on Rococo

### ISSUE THREAD

**Issue by goncer** [paritytech/subport#356]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Mangata

### Parachain Name

Mangata

### ParaID

2110

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[node_0.11.1_genesis_state_public_testnet.remove.zip](https://github.com/paritytech/subport/files/8570179/node_0.11.1_genesis_state_public_testnet.remove.zip)

### Upload your Validation Code (genesis runtime Wasm)

[node_0.11.1_genesis_wasm_public_testnet.remove.zip](https://github.com/paritytech/subport/files/8570181/node_0.11.1_genesis_wasm_public_testnet.remove.zip)

### (Optional) Upload your Chain Specification

[node_0.11.1_public_testnet_spec.remove.zip](https://github.com/paritytech/subport/files/8570191/node_0.11.1_public_testnet_spec.remove.zip)

### Anything else we should know?

Had to name the files with "remove.zip". remove it if necessary :)

We want to start a XCM channel with Acala! 

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding parathread in aprox 1h. Leases will be granted afterwards

**Comment by al3mart** [comment]
Onboarding in 1h20'

**Comment by goncer** [comment]
Thanks guys! hopefully we manage to deploy the nodes by Monday! :)
