### ISSUE TITLE
Integritee Parachain slot

### ISSUE THREAD

**Issue by brenzi** [paritytech/subport#358]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Integritee

### Parachain Name

Integritee on Rococo

### ParaID

2015

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[integritee-rococo.state.zip](https://github.com/paritytech/subport/files/8589106/integritee-rococo.state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[integritee_runtime-v17.compact.compressed.wasm.zip](https://github.com/paritytech/subport/files/8589110/integritee_runtime-v17.compact.compressed.wasm.zip)

### (Optional) Upload your Chain Specification

[integritee-rococo.json.zip](https://github.com/paritytech/subport/files/8589115/integritee-rococo.json.zip)

### Anything else we should know?

We want to start an HRMP Channel with 
* Acala Team: 
* Moonbeam:

### Register your Rococo parachain details for `polakdot-js/apps`

- [x] Polkadot-js Apps UI PR completed and merged

**Comment by al3mart** [comment]
Onboarding parathread now, afterwards I would assing a slot

**Comment by al3mart** [comment]
Onboarding happening now. Aprox 1h30' to finish
