### ISSUE TITLE
Rococo Slot Request

### ISSUE THREAD

**Issue by abhath-labs** [paritytech/subport#359]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Bitgreen

### Parachain Name

BitgreenRococo

### ParaID

2001

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[bitg-parachain-rococo-2001-genesis.zip](https://github.com/paritytech/subport/files/8583053/bitg-parachain-rococo-2001-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[bitg-parachain-rococo-2001-wasm.zip](https://github.com/paritytech/subport/files/8583054/bitg-parachain-rococo-2001-wasm.zip)

### (Optional) Upload your Chain Specification

[bitg-parachain-rococo-2001-raw.json.zip](https://github.com/paritytech/subport/files/8583057/bitg-parachain-rococo-2001-raw.json.zip)

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Sorry, I would prefer to keep paraId lower than 3000 for paras holding a permanent slot. Could you please reserve a new paraId and build your state and wasm again, plase ?

**Comment by abhath-labs** [comment]
Sure, just reserved 3000, will upload new wasm/genesis asap.

**Comment by abhath-labs** [comment]
ParaId : 3000
Genesis :
[bitg-parachain-rococo-3000-genesis.zip](https://github.com/paritytech/subport/files/8585028/bitg-parachain-rococo-3000-genesis.zip)
Wasm : 
[bitg-parachain-rococo-3000-wasm.zip](https://github.com/paritytech/subport/files/8585030/bitg-parachain-rococo-3000-wasm.zip)
Chainspec :  
[bitg-parachain-rococo-3000-raw.json.zip](https://github.com/paritytech/subport/files/8585031/bitg-parachain-rococo-3000-raw.json.zip)

**Comment by al3mart** [comment]
Registering parathread. Afterwards I would be able to assing the leases

**Comment by al3mart** [comment]
Temp slot assigned, will onboard in the next rotation
