### ISSUE TITLE
query transaction

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/subport#36]
Is there a way to know the transaction hash information for each block call by using the substrate rpc? I want to extract the transaction hash information that for example alice sent 100 to bob by searching the block and extracting that alice gave 100  to bob in the corresponding transaction.

**Comment by danforbes** [comment]
Can you please clarify your question? In the meantime, you may want to refer to this section in the Polkadot wiki that describes why transactions on Substrate-based chains _cannot_ be uniquely identified by a hash. https://wiki.polkadot.network/docs/en/build-protocol-info#unique-identifiers-for-extrinsics

**Comment by puffanddmx** [comment]
Usually transaction hash is included in block information. However, if you look at the block information below, it seems that there is no transaction hash information. However, if you look at the decomposition in extrinsics, information about how much a sent to b is visible, but there is no information about the transaction hash. When search for the transaction hash, i want to know the information that a sends to b. This is because in general blockchain, deposits and withdrawals are recorded based on transaction hash.

my transaction hash : 0x585d7b01c1ec1de2fa9c12c20a1b35cde18f55fc88206fcada45589f3aaebafb

get block 
{"block":{"header":{"parentHash":"0xe7d2b3ac4bc01be44682a79386b28c0fe71160578fbbdd0bda6728cbeaf9ecb5","number":1092,"stateRoot":"0x58fd0f03bfbbc9a8d9eb937c641a02e483616c135bfca3b8dd010c447464a799","extrinsicsRoot":"0x6b1270f2dd4c30fb5c76faf17c683daac4f049b92c41b08c969c58fc3b06455f","digest":{"logs":[{"PreRuntime":[1634891105,"0x3b781a1300000000"]},{"Seal":[1634891105,"0x60aefed5112ce37c55070d02105b3a54b4118e0b5755a56d0c50f13fa5ce9358923af4c72c66eb5a18f034791e1867fb7e5782ef2011291bb0e4d8c8cb935e83"]}]}},"extrinsics":["0x280402000b6440fc1c7501","0x490284d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d011c2346e75224e02786957ecd69b0c8627d8a89d5c5b758a0b65c97f0de5c0d3db93b10ffb9a81a8cca8c22ba571487d69f92a54837427d564b5dad5789215b820604080007008eaf04151687736326c9fea17e25fc5287613693c912909cb226aa4794f26a48170000a0dec5adc93536"]},"justification":"0x"}

**Comment by puffanddmx** [comment]
Thanks

**Comment by danforbes** [comment]
@puffanddmx you may also want to look into indexing solutions such as Substrate Archive...
GitHub https://github.com/paritytech/substrate-archive
Demonstration https://www.crowdcast.io/e/substrate-seminar
