### ISSUE TITLE
t0rn rococo slot

### ISSUE THREAD

**Issue by chiefbiiko** [paritytech/subport#361]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

t3rn

### Parachain Name

t0rn

### ParaID

3333

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://raw.githubusercontent.com/t3rn/t3rn/v1.0.0-rc.2/specs/t0rn.genesis

### Upload your Validation Code (genesis runtime Wasm)

https://raw.githubusercontent.com/t3rn/t3rn/v1.0.0-rc.2/specs/t0rn.wasm

### (Optional) Upload your Chain Specification

https://raw.githubusercontent.com/t3rn/t3rn/v1.0.0-rc.2/specs/t0rn.raw.json

### Anything else we should know?

We would love to keep the slot for as long as possible <3

### Register your Rococo parachain details for `polakdot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7443

**Comment by al3mart** [comment]
Onboarding parathread. Once this is done I will be able to assign leases

**Comment by al3mart** [comment]
Temp slot assigned, will onboard in the next rotation

**Comment by NicoMorganParity** [comment]
Hello @chiefbiiko,
Can you please share with us your Parachain Manager Account.
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.
