### ISSUE TITLE
Genshiro parachain change head and code

### ISSUE THREAD

**Issue by muctep-dehuc** [paritytech/subport#362]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Equilibrium

### Parachain Name

Genshiro

### ParaID

2024

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[genesis-state.txt](https://github.com/paritytech/subport/files/8588875/genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[genesis-wasm.txt](https://github.com/paritytech/subport/files/8588876/genesis-wasm.txt)

### Anything else we should know?

We want to reset current head and code on relay to ones, given in this issue

### Register your Rococo parachain details for `polakdot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7423

**Comment by al3mart** [comment]
New state and code set
