### ISSUE TITLE
 Rococo Slot Request from Robonomics.network

### ISSUE THREAD

**Issue by PavelSheremetev** [paritytech/subport#364]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Robonomics.network

### Parachain Name

Robonomics.network

### ParaID

3001

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[genesis.state.txt](https://github.com/paritytech/subport/files/8592101/genesis.state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[genesis.wasm.txt](https://github.com/paritytech/subport/files/8592103/genesis.wasm.txt)

### Anything else we should know?

We want to launch an XCM channel with community parachains.

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7492

**Comment by al3mart** [comment]
Hey! We are trying to shape Rococo to be as close to Kusama as possible, for this very reason one thing we are asking to teams testing on Rococo is to build their state and code using the same paraId than in Kusama. So I would appreciate very much if you could update this issue with the artifacts built for paraId `2048`.
Don't worry for reserving the parId, I can register you for the correct one from my side

**Comment by PavelSheremetev** [comment]
Restarted nodes for paraid 2048
Attached below are the current genesis state and genesis wasm:
[genesis.state.txt](https://github.com/paritytech/subport/files/8602455/genesis.state.txt)
[genesis.wasm.txt](https://github.com/paritytech/subport/files/8602457/genesis.wasm.txt)

**Comment by al3mart** [comment]
Onboarding parathread now, 1h 40' to go

**Comment by al3mart** [comment]
Onboarding happening now.
If you need anything more, please feel free to reopen this issue

**Comment by PavelSheremetev** [comment]
Hi! We would like to test HRMP channel opening with Rococo Statemint. Can you help us with this? What is required from our side?

**Comment by al3mart** [comment]
Rockmine is now all set on with paraId `1000`, you may now start opening your channels.

The way this works is, you need to compose a call like this one - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/extrinsics/decode/0x1700e8030000e803000000900100

Sace the encoded call data and use it in a xcm message from your para to the relay chain. You xcm message might look something similiar to this one - https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-statemint-rpc.polkadot.io#/extrinsics/decode/0x1f00010100020c000400000000070010a5d4e81300000000070010a5d4e80006020700a0db215d38170000080000e803000000900100

**Comment by al3mart** [comment]
So far I have initiated a request from Rockmine to your para for openin a channel, so right now you would need to accept that request, and open one from your para to Rockmine

**Comment by PavelSheremetev** [comment]
Is this exrinsic is right?
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.rpc.robonomics.network#/explorer/query/0xa9b450f118efc9dc879098704dc0ad39b972757dc4a49dd922a02500bbce5a84

**Comment by al3mart** [comment]
Check out this call, I guess this one should work for you 
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.rpc.robonomics.network#/extrinsics/decode/0x1700010100020c000400000000070010a5d4e81300000000070010a5d4e80006000700863ba1015c5a02081701e8030000170000080000e803000000900100

**Comment by PavelSheremetev** [comment]
Transaction completed successfully.
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.rpc.robonomics.network#/explorer/query/0x1a699b2cd2ade489a727e86fb73ee3c29fbb6346d9eeefc1bc446942a50a0b88

**Comment by al3mart** [comment]
I will proceed accepting your channel request from Rockmine

**Comment by PavelSheremetev** [comment]
Hi, we sent this request. Check it please and proceed accepting if all is ok.
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.rpc.robonomics.network#/explorer/query/0x6dbd1e6b4e4ef1551ea589a62cb64f707c535dcb96b8cf504613dd4dbbb08111

**Comment by al3mart** [comment]
I don't see the open request yet
```
[
  {
    sender: 2,000
    recipient: 2,021
  }
  {
    sender: 1,000
    recipient: 2,048
  }
  {
    sender: 2,000
    recipient: 2,087
  }
]
```

But there channel `1000 -> 2048` is still yet to be accepted, which you could go ahead and do

**Comment by dergudzon** [comment]
Hi, we are finally accepted channel `1000 -> 2048` and created open request for channel `2048 -> 1000`. Accept it please.
```
hrmp.hrmpOpenChannelRequestsList: Vec<PolkadotParachainPrimitivesHrmpChannelId>
[
  {
    sender: 2,000
    recipient: 2,021
  }
  {
    sender: 2,048
    recipient: 1,000
  }
  {
    sender: 2,000
    recipient: 2,087
  }
]
```

**Comment by al3mart** [comment]
Accepted, channel should be open soonish

**Comment by dergudzon** [comment]
Hi @al3mart! Can I ask you about re-init the Robonomics parachain (paraid 2048) with new genesis-wasm and genesis-state?
