### ISSUE TITLE
Reset Basilisk on Rococo

### ISSUE THREAD

**Issue by green-jay** [paritytech/subport#365]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

HydraDX

### Parachain Name

Basilisk

### ParaID

2090

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Long term, we do have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[basilisk_rococo_2090.state.txt](https://github.com/paritytech/subport/files/8596449/basilisk_rococo_2090.state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[basilisk_rococo_2090.wasm.txt](https://github.com/paritytech/subport/files/8596450/basilisk_rococo_2090.wasm.txt)

### Anything else we should know?

We are already onboarded so we need to reset with the new head. Thanks!

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: (https://github.com/polkadot-js/apps/pull/7180)

**Comment by al3mart** [comment]
New artifacts set

**Comment by green-jay** [comment]
hi @al3mart,
Can we give it one more go please? I got a bunch of different errors and could not get collators to work but I wasn't really sure where the problem was. Just making sure - we need to reset our chain completely and clear everything from old chain.
[basilisk_2090_rococo.wasm.txt](https://github.com/paritytech/subport/files/8609194/basilisk_2090_rococo.wasm.txt)
[basilisk_2090_rococo.state.txt](https://github.com/paritytech/subport/files/8609195/basilisk_2090_rococo.state.txt)
[basilisk-raw.json.txt](https://github.com/paritytech/subport/files/8609224/basilisk-raw.json.txt)

**Comment by al3mart** [comment]
yeah, after reseting your state and wasm you will need to run your collators from scratch, meaning new dbs. I am going to set this new artifacts again, but if your errors persists share with me the logs you are getting.

**Comment by green-jay** [comment]
all back up and running :)

**Comment by NicoMorganParity** [comment]
Hello @green-jay,
Can you please share with us your Parachain Manager Account for Basalisk?
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.
