### ISSUE TITLE
Rococo Slot Request

### ISSUE THREAD

**Issue by stanly-johnson** [paritytech/subport#366]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Virto Network

### Parachain Name

VirtoRococo

### ParaID

3003

### This para ID does NOT conflict with another Rococo para ID?

- [X] Yes, we doubled-checked it's free, or we reserved this para ID explicitly.

### Is this a request for a long term slot?

Short term, we don't have a matching para ID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-3003-genesis.zip](https://github.com/paritytech/subport/files/8612972/para-3003-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-3003-wasm.zip](https://github.com/paritytech/subport/files/8612973/para-3003-wasm.zip)

### (Optional) Upload your Chain Specification

[virto-rococo-3003-raw.json.zip](https://github.com/paritytech/subport/files/8612977/virto-rococo-3003-raw.json.zip)

### Register your Rococo parachain details for `polakdot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Please, complete the registration of your parathread so I can assign you a short term slot.

**Comment by stanly-johnson** [comment]
parathread onboarded

**Comment by al3mart** [comment]
Temp slot assigned, you will onboard in the next lease period
