### ISSUE TITLE
OriginTrail Parachain Testnet Slot Request

### ISSUE THREAD

**Issue by NZT48** [paritytech/subport#368]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Trace Labs

### Parachain Name

OriginTrail Parachain

### ParaID

3005

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[testnet-3005-genesis.zip](https://github.com/paritytech/subport/files/8632262/testnet-3005-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[testnet-3005-wasm.zip](https://github.com/paritytech/subport/files/8632265/testnet-3005-wasm.zip)

### (Optional) Upload your Chain Specification

[rococo-testnet-3005-raw.json.zip](https://github.com/paritytech/subport/files/8632268/rococo-testnet-3005-raw.json.zip)

### Anything else we should know?

Parathread is still onboarding, it will finish at 18:00 5.5.2022. CET

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Slot assigned and onboarding happening, aprox 1h 30' mins to go.
