### ISSUE TITLE
Substrate node template error#E0463 - can't find crate for std

### ISSUE THREAD

**Issue by Tassz44** [paritytech/subport#37]
I am following the tutorial [importing contracts pallet crate]. Installed nightly-2020-10-06 and cargo build. When I run code get error - "cant find std"_"the wasm32-unknown-unknown target may not be installed". Can not work out where I am going wrong... Have added [dependencies] and [features] runtime code - then ran cargo check... where I get error... Would like to know where I am going wrong, and how too solve issue..

**Comment by Tassz44** [comment]
this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

**Comment by danforbes** [comment]
You may be encountering this problem https://github.com/substrate-developer-hub/substrate-node-template/issues/90#issuecomment-706041447

**Comment by danforbes** [comment]
I think to get around the issue with `cargo check` you can try running it like this `cargo +nightly-2020-10-06 check`. I am not at all familiar with this error, which looks specific to Windows `the cargo.exe binary...is not applicable to nightly-2020-10-06-x86_64-unknown-linux-gnu' toolchain`. @swader do you have any ideas?

**Comment by Swader** [comment]
I only use WSL2 so no, sorry

**Comment by Tassz44** [comment]
Thanks Dan/Bruno, it compiled successfully using - cargo +nightly-2020-10-06 check.
________________________________

**Comment by danforbes** [comment]
Closing this Issue based on your last comment, @Tassz44. Glad to hear you're up and running :rocket: Feel free to open another Issue if something else pops up.
