### ISSUE TITLE
Centrifuge: Altair slot in Rococo for XCM testing

### ISSUE THREAD

**Issue by NunoAlexandre** [paritytech/subport#371]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Centrifuge

### Parachain Name

Altair Rococo

### ParaID

2088

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama. *

(*) If we can get a permanent slot for Altair on Rococo, that would be much appreciated since it will be useful for testing future XCM integrations. However, we already have a slot for Centrifuge in Rococo (Catalyst), so we understand that might not be possible. In that case, a temporary slot with 1 week lease should do.

### Upload your Genesis Head (genesis state)

[xcm-altair-dev.txt](https://github.com/paritytech/subport/files/8651606/xcm-altair-dev.txt)

### Upload your Validation Code (genesis runtime Wasm)

[parachain_altair_runtime-aa467c6.compact.compressed.txt](https://github.com/paritytech/subport/files/8651608/parachain_altair_runtime-aa467c6.compact.compressed.txt)

### Anything else we should know?

We want to test XCM integrations with Karura (para id 2000)

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
State and code set again for your para

**Comment by NunoAlexandre** [comment]
thanks a ton, @al3mart!
