### ISSUE TITLE
Mangata <3 Roccoco: long-lasting slot on Rococo ( 2nd attempt )

### ISSUE THREAD

**Issue by goncer** [paritytech/subport#374]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Mangata

### Parachain Name

Mangata

### ParaID

2110

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[node_0.11.1_genesis_state_public_testnet_2110.remove.zip](https://github.com/paritytech/subport/files/8659385/node_0.11.1_genesis_state_public_testnet_2110.remove.zip)

### Upload your Validation Code (genesis runtime Wasm)

[node_0.11.1_genesis_wasm_public_testnet_2110.remove.zip](https://github.com/paritytech/subport/files/8659386/node_0.11.1_genesis_wasm_public_testnet_2110.remove.zip)

### (Optional) Upload your Chain Specification

[node_0.11.1_public_testnet_spec_2110.remove.zip](https://github.com/paritytech/subport/files/8659389/node_0.11.1_public_testnet_spec_2110.remove.zip)

### Anything else we should know?

I messed up with headers and specs, so we need to resetup the relay with new header + wasm :facepalm: 
https://github.com/paritytech/subport/issues/356

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Code and head set!

**Comment by goncer** [comment]
\ o /

**Comment by NicoMorganParity** [comment]
Hello @goncer,
Can you please share with us your Parachain Manager Account.
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.

**Comment by goncer** [comment]
Hi @NM2146 
Ive been looking at this, and it seems that nobody has the user who setup the parachain.

https://rococo.subscan.io/parachain/2110

So I guess that  the best would be using the following address ( if possible ): `5CthcoS3CYHoVHDMUacydayRLMzMWedKryjsrvzrmv3VHCKP` 

Thannnks!
