### ISSUE TITLE
Reset Nodle Rococo Slot

### ISSUE THREAD

**Issue by ETeissonniere** [paritytech/subport#375]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Nodle

### Parachain Name

Nodle Parachain

### ParaID

2026

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[state.txt](https://github.com/paritytech/subport/files/8662872/state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[wasm.txt](https://github.com/paritytech/subport/files/8662873/wasm.txt)

### Anything else we should know?

2026 is currently running but we managed to brick it. Our team sent an upgrade without using the correct procedure.

### Register your Rococo parachain details for `polkadot-js/apps`

Already done :)

**Comment by al3mart** [comment]
New head and code set.
