### ISSUE TITLE
Slot request for Astar

### ISSUE THREAD

**Issue by Dinonard** [paritytech/subport#376]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Astar Network

### Parachain Name

Astar

### ParaID

2006

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[astar-genesis-state.txt](https://github.com/paritytech/subport/files/8686468/astar-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[astar-genesis-wasm.txt](https://github.com/paritytech/subport/files/8686470/astar-genesis-wasm.txt)

### (Optional) Upload your Chain Specification

[Chain spec link](https://github.com/AstarNetwork/Astar/blob/master/bin/collator/res/astar-rococo.json)

### Anything else we should know?

Hello, I hope that what I've provided will be enough.
I tested it locally and everything works.

We need this slot so we can test XCMP with other parachains.

I will prepare the PR in polkadot-js next week if that is fine.

Thanks!

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Slot assigned, on boarding now.
