### ISSUE TITLE
Request slot for completing the tutorial.

### ISSUE THREAD

**Issue by ruibinx** [paritytech/subport#378]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Individual 

### Parachain Name

Parachain template

### ParaID

3012

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-3012-genesis.zip](https://github.com/paritytech/subport/files/8727334/para-3012-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-3012-wasm.zip](https://github.com/paritytech/subport/files/8727335/para-3012-wasm.zip)

### Anything else we should know?

A parathread can't produce blocks for now according to https://substrate.stackexchange.com/questions/359/can-parathread-produce-blocks. To complete the tutorial for rococo testnet, I need to apply for a parachain slot. Or is there any other way to test on rococo testnets? Any help is appreciated. 

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
->

**Comment by al3mart** [comment]
Rococo is meant for testing before going to production, or while preparing your code for production. If you are just trying to finish the tutorial I would suggest launching your own rococo-local testnet and connecting your para in there.
Though, this would be completely applicable further in time.

**Comment by al3mart** [comment]
But still, if you think this still applies, feel free to reopen this issue :)
