### ISSUE TITLE
Imbue Network Rococo slot

### ISSUE THREAD

**Issue by samelamin** [paritytech/subport#380]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Imbue Network

### Parachain Name

imbue-dev

### ParaID

3017

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://raw.githubusercontent.com/ImbueNetwork/imbue/main/res/para-3017-genesis-rococo

### Upload your Validation Code (genesis runtime Wasm)

https://raw.githubusercontent.com/ImbueNetwork/imbue/main/res/para-3017-wasm-rococo

### (Optional) Upload your Chain Specification

https://raw.githubusercontent.com/ImbueNetwork/imbue/main/res/imbue-raw.json

### Anything else we should know?

All that is required is upgrading paraID 3017 to a parachain

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Temp slot assigned, to be onboarded on the next lease period.

**Comment by al3mart** [comment]
Reonboard at the end of LP 27
