### ISSUE TITLE
OriginTrail Parachain Testnet Permanent Slot Request

### ISSUE THREAD

**Issue by NZT48** [paritytech/subport#382]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Trace Labs

### Parachain Name

OriginTrail Parachain

### ParaID

2043

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[rococo-final-2043-genesis.zip](https://github.com/paritytech/subport/files/8775308/rococo-final-2043-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[rococo-final-2043-wasm.zip](https://github.com/paritytech/subport/files/8775310/rococo-final-2043-wasm.zip)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: [PR link](https://github.com/polkadot-js/apps/pull/7544)

**Comment by al3mart** [comment]
Onboarding parathread now, once that is finished we will be able to assgin you a slot

**Comment by al3mart** [comment]
Slot assigned. Please, feel free to reopen this issue for anything related

**Comment by NZT48** [comment]
Hi @al3mart, I have made a mistake and accidentally uploaded wrong genesis and wasm file, I'm really sorry for this, can you please offboard our current parachain and register it back with wasm and genesis files provided below:

[testnet-2043-wasm.zip](https://github.com/paritytech/subport/files/8781181/testnet-2043-wasm.zip)
[testnet-2043-genesis.zip](https://github.com/paritytech/subport/files/8781182/testnet-2043-genesis.zip)

**Comment by NicoMorganParity** [comment]
Hello @NZT48,
Can you please share with us your Parachain Manager Account. 
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.
