### ISSUE TITLE
GM Parachain temporary slot request

### ISSUE THREAD

**Issue by arrudagates** [paritytech/subport#383]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [x] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

GM or Die DAO

### Parachain Name

GM Parachain

### ParaID

3019

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[rococo-live-genesis-state.txt](https://github.com/paritytech/subport/files/8791282/rococo-live-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[rococo-live-genesis-wasm.txt](https://github.com/paritytech/subport/files/8791283/rococo-live-genesis-wasm.txt)

### (Optional) Upload your Chain Specification

[rococo-parachain-live.txt](https://github.com/paritytech/subport/files/8791287/rococo-parachain-live.txt)
[rococo-parachain-live-raw.txt](https://github.com/paritytech/subport/files/8791288/rococo-parachain-live-raw.txt)

### Anything else we should know?

This is a project being developed by ChaosDAO members, and as such all current code is hosted on https://github.com/ChaosDAO-org/gm_chain/.
There's also a project website that's still very much a work in progress, but you can find team member names in https://www.gmordie.com/team.html.

If more information is needed, I'm happy to provide it!

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7654

**Comment by arrudagates** [comment]
Update: Added polkadot-js/apps PR

**Comment by arrudagates** [comment]
Update: Polkadot.js PR merged

**Comment by arrudagates** [comment]
@al3mart Could you take a look at this slot request?

**Comment by al3mart** [comment]
At the moment the config is as follows, there is a max of 5 temp slot parachains that can be up at the same time, they will be up for 3 days, then offboarded back to parathread to make space for another 5.
If it happens that at some point there is less than 5 paras up, in the comming sessions new paras will be onboarded as parachain if it happens that there are temp slot holders waiting to be onboarded
