### ISSUE TITLE
Kintsugi Rococo slot

### ISSUE THREAD

**Issue by sander2** [paritytech/subport#384]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Interlay

### Parachain Name

Kintsugi Rococo Testnet

### ParaID

2092

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[rococo-genesis.zip](https://github.com/paritytech/subport/files/8815954/rococo-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[rococo-wasm.zip](https://github.com/paritytech/subport/files/8815948/rococo-wasm.zip)

### Anything else we should know?

For testing XCM

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Your parathread is now onboarding, once that is done you will be able to be assigned a slot.
Aprox 1h20' to go.
