### ISSUE TITLE
Kintsugi Rococo Slot (correction)

### ISSUE THREAD

**Issue by sander2** [paritytech/subport#388]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Interlay

### Parachain Name

Kintsugi Rococo Testnet

### ParaID

2092

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[rococo-state-hex.zip](https://github.com/paritytech/subport/files/8872248/rococo-state-hex.zip)

### Upload your Validation Code (genesis runtime Wasm)

[rococo-wasm-hex.zip](https://github.com/paritytech/subport/files/8872249/rococo-wasm-hex.zip)

### Anything else we should know?

We previously [requested](https://github.com/paritytech/subport/issues/384) a slot. However, when exporting the wasm blob to upload here we accidentally used `docker run -t`, which causes docker to use tty rules, substituting all `0x0a` (a.k.a. `\n`) by `0x0d 0x0a` (a.k.a. `\r \n`). This of course changes the code hash, causing our chain to fail to produce blocks. I apologize for submitting the invalid blob previously. Can you remove the previously registration and use this one instead? Thanks!

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
New artifacts set
