### ISSUE TITLE
 1010: Invalid Transaction: Transaction has a bad signature'

### ISSUE THREAD

**Issue by lansehuiyi6** [paritytech/subport#389]
Transaction failed because of ' 1010: Invalid Transaction: Transaction has a bad signature''

I've retried for sometimes, and then it successed. 
can anyone tell me why ' 1010: Invalid Transaction: Transaction has a bad signature'' happened?

**Comment by al3mart** [comment]
Usually this can be originated by signing transaction using the wrong metadata. But as ggwpez as mentioned, without the concrete scenario this is just a guess work.

I invite you to ask this in https://substrate.stackexchange.com/ where you can have access to a full community of substrate devs that perhaps are experiencing or have the same doubts as you.
