### ISSUE TITLE
errorE0282#  type annotations needed & could not compile `sp-arithmetic`

### ISSUE THREAD

**Issue by Tassz44** [paritytech/subport#39]
I am following tutorial [Implementing the Contract Trait]. 
Added code snip to `parameter_types!` and to `imp trait runtime`. When I run `cargo check -p node-template-runtime` receive error: 
error[E0282]: type annotations needed
error: could not compile `sp-arithmetic`
note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)

I've had this error previously and it was due to nightly?

I am using windows not mac..

**Comment by Tassz44** [comment]
made changes to' runtime_lib.rs' and when I run 'cargo +nightly-2020-10-06 check' receive following errors#E0277: 
cannot multiply `MILLICENTS` to `{integer}`
cannot multiply `CENTS` to `{integer}`

**Comment by Tassz44** [comment]
I added code snip to `pub const` and run `cargo check -p node-template-runtime`.. I get same error mentioned in initial post above:
error[E0282]: type annotations needed
error: could not compile `sp-arithmetic`

I would like to know if its due to my own mistake or is this due to nightly?

**Comment by Tassz44** [comment]
Strange - when I run `cargo +nightly-2020-10-06 check` instead of `cargo check -p node-template-runtime` I receive a different error: cannot multiply MILLICENTS to {integer}` cannot multiply CENTS to {integer}

**Comment by danforbes** [comment]
I would need more information about the changes you made to be able to help at this point. It seems like you changed some types and it's now causing problems.

**Comment by Tassz44** [comment]
Hi Dan, thanks for your reply.

I forgot to add 'cargo +nightly-2020-10-06 check -p node-template-runtime'...😩
________________________________
