### ISSUE TITLE
Can't register Parachain ID on Rococo

### ISSUE THREAD

**Issue by DappGuy** [paritytech/subport#390]
it wont let us register a parachain id on rococo the nextFreeId is "3,026" and its already taken from Bajun Network

"system.ExtrinsicFailed registrar.AlreadyRegistered"  when tx is submitted

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/parachains/parathreads

**Comment by NukeManDan** [comment]
This should be fix now, you will need to register a new ID and make sure your chain spec reflects this. Please let me know if oyu have issues! cc @al3mart
