### ISSUE TITLE
Reset KILT on rococo

### ISSUE THREAD

**Issue by ggera** [paritytech/subport#392]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

KILT Protocol

### Parachain Name

KILT

### ParaID

2086

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[kilt_rococo_2086.state.txt](https://github.com/paritytech/subport/files/8897774/kilt_rococo_2086.state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[kilt_rococo_10620.wasm](https://github.com/KILTprotocol/kilt-node/releases/download/1.6.2/spiritnet_runtime.compact.compressed.wasm)

### (Optional) Upload your Chain Specification

[rilt_chainspec.json](https://github.com/KILTprotocol/kilt-node/blob/develop/nodes/parachain/res/rilt.json)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - [Available here](https://github.com/polkadot-js/apps/pull/7736)

**Comment by al3mart** [comment]
Slot assgined, onboarding as parachain in around 1h 50' from now.

**Comment by wischli** [comment]
Unfortunately, the provided data was outdated. Here's the (hopefully) correct one:

Upload your Genesis Head (genesis state)
[rilt-state.txt](https://github.com/paritytech/subport/files/8918410/rilt-state.txt)
ur Genesis Head (genesis state)

Upload your Validation Code (genesis runtime Wasm)
[rilt-validation.wasm](https://github.com/paritytech/subport/files/8919699/rilt-wasm.txt)

(Optional) Upload your Chain Specification
[rilt-spec.json](https://github.com/KILTprotocol/kilt-node/blob/develop/nodes/parachain/res/rilt.json)
