### ISSUE TITLE
Update parachain head for Genshiro

### ISSUE THREAD

**Issue by muctep-dehuc** [paritytech/subport#393]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Equilibrium

### Parachain Name

Genshiro

### ParaID

2024

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[state-rococo-gens-node1.txt](https://github.com/paritytech/subport/files/8910827/state-rococo-gens-node1.txt)

### Upload your Validation Code (genesis runtime Wasm)

[wasm-rococo-gens-node1.txt](https://github.com/paritytech/subport/files/8910825/wasm-rococo-gens-node1.txt)

### Anything else we should know?

We want to save all HRMP channels 

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Done!
