### ISSUE TITLE
How to customize the cross chain on Avalanche pegged to Substrate Native Token? 

### ISSUE THREAD

**Issue by WB-Expert5007** [paritytech/subport#398]
Hi, I am going to customize the cross chain on Avalanche pegged to Substrate Native Token? I am using the substrate-node-template (v4.0.0-dev) project, https://github.com/substrate-developer-hub/substrate-node-template, now.

For this, what steps should I follow? Please teach me step by step.
And please give me reference projects.

Best Regards.

**Comment by NukeManDan** [comment]
This repo is not for submitting "please tell me how to X" requests.
