### ISSUE TITLE
Reset Imbue Rococo slot to match Kusama

### ISSUE THREAD

**Issue by samelamin** [paritytech/subport#399]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Imbue Network

### Parachain Name

imbue

### ParaID

2121

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://raw.githubusercontent.com/ImbueNetwork/imbue/main/res/para-2121-genesis-rococo

### Upload your Validation Code (genesis runtime Wasm)

https://raw.githubusercontent.com/ImbueNetwork/imbue/main/res/para-2121-wasm-rococo

### (Optional) Upload your Chain Specification

https://raw.githubusercontent.com/ImbueNetwork/imbue/main/res/imbue-raw.json

### Anything else we should know?

We also want a channel open to Acala's rococo chain to test aUSD transfers

### Register your Rococo parachain details for `polkadot-js/apps`

Already registered

We need the chain reset as we launched a new environment

**Comment by samelamin** [comment]
Quick question, our parachain on kusama has an id of 2121, do we need a matching paraid for rococo? if so how do we change it?

**Comment by al3mart** [comment]
We can register for that paraId for you. If you want to keep the storage from the running one, you can provide us the last head as the state to register and you can tweak your genesis to use that head too.

For the moment I will proceed registering what you have shared, there will be space to modify this if necessary.

**Comment by al3mart** [comment]
Onboarding parathread ~1h41' from now

**Comment by samelamin** [comment]
@al3mart thanks for this. we are happy getting reset, please onboard whenever you are ready :)

**Comment by al3mart** [comment]
Onboarding parachain on aprox 2h from now. Anything follow up, please feel free to reopen this issue.

**Comment by samelamin** [comment]
@al3mart can we reopen this issue please? our chain got reset
