### ISSUE TITLE
Error: Input("Error parsing spec file: expected value at line 1 column 1")

### ISSUE THREAD

**Issue by Harman-singh-waraich** [paritytech/subport#40]
i am following the run your private node tutorial and encountereed this error:
PS C:\Users\hp\desktop\substrate-node-template>  ./target/release/node-template build-spec --chain=customSpec.json --raw --disable-default-bootnode > customSpecRaw.json
Error: Input("Error parsing spec file: expected value at line 1 column 1")

i tried without making any change to customSpec.json but still the error is there

**Comment by danforbes** [comment]
It is possible that there is a bug when using Windows, but since I do not have access to a Windows machine I am not able to confirm. Can you try using Windows Subsystem for Linux? I have confirmed that building raw chain specs works just fine on Linux systems.

**Comment by danforbes** [comment]
Related https://stackoverflow.com/q/64404773/858003

**Comment by riusricardo** [comment]
Not a windows issue.
**Microsoft Windows 10 Pro - x64**
**nightly-2020-10-06-x86_64-pc-windows-msvc**
```
C:\Users\Test\.dev\substrate-node-template>.\target\release\node-template.exe  build-spec --disable-default-bootnode --chain local > customSpec.json
Oct 18 00:36:28.912  INFO Building chain spec

C:\Users\Test\.dev\substrate-node-template>.\target\release\node-template.exe build-spec --chain=customSpec.json --raw --disable-default-bootnode > customSpecRaw.json
Oct 18 00:36:45.509  INFO Building chain spec
```

**Comment by NukeManDan** [comment]
@Harman-singh-waraich is this still an issue? If so, please reopen this 🙏🏼

**Comment by Kifal15** [comment]
> i am following the run your private node tutorial and encountereed this error:
> PS C:\Users\hp\desktop\substrate-node-template> ./target/release/node-template build-spec --chain=customSpec.json --raw --disable-default-bootnode > customSpecRaw.json
> Error: Input("Error parsing spec file: expected value at line 1 column 1")
> 
> i tried without making any change to customSpec.json but still the error is there

Were you able to figure out a solution for this ? im facing the same error so thats why !

**Comment by ceruleanstreak** [comment]
Hey. I'm from March 2022 and the issue is still here on Windows 11

**Comment by Kifal15** [comment]
> Hey. I'm from March 2022 and the issue is still here on Windows 11
Build a chain spec using linux it would work ,this command doesnt work on windows , i spent a long time until i figured it out :D

**Comment by bradenwattsq** [comment]
I have the same problem in debian 11
