### ISSUE TITLE
Rococo slot request for Sora parachain

### ISSUE THREAD

**Issue by xDimon** [paritytech/subport#400]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Soramitsu

### Parachain Name

SORA Rococo Parachain

### ParaID

2011

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[sora_rococo-state.txt](https://github.com/paritytech/subport/files/9012000/sora_rococo-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[sora_rococo-wasm.txt](https://github.com/paritytech/subport/files/9012011/sora_rococo-wasm.txt)

### (Optional) Upload your Chain Specification

[sora_rococo-plain.json.txt](https://github.com/paritytech/subport/files/9012017/sora_rococo-plain.json.txt)
[sora_rococo-raw.json.txt](https://github.com/paritytech/subport/files/9012018/sora_rococo-raw.json.txt)

### Anything else we should know?

This is initial test

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding parathread ~ 1h40' from now

**Comment by al3mart** [comment]
Onboarding parachain on aprox 2h from now. Anything follow up, please feel free to reopen this issue.

**Comment by SBalaguer** [comment]
@xDimon You Rococo Parachain has not been producing blocks in 150 Days. Please let us know if you intend to have it working, otherwise in 2 days we will be downgrading you to a parathread, and we can upgrade you when you want.

**Comment by N1ghtStorm** [comment]
> @xDimon You Rococo Parachain has not been producing blocks in 150 Days. Please let us know if you intend to have it working, otherwise in 2 days we will be downgrading you to a parathread, and we can upgrade you when you want.

Hello! I created this issue https://github.com/paritytech/subport/issues/539
Uploaded new genesis and wasm validation code

**Comment by al3mart** [comment]
Closing as this issue is stale
