### ISSUE TITLE
Webb rococo slot request

### ISSUE THREAD

**Issue by 1xstj** [paritytech/subport#401]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Webb

### Parachain Name

egg-rococo

### ParaID

4006

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[webb-rococo-4006-genesis.zip](https://github.com/paritytech/subport/files/9037291/webb-rococo-4006-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[webb-rococo-4006-wasm.zip](https://github.com/paritytech/subport/files/9037293/webb-rococo-4006-wasm.zip)

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Temp slot assigned, you should onboard in the next rotation.
