### ISSUE TITLE
Why doesn't ```ERA``` change on polkadot app?

### ISSUE THREAD

**Issue by WB-Expert5007** [paritytech/subport#402]
Hello, I have followed this guides, ```https://wiki.polkadot.network/docs/maintain-guides-how-to-validate-polkadot```, to add validators on POS substrate node project.
Please check this.
![image](https://user-images.githubusercontent.com/96474901/177386573-002d609a-82e3-43ba-8ec2-78657d5fda65.png)

I have added some validators as guide and a lot of ```ERA``` time spent already, but all waiting validators doesn't active.
What is wrong?

How can I solve this problem?
How can I make era to change?

**Comment by al3mart** [comment]
Let's close this issue in favor of this SE post
https://substrate.stackexchange.com/questions/2781/era-time-is-not-completing/3607?noredirect=1#comment3489_3607
