### ISSUE TITLE
Genshiro reregister parachain

### ISSUE THREAD

**Issue by muctep-dehuc** [paritytech/subport#403]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Equilibrium

### Parachain Name

Genshiro

### ParaID

2024

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[state.txt](https://github.com/paritytech/subport/files/9055568/state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[wasm.txt](https://github.com/paritytech/subport/files/9056328/wasm.txt)

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
yoou are good to go.
