### ISSUE TITLE
add 565.ee to rococoTest parachain

### ISSUE THREAD

**Issue by 565ee** [paritytech/subport#406]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

565.ee

### Parachain Name

565.ee

### ParaID

4018

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[rococo-para-4018-genesis.zip](https://github.com/paritytech/subport/files/9075933/rococo-para-4018-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[rococo-para-4018-wasm.zip](https://github.com/paritytech/subport/files/9075935/rococo-para-4018-wasm.zip)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/commit/c6e30c324ffd5d14b9da81d0aa9e881da4979e0e

**Comment by al3mart** [comment]
Hello, long term slots are granted to teams that have secured an slot in either Kusama or Polkadot. I have not been able to identify you on these chains, could you please let me know which is your paraId in these networks ?

**Comment by 565ee** [comment]
i  changed to  Short-term: we registered a parathread with the paraID above.
