### ISSUE TITLE
Request for Rococo parachain slot

### ISSUE THREAD

**Issue by lhtvineettiwari** [paritytech/subport#407]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

LHT

### Parachain Name

LHT

### ParaID

4020

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/1NwSLFTv4RUUfFDFEmXtsA4inaGjYER2H/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/1JQwe0q9UTqxdufl44YV3esVtD9qZufQU/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding on next rotation

**Comment by lhtvineettiwari** [comment]
HI @al3mart, kindly let us know the time of next rotation ?

**Comment by al3mart** [comment]
```
assignedSlots.temporarySlots: Option<PolkadotRuntimeCommonAssignedSlotsParachainTemporarySlot>

{
  manager: 5HTLx2XejSHhAMquCAVBpqEw3ZrDFacNs5KZTDwr3UWr2utp
  periodBegin: 71
  periodCount: 3
  lastLease: null
  leaseCount: 0
}

```

In the comming LP you should go up, so most likely this will happen tomorrow
