### ISSUE TITLE
Rococo Slot Request for OLI Parachain

### ISSUE THREAD

**Issue by m-yahya** [paritytech/subport#408]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

OLI Systems

### Parachain Name

OLI-Parachain

### ParaID

4023

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4023-genesis.zip](https://github.com/paritytech/subport/files/9096800/para-4023-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-4023-wasm.zip](https://github.com/paritytech/subport/files/9096803/para-4023-wasm.zip)

### (Optional) Upload your Chain Specification

[rococo-oli-parachain-4023-raw.zip](https://github.com/paritytech/subport/files/9096810/rococo-oli-parachain-4023-raw.zip)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding in the following rotation
