### ISSUE TITLE
Bit.Country Rococo Parachain Slot Request

### ISSUE THREAD

**Issue by justinphamnz** [paritytech/subport#409]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Bit.Country & Metaverse.Network

### Parachain Name

Pioneer

### ParaID

2096

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/1G6iC1kvAF5A4vMpSvb7N4PW-ib7CWBqL/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/1o1xcD75RpSmcg3Lr5djpxlQpS1tE_ZPf/view?usp=sharing

### (Optional) Upload your Chain Specification

https://drive.google.com/file/d/1OC4Eeyh34_6thJLsGUd_breLz0Je_6z7/view?usp=sharing

### Anything else we should know?

We already got a slot on Kusama, and would like to utilise Rococo for production tests and XCM tests with other parachain.

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Parathread regstering now, afterwards the slot will be granted.

**Comment by al3mart** [comment]
Onboarding as a parachain

**Comment by justinphamnz** [comment]
Hi @al3mart,

Could you please help to upgrade our Bit.Country Rococo slot with new Wasm and State as discussed?

Wasm: https://drive.google.com/file/d/1XsGYjqdecEHZlXJA27Av4wXJzrdJfDzs/view?usp=sharing
State: https://drive.google.com/file/d/1yfyd65GvWt3ZGRXsOHbuGBA7NKONZM5b/view?usp=sharing

**Comment by al3mart** [comment]
Done!

**Comment by justinphamnz** [comment]
Good day Alejandro @al3mart,

We just rolled out a runtime upgrade using parachainSystem. After enact new wasm, we faced the error on our collator node on Rococo

2022-08-15 09:24:19 [Parachain] Block import error: State Database error: Too many sibling blocks inserted     2022-08-15 09:24:19 [Parachain] Error with block built on 0x57b6613cd5118d3d80b33632988363d7a064abe7f74a91c1a11e39cfddb6e938: Import failed: State Database error: Too many sibling blocks inserted

Is there any feasible way we can fix it? Or I need to upgrade new wasm and state?

**Comment by al3mart** [comment]
@justinphamnz check this SE post
https://substrate.stackexchange.com/questions/3054/how-to-prune-sibling-blocks

**Comment by justinphamnz** [comment]
Hi @al3mart,

Hope you are well,

We restarted our Rococo node. Could you please help to override our new Wasm and genesis state for Bit.Country 2096 Rococo parachain?

**Genesis state**: https://drive.google.com/file/d/1sIYjxumjOnwQglHn0k75hhdswW_aoSs6/view
**Wasm**: https://drive.google.com/file/d/1EY3neZPny3wAekVVKliRDEHrdIvWI-QM/view

**Comment by al3mart** [comment]
These are set now
