### ISSUE TITLE
cannot find value `wasm_binary` in this scope

### ISSUE THREAD

**Issue by Tassz44** [paritytech/subport#41]
I am following the tutorial https://substrate.dev/docs/en/tutorials/add-contracts-pallet. 

When I build 'cargo +nightly' with Ubuntu 20.04LTS it builds successfully.

But when I build 'cargo +nightly' with VS Code in receive an error:

![image](https://user-images.githubusercontent.com/72080913/96457216-656b2300-1217-11eb-80b9-2e44392676d5.png)

Is this a bug or it due to me!

**Comment by danforbes** [comment]
It sounds like you are building an old version, possibly `v2.0.0-rc4`. In this version, use `WASM_BINARY` instead of `wasm_binary`. Best thing would be to use the most recent `v2.0.0` final version. Please close this Issue if that solves or your problem.

**Comment by riusricardo** [comment]
The problem is that you deleted the first parameter in the `testnet_genesis` function.
It should have 5 parameters. https://github.com/substrate-developer-hub/substrate-node-template/blob/master/node/src/chain_spec.rs#L130-L134
The first error is pointing to line 138 which is expecting this value. https://github.com/substrate-developer-hub/substrate-node-template/blob/master/node/src/chain_spec.rs#L139

It should be fixed if you add the 5 parameters to the `testnet_genesis` function.

**Comment by Tassz44** [comment]
Many thanks  riusricardo & danforbes fixed my issue!

**Comment by Tassz44** [comment]
I thought this issue was fixed...  Ran `cargo +nightly-2020-10-06 build --release`, and at the end of build receive error: unresolved import `structopt`

![img](https://user-images.githubusercontent.com/72080913/96551930-f6d7a500-12aa-11eb-90a0-c0b0bf378ad8.jpg)

**Comment by Tassz44** [comment]
the error appears to be coming from top of page:
`use sp_core::{Pair, Public, sr25519};
use sp_core::{Pair, Public, sr25519};
use node_template_runtime::{
	AccountId, AuraConfig, BalancesConfig, GenesisConfig, GrandpaConfig,
	SudoConfig, SystemConfig, WASM_BINARY, Signature, ContractsConfig
};
use sp_consensus_aura::sr25519::AuthorityId as AuraId;
use sp_finality_grandpa::AuthorityId as GrandpaId;
use sp_runtime::traits::{Verify, IdentifyAccount};
use sc_service::ChainType;`

**Comment by Tassz44** [comment]
Hi,

followed your comments and updated 'chain-spec.rs'..

when I run 'cargo +nightly-2020-10-06 build --release' receive following error: unresolved import structopt
#

[img]<https://user-images.githubusercontent.com/72080913/96551930-f6d7a500-12aa-11eb-90a0-c0b0bf378ad8.jpg>


the error appears to be coming from top of page:

use sp_core::{Pair, Public, sr25519};
use node_template_runtime::{
AccountId, AuraConfig, BalancesConfig, GenesisConfig, GrandpaConfig,
SudoConfig, SystemConfig, WASM_BINARY, Signature, ContractsConfig
};
use sp_consensus_aura::sr25519::AuthorityId as AuraId;
use sp_finality_grandpa::AuthorityId as GrandpaId;
use sp_runtime::traits::{Verify, IdentifyAccount};
use sc_service::ChainType;


________________________________

**Comment by riusricardo** [comment]
This is a different issue. Do you have this line https://github.com/substrate-developer-hub/substrate-node-template/blob/master/node/Cargo.toml#L23 in node/Cargo.toml?

**Comment by Tassz44** [comment]
Thanks for your comments and link... It has solved my issue!

**Comment by Tassz44** [comment]
Thanks for your comments and link... It has solved my issue!😊
________________________________

**Comment by Tassz44** [comment]
I am using VS Code...

________________________________
