### ISSUE TITLE
Reset the Rocfinity parachain on Rococo

### ISSUE THREAD

**Issue by rakanalh** [paritytech/subport#411]
### You completed the Cumulus Tutorial for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Enjin / Efinity

### Parachain Name

Rocfinity

### ParaID

2021

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[efinity-genesis.zip](https://github.com/paritytech/subport/files/9105518/efinity-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[efinity_runtime.compact.compressed.wasm.zip](https://github.com/paritytech/subport/files/9105520/efinity_runtime.compact.compressed.wasm.zip)

### (Optional) Upload your Chain Specification

[efinity-raw-spec.json.zip](https://github.com/paritytech/subport/files/9105521/efinity-raw-spec.json.zip)

### Anything else we should know?

- We want to start an XCM channel from/to Acala's test network with ParaID 2000.

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
All set

**Comment by rakanalh** [comment]
@al3mart Could you please redeploy with the following files?
[Rocfinity-v2.1.0.zip](https://github.com/paritytech/subport/files/9120136/Rocfinity-v2.1.0.zip)

**Comment by al3mart** [comment]
New artifacts pushed

**Comment by al3mart** [comment]
New head set

**Comment by Lohann** [comment]
Hey @al3mart sorry for bothering you again, the desync issue persistent so we re-built the genesis using polkadot-v0.9.26 release, could you set this new genesis for us?
[rocfinity-genesis.zip](https://github.com/paritytech/subport/files/9199562/rocfinity-genesis.zip)

**Comment by al3mart** [comment]
New artifacts set!

**Comment by rakanalh** [comment]
Please help reset Rocfinity using the attached artifact
[rocfinity-genesis.zip](https://github.com/paritytech/subport/files/9316528/rocfinity-genesis.zip)
s

**Comment by rakanalh** [comment]
@al3mart Please upload the same wasm from the zip before and use the following genesis instead:
[rocfinity-genesis-head.txt](https://github.com/paritytech/subport/files/9351363/rocfinity-genesis-head.txt)

**Comment by rakanalh** [comment]
@al3mart Please deploy the attached files and let's see what happens on our side.

[rocfinity.tar.gz](https://github.com/paritytech/subport/files/9460098/rocfinity.tar.gz)

**Comment by rakanalh** [comment]
[Rocfinity.tar.gz](https://github.com/paritytech/subport/files/9989018/Rocfinity.tar.gz)
