### ISSUE TITLE
Rococo testnet slot for Datahighway

### ISSUE THREAD

**Issue by sudipghimire533** [paritytech/subport#416]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

DataHighway

### Parachain Name

DataHighway Spreehafen Testnet

### ParaID

2116

### Is this for a short or long term slot?

Long-term: We have matching paraId in kusama or Polkadot

### Upload your Genesis Head (genesis state)
https://github.com/DataHighway-DHX/DataHighway-Parachain/blob/v3.6.0/res/rococo/rococo-parachain-state

### Upload your Validation Code (genesis runtime Wasm)
https://github.com/DataHighway-DHX/DataHighway-Parachain/blob/v3.6.0/res/rococo/rococo-parachain-wasm

### (Optional) Upload your Chain Specification
https://github.com/DataHighway-DHX/DataHighway-Parachain/blob/v3.6.0/res/rococo/rococo.json

### Anything else we should know?
- I have not done [this step](https://docs.substrate.io/tutorials/connect-other-chains/rococo-slot/#register-as-a-parathread). Since I need paraId: 2116 and I don't get to choose it

### Register your Rococo parachain details for `polkadot-js/apps`

- [X] Polkadot-js Apps UI PR completed

**Comment by al3mart** [comment]
Onboarding parathread in aprox 1h10' from now

**Comment by al3mart** [comment]
Onboarding as parachain soon

**Comment by sudipghimire533** [comment]
Hello parity team.
We want to start a testnet with same wasm & state but from scratch. We basically want to reset our testnet in rococo. What shall we do for this.

**Comment by al3mart** [comment]
The new artifacts have been set on the relaychain storage, you just need to spin up your collators with the desired genesis state and wasm
