### ISSUE TITLE
Rococo testnet slot for Dortaj BlockChain

### ISSUE THREAD

**Issue by kia9372** [paritytech/subport#417]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Dortaj Blockchain

### Parachain Name

Dortaj

### ParaID

4034

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://file.io/5JiiLMSpSWWm

### Upload your Validation Code (genesis runtime Wasm)

https://file.io/qa0bp8pWCsgG

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
A few things here, 

the head you have uploaded seems to have been removed. If you could point to a repo it would be easier to manage instead of using some hosting service. You even can submit files here github.

Sencondarily, long terms slots are reserved for parachains that have secured a slot in one of the production networks ( Kusama or Polkadot ), please help me identify your paraId in one of those networks.

**Comment by kia9372** [comment]
Upload your Genesis Head (genesis st
[para-4034-genesis.zip](https://github.com/paritytech/subport/files/9173405/para-4034-genesis.zip)
ate)



Upload your Validation Code (genesis runtime Wasm)
[para-4034-wasm.zip](https://github.com/paritytech/subport/files/9173407/para-4034-wasm.zip)


My ParaId is : 4034

**Comment by kia9372** [comment]
I Registered ParaId Here : 

![image](https://user-images.githubusercontent.com/8811020/180597671-66ed46dc-2d7b-49c6-89a8-82ac9e94f645.png)

**Comment by al3mart** [comment]
This is great thank you.

As I pointed out in my previous message, long term slots are reserved for teams that have secured a slot on Kusama or Polkadot. Let's grant you a short term slot for the moment, and we can change that later if needed.

As for now, I have registered your para with a short term slot, you will onboard as a parachain in the coming rotations.
```
assignedSlots.temporarySlots: Option<PolkadotRuntimeCommonAssignedSlotsParachainTemporarySlot>

{
  manager: 5DPkrTYuHhvrkD1Hxz4Xf96NFcSLT77cbwqJPhb34RoEVVU3
  periodBegin: 84 // this is the first LP in which you can become a parachain
  periodCount: 3
  lastLease: null
  leaseCount: 0
}
```
