### ISSUE TITLE
Rococo slot for Bifrost

### ISSUE THREAD

**Issue by ark930** [paritytech/subport#418]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Liebi Technologies

### Parachain Name

Bifrost K Rococo Testnet

### ParaID

2001

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[bifrost-k-rococo.state.zip](https://github.com/paritytech/subport/files/9159015/bifrost-k-rococo.state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[bifrost-k-rococo.wasm.zip](https://github.com/paritytech/subport/files/9159018/bifrost-k-rococo.wasm.zip)

### (Optional) Upload your Chain Specification

[bifrost-k-rococo.json.zip](https://github.com/paritytech/subport/files/9159020/bifrost-k-rococo.json.zip)

### Register your Rococo parachain details for `polkadot-js/apps`

- [X] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7894

**Comment by al3mart** [comment]
Onboarding parathread in arpox 1h 50'

**Comment by al3mart** [comment]
Onboarding as parachain in aprox 1h50'
