### ISSUE TITLE
Onboard Crust Testnet on the Rococo Network 

### ISSUE THREAD

**Issue by mmyyrroonn** [paritytech/subport#419]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Crust Network

### Parachain Name

Crust Network

### ParaID

2012

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://gw.crustapps.net/ipfs/QmRHAdtJxy5PYWovawSx7dAJ5BbYyCAy1mAYjDqfJxLgzF?filename=crust-collator-state-staging

### Upload your Validation Code (genesis runtime Wasm)

https://gw.crustapps.net/ipfs/QmcHBVkU7xsnzdmJWzzPffZHUqmF1w3wpPMnPPRQXKLt5t?filename=crust-collator-wasm-staging

### Anything else we should know?

We need to test XCMP with other parachains, such as phala and biforest. Please send some ROCs into the sovereign account.

### Register your Rococo parachain details for `polkadot-js/apps`

https://github.com/polkadot-js/apps/pull/7905

**Comment by al3mart** [comment]
Onboarding parathread in aprox 1h 45' from now

**Comment by al3mart** [comment]
Onboarding as parachain in aprox 2h
