### ISSUE TITLE
Reset Webb parachain

### ISSUE THREAD

**Issue by 1xstj** [paritytech/subport#420]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Webb

### Parachain Name

egg-rococo

### ParaID

4006

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[webb-rococo-4006-genesis.zip](https://github.com/paritytech/subport/files/9197025/webb-rococo-4006-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[webb-rococo-4006-wasm.zip](https://github.com/paritytech/subport/files/9189151/webb-rococo-4006-wasm.zip)

### Anything else we should know?

We would like to restart the chain with the new genesis and wasm.

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
First of all, please, correctly upload your genesis head. Edit this issue with the correct data.

Once that is on place, I will set the new artifacts in this issue, and as you still have one temp slot, the next time you onboard as parachain it will be with these new artifacts. So, you will need to have your collators ready for it

**Comment by 1xstj** [comment]
@al3mart Updated the issue. Collators are already running with new data. Thanks

**Comment by al3mart** [comment]
New artifacts set
