### ISSUE TITLE
Rococo testnet slot for Subzero

### ISSUE THREAD

**Issue by vasylenko-yevhen** [paritytech/subport#423]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Zero Reality

### Parachain Name

Subzero

### ParaID

4040

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[subzero-genesis.tar.gz](https://github.com/paritytech/subport/files/9200659/subzero-genesis.tar.gz)

### Upload your Validation Code (genesis runtime Wasm)

[subzero-wasm.tar.gz](https://github.com/paritytech/subport/files/9200667/subzero-wasm.tar.gz)

### (Optional) Upload your Chain Specification

[rococo-parachain-raw.json.tar.gz](https://github.com/paritytech/subport/files/9201014/rococo-parachain-raw.json.tar.gz)

### Anything else we should know?

We would like to test communication with other parachains via XCM/HRMP protocols.

### Register your Rococo parachain details for `polkadot-js/apps`

https://github.com/polkadot-js/apps/pull/7919

**Comment by al3mart** [comment]
Temp slot assigned, you will onboard in the coming rotations
