### ISSUE TITLE
Add Amplitude (Kusama) to Rococo

### ISSUE THREAD

**Issue by gonzamontiel** [paritytech/subport#425]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

PendulumChain

### Parachain Name

Amplitude

### ParaID

2124

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[rococo-2124-genesis.zip](https://github.com/paritytech/subport/files/9219983/rococo-2124-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[rococo-2124-wasm.zip](https://github.com/paritytech/subport/files/9219986/rococo-2124-wasm.zip)

### (Optional) Upload your Chain Specification

https://github.com/pendulum-chain/pendulum/blob/main/res/amplitude-spec-rococo-raw.json

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7936

**Comment by al3mart** [comment]
Onboarding parathread in aprox 1h 17' from now

**Comment by al3mart** [comment]
Long term slot assigned.

**Comment by gonzamontiel** [comment]
hey @al3mart , we would need a testnet reset with the same wasm and genesis block indicated here, we need to rerun our nodes from the start. thanks!

**Comment by gonzamontiel** [comment]
hi @al3mart, due to a misconfiguration in our Rococo collators, once again we would want to reset our testnet to the same wasm function. I'm sorry if this causes any inconvinience. Can you let us know when this can happen?

**Comment by NicoMorganParity** [comment]
Hello @gonzamontiel,
Can you please share with us your Parachain Manager Account.
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.
