### ISSUE TITLE
lht4050

### ISSUE THREAD

**Issue by lhtpavankumar** [paritytech/subport#427]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

lht

### Parachain Name

lht4050

### ParaID

4050

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

C:\Users\Development\Desktop\substrate-parachain-template\para-2000-genesis

### Upload your Validation Code (genesis runtime Wasm)

C:\Users\Development\Desktop\substrate-parachain-template\para-2000-wasm

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
short term slot assigned. Onboard will happen in the coming rotations.

(you did not upload the wasm and state correctly, it was not necessary this time, but you may want to fix that )
