### ISSUE TITLE
rococo

### ISSUE THREAD

**Issue by lhttushargoplani** [paritytech/subport#428]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

LHT 4055

### Parachain Name

Avengers

### ParaID

4055

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

0x000000000000000000000000000000000000000000000000000000000000000000d55cc9b750bd6cf10aacfbf2b9ea9c7c9a685ca18e64b130c8eafafc5b92743103170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm)

T:\LeewayHertz\substarte\substrate-parachain-template\para-2000-wasm

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
short term slot assigned
