### ISSUE TITLE
v

### ISSUE THREAD

**Issue by lhtvikaschauhan** [paritytech/subport#429]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

vikas_team

### Parachain Name

vikas_parachain

### ParaID

4049

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

0x00000000000000000000000000000000000000000000000000000000000000000006b28b6a5e3d581b70e7f6414dd230407a665370909d3bd64384bda75e959ae503170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm)

D:\Work\substrate\Day 5\substrate-parachain-template\para-2000-wasm

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
short term slot assigned
