### ISSUE TITLE
Veda

### ISSUE THREAD

**Issue by srith0798** [paritytech/subport#430]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

tech_Rococo

### Parachain Name

Rococo-kill

### ParaID

4075

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/1Q_ZB-QA-t5lLfz3BgJNcShgJB7MbUa8Q/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/1Jx-YKbud8aDRmw4lzV7bgZVB2OQyPOY1/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by srith0798** [comment]
@al3mart  Could you please approve my slot request

**Comment by al3mart** [comment]
short term slot assigned
