### ISSUE TITLE
vikas

### ISSUE THREAD

**Issue by lhtvikaschauhan** [paritytech/subport#431]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

vikas_team

### Parachain Name

vikas_parachain

### ParaID

4073

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/1kLwcCwZdZa3B9Z4pzVaIyKwc6ex5J7uK/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/1AqYbDHVQzuUPJJkYMSGZl6t5MeUtpfyL/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by lhtvikaschauhan** [comment]
@al3mart  can you please provide us temp parachain slot, so that we can test our parachain working features in rococo.

**Comment by al3mart** [comment]
short term slot assigned
