### ISSUE TITLE
lht

### ISSUE THREAD

**Issue by lhttushargoplani** [paritytech/subport#433]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [x] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

team_tushar

### Parachain Name

rococo-world

### ParaID

4072

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/1xqnerP2tJIM4TjEGtOwuv7DmFKiF8I-L/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/1U2CHuQ2vysQYwChWOEgjXdr0SrN-vuWX/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by lhttushargoplani** [comment]
@al3mart can you please provide me temp parachain slot

**Comment by al3mart** [comment]
short term slot assigned
