### ISSUE TITLE
lhtpavana

### ISSUE THREAD

**Issue by lhtpavankumara** [paritytech/subport#434]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

rococo-tashi

### Parachain Name

rococo-para

### ParaID

4077

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

0x0000000000000000000000000000000000000000000000000000000000000000003a00dbb4a518a1bd8293531db11ba78e7d288065204b8b81ae06ec74406d589f03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm)

0x52bc537646db8e0528b52ffd0058e48a04ee88454011501050cc281d808f67a55f011d72426dc90b2ce5130b58af04f73c0130f19bf13a2e8dcac12b7a5087512d0b95703c055d38d1619cad96ecd0396a0f0fc0be7de32e1a5674df76235b6eb2a59452ca94525b122c10b110409c3fedc4e3512ee7db537775841372a877f2dbdd39fd9a7d73461b4523a0ca420d21b2a8a38823a0f94168df0d6d14eadbc8aeb8acbe9d4803b55023f976a7f1679daa34a753d777fb62436ee38dfeaeb84cf16f3b358a77e576b87602936601b8d60159fb6502e3fa5d6

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
short term slot assigned
