### ISSUE TITLE
Parachain Slot Request By RK

### ISSUE THREAD

**Issue by lhtRaghkumarTentu** [paritytech/subport#435]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

LHT_RK & Team

### Parachain Name

LHT-RK

### ParaID

4076

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)
https://drive.google.com/file/d/1OkdLe-U2PfMP_1EEHag3o8eh22A41VEt/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)
https://drive.google.com/file/d/1cm-cy1aFQ3YU5DIsyoOl-fsck5NYqTZg/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by lhtRaghkumarTentu** [comment]
@al3mart Pls Kindly Approve My Slot

**Comment by al3mart** [comment]
short term slot assigned
