### ISSUE TITLE
Srinivas

### ISSUE THREAD

**Issue by Srinivas766** [paritytech/subport#436]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

leewayhertz

### Parachain Name

rococo

### ParaID

4079

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

0x00000000000000000000000000000000000000000000000000000000000000000046afe72be9b47ba4cb5448e018e067a8d94aacdbed6d09d15a793215658660f803170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm)

0x52bc537646db8e0528b52ffd0058fc8e047e8dc54e11511060ea261da8edc0db2db7006417ac233ad9bca04c4c5c22acffa1477573941996e068d2d7458df3a82d47d74ad8ffaa2bcdaaa650657e9020a713063159b11f923d86e2862ced46b6dc644bb9a59429a562123c10c310755b463cd543fd93dfeecfe9d7ed9b37da281a81151833418071830824a431816aa189360a366a1df53d645b595adf1ea47f5ad545befd71fc5ba72ac5e954f6ddbe5a1077f4b795658a87dda951bcada725db1a26dd02902d0d5b7b56fa22fb6d6101f3a746b1ef4eb6da82060b0ab288410ec048816a351f8e3f632d08368a3b1df6fd6af41e366b41dc2181bedc7e96ad76e4eaaaffe5b3b57d26d8a8ae1abd27f9a953993fdfe994cc24867515739263926ebfb

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
short term slot assigned
