### ISSUE TITLE
Deepaklht

### ISSUE THREAD

**Issue by lhtdeepak** [paritytech/subport#437]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Deepak_Team

### Parachain Name

Deepak_Parachain

### ParaID

4074

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/1Sg2Zi9OJaLCkve0lmoKPZNPL97mhTXdX/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/16EJuIc-yrD3SXF16MNMwMP8QRtaQ8Mp8/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by lhtdeepak** [comment]
@al3mart  https://github.com/al3mart can you please provide us temp parachain slot, so that we can test our parachain working features in rococo.

**Comment by lhtdeepak** [comment]
@al3mart  can you please provide us temp parachain slot, so that we can test our parachain working features in rococo.

**Comment by al3mart** [comment]
short term slot assigned
