### ISSUE TITLE
vishalrococonetwork

### ISSUE THREAD

**Issue by vishal33singh** [paritytech/subport#438]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

leewayhertzrococo

### Parachain Name

vishalrococo

### ParaID

4080

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

0x000000000000000000000000000000000000000000000000000000000000000000ae0f6eb7e61279ea1b618dc0aea85d0727a12e688cd41c5ef0b3af2c596c922f03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm)

0x52bc537646db8e0528b52ffd00586c8b04ae8ac54411511058cb281d9479c67342095c028e66c884f0080c61390413ee50bbe26a04d806e606501dbca32bb55eab1fa194bbd3fee7748310ac7404860ed5da95401add076e237065f76d37b2e5265b4a29a54c29055c123110ba10502ee7cb537795840b72a877f2dbdd39fd9a7d73461b4523a0d2220d22b498e30824980922689f0d6d14eabbc8aeb4acbe7d48ff74501ff976a7f1679daa14a753d777fb62426ee38dfeaeb458f16f3b358a77e57ab87602936601b8d60159fb6502e3fa5d65d1e24f8d62df9d4b5503388ec0c10dda70821154042de6a3f15f8c09bd46f1a6c3be5f8fdcbf664c883725cf57dbbfaec592c4adfa479f8dadb3798ddaea91fb929f3a75b9f39d4ec94b5ad6562d2fb92569f6eb59a7a43bc7e994e5ce2fa9f15f56a3a83396a4f4af5174abd44b2eb57daa1db9b7fce25e76a695dafea5ed97acd3af4ff7f383076df7ec12a93bbf5b8d6ef76995df4886f5a91d41a1eb6aba58dc58abd361eb6ceafc876ddbd046f134cab9f46d14bb37caf962427273517b5be58fbe5aa6f56c5467effc69fb3eddcf4b4a4a4a4a0a728e5a23ee9df37c89e111d7

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
short term slot assigned
