### ISSUE TITLE
Send DOT with “reap the sender” from https://polkadot.js.org/ doesn't work

### ISSUE THREAD

**Issue by zhouziyan** [paritytech/subport#44]
I trying to reap my account from https://polkadot.js.org/, but doesn't work.

Steps:
1. choose "without keep-alive checks"
2. choose "transfer the full account balance, reap the sender"
3. make transfer --> sign & submit

The transaction always failed with keep-alive check.

**Comment by emostov** [comment]
<img width="1048" alt="Screen Shot 2020-10-27 at 10 49 20 AM" src="https://user-images.githubusercontent.com/32168567/97341343-2d309980-1842-11eb-9c3f-c05ddb0b3ee6.png">

What amount shows up in `transferrable minus fees`? Is the number greater than zero? Is it greater than the existential deposit?

Can you give the exact error?

**Comment by zhouziyan** [comment]
![image](https://user-images.githubusercontent.com/5153181/98343066-3abcff00-204c-11eb-9654-5e5f9c9de61a.png)

**Comment by zhouziyan** [comment]
![image](https://user-images.githubusercontent.com/5153181/98343209-748e0580-204c-11eb-9e1c-3af64a485be8.png)

**Comment by zhouziyan** [comment]
@emostov See attached two pictures. Thanks.

**Comment by emostov** [comment]
It looks like it mades its way into a block, and was executed, but the execution failed. Can you see the block it was included in and if so can you see the error?

**Comment by zhouziyan** [comment]
Please just have a try to check this issue. It's very easy to reproduce just by sending all tokens.

**Comment by danforbes** [comment]
@zhouziyan do you have any of your DOT staked or bonded?

**Comment by zhouziyan** [comment]
![image](https://user-images.githubusercontent.com/5153181/98797222-442cd980-2447-11eb-991e-564b7dedf3d3.png)

@danforbes  No.

**Comment by NukeManDan** [comment]
@zhouziyan is this still a problem? If so, please reopen this issue 🙏🏼
