### ISSUE TITLE
slot request for lht

### ISSUE THREAD

**Issue by lhtpavankumar** [paritytech/subport#440]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

LHT

### Parachain Name

bright-fork

### ParaID

4058

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/1G6CCjwG6pNmGLv9xXvzGm9BUxup5c4Ds/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/1L-lLIddiayuNcK9lL_sTn9OyaL_el99w/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

https://github.com/polkadot-js/apps/pull/7999

**Comment by lhtpavankumar** [comment]
@al3mart  can you please provide us temp parachain slot, so that we can test our parachain working features in rococo.

**Comment by al3mart** [comment]
short term slot assigned

**Comment by lhtpavankumar** [comment]
@al3mart  can you please provide temp parachain slot again, we can try to test our parachain in rococo
