### ISSUE TITLE
Seraj_parahain_slot

### ISSUE THREAD

**Issue by Seraj2335** [paritytech/subport#444]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Seraj_parachain

### Parachain Name

seraj_Seraj

### ParaID

4087

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/12X9bwVnBXFJZeow94MFfgTp-rJnVCXk9/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/1MGXxm3qI1_tVZrEV0q0g2yiEFGApE6cf/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by Seraj2335** [comment]
@al3mart ,please give me a parachain slot.

**Comment by al3mart** [comment]
Short-term slot assigned
