### ISSUE TITLE
Rococo Slot Request

### ISSUE THREAD

**Issue by Duc-Thang-LC** [paritytech/subport#445]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Mabuu

### Parachain Name

Mabuu Local Parachain

### ParaID

4089

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4089-genesis.txt](https://github.com/paritytech/subport/files/9367812/para-4089-genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4089-wasm.txt](https://github.com/paritytech/subport/files/9367813/para-4089-wasm.txt)

### (Optional) Upload your Chain Specification

[rococo-parachain-4089-raw.json.txt](https://github.com/paritytech/subport/files/9367817/rococo-parachain-4089-raw.json.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Short-term slots assigned
