### ISSUE TITLE
Request for Temporary Slot for MD5 Network

### ISSUE THREAD

**Issue by 3yekn** [paritytech/subport#446]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Hashed Network

### Parachain Name

MD5 Network

### ParaID

4088

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://raw.githubusercontent.com/hashed-io/hashed-parachain/main/resources/md5-genesis-head

### Upload your Validation Code (genesis runtime Wasm)

https://raw.githubusercontent.com/hashed-io/hashed-parachain/main/resources/md5-wasm

### (Optional) Upload your Chain Specification

https://raw.githubusercontent.com/hashed-io/hashed-parachain/main/resources/md5-spec.json

### Anything else we should know?

https://github.com/hashed-io/hashed-parachain

Seeking a temporary slot. I am converting a solo chain to a parachain. At this point, I am mostly interested in testing some of our custom pallets in the parachain environment and test runtime upgrades. 

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/8026

**Comment by al3mart** [comment]
Short-term slot assigned.
