### ISSUE TITLE
How to use `Perquintill` with `Balance`? 

### ISSUE THREAD

**Issue by Chralt98** [paritytech/subport#447]
Hey there,

I saw this in your code for the kusama chain.

https://github.com/paritytech/polkadot/blob/master/runtime/kusama/src/lib.rs#L541

How does this work with a `Balance` type which is `u128`, when `Perquintill` is only allowed for `u64`?

Does this have something to do with the import of `use sp_arithmetic::traits::Saturating` at the top of the function above?

So I assume, that `Perquintill` works with `u128`, the `u128` was silently saturated into `u64` somehow. But how?

I try to use the following.

```rust
let share = <BalanceOf<T>>::from(193_913u128);
let sum = <BalanceOf<T>>::from(138_934_220u128);
let ratio = sp_arithmetic::Perquintill::from_rational::<BalanceOf<T>>(share, sum);
```

I get the following error:
```error
the trait bound `<<T as pallet::Config>::AssetManager as MultiCurrency<<T as frame_system::Config>::AccountId>>::Balance: From<u64>` is not satisfied
```

Thank you for your fast answers.

**Comment by al3mart** [comment]
Hey @Chralt98 this would be an amazing post for substrate.stackexchange.com :)
