### ISSUE TITLE
Slot Request for LeewayHertz

### ISSUE THREAD

**Issue by lhtishuchawla** [paritytech/subport#448]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

LeewayHertz

### Parachain Name

IshuLht

### ParaID

4093

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/1eLRR2Vg8xRx9xvGyj4ek2f9hFHidqM_u/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/1s-s92l1TFgD_pd4xGOX5HVUvZa2zZ0lO/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Short-term slot assigned
