### ISSUE TITLE
Slot Request for Confti

### ISSUE THREAD

**Issue by cheft** [paritytech/subport#449]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Contfi

### Parachain Name

Contfi

### ParaID

4094

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4094-genesis.zip](https://github.com/paritytech/subport/files/9391728/para-4094-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-4094-wasm.zip](https://github.com/paritytech/subport/files/9391730/para-4094-wasm.zip)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/8029

**Comment by al3mart** [comment]
Short-term slot assigned
