### ISSUE TITLE
Aventus parachain slot activation

### ISSUE THREAD

**Issue by nahuseyoum** [paritytech/subport#451]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Aventus

### Parachain Name

avn_rococo

### ParaID

4095

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[genesis-rococo-state.zip](https://github.com/paritytech/subport/files/9438171/genesis-rococo-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[genesis-rococo-wasm.zip](https://github.com/paritytech/subport/files/9438174/genesis-rococo-wasm.zip)

### Anything else we should know?

The state file and wasm are contained in a zipped file.

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by SBalaguer** [comment]
Done! Becoming a parachain in ~50'.
