### ISSUE TITLE
Request for parachain slot

### ISSUE THREAD

**Issue by lhtgunaraja** [paritytech/subport#457]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Leewayhertz

### Parachain Name

Neobguna Parachain

### ParaID

4106

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4106-genesis.zip](https://github.com/paritytech/subport/files/9476455/para-4106-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-4106-wasm.zip](https://github.com/paritytech/subport/files/9476459/para-4106-wasm.zip)

### Anything else we should know?

So... We want to test connecting local parachain into rococo testnet

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by lhtgunaraja** [comment]
@al3mart Kindly provide parachain slot.

**Comment by al3mart** [comment]
Please, register a parathread for that paraId before we assign any slot to it.
