### ISSUE TITLE
Aventus parachain long term slot request

### ISSUE THREAD

**Issue by nahuseyoum** [paritytech/subport#458]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Aventus

### Parachain Name

avn_rococo

### ParaID

2056

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[rococo-genesis-state.zip](https://github.com/paritytech/subport/files/9499510/rococo-genesis-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[rococo-wasm.zip](https://github.com/paritytech/subport/files/9555211/wasm.zip)

### (Optional) Upload your Chain Specification

[rococo-chainspec-raw.zip](https://github.com/paritytech/subport/files/9499515/rococo-chainspec-raw.zip)

### Anything else we should know?

We were not able to register a paraID for 2056 on Rococo because polkadotJS automatically assigns the next available slot.

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: (https://github.com/polkadot-js/apps/pull/8103)

**Comment by nahuseyoum** [comment]
@al3mart Can you please help to onboard us as a parachain?

**Comment by brandisio** [comment]
Hi @al3mart, if at all possible please could you attend to this ASAP - we are blocked waiting for the test slot. Our timelines have to be shifted because of the delay.

**Comment by al3mart** [comment]
Could you correctly reupload your validation code, please ?

**Comment by nahuseyoum** [comment]
> Could you correctly reupload your validation code, please ?

Sorry, I have uploaded it again.

**Comment by al3mart** [comment]
Registering parathread

**Comment by nahuseyoum** [comment]
Thank you

**Comment by al3mart** [comment]
Parathread is in place.
Though, I have been checking and so far we have hit the limit on LongTermSlots, which is set to 20 at the moment. I have already pushed a change to bump value.

For the moment, I am assigning you LPs for a duration of 1 month. That should be long enough for the next release to happen and with that the new Rococo runtime with this updated value.
After this runtime upgrade I would be able to assign you a long term slot.

From your side you should note no difference, but I prefer you to be aware of this.

**Comment by nahuseyoum** [comment]
Hello, can you please replace our wasm and state file with the new ones we have attached? Thank you

[genesis_avn_rococo_v3_state.zip](https://github.com/paritytech/subport/files/9626655/genesis_avn_rococo_v3_state.zip)
[genesis_avn_rococo_v3_wasm.zip](https://github.com/paritytech/subport/files/9626656/genesis_avn_rococo_v3_wasm.zip)

**Comment by SBalaguer** [comment]
Re-opening as per the previous comment.

**Comment by al3mart** [comment]
Done!

**Comment by thadouk** [comment]
Hello @al3mart
We haven't been able to start the rococo parachain yet. We though to start from scratch and re-create the whole configuration.
Would it be possible please to replace the wasm and state file for this parachain (id: 2056) with this runtime and state:

- [avn_rococo_v4_raw_state.zip](https://github.com/paritytech/subport/files/9811517/avn_rococo_v4_raw_state.zip)
- [avn_rococo_v4_raw_wasm.zip](https://github.com/paritytech/subport/files/9811519/avn_rococo_v4_raw_wasm.zip)

**Comment by thadouk** [comment]
Hello all
Unfortunately we still haven't been able to start our rococo parachain with ID 2056.
I have generated a new chainspec (v4) and a new set of genesis/state file combination
Could you please use these and reset the state of the parachain?

- [avn_rococo_v4_raw_state.zip](https://github.com/paritytech/subport/files/9820900/avn_rococo_v4_raw_state.zip)
- [avn_rococo_v4_raw_wasm.zip](https://github.com/paritytech/subport/files/9820901/avn_rococo_v4_raw_wasm.zip)
-

**Comment by al3mart** [comment]
done

**Comment by thadouk** [comment]
Can we also please upgrade the parathread to become a parachain?
A long term lease preferably since we have a matching para-id on polkadot.

**Comment by thadouk** [comment]
Hi @SBalaguer @al3mart 
Would it be possible to replace our wasm and state file on our rococo parachain with paraid 2056?
- [genesis.v5.state.zip](https://github.com/paritytech/subport/files/10135754/genesis.v5.state.zip)
- [genesis.v5.wasm.zip](https://github.com/paritytech/subport/files/10135755/genesis.v5.wasm.zip)
Thanks in advance!

**Comment by al3mart** [comment]
All set

**Comment by NicoMorganParity** [comment]
Hello @thadouk,
Can you please share with us your Parachain Manager Account. 
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.

**Comment by nahuseyoum** [comment]
Hi @NM2146 if its ok for the same address to own multiple parachains, please use `5HYowb6rNcawJMKmzZZQUwTYihmSdNNQii7AJSchGDdEAcnL` for our Rococo parachain manager account.

**Comment by NM2146** [comment]
Hi @nahuseyoum thanks, If you don't mind If you checking `registrar.paras` you can see the account registered for your Rococo Para slot.

**Comment by nahuseyoum** [comment]
Hi @NM2146 thanks I had checked that and found that the current owner is set to the SUDO user of Rococo (5DwBmEFPXRESyEam5SsQF1zbWSCn2kCjyLW51hJHXe9vW4xs). It may have been because our parachain was onboarded directly by Parity. That is why i suggested a different address we would like to associate with out parachain. Hope this makes sense.
