### ISSUE TITLE
Request for temporary slot

### ISSUE THREAD

**Issue by lhtsourabharora** [paritytech/subport#459]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

LeewayHertz

### Parachain Name

Leeway321

### ParaID

4111

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4111-genesis-state.txt](https://github.com/paritytech/subport/files/9524669/para-4111-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4111-wasm.txt](https://github.com/paritytech/subport/files/9524674/para-4111-wasm.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Temp slot assigned
