### ISSUE TITLE
How to store the linked list data of RC and RefCell？

### ISSUE THREAD

**Issue by qaibeibei** [paritytech/subport#46]
In decl_storage, How to store the linked list data of RC and RefCell？，
StorageLinkedMap Has it been deprecated？  
Cannot find StorageLinkedMap in the source code

**Comment by danforbes** [comment]
It looks like `StorageLinkedMap` has been deprecated. Can you be a little bit more specific about what you are trying to accomplish? What have you tried so far and why don't you think it's working?

**Comment by qaibeibei** [comment]
For example, 

type OwnMemItem<T> = MemItem<<T as sysytem::Trait>::AccountId>;

decl_storage!{

       MemLists get(fn memlists）:map hasher(blake2_128_concat) (T::AccountId) => Option<OwnMemItem<T>>;
}




#[cfg_attr(feature ="std",derive(Debug))]
#[derive(Encode,Decode)]
pub struct MemItem<Value>{
      uid:Value,
      parent:Refcell<Weak<MemItem<Value>>>,
      childrens:RefCell<Vec<Rc<MemItem<Value>>>>,
}

Prompt that the Encode trait is not implemented for Rdfcell<.....>


I tried to modify parity-scale-codec-1.3.4/src/codec.rs But no success.

**Comment by qaibeibei** [comment]
> It looks like `StorageLinkedMap` has been deprecated. Can you be a little bit more specific about what you are trying to accomplish? What have you tried so far and why don't you think it's working?

For example,

type OwnMemItem<T> = MemItem<<T as system::Trait>::AccountId>;

decl_storage!{

   MemLists get(fn memlists）:map hasher(blake2_128_concat) (T::AccountId) => Option<OwnMemItem<T>>;
}

#[cfg_attr(feature ="std",derive(Debug))]
#[derive(Encode,Decode)]
pub struct MemItem<Value>{
uid:Value,
parent:Refcell<Weak<MemItem<Value>>>,
childrens:RefCell<Vec<Rc<MemItem<Value>>>>,
}

Prompt that the Encode trait is not implemented for Refcell<.....>

I tried to modify parity-scale-codec-1.3.4/src/codec.rs But no success.

**Comment by danforbes** [comment]
Can you try using [`Box`](https://substrate.dev/rustdocs/v2.0.0/sp_std/boxed/struct.Box.html) instead of `RefCell`?

**Comment by thiolliere** [comment]
> I tried to modify parity-scale-codec-1.3.4/src/codec.rs But no success.

How did you try it? at a first glance the following code should work:
```diff
diff --git a/src/codec.rs b/src/codec.rs
index a7c693e..8504ff0 100644
--- a/src/codec.rs
+++ b/src/codec.rs
@@ -427,6 +427,33 @@ impl<T, X> Decode for X where
 
 }
 
+impl<T: Encode> Encode for core::cell::RefCell<T> where {
+       fn size_hint(&self) -> usize {
+               self.borrow().size_hint()
+       }
+
+       fn using_encoded<R, F: FnOnce(&[u8]) -> R>(&self, f: F) -> R {
+               self.borrow().using_encoded(f)
+       }
+
+       fn encode(&self) -> Vec<u8> {
+               self.borrow().encode()
+       }
+
+       fn encode_to<W: Output>(&self, dest: &mut W) {
+               self.borrow().encode_to(dest)
+       }
+}
+
+impl<T: Decode> Decode for core::cell::RefCell<T> {
+       fn decode<I: Input>(input: &mut I) -> Result<Self, Error> {
+               input.descend_ref()?;
+               let result = Ok(T::decode(input)?.into());
+               input.ascend_ref();
+               result
+       }
+}
+
 /// A macro that matches on a [`TypeInfo`] and expands a given macro per variant.
 ///
 /// The first parameter to the given macro will be the type of variant (e.g. `u8`, `u32`, etc.) and other parameters
```

**Comment by tomusdrw** [comment]
AFAIU you're trying to create a linked list with elements stored the `StorageMap`. You really shouldn't be trying `Encoding` the `RefCell`, cause every list element will actually contain the entire list encoded with it.

The next/previous (or parent/children) should rather be indices, not entire elements.

**Comment by danforbes** [comment]
@qaibeibei are you still stuck on this? If so, can you please provide an update? If not, please close this Issue :pray:

**Comment by thiolliere** [comment]
He reacted positively to answers thus I think we can close it, feel free to reopen for further information
