### ISSUE TITLE
Kabocha Rococo Testnet

### ISSUE THREAD

**Issue by decentration** [paritytech/subport#460]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Decentration (technical steward for Kabocha)

### Parachain Name

Kabocha

### ParaID

4113

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://github.com/kabocha-network/parachain/blob/kab-roc-v0.2.4/genesiswasm/kabocha-4113-genesis

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/kabocha-network/parachain/blob/kab-roc-v0.2.4/genesiswasm/kabocha-4113-wasm

### (Optional) Upload your Chain Specification

https://github.com/kabocha-network/parachain/blob/kab-roc-v0.2.4/specs/kab-roc-test-plain-raw.json

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

XCM channels with Karura, Bitfrost, Kilt and Oak

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {}

**Comment by al3mart** [comment]
Please, register your prathread, if not we would not be able to assign you any slot.

**Comment by decentration** [comment]
oh yes sorry, the call didnt go through, its ready for you whenever your'e ready. cheers

**Comment by decentration** [comment]
para-id 4113 is now a parathread @al3mart.

Also fyi, we have a community run [relay testnet](https://apps.decentration.org/?rpc=wss%3A%2F%2Fpopart1.jelliedowl.com#/accounts), so we are relatively competent with the parachain processes : )

**Comment by al3mart** [comment]
Temp slot assigned

**Comment by decentration** [comment]
hi @al3mart, sorry i thought temp slot was a little longer than that, do you mind reassigning a longer slot, perhaps month or more?
