### ISSUE TITLE
Tinkernet Long Term Rococo Slot Request

### ISSUE THREAD

**Issue by arrudagates** [paritytech/subport#461]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

InvArch

### Parachain Name

Tinkernet Rococo

### ParaID

2125

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

Github requires a supported extension, using txt.
[genesis-state.txt](https://github.com/paritytech/subport/files/9537559/genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

Github requires a supported extension, using txt.
[genesis-wasm.txt](https://github.com/paritytech/subport/files/9537562/genesis-wasm.txt)

### (Optional) Upload your Chain Specification

Github requires a supported extension, using txt.
[tinkernet-rococo-raw.txt](https://github.com/paritytech/subport/files/9537567/tinkernet-rococo-raw.txt)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/8114

**Comment by arrudagates** [comment]
Tinkernet Rococo merged into polkadot.js/apps

**Comment by al3mart** [comment]
Onboarding parathread

**Comment by al3mart** [comment]
Parathread is in place.
Though, I have been checking and so far we have hit the limit on LongTermSlots, which is set to 20 at the moment. I have already pushed a change to bump value.

For the moment, I am assigning you LPs for a duration of 1 month. That should be long enough for the next release to happen and with that the new Rococo runtime with this updated value.
After this runtime upgrade I would be able to assign you a long term slot.

From your side you should note no difference, but I prefer you to be aware of this.
