### ISSUE TITLE
Updating MD5 parachain ID (new long-term slot should replace short-term slot)

### ISSUE THREAD

**Issue by mgravitt** [paritytech/subport#464]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Hashed Network

### Parachain Name

MD5 Network

### ParaID

2089

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://raw.githubusercontent.com/hashed-io/hashed-substrate/develop/resources/md5-genesis-head

### Upload your Validation Code (genesis runtime Wasm)

https://raw.githubusercontent.com/hashed-io/hashed-substrate/develop/resources/md5-wasm

### (Optional) Upload your Chain Specification

https://raw.githubusercontent.com/hashed-io/hashed-substrate/develop/resources/md5-spec.json

### Anything else we should know?

I have reserved this parachain ID on Polkadot.

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/8121/files

**Comment by al3mart** [comment]
Closing as this looks stale
