### ISSUE TITLE
Kabocha Rococo Permanent Slot

### ISSUE THREAD

**Issue by decentration** [paritytech/subport#468]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Decentration

### Parachain Name

Kabocha

### ParaID

2113

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://github.com/kabocha-network/parachain/blob/kab-roc-v0.2.4/genesiswasm/kabocha-2113-genesis-rococo

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/kabocha-network/parachain/blob/kab-roc-v0.2.4/genesiswasm/kabocha-2113-wasm-rococo

### (Optional) Upload your Chain Specification

https://github.com/kabocha-network/parachain/blob/kab-roc-v0.2.4/specs/kab-roc-test-plain-raw.json

### Anything else we should know?

Kabocha is on Kusama main net. (2113)

We'd like to start XCM channels with Karura, Bitfrost... and thereafter Kilt, Oak, Encointer. 

I think it requires sudo, but do i need to register the para-id 2113 (equivalent to Kusama main net) from my side? I

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding parathread

**Comment by decentration** [comment]
parathread looks good and ready for parachain upgrade.

p.s. we made a [PR](https://github.com/polkadot-js/apps/pull/8149) to polkadot js apps for branding update.

**Comment by al3mart** [comment]
As longTerm slots are full at the moment I have assigned you LPs for 1 month, that will be long enough for the next runtime upgrade of Rococo to happen and bump the maximum number of long term slots.
