### ISSUE TITLE
Why does event system consume the ownership?

### ISSUE THREAD

**Issue by MyronFanQiu** [paritytech/subport#47]
I'm not familiar with rust enough. Right now, if I want to emit two events with same information, I would clone the vars for the first event. I'm not sure whether it's the best practice or not. Is there any suggestion ?
```rust
let prev_pk = vec![0];
let curr_pk = vec![1];
Self::deposit_event(RawEvent::ChillSuccess(reporter.clone(), prev_pk));
Self::deposit_event(RawEvent::ABUpgradeSuccess(reporter, curr_pk));
```
Meanwhile, if a private func need to emit an event, I have to pass the ownership into this function. Even though the business logic might not need the ownership at all.

**Comment by Swader** [comment]
Borrow instead of clone:

```rust
let prev_pk = vec![0];
let curr_pk = vec![1];
Self::deposit_event(RawEvent::ChillSuccess(&reporter, prev_pk));
Self::deposit_event(RawEvent::ABUpgradeSuccess(reporter, curr_pk));
```

**Comment by MyronFanQiu** [comment]
@Swader However, I cannot do that. Which version of substrate supports borrow?

```rust
   --> cstrml/swork/src/lib.rs:230:65
    |
230 |             Self::deposit_event(RawEvent::EnclaveUpgradeSuccess(&new_code, expire_block));
    |                                                                 ^^^^^^^^^
    |                                                                 |
    |                                                                 expected struct `std::vec::Vec`, found reference
    |                                                                 help: consider removing the borrow: `new_code`
    |
    = note: expected struct `std::vec::Vec<u8>`
            found reference `&std::vec::Vec<u8>`
```

**Comment by Swader** [comment]
This is different from your code snippet above, but I am not sure why this does not work, someone else will have to chime in.

**Comment by MyronFanQiu** [comment]
> This is different from your code snippet above, but I am not sure why this does not work, someone else will have to chime in.

The code snippet in the first comment is the solution I choose right now. The second the code snippet is the question/problem I met. They're same. What I want is the code snippet you shown. Do you mean your code is the design but somehow it doesn't work? If that's the case, I can try to dive into and figure out the reason to solve it.

**Comment by Swader** [comment]
I mean borrows are pretty standard in Rust and used across our Substrate tutorials: https://substrate.dev/docs/en/tutorials/build-a-dapp/pallet#callable-functions

I'm not knowledgeable enough to guess why it might not work in your case, however, sorry.

**Comment by MyronFanQiu** [comment]
> I mean borrows are pretty standard in Rust and used across our Substrate tutorials: https://substrate.dev/docs/en/tutorials/build-a-dapp/pallet#callable-functions
> 
> I'm not knowledgeable enough to guess why it might not work in your case, however, sorry.

I think that's not the truth. `borrows` are pretty standard in Rust. However, in substrate event system, I don't think we can use `borrows`. The [tutorial](https://substrate.dev/docs/en/tutorials/build-a-dapp/pallet#callable-functions) would transfer the ownership to the event function as well.

I listed some examples in the substrate.
- Staking
https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L1436
https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L2321
- Balance
https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L612
https://github.com/paritytech/substrate/blob/master/frame/balances/src/lib.rs#L659
- Collective
https://github.com/paritytech/substrate/blob/master/frame/collective/src/lib.rs#L1082
- Treasury
https://github.com/paritytech/substrate/blob/master/frame/treasury/src/lib.rs#L698
https://github.com/paritytech/substrate/blob/master/frame/treasury/src/lib.rs#L744

Actually, according to the substrate, `clone` is the best practice for such case. But it do cause inconvenience for me. I want to confirm whether it is by design or not. I didn't look into event system right now. I don't know the whole picture and context. If it's by design, I want to know the reason and whether we can use `borrows`. If it's not by design, maybe I can help to figure out the reason behind current behavior.

**Comment by Swader** [comment]
I've used borrows in substrate (the tutorial example) without issue. You're right in that clone is used a lot in Substrate, but I don't think that's actually necessary. Let me ping some people.

**Comment by apopiak** [comment]
> I'm not familiar with rust enough. Right now, if I want to emit two events with same information, I would clone the vars for the first event. I'm not sure whether it's the best practice or not. Is there any suggestion ?

It's perfectly fine to clone the variables if you pass them to the events twice. Rust just surfaces memory management that might be hidden in other languages.

**Comment by apopiak** [comment]
> Meanwhile, if a private func need to emit an event, I have to pass the ownership into this function. Even though the business logic might not need the ownership at all.

You can also pass in a borrow and then clone the object when emitting the event.
e.g. something like:
```rust
fn my_func(reporter: &T::AccountId) {
    let prev_pk = vec![0];
    Self::deposit_event(RawEvent::ChillSuccess(reporter.clone(), prev_pk));
}
```

**Comment by MyronFanQiu** [comment]
@apopiak Thanks for the example you provided. I will have a try. @Swader Thanks for your help. I may dig into it later to see how to pass a borrow.
