### ISSUE TITLE
Requesting slot for Kapex on Rococo

### ISSUE THREAD

**Issue by chrisdcosta** [paritytech/subport#470]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Totem Accounting

### Parachain Name

Kapex (Stagex on Rococo)

### ParaID

2007

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://github.com/totem-tech/totem-parachains/blob/stagex-v1.1.0/res/stagex/stagex-genesis-state.state

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/totem-tech/totem-parachains/blob/stagex-v1.1.0/res/parachain-genesis-wasm.wasm

### (Optional) Upload your Chain Specification

https://github.com/totem-tech/totem-parachains/blob/stagex-v1.1.0/res/stagex/stagex-parachain-raw.json

### Anything else we should know?

We are looking to do pre-production upgrade tests on Rococo in the coming weeks
- upgrade with a fix coming from the audit
- upgrade for the underlying polkadot node to 0.9.28 and the various compatibility changes required in our node
- test funds distribution transaction
- upgrade to remove transaction lock from balances module

Afterward we will immediately work on 
- upgrade to community governance (and we will need some guidance / roadmap on migrating from Sudo Pallet to full decentralised governance

### Register your Rococo parachain details for `polkadot-js/apps`

Registered Issue https://github.com/polkadot-js/apps/issues/8144 on polkadotjs apps

and pull request https://github.com/polkadot-js/apps/pull/8145

**Comment by al3mart** [comment]
Upgrading parathread

**Comment by al3mart** [comment]
As longTerm slots are full at the moment I have assigned you LPs for 1 month, that will be long enough for the next runtime upgrade of Rococo to happen and bump the maximum number of long term slots.

**Comment by chrisdcosta** [comment]
@NM2146 the parachain upload was managed by @al3mart for us - but if possible could you change that to account `5FHPh356Qx1nkMkwc3BxWR7Tj1ibghSg6aWaJimj2Jod4ZWA` and provide some funds to execute transactions.

Also our chain had to be restarted and new genesis states added. I think this is why it is sitting in Parathread state. We are fixing this week though, as we would like to move forward with some upgrades.
