### ISSUE TITLE
parachain slot request for 4124

### ISSUE THREAD

**Issue by lhtpavankumar** [paritytech/subport#471]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Leewayhertz

### Parachain Name

Tashi Devnet

### ParaID

4124

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://drive.google.com/file/d/1z4TvrcuCDabIz-kRdt2XY0aCiOMFcs-l/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm)

https://drive.google.com/file/d/1AdUfJEJQtD4PIIoMTmyzNl1tzjQHMMK8/view?usp=sharing

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by lhtpavankumar** [comment]
@al3mart can you pls provide us the slot for parachain id 4124

**Comment by lhtpavankumar** [comment]
hi @al3mart  can you pls provide the slot, we are excited to launch this parachain soon

**Comment by lhtpavankumar** [comment]
hi all, 
May I know why it does getting late to approve a temporary slot for a parachain
I also see that the above new issues are getting responses quickly

**Comment by al3mart** [comment]
Slot assigned, you would onboard shortly.
