### ISSUE TITLE
HydraDX slot

### ISSUE THREAD

**Issue by green-jay** [paritytech/subport#473]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

HydraDX

### Parachain Name

HydraDX

### ParaID

2034

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[hydradx_2034_rococo.state.txt](https://github.com/paritytech/subport/files/9617831/hydradx_2034_rococo.state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[hydradx_2034_rococo.wasm.txt](https://github.com/paritytech/subport/files/9617835/hydradx_2034_rococo.wasm.txt)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/8154

**Comment by al3mart** [comment]
Registering parathread

**Comment by al3mart** [comment]
Onboarding now

**Comment by NicoMorganParity** [comment]
Hi @green-jay,
Can you please share with us your Parachain Manager Account. 
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.
