### ISSUE TITLE
Reset Tinkernet rococo parachain (2125)

### ISSUE THREAD

**Issue by arrudagates** [paritytech/subport#476]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

InvArch

### Parachain Name

Tinkernet Rococo

### ParaID

2125

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[genesis-state-2.txt](https://github.com/paritytech/subport/files/9641082/genesis-state-2.txt)

### Upload your Validation Code (genesis runtime Wasm)

[genesis-wasm-2.txt](https://github.com/paritytech/subport/files/9641085/genesis-wasm-2.txt)

### (Optional) Upload your Chain Specification

[Uploading tinkernet-rococo-2-raw.txt…]()

### Anything else we should know?

We already had a rococo parachain running, but due to some issues with the node, our database got into an unrecoverable state, so we're requesting a reset with new state and validation code. The original issue for the rococo slot is #461 

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/8114

**Comment by al3mart** [comment]
Done!
