### ISSUE TITLE
Temporary slot lease: ParaId 4135

### ISSUE THREAD

**Issue by evilrobot-01** [paritytech/subport#478]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Parity

### Parachain Name

DS

### ParaID

4135

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4135-genesis-state.txt](https://github.com/paritytech/subport/files/9657155/para-4135-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4135-wasm.zip](https://github.com/paritytech/subport/files/9657160/para-4135-wasm.zip)

### Anything else we should know?

Working through the tutorial at https://docs.substrate.io/tutorials/connect-relay-and-parachains/acquire-a-testnet-slot/

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
done!

**Comment by evilrobot-01** [comment]
Completed successfully, have set a reminder to deregister parathread when temporary slot lease expires. Thanks very much!

**Comment by al3mart** [comment]
There is no need to deregister your parathread, just leave it there, by holding a temp slot your paraId is part of a pool of all temp slots holding paraIds, from where, in a round robin fashion, LPs will be assigned.
Meaning eventually you will become a parachain again.
