### ISSUE TITLE
Request slot for parachain id 4137

### ISSUE THREAD

**Issue by mrgThang** [paritytech/subport#479]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Run

### Parachain Name

DID

### ParaID

4137

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4137-genesis-state.txt](https://github.com/paritytech/subport/files/9671215/para-4137-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4137-wasm.txt](https://github.com/paritytech/subport/files/9671216/para-4137-wasm.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Short term slot assigned, you should onboard on the coming rotations
