### ISSUE TITLE
Migration with upgraded OpaqueKeys

### ISSUE THREAD

**Issue by mn13** [paritytech/subport#48]
Guys. I have a problem with migration to new version of runtime, where i changed OpaqueKeys struct (had two modules in old struct, now three).

Problem: queuedKeys storage have validator with key 0x00000...0. New added module don't work.
And I can't to update keys in `on_runtime_upgrade()` because session storage is private and session pallet module don't have public methods to work with it. 

What is a correct way to do migration with upgraded OpaqueKeys?

**Comment by mn13** [comment]
Well, fork the session pallet is nice advice, thank you :) but it needed fork the aura and some another pallets.

I tried get raw keys from `NextKeys` with `frame_support::storage::migration::StorageIterator` and now don't know how to deserialize them in migration. May be you have some ideas?

**Comment by danforbes** [comment]
Maybe this will help? https://github.com/danforbes/substrate-node-template/blob/df/tut/adv-upgrade/pallets/nicks/src/lib.rs

**Comment by mn13** [comment]
@danforbes thanks for your answer but this variant is only works if i can to edit pallet, but i use substrate's session pallet that i can't edit by default.

I'll do some attempts to deserialize keys today and if this will not lead to success will try to to fork substrate and make migration inside session pallet

**Comment by apopiak** [comment]
One more point about before we jump into more details:
I would advise to avoid this migration if possible.
I am assuming that you have a chain running that you want to apply this upgrade to that has enough value to merit this much effort.

With that out of the way:
So you could introduce deprecated versions of the [`QueuedKeys` and `NextKeys`](https://github.com/paritytech/substrate/blob/a200cdb93c6af5763b9c7bf313fa708764ac88ca/frame/session/src/lib.rs#L414-L422) (in the session pallet) that you need to migrate, so you could migrate them from a custom runtime migration in your `runtime.rs`.
You could just call `take` for the `QueuedKeys` and [`drain`](https://crates.parity.io/frame_support/storage/trait.IterableStorageMap.html#tymethod.drain) for `NextKeys`. The trouble (as I see it) is that you would need to transform them into the new opaque keys, which I'm also unsure how to do and might require adjusting Substrate/FRAME code.

**Comment by apopiak** [comment]
Talked to someone familiar with the session pallet and they said:
> I'd do a runtime migration that initializes the new members of OpaqueKeys to zero and then give validators a couple of sessions to rotate keys before activating the functionality that uses the new keys.

So you would split it into two runtime migrations.

**Comment by mn13** [comment]
I'm back with a report :)
I´ve done the migration exactly like here


> Talked to someone familiar with the session pallet and they said:
> 
> > I'd do a runtime migration that initializes the new members of OpaqueKeys to zero and then give validators a couple of sessions to rotate keys before activating the functionality that uses the new keys.
> 
> So you would split it into two runtime migrations.

and succeeded. Some additions for someone, who will face with same trouble:
1. One can initialize new members of OpaqueKeys with core::default::Default::default()
2. If one upgrades his/her code via polkadot.js/apps, don't forget to upgrade the types in the settings and reload the page.
