### ISSUE TITLE
helixstreet.io ( ParaID 3025 / 4132 )

### ISSUE THREAD

**Issue by helixstreet** [paritytech/subport#480]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

helixstreet.io

### Parachain Name

helixstreet

### ParaID

4132

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[helixstreet_para-4132-genesis-state.txt](https://github.com/paritytech/subport/files/9674946/helixstreet_para-4132-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[helixstreet_para-4132-wasm.txt](https://github.com/paritytech/subport/files/9674953/helixstreet_para-4132-wasm.txt)

### (Optional) Upload your Chain Specification

[helixstreet_rococo_parachain_4132_plain.json.txt](https://github.com/paritytech/subport/files/9674950/helixstreet_rococo_parachain_4132_plain.json.txt)

### Anything else we should know?

**REMARKS
=========**
helixstreet has already a ParaID 3025 - unfortunately we made a mistake with the genesis file and cannot reproduce it .  
The new genesis files for 3025 are also here and wasm are here:

https://github.com/helixstreet/helixstreet-rococo-configs

May i kindly ask 

_**a/**_
either to create a new Parathread with the reserved  **ParaID 4132** ( Configs are also here https://github.com/helixstreet/helixstreet-rococo-configs-4132 ) or 

**_b/_**
update the Genesis + Wasm for **ParaID 3025** - ( there seems an extrinsic like forceRegister )

In case **_a/_** i would  release the ParaID 3025.  For b/ i tried with (also with the sudo wrapper emulation ) but without any success. I think that's only possible for rococo admins

Thx and sorry for the hassle. The help here is highly appreciated.
tom

### Register your Rococo parachain details for `polkadot-js/apps`

- [X] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}
  
With PRs

- #7746  
- #7749 
- #7771  
- #7764 

PR: https://github.com/polkadot-js/apps/pull/7746/files

```
  _{
    info: 'helixstreet',
    paraId: 3025,
    text: 'Helixstreet',
    providers: {
      Helixstreet: 'wss://rpc-rococo.helixstreet.io'
    }
  },_
```
helixstreet was included in polkadot.js/apps

**Comment by helixstreet** [comment]
Hi,
Thx, that would you be great. Yes, those configs are fine for 3025
Best regards,
tom

**Comment by al3mart** [comment]
New artifacts set.
Could you pls, modify the issue to reflect the correct paraId ? Just for easier tracking on the future :)

**Comment by helixstreet** [comment]
Hi,
done.
Hope it is OK so.
Best regards,
tom
