### ISSUE TITLE
Bifrost request rococo slot (2030)

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/subport#484]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Liebi Technologies

### Parachain Name

Bifrost K Rococo

### ParaID

2030

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[bifrost-kusama-rococo.state.zip](https://github.com/paritytech/subport/files/9776971/bifrost-kusama-rococo.state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[bifrost-kusama-rococo.wasm.zip](https://github.com/paritytech/subport/files/9776974/bifrost-kusama-rococo.wasm.zip)

### (Optional) Upload your Chain Specification

[bifrost-kusama-rococo-raw.json.zip](https://github.com/paritytech/subport/files/9776979/bifrost-kusama-rococo-raw.json.zip)

### Register your Rococo parachain details for `polkadot-js/apps`

- [ x ] Polkadot-js Apps UI PR completed
  - Available here: [Update bifrost rococo paraId](https://github.com/polkadot-js/apps/pull/8232/commits/65c88ed03db27e2f27ece905f927f33729192fea)

**Comment by al3mart** [comment]
registering parathread

**Comment by al3mart** [comment]
slot assigned!
