### ISSUE TITLE
RocStar parachain reset request

### ISSUE THREAD

**Issue by Dinonard** [paritytech/subport#485]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Astar

### Parachain Name

RocStar

### ParaID

2006

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[rocstar-genesis-state.zip](https://github.com/paritytech/subport/files/9797770/rocstar-genesis-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[rocstar-genesis-wasm.zip](https://github.com/paritytech/subport/files/9797769/rocstar-genesis-wasm.zip)

### (Optional) Upload your Chain Specification

[rocstar.zip](https://github.com/paritytech/subport/files/9783841/rocstar.zip)

### Anything else we should know?

Hi,

we'd like to reset our parachain on Rococo - RocStar. We have an active slot on `paraId: 2006` but need to replace the base runtime (different spec name). New genesis state and WASM are attached.
Is this feasible?

### Register your Rococo parachain details for `polkadot-js/apps`

Existing parachain.

**Comment by Dinonard** [comment]
Hey, just a friendly reminder about this :pray: 

Would it be possible to get a soft estimate when could this be done?
Thank you!

**Comment by al3mart** [comment]
Sorry for the late response, I see parachain 2006 is already onboarded, do you need any further action ?

**Comment by al3mart** [comment]
done!

**Comment by Dinonard** [comment]
Great, thank you!

Will confirm once we're up and running again :+1:

**Comment by Dinonard** [comment]
@al3mart could you please check if head is set correcty?

According to `polkadot-js`, `paras->heads(2006)` it's set to:
`0xea42d086d83708501d835f9bec120a7b75390c9a3d673d2c20e282613cda89da8ade30003634cbb0704f9a25664404391b8de19362871cb4beefc4b1f157e37eaa3b7b7aa642de2121934d9076a72c268b7ad6246849444e247114bff917445a25bddaf30c066175726120d2f64808000000000466726f6e8801c4b081d527cdabe5cc00108022670928c49df30a2fe068ad7320554516e824f10005617572610101a8473f00f44e4279c3de89ed8055bd4fdaefe235f6dde529db1e746fb59f3769c5d79f584a68778cdf14d3a81395f9855f1ca2b690490065b1f412c43fd5b281`

But the file above with the genesis state contains: `0x000000000000000000000000000000000000000000000000000000000000000000dab6803788595d26175d4fbd64784ec2d8d30e92e007606136b0b3b12bb4a2a503170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400`

**Comment by al3mart** [comment]
This is solved now
