### ISSUE TITLE
Request for long-term slot for Bajun

### ISSUE THREAD

**Issue by cowboy-bebug** [paritytech/subport#486]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Ajuna Network

### Parachain Name

Bajun Rococo

### ParaID

2119

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://raw.githubusercontent.com/ajuna-network/Ajuna/main/resources/bajun/rococo/genesis-state

### Upload your Validation Code (genesis runtime Wasm)

https://raw.githubusercontent.com/ajuna-network/Ajuna/main/resources/bajun/rococo/genesis-wasm

### Anything else we should know?

Nope.

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/8129

**Comment by al3mart** [comment]
Slot assigned. Onboarding will happen in the following hour.

**Comment by NicoMorganParity** [comment]
Hello @cowboy-bebug,
Can you please share with us your Parachain Manager Account.
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.
