### ISSUE TITLE
Resetting rococo testnet for Datahighway parachain

### ISSUE THREAD

**Issue by sudipghimire533** [paritytech/subport#487]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Datahighway

### Parachain Name

DataHighway Spreehafen Testnet

### ParaID

2116

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://github.com/DataHighway-DHX/DataHighway-Parachain/blob/v3.6.0/res/rococo/rococo-parachain-state

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/DataHighway-DHX/DataHighway-Parachain/blob/v3.6.0/res/rococo/rococo-parachain-wasm

### (Optional) Upload your Chain Specification

https://github.com/DataHighway-DHX/DataHighway-Parachain/blob/v3.6.0/res/rococo/rococo.json

### Anything else we should know?

We already have this testnet running but what we want is to reset it i.e start again from block 0

### Register your Rococo parachain details for `polkadot-js/apps`

- [X] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
New wasm and state set!

**Comment by sudipghimire533** [comment]
How can we verify. Our parachain is not producing block
