### ISSUE TITLE
Please renew slot for para id 2113, a permanent slot if available. 

### ISSUE THREAD

**Issue by decentration** [paritytech/subport#488]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Decentration

### Parachain Name

Kabocha

### ParaID

2113

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

...

### Upload your Validation Code (genesis runtime Wasm)

...

### Anything else we should know?

We had a slot, which just expired. Can you reassign us a long term slot? Thanks. 

### Register your Rococo parachain details for `polkadot-js/apps`

...

**Comment by decentration** [comment]
just checking in here, hoping we can be sped up, we've got multiple partner testing, and this is a blocker.

**Comment by al3mart** [comment]
Slot assigned, upgrading happening in less than 2h from now.

**Comment by decentration** [comment]
Thanks ✌️
