### ISSUE TITLE
Reset head and validation code for para 2100

### ISSUE THREAD

**Issue by F3Joule** [paritytech/subport#489]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

DappForce

### Parachain Name

Subsocial

### ParaID

2100

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[2100-state.txt](https://github.com/paritytech/subport/files/9911904/2100-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[2100-wasm.txt](https://github.com/paritytech/subport/files/9911906/2100-wasm.txt)

### (Optional) Upload your Chain Specification

https://github.com/dappforce/subsocial-parachain/blob/f3/soonsocialx/node/res/soonsocial.json

### Anything else we should know?

Current chain state, after doing some migration tests became too big, so we want to reset it.

### Register your Rococo parachain details for `polkadot-js/apps`

- [X] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/7374

**Comment by al3mart** [comment]
Sorry for the late action, the new wasm and state is now set.
