### ISSUE TITLE
Rococo Slot Request from Robonomics.network (re-init)

### ISSUE THREAD

**Issue by dergudzon** [paritytech/subport#490]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Robonomics.network

### Parachain Name

Robonomics.network

### ParaID

2048

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[genesis-state.txt](https://github.com/paritytech/subport/files/9942448/genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[genesis-wasm.txt](https://github.com/paritytech/subport/files/9942449/genesis-wasm.txt)

### (Optional) Upload your Chain Specification

file:///home/gdz/Documents/Projects/airalab/ansible-robonomics-network/inventory/rococo-robonomics/data/uploads/parachain-spec-raw-230.json

### Anything else we should know?

Hey! We already have Robonomics parachain with paraid 2048 on Rococo. Can you please re-init this parachain with new genesis-wasm? 

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {https://github.com/polkadot-js/apps/pull/7492/files}

**Comment by al3mart** [comment]
The new artifacts are now set.

**Comment by dergudzon** [comment]
Hello @al3mart! Can we completely restart the parachain 2048? I mean do ParaCleanup and then ParaInitialize using genesis-wasm and genesis-state from this issue.

**Comment by al3mart** [comment]
All set now, please let me know if further actions are required.

**Comment by dergudzon** [comment]
Hey, @al3mart! Can you update it for paraid 2048?
[genesis-state-270.txt](https://github.com/paritytech/subport/files/10319423/genesis-state-270.txt)
[genesis-wasm-270.txt](https://github.com/paritytech/subport/files/10319425/genesis-wasm-270.txt)
