### ISSUE TITLE
Update runtime state & wasm for datahighway testnet

### ISSUE THREAD

**Issue by sudipghimire533** [paritytech/subport#491]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Datahighway

### Parachain Name

DataHighway Spreehafen Testnet

### ParaID

2116

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://github.com/DataHighway-DHX/DataHighway-Parachain/blob/sg/new-node-keys/res/rococo/rococo-parachain-state

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/DataHighway-DHX/DataHighway-Parachain/blob/sg/new-node-keys/res/rococo/rococo-parachain-wasm

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
This has already been addresses, is there need of any further action ? If so please let me know and I will quickly set the new artifacts.

**Comment by sudipghimire533** [comment]
Yes these are newly generated state/wasm. Unfortunately, We lost the session keys after we submitted last one. So would be great if you can set these

**Comment by SBalaguer** [comment]
Executed. Details [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/explorer/query/0x66a0b93020eb20d2d442f78e067fa0f6e402e8a851a2f13b2cc2f032ffd36bbd)
