### ISSUE TITLE
Bitgreen permanent slot request

### ISSUE THREAD

**Issue by abhath-labs** [paritytech/subport#493]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Bitgreen

### Parachain Name

bitgreen-rococo

### ParaID

2048

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[bitgreen-rococo-genesis.zip](https://github.com/paritytech/subport/files/9959213/bitgreen-rococo-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[bitgreen-rococo-wasm.zip](https://github.com/paritytech/subport/files/9959209/bitgreen-rococo-wasm.zip)

### (Optional) Upload your Chain Specification

[bitgreen-rococo-raw.json.zip](https://github.com/paritytech/subport/files/9959210/bitgreen-rococo-raw.json.zip)

### Register your Rococo parachain details for `polkadot-js/apps`

- [X] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
We tend to work with Kusama paraIds on Rococo (for long-term slots).
Unfortunately, Robonomics holds this paraId on Kusama and it is using it on Rococo aswel. I would like to respect that.

Though, I know is unfortunate I would recommend maybe using a paraId like `20048`, that ensures you to not overlap in quite some time with any other para. But the spec, state and wasm would need to be built again for a new paraId.

Please, let me know what are your thoughts on this and lets take action acordingly.

**Comment by al3mart** [comment]
upgrading to parachain now
