### ISSUE TITLE
Hopes of a stable API

### ISSUE THREAD

**Issue by holygits** [paritytech/subport#5]
Some rough data showing the # of `B1-breaksapi` labelled PRs that have been merged over the last year.

<img width="851" alt="Screen Shot 2020-04-09 at 2 41 08 PM" src="https://user-images.githubusercontent.com/5133901/78852377-44f42c00-7a70-11ea-900a-c1227af4c1f7.png">

I'm aware that not all the changes are equal in complexity but this at least shows some indication of how changes are being approached in the framework.

As a downstream project it feels like most our time is spent playing catch up with the changes,
there are some things where I see good opportunities to contribute PRs here but the driver feels more like "If I push my code upstream then it won't break when the next big refactor happens" vs. "this would be a valuable contribution to the ecosystem"

So this is a request to consider the complexity that's being handed to all downstream projects from the frequent refactors and changes and ultimately the detriment to contribution it has.

**Comment by gnunicorn** [comment]
Hello @holygits ,

indeed this project is in fast development, and it will stay that way for a few parts on-going. The statistic is a bit misleading though as it tracks _any_ breaking change on _any_ of the crates, the majority of them are internal though and 95% users will never see/notice those changes.

However, exactly as @HCastano is saying, the key idea behind releasing 2.0 to crates.io is to make that process less burden for downstream users by adhering to SemVer and providing a Changelog that helps upgrading.

We are on the road to adding last features and than stabilising towards releasing 2.0 . We believe that is then going to be a good base for the vast majority of projects.
