### ISSUE TITLE
Rococo slot request for testing parachains with para_id 4175

### ISSUE THREAD

**Issue by DuyUIT2k** [paritytech/subport#502]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

OMU Blockchain Team

### Parachain Name

ScoreChain

### ParaID

4175

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4175-genesis-state.txt](https://github.com/paritytech/subport/files/10046665/para-4175-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4175-wasm.txt](https://github.com/paritytech/subport/files/10046667/para-4175-wasm.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Short term slot assigned.
```
{
  manager: 5FWWVLzeQHwE3bpVgFpSMYhXUdvvyetkLYRfGumzKqw1htM1
  periodBegin: 205
  periodCount: 3
  lastLease: null
  leaseCount: 0
}
```

You will onboard not before `205`
