### ISSUE TITLE
Rococo Request Slot for parachain 4177

### ISSUE THREAD

**Issue by mutobui** [paritytech/subport#504]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

grindy.io

### Parachain Name

Gafi Network

### ParaID

4177

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[4177-genesis-head.txt](https://github.com/paritytech/subport/files/10109379/4177-genesis-head.txt)

### Upload your Validation Code (genesis runtime Wasm)

[4177-genesis-state.txt](https://github.com/paritytech/subport/files/10109375/4177-genesis-state.txt)

### (Optional) Upload your Chain Specification

https://github.com/grindytech/gafi/blob/rococo/resources/rococo-parachain-plain.json

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Short term slot set. Onboarding should happen in the coming rotations
