### ISSUE TITLE
Goldy Bhai

### ISSUE THREAD

**Issue by Anteck-Anuj** [paritytech/subport#506]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Goldy Bhai

### Parachain Name

Goldy

### ParaID

4185

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4185-genesis-state.zip](https://github.com/paritytech/subport/files/10154425/para-4185-genesis-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-4185-wasm.zip](https://github.com/paritytech/subport/files/10154429/para-4185-wasm.zip)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Short-term slot assigned, should upgrade in the next rotation
