### ISSUE TITLE
Acurast Rococo slot request

### ISSUE THREAD

**Issue by godenzim** [paritytech/subport#508]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Acurast

### Parachain Name

Acurast

### ParaID

4191

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4191-genesis.txt](https://github.com/paritytech/subport/files/10225064/para-4191-genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4191-wasm.txt](https://github.com/paritytech/subport/files/10225067/para-4191-wasm.txt)

### Anything else we should know?

We want to start a XCM channel with Rockmine parachain with 1000 paraID

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/8546

**Comment by al3mart** [comment]
Short term slot assigned. Upgrade will happen in the coming rotations
