### ISSUE TITLE
Sequester Rococo Slot Request

### ISSUE THREAD

**Issue by brendanedelson** [paritytech/subport#509]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Sequester

### Parachain Name

Setester

### ParaID

4197

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4197-genesis-state.txt](https://github.com/paritytech/subport/files/10233440/para-4197-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4197-wasm.txt](https://github.com/paritytech/subport/files/10233441/para-4197-wasm.txt)

### Anything else we should know?

We want to start out by opening our first XCM channel with the Bitgreen rococo parachain with paraID 20048. 

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Short-term slot assigned, upgrading will happen in the coming rotations.
