### ISSUE TITLE
Off-chain worker migration from RC4

### ISSUE THREAD

**Issue by spencerbh** [paritytech/subport#51]
Having issues with moving and existing OCW pallet to the current substrate-node-template, im coming from RC4. Pallet compiles fine (doesn't mean much ), but I am lost on placing development keys into the keystore. I see that the docs are due to be updated on issue #776 of the [substrate-developer-hub.github.io](substrate-developer-hub.github.io) , Are there some other docs/examples concerning [`if config.offchain_worker.enabled {`](https://github.com/substrate-developer-hub/substrate-node-template/blob/cbf28f104237648512e8e3b6af2126e840d56243/node/src/service.rs#L106) ? Like how to modify the config in general? Is it via chain_spec.rs ?

**Comment by spencerbh** [comment]
:100: :volcano: thanks to Mr. Dan Forbes + others:
the _easiest_ way to get keys into the keystore is via RPC call -> author_insertKey (for polkadot.js)

for example alice's key and relevant info (for dev purposes): 
```
// keyType --> "demo",
// suri --> "bottom drive obey lake curtain smoke basket hold race lonely fit walk//Alice",
// publicKey --> "0xd43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d"
```
which is sourced from:
`node-template: subkey inspect //Alice` and `node-template: subkey inspect "bottom drive obey lake curtain smoke basket hold race lonely fit walk//Alice"`

previously I had been relying on this cli option [--features ocw](https://github.com/substrate-developer-hub/recipes/blob/cd56c5810df389ef1f7449816002a03afd379c1a/nodes/kitchen-node/src/service.rs#L50)
would be great to implement a similar flag for the current node template.

**Comment by danforbes** [comment]
I'm going to close this Issue, Spencer, but please feel free to reopen it or open a new one if you have more problems/questions.
