### ISSUE TITLE
Ethos Rococo Slot Request

### ISSUE THREAD

**Issue by ashi20192020** [paritytech/subport#512]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Jur

### Parachain Name

Ethos Testnet

### ParaID

2095

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[ethos-genesis.txt](https://github.com/paritytech/subport/files/10328060/ethos-genesis.txt)

### Upload your Validation Code (genesis runtime Wasm)

[ethos--wasm.txt](https://github.com/paritytech/subport/files/10328064/ethos--wasm.txt)

### (Optional) Upload your Chain Specification

[ethosTestnetSpecRaw.json.txt](https://github.com/paritytech/subport/files/10272589/ethosTestnetSpecRaw.json.txt)

### Anything else we should know?

The goal of the Ethos parachain is to provide tools and infrastructure for other parachains to become Network States within the Rococo network. To know more kindly check our official [documentation](https://github.com/jurteam/jur-documentation).

At a later stage, we’ll be integrating XCM channels and functionalities for external parachains to be able to call features on Ethos, for now we want to test them with our community

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/8571

**Comment by 0xlyd** [comment]
Hey @al3mart 👋 is there any way we could speed up the process somehow? We wanted to test our token swap pallet on Rococo but are currently blocked by this 🙏

**Comment by 0xlyd** [comment]
Hey @NukeManDan @gnunicorn can someone take this up? We need to test a couple of pallets with our community and we are blocked otherwise 🙏

**Comment by al3mart** [comment]
Onboarding parathread at the moment, ~1h 10' to go

**Comment by 0xlyd** [comment]
Amazing thanks @al3mart appreciated 🙏

**Comment by al3mart** [comment]
Long-term slot assigned, onboarding happening in ~1h from now.
If any further action is required, please feel free to post a comment in this issue.

**Comment by StefanoFaiola** [comment]
@al3mart Hi,
Jur seems to be currently remove from Rococo, could you please fix this or provide some updates? we can't move our tokens.
