### ISSUE TITLE
Dolphin -> Calamari slot

### ISSUE THREAD

**Issue by ghzlatarev** [paritytech/subport#513]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Manta Network

### Parachain Name

Calamari

### ParaID

2084

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[calamari-state.txt](https://github.com/paritytech/subport/files/10314168/calamari-on-moonbase-state.1.txt)

### Upload your Validation Code (genesis runtime Wasm)

[calamari-wasm.txt](https://github.com/paritytech/subport/files/10314171/calamari-wasm.txt)

### (Optional) Upload your Chain Specification

https://manta-ops.s3.amazonaws.com/calamari-on-moonbase/calamari-on-moonbase-live.json

### Anything else we should know?

We have an existing deployment called Dolphin (2084) that we've stopped using and would like to be offboarded.
Then we want to deploy our Calamari runtime, which is the same as the one we have deployed as a parachain to Kusama.
Mainly to test xcm related functionalities with teams like Astar.

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by SBalaguer** [comment]
Executed on [this block](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/explorer/query/0x8015d85809b60c32b463f3f045a2200842988faf71191db7357a8906da554ac3)
