### ISSUE TITLE
Diora Slot Request

### ISSUE THREAD

**Issue by DappGuy** [paritytech/subport#515]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

DioraDAO

### Parachain Name

Diora Network

### ParaID

4202

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4202-genesis-state.txt](https://github.com/paritytech/subport/files/10359918/para-4202-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4202-wasm.txt](https://github.com/paritytech/subport/files/10359920/para-4202-wasm.txt)

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
short term slot assigned, onboarding should happen in the coming LPs
