### ISSUE TITLE
Offboard/Re-onboard Calamari (2084)

### ISSUE THREAD

**Issue by ghzlatarev** [paritytech/subport#518]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Manta Network

### Parachain Name

Calamari

### ParaID

2084

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[calamari-rococo-state.txt](https://github.com/paritytech/subport/files/10418131/calamari-rococo-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[calamari-rococo-wasm.txt](https://github.com/paritytech/subport/files/10418132/calamari-rococo-wasm.txt)

### (Optional) Upload your Chain Specification

[calamari-rococo.json.txt](https://github.com/paritytech/subport/files/10418135/calamari-rococo.json.txt)

### Anything else we should know?

Hey guys, we recently deployed Calamari, but it seems I gave you guys the wrong state/wasm or there was some other unknown issue. Anyway we want to redeploy with the state/wasm in this PR.
Thanks.

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by SBalaguer** [comment]
This has been executed. [Here's](https://rococo.subscan.io/extrinsic/0x11c6a468ee44495fa5978ee1465aa6ac6cd05f353e449227a8a803d1d9d09c25) the extrinsic. Let me know if anything!

**Comment by ghzlatarev** [comment]
> This has been executed. [Here's](https://rococo.subscan.io/extrinsic/0x11c6a468ee44495fa5978ee1465aa6ac6cd05f353e449227a8a803d1d9d09c25) the extrinsic. Let me know if anything!

Hey sorry about this, but can you re-onboard us again with https://github.com/paritytech/subport/issues/522 ? Thanks.

**Comment by ghzlatarev** [comment]
@SBalaguer bump
