### ISSUE TITLE
Reset bitgreen rococo slot

### ISSUE THREAD

**Issue by abhath-labs** [paritytech/subport#519]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Bitgreen

### Parachain Name

BitgreenRococo

### ParaID

20048

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[bitgreen-para-20048-genesis.zip](https://github.com/paritytech/subport/files/10433384/bitgreen-para-20048-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[bitgreen-para-20048-wasm.zip](https://github.com/paritytech/subport/files/10433386/bitgreen-para-20048-wasm.zip)

### Anything else we should know?

We would like to reset the parachain to this new head and wasm

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by SBalaguer** [comment]
@abhath-labs I see paraID 20048 producing blocks. Do you still need to reset the parachain? You should be able to do a runtime upgrade.

**Comment by SBalaguer** [comment]
Great @abhath-labs! I just executed this, you can find the extrinsic [here](https://rococo.subscan.io/extrinsic/0xcd4c7903461dcc33ed1144debd27b64ca727dede37e474069b6b844949f26a03). Let me know if anything!

**Comment by al3mart** [comment]
This is indeed, related to the dmp head state kept in the relay for that paraId. When not properly cleaned it would hit [this assert](https://github.com/paritytech/cumulus/blob/827394ff81b2b206e2cebbeecc2922de746b842a/pallets/parachain-system/src/lib.rs#L815).
As parachains in rococo change their state quite frequently, we encounter this often.

I have now killed that storage for you, so you should be able to produce blocks now.

**Comment by NicoMorganParity** [comment]
Hello @abhath-labs,
Can you please share with us your Parachain Manager Account.
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.

**Comment by abhath-labs** [comment]
Hey @NM2146 
This is the parachain manager account : 5H3R2XduBHH5uXHaJhYQeFqfFzMJct67xTZq9G7QWP5tNxX4

Could you also please upgrade our chain from parathread to parachain, we would like to test runtime upgrade before mainnet. Let me know if we should open a new issue for this. Thanks 🙏

**Comment by NM2146** [comment]
Hey @abhath-labs Since the new [Paseo testnet](https://github.com/paseo-network) is live it would be a good Idea to migrate over using [this guide](https://github.com/paseo-network/support/blob/main/docs/rococo_migration.md)!

**Comment by SBalaguer** [comment]
@abhath-labs it's also worth mentioning that Rococo now has Coretime integrated, so you can buy a core directly and use it without the need of having any manual onboarding.
