### ISSUE TITLE
2105 can not produce block

### ISSUE THREAD

**Issue by AurevoirXavier** [paritytech/subport#520]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Darwinia Network

### Parachain Name

Pangolin2

### ParaID

2105

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

https://github.com/darwinia-network/darwinia-2.0/releases/tag/pangolin2

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/darwinia-network/darwinia-2.0/releases/tag/pangolin2

### Register your Rococo parachain details for `polkadot-js/apps`

I send a solo to para extrinsic.

And I am using this pallet https://github.com/paritytech/cumulus/tree/master/pallets/solo-to-para.

But our new chain can not produce blocks now.

Everything is tested on rococo-local.

Steps:

1. stop our solo chain
2. make solo chain into a para chain
3. export the new genesis
4. call solo to para in the old para chain
5. start new chain

```rs
  left: `0x0000000000000000000000000000000000000000000000000000000000000000`,
 right: `0xd6ad7c02452ff62b8032b22f0c327a3a81e94f0807a6337336f7cf3397b3b746`', /root/.cargo/git/checkouts/cumulus-59522f43471fa161/27721d7/pallets/parachain-system/src/lib.rs:838:9
2023-01-20 05:19:42 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
2023-01-20 05:19:42 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
2023-01-20 05:19:42 [Parachain] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x47cb92 - <unknown>!rust_begin_unwind
    1: 0x60197 - <unknown>!core::panicking::panic_fmt::h6d1629d4208ae76c
    2: 0x6038b - <unknown>!core::panicking::assert_failed_inner::h5ac4b0a02b282d18
    3: 0x3c8ac9 - <unknown>!core::panicking::assert_failed::hd3a6f090a6f8c889
    4: 0x3207bd - <unknown>!cumulus_pallet_parachain_system::<impl cumulus_pallet_parachain_system::pallet::Pallet<T>>::process_inbound_downward_messages::h57101b69e8a70119
    5: 0x362862 - <unknown>!frame_support::storage::transactional::with_storage_layer::h1517572e712a3942
    6: 0x2f8925 - <unknown>!<cumulus_pallet_parachain_system::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h11b21a934757b390
    7: 0x339dc3 - <unknown>!<pangolin_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h17dd85336fc818ce
    8: 0x33855f - <unknown>!<pangolin_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::h02c2ec8c012bf2d0
    9: 0x174a37 - <unknown>!<fp_self_contained::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra,SelfContainedSignedInfo> as sp_runtime::traits::Applyable>::apply::ha3bb9059905d5c35
   10: 0x3bbb03 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::h398785606cd63602
   11: 0x2d6d8a - <unknown>!BlockBuilder_apply_extrinsic
. Dropping.
2023-01-20 05:19:42 [Parachain] panicked at 'set_validation_data inherent needs to be present in every block!', /root/.cargo/git/checkouts/cumulus-59522f43471fa161/27721d7/pallets/parachain-system/src/lib.rs:192:13
2023-01-20 05:19:42 [Parachain] Proposing failed: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x47cb92 - <unknown>!rust_begin_unwind
    1: 0x60197 - <unknown>!core::panicking::panic_fmt::h6d1629d4208ae76c
    2: 0x31487b - <unknown>!<cumulus_pallet_parachain_system::pallet::Pallet<T> as frame_support::traits::hooks::OnFinalize<<T as frame_system::pallet::Config>::BlockNumber>>::on_finalize::h17000c5b8e5a9489
    3: 0x2ccc8f - <unknown>!<(TupleElement0,TupleElement1,TupleElement2,TupleElement3,TupleElement4,TupleElement5,TupleElement6,TupleElement7,TupleElement8,TupleElement9,TupleElement10,TupleElement11,TupleElement12,TupleElement13,TupleElement14,TupleElement15,TupleElement16,TupleElement17,TupleElement18,TupleElement19,TupleElement20,TupleElement21,TupleElement22,TupleElement23,TupleElement24,TupleElement25,TupleElement26,TupleElement27,TupleElement28,TupleElement29,TupleElement30,TupleElement31,TupleElement32,TupleElement33,TupleElement34,TupleElement35,TupleElement36,TupleElement37) as frame_support::traits::hooks::OnFinalize<BlockNumber>>::on_finalize::h40843a262860392c
    4: 0x3bbea0 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::h0ce0bc5ded98c1eb
    5: 0x3bbfef - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::finalize_block::h9318a9a9cad6485f
    6: 0x2d6e54 - <unknown>!BlockBuilder_finalize_block
 ```

**Comment by AurevoirXavier** [comment]
> @AurevoirXavier would you need to reset the genesis and wasm?

Yes.

But the most important thing is why it failed.

Could you help us to analyze this?

Because we are going to perform this on Kusama.

**Comment by al3mart** [comment]
Right, let me answer on the linked issue :+1:

**Comment by AurevoirXavier** [comment]
> I have now killed that storage for you, so you should be able to produce blocks now.

Thanks! That error is gone.

But we got a new error.

```rs
2023-01-24 01:08:42 [Parachain] panicked at 'assertion failed: cur_head == target_head', /root/.cargo/git/checkouts/cumulus-59522f43471fa161/27721d7/pallets/parachain-system/src/lib.rs:928:13
2023-01-24 01:08:42 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
2023-01-24 01:08:42 [Parachain] 1 storage transactions are left open by the runtime. Those will be rolled back.
2023-01-24 01:08:42 [Parachain] ❗️ Inherent extrinsic returned unexpected error: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x47cb92 - <unknown>!rust_begin_unwind
    1: 0x60197 - <unknown>!core::panicking::panic_fmt::h6d1629d4208ae76c
    2: 0x601e0 - <unknown>!core::panicking::panic::h8cc1c9e390838020
    3: 0x321085 - <unknown>!cumulus_pallet_parachain_system::<impl cumulus_pallet_parachain_system::pallet::Pallet<T>>::process_inbound_horizontal_messages::h64b8492611d15950
    4: 0x3628bb - <unknown>!frame_support::storage::transactional::with_storage_layer::h1517572e712a3942
    5: 0x2f8925 - <unknown>!<cumulus_pallet_parachain_system::pallet::Call<T> as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h11b21a934757b390
    6: 0x339dc3 - <unknown>!<pangolin_runtime::RuntimeCall as frame_support::traits::dispatch::UnfilteredDispatchable>::dispatch_bypass_filter::h17dd85336fc818ce
    7: 0x33855f - <unknown>!<pangolin_runtime::RuntimeCall as sp_runtime::traits::Dispatchable>::dispatch::h02c2ec8c012bf2d0
    8: 0x174a37 - <unknown>!<fp_self_contained::checked_extrinsic::CheckedExtrinsic<AccountId,Call,Extra,SelfContainedSignedInfo> as sp_runtime::traits::Applyable>::apply::ha3bb9059905d5c35
    9: 0x3bbb03 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::apply_extrinsic::h398785606cd63602
   10: 0x2d6d8a - <unknown>!BlockBuilder_apply_extrinsic
. Dropping.
2023-01-24 01:08:42 [Parachain] panicked at 'set_validation_data inherent needs to be present in every block!', /root/.cargo/git/checkouts/cumulus-59522f43471fa161/27721d7/pallets/parachain-system/src/lib.rs:192:13
2023-01-24 01:08:42 [Parachain] Proposing failed: Import failed: Error at calling runtime api: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x47cb92 - <unknown>!rust_begin_unwind
    1: 0x60197 - <unknown>!core::panicking::panic_fmt::h6d1629d4208ae76c
    2: 0x31487b - <unknown>!<cumulus_pallet_parachain_system::pallet::Pallet<T> as frame_support::traits::hooks::OnFinalize<<T as frame_system::pallet::Config>::BlockNumber>>::on_finalize::h17000c5b8e5a9489
    3: 0x2ccc8f - <unknown>!<(TupleElement0,TupleElement1,TupleElement2,TupleElement3,TupleElement4,TupleElement5,TupleElement6,TupleElement7,TupleElement8,TupleElement9,TupleElement10,TupleElement11,TupleElement12,TupleElement13,TupleElement14,TupleElement15,TupleElement16,TupleElement17,TupleElement18,TupleElement19,TupleElement20,TupleElement21,TupleElement22,TupleElement23,TupleElement24,TupleElement25,TupleElement26,TupleElement27,TupleElement28,TupleElement29,TupleElement30,TupleElement31,TupleElement32,TupleElement33,TupleElement34,TupleElement35,TupleElement36,TupleElement37) as frame_support::traits::hooks::OnFinalize<BlockNumber>>::on_finalize::h40843a262860392c
    4: 0x3bbea0 - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::idle_and_finalize_hook::h0ce0bc5ded98c1eb
    5: 0x3bbfef - <unknown>!frame_executive::Executive<System,Block,Context,UnsignedValidator,AllPalletsWithSystem,COnRuntimeUpgrade>::finalize_block::h9318a9a9cad6485f
    6: 0x2d6e54 - <unknown>!BlockBuilder_finalize_block
```

**Comment by al3mart** [comment]
Right, this is an interesting issue.
Though, with the very same roots than the previous one, some mismatch in state between the relay and the para because the new state the para has been "forced" to without mutating the corresponding relay state.

In this case the values triggering the [assertion failure ](https://github.com/paritytech/cumulus/blob/827394ff81b2b206e2cebbeecc2922de746b842a/pallets/parachain-system/src/lib.rs#L905)are `mqc_head` for hrmp channels.
This value is present in the struct [`HrmpChannel`](https://github.com/paritytech/polkadot/blob/7129e9bdba2c82e4b173f567b5d6a3c3f7191782/runtime/parachains/src/hrmp.rs#L118), maintained in storage within the map [`HrmpChannels`](https://github.com/paritytech/polkadot/blob/7129e9bdba2c82e4b173f567b5d6a3c3f7191782/runtime/parachains/src/hrmp.rs#L378).
At the same time, the parachain keeps `[LastHrmpMqcHeads](https://github.com/paritytech/cumulus/blob/aa300bd85999e8152908efcaba2d28d61317db87/pallets/parachain-system/src/lib.rs#L597)`. These are the values being compared, and not matching.

To get rid of the panic we could try to mutate the storage accordingly to avoid hitting this. Quite hacky, and not that straight forward. Also, I would like to move away from mutating storage keys by hand.
Another option is closing your hrmp channels, this will effectively clean all the storage for them and there is a "legal" way of doing this, understand there are extrinsics exposed that allow this operation to be made with the proper warranties.
Of course the channels could be open again immediately from our side after closing them, once we see your chain is producing blocks again.
The channels open right now are
```
2000 -> 2105
2105 -> 2000
2012 -> 2105
2105 -> 2012
```

So if this is not a burden for you, I would like to proceed closing and cleaning the channels and opening this again.

**Comment by AurevoirXavier** [comment]
> So if this is not a burden for you, I would like to proceed closing and cleaning the channels and opening this again.

Thanks! It's totally fine. Please do that.

So, we should close our HRMP channels first, then call the solo to para on Kusama. Right?

**Comment by al3mart** [comment]
Those are a bunch.

The following is something I need to research and test a bit first, but ideally everything would be sorted out if you could have some the same state in `LastHrmpMqcHeads` in your para than what the relay will be sharing.
This would imply forcing some genesis state for parachain-system pallet to set these values, but the genesis config for this pallet doesn't allow that. As this scenario is not something usual.
Then, and this is what I would like to very, if there is a way to include some arbitrary key:value pair in the chainspec, without having to modify the chain_spec.rs logic.

**Comment by al3mart** [comment]
btw, channels are now cleaned :+1:

**Comment by AurevoirXavier** [comment]
> This would imply forcing some genesis state for parachain-system pallet to set these values, but the genesis config for this pallet doesn't allow that.

We have this tool. We can preset any genesis data if necessary.

https://github.com/darwinia-network/darwinia-2.0/blob/main/tool/state-processor/src/main.rs

**Comment by AurevoirXavier** [comment]
> The following is something I need to research and test a bit first

Thanks. This issue is solved. 

But I think maybe we could discuss/track this somewhere.

**Comment by al3mart** [comment]
Do you mean the issue itself, if that's the case we very well could create a SE post.

**Comment by AurevoirXavier** [comment]
> Do you mean the issue itself, if that's the case we very well could create a SE post.

Sorry for the late response.

I mean, maybe we should add these on the pallet-solo-to-para README/guide.

**Comment by AurevoirXavier** [comment]
This could be a guide https://github.com/darwinia-network/darwinia-2.0/pull/278 for future people.

**Comment by AurevoirXavier** [comment]
Hi @al3mart! Can you share what storage did you clean last time?

> This is indeed, related to the dmp head state kept in the relay for that paraId. When not properly cleaned it would hit [this assert](https://github.com/paritytech/cumulus/blob/827394ff81b2b206e2cebbeecc2922de746b842a/pallets/parachain-system/src/lib.rs#L815). As parachains in rococo change their state quite frequently, we encounter this often.
> 
> I have now killed that storage for you, so you should be able to produce blocks now.

This one, the first cleaning.

---

Recently I online our second parachain. And we preset the `LastDmqMqcHead` and `LastHrmpMqcHeads` correctly.

But we still got the `set_validation_data inherent needs to be present in every block!`.

Is there any other storage we missed?

Thanks!
