### ISSUE TITLE
Offboard/Re-onboard Calamari (2084)

### ISSUE THREAD

**Issue by ghzlatarev** [paritytech/subport#522]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Manta Network

### Parachain Name

Calamari

### ParaID

2084

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[calamari-rococo-state-401.txt](https://github.com/paritytech/subport/files/10495115/calamari-rococo-state-401.txt)

### Upload your Validation Code (genesis runtime Wasm)

[calamari-rococo-wasm-401.txt](https://github.com/paritytech/subport/files/10495116/calamari-rococo-wasm-401.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by ghzlatarev** [comment]
@SBalaguer bump

**Comment by al3mart** [comment]
All set.

**Comment by NicoMorganParity** [comment]
Hello @ghzlatarev,
I know you have ParaID 9999 aswell but can you provide a Parachain Manager Account for this Rococo chain aswell? Thanks!

**Comment by ghzlatarev** [comment]
How do I check if I already used some account ?
Otherwise I would like to use this one `5EFHTWLstvwzuMZmZarpQxHGARDkma8zYCyssp1HXQEJKRYi`
