### ISSUE TITLE
Requesting encointer-parachain upgrade to v13

### ISSUE THREAD

**Issue by clangenb** [paritytech/subport#523]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Encointer Association

### Parachain Name

Encointer Litaer

### ParaID

1003

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

1

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/encointer/encointer-parachain/releases/download/1.3.3/encointer_runtime-v13.compact.compressed.wasm

### Anything else we should know?

Again, as a common good parachain, we can't do this on our own. :)

There is no particular hurry with this upgrade.

**Comment by al3mart** [comment]
Hey, the new runtime will be enacted at relay block#3,944,809
