### ISSUE TITLE
Reset bifrost rococo slot (2030)

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/subport#524]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Liebi Technologies

### Parachain Name

Bifrost K Rococo

### ParaID

2030

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[bifrost-kusama-rococo.genesis.zip](https://github.com/paritytech/subport/files/10529984/bifrost-kusama-rococo.genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[bifrost-kusama-rococo.wasm.zip](https://github.com/paritytech/subport/files/10529986/bifrost-kusama-rococo.wasm.zip)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed

**Comment by hqwangningbo** [comment]
@al3mart Can you help us to implement these two methods, because there is another problem with the last upgrade block.

<img width="896" alt="image" src="https://user-images.githubusercontent.com/57781136/215333589-49c9d7aa-5a1d-4d87-8247-667be2a7b296.png">

**Comment by al3mart** [comment]
New code and state set

**Comment by hqwangningbo** [comment]
@al3mart Bifrost is still in the state of parathread, can you help us become a parachain, thank you

**Comment by al3mart** [comment]
slot assigned again
