### ISSUE TITLE
Rococo slot for Robonomics

### ISSUE THREAD

**Issue by dergudzon** [paritytech/subport#525]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Robonomics.network

### Parachain Name

Robonomics.network

### ParaID

4219

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[genesis-state-paraid-4219.txt](https://github.com/paritytech/subport/files/10533769/genesis-state-paraid-4219.txt)

### Upload your Validation Code (genesis runtime Wasm)

[genesis-wasm-paraid-4219.txt](https://github.com/paritytech/subport/files/10533770/genesis-wasm-paraid-4219.txt)

### (Optional) Upload your Chain Specification

[alpha-spec-raw-4219.json.txt](https://github.com/paritytech/subport/files/10533780/alpha-spec-raw-4219.json.txt)

### Anything else we should know?

We want to start a XCM channel with Basilisk parachain with 2090 paraID

Actually, we can use 2048 paraId, but then we need to completely restart it. 
Previous attempt to do it was unsuccessful, unfortunately. I think it because in previous attemt we didn't use ParaCleanup for paraid 2048.
So we can try to do it one more time, but than I need to send another genesis, wasm and spec. 

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Short term slot assigned, onboarding should happen in the coming LP

**Comment by dergudzon** [comment]
Hey, @al3mart! How can I see, paraId 4219 become a parathread.
Can you continue lease for it? We just didn't have time to test everything. 
I think we need one week at least.

**Comment by al3mart** [comment]
Hey, I can see your last LP was assigned 10 days ago, from the moment of writing.
It is true that for some scenarios 3 LPs might be a bit tight, also not the first team that points this out, let me assign your paraId a slot for a week, though consider this an exception, as every team should run with the same rules :)

Hopefully we would be able to tweak the parameters of the pallet in charge of this assignments so they are a bit more fitting.

**Comment by NicoMorganParity** [comment]
Hello @dergudzon,
Can you please share with us your Parachain Manager Account.
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.
