### ISSUE TITLE
Reset webb parachain slot

### ISSUE THREAD

**Issue by 1xstj** [paritytech/subport#526]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Webb

### Parachain Name

Tangle Rococo

### ParaID

4006

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[tangle-genesis-state.zip](https://github.com/paritytech/subport/files/10555086/tangle-genesis-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[tangle-genesis-wasm.zip](https://github.com/paritytech/subport/files/10555088/tangle-genesis-wasm.zip)

### Anything else we should know?

We would like to reset the state and wasm for our parachain slot at 4006. Thanks

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
wasm and state set!
