### ISSUE TITLE
Sequester Rococo Parachain Head Reset

### ISSUE THREAD

**Issue by zedelson** [paritytech/subport#527]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Sequester

### Parachain Name

Setester

### ParaID

4197

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4197-genesis-state.txt](https://github.com/paritytech/subport/files/10575505/para-4197-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4197-wasm.txt](https://github.com/paritytech/subport/files/10575506/para-4197-wasm.txt)

### Anything else we should know?

We need to use sudo to reset our parachain head & chainspec. 

When launching our parachain collators, we ran into [this collation issue](https://github.com/sora-xor/sora2-parachain/issues/59), stopped producing blocks, and then we lost access to the archived chain state. Thus, we would like to fully reset the parachain to the genesis state, and which point we will relaunch the collators.

I have attached the updated validation code and genesis head here for our chain post updating to v0.9.37 (which fixed the issue), and we have tested on rococo local

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
all set up
