### ISSUE TITLE
Reset the Sora parachain on Rococo

### ISSUE THREAD

**Issue by N1ghtStorm** [paritytech/subport#529]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Soramitsu

### Parachain Name

SORA

### ParaID

2011

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[para-rococo-v2-genesis.zip](https://github.com/paritytech/subport/files/10662916/para-rococo-v2-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-rococo-v2-wasm.zip](https://github.com/paritytech/subport/files/10662920/para-rococo-v2-wasm.zip)

### (Optional) Upload your Chain Specification

[sora_rococo-parachain-v2-raw.json.zip](https://github.com/paritytech/subport/files/10662928/sora_rococo-parachain-v2-raw.json.zip)

### Anything else we should know?

Is it possible to start a XCM  HRMP channel with Rockmine Parachain with ParaId 1000

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by AlexD10S** [comment]
Upgrading from parathread to parachain ~ 1h10' from now
