### ISSUE TITLE
Error sending kusama: "txn version not supported" Jan-2023

### ISSUE THREAD

**Issue by Juliodimain** [paritytech/subport#530]
Hi, when I try to send kusamas via ledger on https://polkadot.js.org/apps, appears again the old error "txn versión not supported"

Ledger nano X: firmware 2.0.2
Ledger live: 2.52.0
Kusama app on ledger: v18.9350.1

I try using chrome and brave on last version on windows 10 pro 22h2 and on android 13
Reinstalling kusama app on ledger.
With and without the browser extension.
With and without keep-alive checks. 

Always the same error.

The account was create on 13 of decembre of 2022.

Thanks in advance for your support

**Comment by al3mart** [comment]
This seems like you would need to update the metadata being used. Meaning there has been a runtime upgrade that changes how txns are encoded, and you are trying to encode yours using an old version.

This kind of support is way better sorted out in: https://support.polkadot.network/support/home
And also, have a look at this wiki entry, as you might find it useful: https://wiki.polkadot.network/docs/kusama-statemine-ledger#support
