### ISSUE TITLE
Reset Tinkernet rococo parachain (2125)

### ISSUE THREAD

**Issue by arrudagates** [paritytech/subport#532]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

InvArch

### Parachain Name

Tinkernet Rococo

### ParaID

2125

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[genesis-state-3.txt](https://github.com/paritytech/subport/files/10708284/genesis-state-3.txt)

### Upload your Validation Code (genesis runtime Wasm)

[genesis-wasm-3.txt](https://github.com/paritytech/subport/files/10708286/genesis-wasm-3.txt)

### Anything else we should know?

The database for the rococo parachain got corrupted, so I need it to be reset starting from genesis again.

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Slot assigned!
