### ISSUE TITLE
Add Idiyanale to Rococo -- 4222

### ISSUE THREAD

**Issue by woss** [paritytech/subport#533]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Anagolay Network

### Parachain Name

Idiyanale Rococo

### ParaID

4222

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-genesis-4222.txt](https://github.com/paritytech/subport/files/10715871/para-genesis-4222.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-wasm-4222.txt](https://github.com/paritytech/subport/files/10715873/para-wasm-4222.txt)

### (Optional) Upload your Chain Specification

[idiyanale-parachain-raw-4222.json.txt](https://github.com/paritytech/subport/files/10715874/idiyanale-parachain-raw-4222.json.txt)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here:  https://github.com/polkadot-js/apps/pull/9000

**Comment by al3mart** [comment]
Short-term slot has been assigned. Onboarding should happen in the coming rotation.

**Comment by woss** [comment]
spec_version: `117` 

[idiyanale-parachain-raw-4222.json.txt](https://github.com/paritytech/subport/files/10785697/idiyanale-parachain-raw-4222.json.txt)
[para-genesis-4222.txt](https://github.com/paritytech/subport/files/10785695/para-genesis-4222.txt)
[para-wasm-4222.txt](https://github.com/paritytech/subport/files/10785696/para-wasm-4222.txt)

**Comment by al3mart** [comment]
All set!

**Comment by woss** [comment]
Update requested:
spec_version: 117
reason: after 2  weeks of trying to figure out these files work on rococo-local

[state-4222.txt](https://github.com/paritytech/subport/files/10873726/state-4222.txt)
[wasm-4222.txt](https://github.com/paritytech/subport/files/10873727/wasm-4222.txt)
