### ISSUE TITLE
Rococo Request Slot for parachain 4231

### ISSUE THREAD

**Issue by lorks** [paritytech/subport#536]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Individual

### Parachain Name

Prototest

### ParaID

4231

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4231-genesis-state.txt](https://github.com/paritytech/subport/files/10733046/para-4231-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[para-4231-wasm.txt](https://github.com/paritytech/subport/files/10733048/para-4231-wasm.txt)

### (Optional) Upload your Chain Specification

[plain-parachain-chainspec.json.txt](https://github.com/paritytech/subport/files/10733051/plain-parachain-chainspec.json.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Short term slot has been assigned. Upgrade to parachain should happen in the comming LP.
