### ISSUE TITLE
Reset GIANT parachain (4227)

### ISSUE THREAD

**Issue by ToufeeqP** [paritytech/subport#538]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

GIANT protocol

### Parachain Name

GIANT Testnet

### ParaID

4227

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[genesis state](https://drive.google.com/file/d/1t6A-0OD_7auBw_Rp6HZlBMphLi4eavX_/view?usp=share_link)

### Upload your Validation Code (genesis runtime Wasm)

[STF](https://drive.google.com/file/d/1vlweqLYnJtzaaMDk6vS0ErtUBIe7Qx9P/view?usp=share_link)

### Anything else we should know?

Our collator database got corrupted due to a storage issue so we had to restart the new collators, can you please reset it ASAP?

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available [here:](https://github.com/polkadot-js/apps/pull/9034)

**Comment by ToufeeqP** [comment]
@al3mart Can you please look into this?

**Comment by al3mart** [comment]
Oh, I did the whole onboarding at this Monday and forgot to update the issue, sorry. I could assign a few LPs extra in exchange  for this :)

**Comment by ToufeeqP** [comment]
@al3mart Have you already reset our parachain?

**Comment by al3mart** [comment]
State and wasm set again :+1:

**Comment by ToufeeqP** [comment]
Thanks, it is working fine now

**Comment by ToufeeqP** [comment]
@al3mart we're facing one issue, we're unable to produce new blocks, it's throwing the `Discarding slot xxx, block production took too long`. It is happening because some operation(s) is happening on the on_initialize hook, which might take more weight than expected. However, with the same code, our solo chain seems to work fine. Is there any way you can think of to mitigate this issue? if not can you please reset it once again so that we can update our runtime to use the on_idle hook instead of on_initialize?
