### ISSUE TITLE
Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature"

### ISSUE THREAD

**Issue by qaibeibei** [paritytech/subport#54]
I didn't move anything  ，It's wrong to use it today
https://polkadot.js.org/apps/

1002: Verification Error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature"): RuntimeApi, Execution failed: ApiError, \"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiSignature\

**Comment by danforbes** [comment]
You probably need to add types https://polkadot.js.org/docs/api/FAQ#the-node-returns-a-could-not-convert-error-on-send

**Comment by danforbes** [comment]
@qaibeibei are you still stuck on this? If so, can you please provide an update? If not, please close this Issue :pray:

**Comment by danforbes** [comment]
Closing due to lack of inactivity. Please feel free to reopen this Issue or create a new one if you're still having problems.
