### ISSUE TITLE
[Relaychain] core is not assigned to our para. Keep going.

### ISSUE THREAD

**Issue by woss** [paritytech/subport#541]
I'm having this issue when trying to get my parachain to produce blocks.

Here is the link with the spec, and docker-compose that i am using to start the chain https://gitlab.com/anagolay/collators

Here is the [polkadotjs](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo.rpc.idiyanale.anagolay.io#/chainstate) link
```sh
TRACE tokio-runtime-worker parachain::collation-generation: [Relaychain] core is not assigned to our para. Keep going. core_idx=30 relay_parent=0x6fef350e93a4e3535de908fd9b8f010d4e97486c36d91dfb39886221357ac1f0 our_para=4222 their_para=2119
```
The full error is here
![image](https://user-images.githubusercontent.com/80440/221579512-2021e4df-83f6-4116-80c0-f95937f42747.png)

Please let me know if you need anything from me to solve this issue :)

**Comment by bkchr** [comment]
The logs you are showing are not any errors.

**Comment by woss** [comment]
right, so it's a TRACE of an issue that is preventing the parachain to produce blocks. in my opinion, that is an error, but probably not an error from the substrate point of view.

@bkchr do you know any solution for this? or where is the problem?

**Comment by samelamin** [comment]
@woss those are not errors, the trace is just telling you the core is not assigned to your parachain, but if you are a parachain there will be cores assigned to it 


Out of interest, it doesnt look like the parachain has any peers? are you using `--force-authoring`? becuase if not then you need a network of nodes to actually produce blocks

also ensure you have the aura keys added to the session

There could be a variety of reasons you are not producing blocks and unfortunatly the logs you attached are not enough to identify the issue

**Comment by al3mart** [comment]
@woss should we close this issue ?

**Comment by woss** [comment]
let's keep it open until we get the idiyanale working on rococo. i have this pinned to my notifications so no worries that it will stay open
