### ISSUE TITLE
Reset Dali Parachain for Picasso Parachain

### ISSUE THREAD

**Issue by andyjsbell** [paritytech/subport#543]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Composable Finance

### Parachain Name

Picasso

### ParaID

2087

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[picasso-rococo-genesis-state.zip](https://github.com/paritytech/subport/files/10875145/picasso-rococo-genesis-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[picasso-rococo-wasm.zip](https://github.com/paritytech/subport/files/10875148/picasso-rococo-wasm.zip)

### (Optional) Upload your Chain Specification

[picasso-rococo-raw.zip](https://github.com/paritytech/subport/files/10875160/picasso-rococo-raw.zip)

### Anything else we should know?

We currently have our Dali runtime on Rococo and would like to replace this with our Picasso runtime on Rococo.

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by andyjsbell** [comment]
@al3mart Are you able to look at this please?

**Comment by SBalaguer** [comment]
@andyjsbell what account should be the owner of this parachian? I need to force register it.

**Comment by andyjsbell** [comment]
@SBalaguer try this `5EyK95UCZaWbD3YUvvQKgaSYeP9L6rhd6ddi25xLt3crPCBX` one 👍 
Thanks!

**Comment by al3mart** [comment]
Upgrading to parachain again, 2h to go from the moment of writing

**Comment by al3mart** [comment]
Alright, you are all set up again!
