### ISSUE TITLE
Calamari

### ISSUE THREAD

**Issue by ghzlatarev** [paritytech/subport#547]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Calamari Network

### Parachain Name

Calamari

### ParaID

9999

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[calamari-rococo-state.txt](https://github.com/paritytech/subport/files/10990058/calamari-rococo-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[calamari-rococo-wasm.txt](https://github.com/paritytech/subport/files/10990060/calamari-rococo-wasm.txt)

### Anything else we should know?

Hey guys, our Kusama parachain's ID is 2084, however we initially used this ID for a different runtime which we called Dolphin. Now I tried to redeploy Calamari using the 2084 id, however I'm hitting a strange error on startup, that I have not been able to debug. And I'm suspecting there's some uncleaned state from the old 2084 parachain. I've actually encountered this problem on our own internal relay chain, and back then the solutions I had found were to either restart the relay chain (not possible in this case) or deploy the parachain with a different id - 9999.
Is it possible to do so ? It is fairly critical in order to get some testing done with Astar network.

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding parathread

**Comment by al3mart** [comment]
Slot has been assigned now, upgrade happening in around 2h form now.

**Comment by NicoMorganParity** [comment]
Hello @ghzlatarev,
Can you please share with us your Parachain Manager Account.
A Rococo account that would be set as the manager for this parachain. You might have already set one if you have registered the parachain on your own, please use the same account. This will allow you to have better control and flexibility in managing your Para.

**Comment by NM2146** [comment]
Hey @ghzlatarev If you check `registrar.paras` you can see the account registered for both your slots

**Comment by ghzlatarev** [comment]
Ok so 2084 doesn't have a manager so please use `5EFHTWLstvwzuMZmZarpQxHGARDkma8zYCyssp1HXQEJKRYi`
9999 was created with this address already.
