### ISSUE TITLE
Reset doesn't seem to take effect

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/subport#548]
![image](https://user-images.githubusercontent.com/57781136/226396984-a145f6ea-2f17-4f38-8e6d-74aa2b12fe41.png)

Because some data on the relay chain has not been cleared
As a result, our collector nodes have been reporting errors and not producing blocks

![image](https://user-images.githubusercontent.com/57781136/226397189-58ed976f-c468-456b-a876-761a73d45c7b.png)

Can you help us set it up again, the relevant files are in this issue. https://github.com/paritytech/subport/issues/524

**Comment by hqwangningbo** [comment]
@bkchr @al3mart

**Comment by al3mart** [comment]
Let me review the whole scenario again, I remember talking with @hqwangningbo some time ago about this.
I'll be back to you shortly.

**Comment by al3mart** [comment]
Alright, so

Just a summary on your never ending upgrading state.
At this moment the relay maintains the following state for your para related to the upgrade:

- `UpgradeGoAheadSignal`
- `FutureCodeUpgrades`
- `FutureCodeHash`

`UpgradeGoAheadSignal` is what is signaling to your parachain that you are ok to apply the new validation function, and this entry in the relay chain storage will be removed once the new parachain block is final, if I have understood everything correctly.

As you are running something completely different at the moment that nothing has to do with this upgrade the only thing I can think off to get you sorted is cleaning this entries. At the same time I would like to avoid as much as possible killing keys by hand, so ideally, what we would be looking for here is a complete offboarding of your parachain, that will execute all the "cleaning" logic [here](https://github.com/paritytech/polkadot/blob/31dde2d25de02965c0c223c7586e555b7f45b877/runtime/parachains/src/paras/mod.rs#L1228).

Unfortunately, as you have a pending upgrade (point of view of the relay) no legal actions can be taken to move the life cycle of your para from `Parachain` to `OffboardingParachain`, as this pending upgrade is reason enough to forbid this change.

So, what I propose is the following:

- Mutate by hand the lifecycle storage key for your parachain to `OffboardingParachain`.
- - key: `0xcd710b30bd2eab0352ddcc26417aa194281e0bfde17b36573208a06cb5cfba6b81004131e62a7368ee070000`
- - value: `0x06` 

- Then, execute `paras.forceQueueAction(2030)` to trigger [`apply_actions_queue`](https://github.com/paritytech/polkadot/blob/31dde2d25de02965c0c223c7586e555b7f45b877/runtime/parachains/src/paras/mod.rs#L1202) and get a legal offboarding, after which, we could onboard you again from scratch.

As this involves mutating keys by hand, I rather be cautious and only proceed if @bkchr is positive that this won't have any side effects on the network or other parachains. I have review the scenario, and done these steps locally a couple of times checking that  everything keeps in shape, but I would be more comfortable after a double check.

**Comment by bkchr** [comment]
Can you not just clean `PvfActiveVoteList` and `PvfActiveVoteMap`?

**Comment by al3mart** [comment]
Well, at the moment those two keys are empty in Rococo.
![image](https://user-images.githubusercontent.com/11448715/229104408-5cd57c2b-5bb7-4eae-bdc8-339523a461d4.png)
I guess pre-checking voting already happened for that upgrade, but I might be lacking some details around the whole pre-checking. Though, it seems I cannot proceed this way.

**Comment by bkchr** [comment]
https://github.com/paritytech/polkadot/blob/40974fb99c86f5c341105b7db53c7aa0df707d66/runtime/common/src/paras_sudo_wrapper.rs#L89 so this is not working? But why?

**Comment by hqwangningbo** [comment]
@al3mart Can sudo_schedule_para_cleanup be executed ? I think this method can delete these information.

**Comment by hqwangningbo** [comment]
@bkchr Please ask a question, we have no problem to test the runtime upgrade locally, but using the online rococo environment to upgrade will always get stuck and the page keeps showing "upgrading", this has happened twice. What is the reason for this, do you understand?
<img width="1273" alt="image" src="https://user-images.githubusercontent.com/57781136/229125751-7c10a787-7d25-4d9d-8eb8-b17b30ce8966.png">

**Comment by al3mart** [comment]
@hqwangningbo I am about to register your parachain again, could you share a Rococo account that you control to set that one as the manager of the parachain ? Thanks

**Comment by hqwangningbo** [comment]
12VZEHGNeJ27kKUu6VsdJV6BBJ4YJfr1ewDxpSLkVqAju8b6

**Comment by hqwangningbo** [comment]
@al3mart thanks,bro

**Comment by al3mart** [comment]
Upgrading parachain now, 1h12' from the moment of writing.

**Comment by al3mart** [comment]
@hqwangningbo Please, let us know if you encounter more related issues.

**Comment by hqwangningbo** [comment]
@al3mart Thank you very much for your work. This issue can be closed. When our code is completed later, we may resubmit the genesis and code, because the newly registered one has become unusable
