### ISSUE TITLE
Quantum Portal Rococo Slot

### ISSUE THREAD

**Issue by 3ierratango** [paritytech/subport#549]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Ferrum

### Parachain Name

Quantum Portal Network

### ParaID

4238

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[genesis-state.zip](https://github.com/paritytech/subport/files/11040394/genesis-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[genesis-wasm.zip](https://github.com/paritytech/subport/files/11040396/genesis-wasm.zip)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by joshuacheong** [comment]
@3ierratango would you be able to take the relevant needed ROC from the faucet found at https://paritytech.github.io/polkadot-testnet-faucet/?

**Comment by al3mart** [comment]
I have just assigned your slot, you should see your para becomes a parachain shortly!
