### ISSUE TITLE
Provide a complete documentation for running the default node(/bin/node) with custom testnet specification. 

### ISSUE THREAD

**Issue by rahul-soshte** [paritytech/subport#55]
I tried copying the command from here https://substrate.dev/docs/en/tutorials/start-a-private-network/ and changing it to suit running https://github.com/paritytech/substrate/tree/master/bin/node. But there is a problem. We dont get the subtleties in making the commands properly. I tried inserting the session keys as mentioned here https://github.com/paritytech/substrate/issues/5078 but still there are lot of issues like where does the stash and controller go for which there is no mention in https://substrate.dev/docs/en/tutorials/start-a-private-network/. @JoshOrndorff  had created a issue for advanced network tutorial but I dont find it anywhere and also that repository is now archived https://github.com/substrate-developer-hub/tutorials/issues/16

**Comment by danforbes** [comment]
Hi, Rahul - do you have a specific question or is this just a general request for more documentation?

**Comment by rahul-soshte** [comment]
What the node-template provides is proof of authority( which happens to be Grandpa + Aura). What I am talking about is https://github.com/paritytech/substrate/bin/node which is not proof of Authority but a PoS network which is a full Substrate Node(Grandpa + Babe) which contains the . So I created a custom testnet specification but the problem is the commands to insert keys into the keystore ( stash + controller + session ) are unclear and how to bond/combine/associate them is unclear even for the initial authorities mentioned in the chain_spec. And also If I wanted to add a node which isn't mentioned in the chain specification, how does it join the network, and validate?

**Comment by NukeManDan** [comment]
@rahul-soshte @is this still a problem? If so, please reopen this issue 🙏🏼 

From what I can tell, there will be much more detailed docs related to parachain operations like https://substrate.dev/cumulus-workshop (this is old at the time of writing, but will be updated) that may help you understand better how to configure a production PoS network. If you have discovered anything useful in the meantime, it would be fantastic if you wouldn't mind sharing insights here for curious others 😁
