### ISSUE TITLE
Energy Web Rococo Slot

### ISSUE THREAD

**Issue by renesy** [paritytech/subport#551]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Energy Web

### Parachain Name

Energy Web Rococo

### ParaID

4237

### Parachain Manager Account

5CfY8x6DZBn7KsgvxZbHHfSjDwxBqsa3cUi6LLLy39qLdToT

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[rococo-genesis.state](https://github.com/paritytech/subport/files/11136277/rococo-genesis.state.txt) (remove .txt extension after download)

### Upload your Validation Code (genesis runtime Wasm)

[parachain_runtime.compact.compressed.wasm](https://github.com/paritytech/subport/files/11136237/parachain_runtime.compact.compressed.wasm.txt) (remove .txt extension after download)

### (Optional) Upload your Chain Specification

[chain-v1.json.txt](https://github.com/paritytech/subport/files/11136229/chain-v1.json.txt) (remove .txt extension after download)

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Registering parathread now as it was not registered previously.

The slot will be assigned once the parathread is registered.

**Comment by al3mart** [comment]
Slot assigned, upgrade should happen shortly.

**Comment by renesy** [comment]
@al3mart Could you please force a reset of the parachain data
We would then like to do a new slot request with different runtime but same paraID

**Comment by al3mart** [comment]
done

**Comment by al3mart** [comment]
Everything is sorted out now, sorry about that.
I have assigned your para a few LPs in exchange for the mess up.

**Comment by renesy** [comment]
@al3mart We would like to get a long term slot. Should I open a new issue for this or continue here?
It seems a registered paraId on Polkadot is a prerequisite for this. How can we make sure to get the same paraId on both relay chains? It looks like the next free paraId is automatically selected but I'd like to reserve the same paraId on Polkadot that we already have here on Rococo.
