### ISSUE TITLE
Rococo slot request for Myriad Social

### ISSUE THREAD

**Issue by irmannmal** [paritytech/subport#554]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Myriad Social

### Parachain Name

Myriad Rococo

### ParaID

4242

### Parachain Manager Account

5HdaTtFK9kYGHLgrBMAKMiHQXF92JX16XBohKSXyvDeWxZTs

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://github.com/myriadsocial/myriad-node-parachain/releases/download/0.0.1/myriad-rococo

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/myriadsocial/myriad-node-parachain/releases/download/0.0.1/myriad-rococo.wasm

### (Optional) Upload your Chain Specification

https://github.com/myriadsocial/myriad-node-parachain/blob/main/node/res/rococo-parachain.json

### Anything else we should know?

-

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
short term slot assigned.
