### ISSUE TITLE
Request for Permanent Slot for July Network

### ISSUE THREAD

**Issue by trinhvanvinh** [paritytech/subport#557]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

July Network

### Parachain Name

July

### ParaID

4245

### Parachain Manager Account

5Ekfio46mz1cWj3bTnGdbt3at8BazEtHeyxuUysNmxLbei3Q

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[july-4245-genesis-state.zip](https://github.com/paritytech/subport/files/11311908/july-4245-genesis-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[july-4245-wasm.zip](https://github.com/paritytech/subport/files/11311915/july-4245-wasm.zip)

### (Optional) Upload your Chain Specification

[raw-parachain-chainspec.json.zip](https://github.com/paritytech/subport/files/11311946/raw-parachain-chainspec.json.zip)

### Anything else we should know?

So... We want to start a XCM channel with July  parachain with all another parachains & relay chain

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by trinhvanvinh** [comment]
@al3mart pls help me

**Comment by trinhvanvinh** [comment]
@al3mart pls help me

**Comment by trinhvanvinh** [comment]
hi @SBalaguer i am using rococo not Kusama or Polkadot. my paraId is 4245. all of information slot on above, thanks

**Comment by SBalaguer** [comment]
Thanks! Then it's a short-term lease, not a long-term one. Given that this is the case, please go ahead and register your parachain information to that paraID so that we can add you to the parachains slots.

You should be using the method `registrar.register` and add to your current paraID the information on the head and wasm of your chain,

<img width="1668" alt="image" src="https://user-images.githubusercontent.com/10047147/236402276-086e665a-b383-4828-81ec-dcd8190bfb10.png">

Thanks!

**Comment by trinhvanvinh** [comment]
hi but,  can i register a slot long-term?. July Network is a parachain long-term. I cannot produce it in short term.

**Comment by trinhvanvinh** [comment]
and, i cannot submit transaction method registrar.register , because i cannot "Owner". I think only account sudo can submit transaction. thanks

**Comment by trinhvanvinh** [comment]
can you send me any type app chat account ? telegram or discord ... I'm waiting lost a lot of time.

**Comment by Wakar473** [comment]
@trinhvanvinh can you explain me more to help you related getting slot on rococo .what is the error? and what you are using sudo or governance for getting slot.

**Comment by Wakar473** [comment]
you can get a slot through  by both pallet sudo or governance.
i am explaining through governance if you do not have a governance pallet simply firstly add governance into your runtime by polkaodot relay chain.
How to add parachain to relay chain  for dynamic amount of lease period that can be increased as per user requirements by governance (slots pallet).

1.   Go to Network UI click on parachains then,

Parathereds>ParaId (Fill parachain ID)> paraThred > (upload para wasm & para genesis state) then click on submit button after onboarding time of parathred it will be added into parathred.

2.  Go to governance UI click on preimage then,

Click on preimage > select account which is same as parachain collator 

account > select “slots” pallet > choose “forceLease(para, leaser, 

amount, periodBegin, periodCount)” > Fill paraId(e.g 2000)> select lease 

account> amount :u128(BalanceOf) > period begin > periodCount > and 

then  copy the preimage hash.

3.  Go to Governance UI click on democracy

Click on “submit proposal” > select the same account which was already selected on the time of submit preimage >  paste preimage hash.

Submit proposal > after submit proposal vote “aye” for yes.

4.  After the minimum epoch period time is completed i.e “3” parathred converted into parachain

5.  Slots pallet provide a facility to add parachain to relay chain for dynamic amount of lease period that can be changed as per user (parachain) requirements and also can increase 2 or more lease period slot at a same time for same parachain.

There is also a way to add more lease period for a same parachain

Flow of lease period – how long the lease period slot is allocated to parachain

NOTE– At Least 3 epoch period taken to add parachain into relay chain by slot pallets.(if the current lease period is 3 and period begin is 10 then it will be added to parachain after 7 epoch time here epoch time and lease period is the same. if not same it will taken dynamic time to add parachain until current lease period becomes 10

If current duration is 8 then it will be added to parachain after 3 epoch duration ie11 lease duration, which means there is 1 loss of slot in parachain as start of duration is 10)

1(i)  If period begin = 10
(ii)  Period count = 100

2(i)  period begin =  200 
(ii)   period count = 300

Then add them
                   10+100 = 110  }
                (Minus 2 minus 1) 
                 200+300 = 500  }
                    
(Parachain got a lease period from 10–108, 200–499)
  
2nd way– adding parachain for single lease period 

If period begin = 27
   Period count = 29
Add → 27+29 = 56
Lease period allotted will be 28 - 54

If current lease period is less than 27 (e.g 1,2,3,4 etc) and it will not cross current lease period of 27 after a period of 3 epochs then the parachain gets a lease period of 28-54 (minus 2 of total sum of period begin and period count).
 hope your understand.if you have query please let my know.

**Comment by SBalaguer** [comment]
Thanks @Wakar473 for the large explanation here. However, Rococo uses the SUDO Pallet so there is no actual governance to vote on.

Still, the first point that you are describing is what we need you @trinhvanvinh to do: you currently hold a paraID, now we need you to register a wasm and genesis to that paraID. If you go to `network > parachains > parathreads` on PolkadotJS and you have the account loaded that holds the paraID, then you'll be able to click on `+ParaThread` that will allow you to add a wasm and genesis to that paraID. With that, then we can upgrade you to a parachain.

<img width="280" alt="image" src="https://user-images.githubusercontent.com/10047147/237018455-51f89ad1-1e58-448d-8acb-eba8a5be11b0.png">

Do let me know if you have more questions about this 🙏

**Comment by al3mart** [comment]
Addressing your request on issue #559 Should we close this one in favor of the other ?

**Comment by SBalaguer** [comment]
Closing in favor of #559. Thanks Ale!

**Comment by Wakar473** [comment]
> Thanks @Wakar473 for the large explanation here. However, Rococo uses the SUDO Pallet so there is no actual governance to vote on.
> 
> Still, the first point that you are describing is what we need you @trinhvanvinh to do: you currently hold a paraID, now we need you to register a wasm and genesis to that paraID. If you go to `network > parachains > parathreads` on PolkadotJS and you have the account loaded that holds the paraID, then you'll be able to click on `+ParaThread` that will allow you to add a wasm and genesis to that paraID. With that, then we can upgrade you to a parachain.
> 
> <img alt="image" width="280" src="https://user-images.githubusercontent.com/10047147/237018455-51f89ad1-1e58-448d-8acb-eba8a5be11b0.png">
> 
> Do let me know if you have more questions about this pray

i mention about governance at first line that if you do not have a governance then firstly integrate a governance pallet into your runtime
and if you have a sudo then it is very easy to add slot through ParasudoWrapper pallet by extrinsics call.
first you need to add parachain by registerd paraid anad then add parathread after onboarding time completed you do the same step which i explain you just before this step(ParasudoWrapper pallet by extrinsics call.)

**Comment by Wakar473** [comment]
> Thanks @Wakar473 for the large explanation here. However, Rococo uses the SUDO Pallet so there is no actual governance to vote on.
> 
> Still, the first point that you are describing is what we need you @trinhvanvinh to do: you currently hold a paraID, now we need you to register a wasm and genesis to that paraID. If you go to `network > parachains > parathreads` on PolkadotJS and you have the account loaded that holds the paraID, then you'll be able to click on `+ParaThread` that will allow you to add a wasm and genesis to that paraID. With that, then we can upgrade you to a parachain.
> 
> <img alt="image" width="280" src="https://user-images.githubusercontent.com/10047147/237018455-51f89ad1-1e58-448d-8acb-eba8a5be11b0.png">
> 
> Do let me know if you have more questions about this pray

you can check through that line is rococo uses governance or not..
[](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/parachains/parathreads
)

**Comment by trinhvanvinh** [comment]
oh oops!!!!. I cannot found my Parathread in Parathreads list.  what happening for my paraId 4245?. 

 Steps::  at column lifecycle when i add files wasm susscess status is "Onboarding", but after some times , it is disapeared on Parathreads list .

 Who can check that problem for me?. 

(I am really want to take a slot parachain only for testnet,
 this is my account telegram: https://t.me/trinhvanvinh ,
 connect with me for support please ) 

Thank you so much.
