### ISSUE TITLE
Permanent slot for Subsocial (update Soonsocial data)

### ISSUE THREAD

**Issue by F3Joule** [paritytech/subport#560]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

DappForce

### Parachain Name

SubsocialX

### ParaID

2100

### Parachain Manager Account

5GjP491LcTa71ZhTBbwp3Eda3xauBX8ESunEsQq3KCQPaz4r

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[soon-2100-state.txt](https://github.com/paritytech/subport/files/11398601/soon-2100-state.txt)

### Upload your Validation Code (genesis runtime Wasm)

[soon-2100-wasm.txt](https://github.com/paritytech/subport/files/11398602/soon-2100-wasm.txt)

### (Optional) Upload your Chain Specification

https://github.com/dappforce/subsocial-parachain/blob/soonsocial/node/res/soonsocial.json

### Anything else we should know?

We want to actively add XCM integrations, starting with opening a channel with Moonbeam (para id 2004).

I can see parathread #2100 with old head and wasm code. We'd like to upgrade those to the specified in this application. Furthermore, it will be great to set a manager account to `5GjP491LcTa71ZhTBbwp3Eda3xauBX8ESunEsQq3KCQPaz4r`.

### Register your Rococo parachain details for `polkadot-js/apps`

- [X] Polkadot-js Apps UI PR completed

**Comment by al3mart** [comment]
You are up now
