### ISSUE TITLE
Societal Rococo Slot Request

### ISSUE THREAD

**Issue by okalenyk** [paritytech/subport#566]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Societal

### Parachain Name

Societal

### ParaID

4253

### Parachain Manager Account

5DyhaP27mcAPQenKkuyHCTLMXVzUq7psMyGpt9m84M35aY8S

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

[para-4253-genesis-state.zip](https://github.com/paritytech/subport/files/11530298/para-4253-genesis-state.zip)

### Upload your Validation Code (genesis runtime Wasm)

[para-4253-wasm.zip](https://github.com/paritytech/subport/files/11530300/para-4253-wasm.zip)

### Anything else we should know?

So... We want to start a XCM channel with Rockmine parachain with 1000 paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

[

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}
](https://github.com/polkadot-js/apps/pull/9477)

**Comment by al3mart** [comment]
Temp slot reassigned, onboarding should happen in the coming LP

**Comment by okalenyk** [comment]
@al3mart Is there a possibility to update genesis/wasm data for the parachain - 4253. Attaching both of them:

[para-4253-genesis-state.zip](https://github.com/paritytech/subport/files/11578725/para-4253-genesis-state.zip)
[para-4253-wasm.zip](https://github.com/paritytech/subport/files/11578727/para-4253-wasm.zip)

P.S. Seems like the `registrar.setCurrentHead()` did work and I see `Starting collation.` in the parachain logs. Looks like updating wasm should be enough.

**Comment by okalenyk** [comment]
Looks like we're producing blocks after adding the aura key to the parachain. Seems like we're good. Thanks a lot!
