### ISSUE TITLE
Slot Renew for Para Id 2006, a permanent slot if available

### ISSUE THREAD

**Issue by ashutoshvarma** [paritytech/subport#567]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Astar

### Parachain Name

RocStar

### ParaID

2006

### Parachain Manager Account

...

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

...

### Upload your Validation Code (genesis runtime Wasm)

...

### Anything else we should know?

Our rococo slot just expired. Can you reassign us a long-term or permanent slot? Thanks.

### Register your Rococo parachain details for `polkadot-js/apps`

Existing parachain.

**Comment by NicoMorganParity** [comment]
Hi @ashutoshvarma Could you also share with us your Parachain Mananger Account please?

**Comment by al3mart** [comment]
Sorted out! I'll be closing the issue but please, feel free to add your para manager account

**Comment by ashutoshvarma** [comment]
Thanks a lot @al3mart !
Can you also set our manager account to the one mentioned below? thanks
Parachain Manager Account (RocStar) - `5H1KCWbGDs5CYBF6f4Tj3E6ziN2Y9on7BrC4mc1ucoT73uUC`
