### ISSUE TITLE
Acurast Rococo Long Term Slot

### ISSUE THREAD

**Issue by godenzim** [paritytech/subport#568]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Acurast Association

### Parachain Name

Acurast Rococo Testnet

### ParaID

2239

### Parachain Manager Account

5FR5q2cEyK2aquPwrJJmVahwpV5AhBgSFtRxxeXtYHkraiMZ

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state)

[acurast-rococo-2239-genesis.zip](https://github.com/paritytech/subport/files/11561658/acurast-rococo-2239-genesis.zip)

### Upload your Validation Code (genesis runtime Wasm)

[acurast-rococo-2239-wasm.zip](https://github.com/paritytech/subport/files/11561665/acurast-rococo-2239-wasm.zip)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: we already did this when we asked for the temporary slot: https://github.com/polkadot-js/apps/pull/8546

**Comment by al3mart** [comment]
Registering parathread now, I'll assigned the slot once that is finished

**Comment by al3mart** [comment]
Slot has been assigned

**Comment by godenzim** [comment]
@al3mart We are experiencing an issue with our nodes: blocks are not produced and they are throwing this error:

```bash
2023-06-07 06:24:18.146 ERROR tokio-runtime-worker runtime: [Parachain] panicked at 'Invalid messaging state in relay chain state proof: DmqMqcHead(Proof)', /Users/godenzim/.cargo/git/checkouts/cumulus-59522f43471fa161/ae4e75b/pallets/parachain-system/src/lib.rs:425:18  
```

the same nodes were able to produce blocks when running locally.

Do you think we are experiencing the same issue as reported in this [other issue](https://github.com/paritytech/subport/issues/414)

**Comment by RomarQ** [comment]
We have figured out the issue. For some reason `parachaininfo > parachainid()` is returning the old id `4191`.

We are looking if it can be fixed on the collator side, if not, we will provide a new state.

**Comment by godenzim** [comment]
Hi @al3mart

We regenerated the genesis head and validation code:

[acurast-rococo-2239-genesis.zip](https://github.com/paritytech/subport/files/11673960/acurast-rococo-2239-genesis.zip)

[acurast-rococo-2239-wasm.zip](https://github.com/paritytech/subport/files/11673961/acurast-rococo-2239-wasm.zip)

Could you please reset them?

**Comment by al3mart** [comment]
Done!

**Comment by RomarQ** [comment]
Hi @al3mart ,

The parachain still has the old genesis:

![image](https://github.com/paritytech/subport/assets/22591718/1f614219-57e3-42ea-a384-3dc740b1121a)

**Comment by RomarQ** [comment]
Yep, in the operation https://rococo.subscan.io/extrinsic/5728448-2 the head is still the old one.

**Comment by al3mart** [comment]
The state and wasm in the [comment above](https://github.com/paritytech/subport/issues/568#issuecomment-1580128649) are the ones meant to be used, right ? 

I can push those again, but I would say these are the ones that were set before.

**Comment by al3mart** [comment]
Looking better now I believe https://rococo.subscan.io/extrinsic/0x3a27fbf96c072d64376d653a5f2a4a9597fd089a7564352ac89ca92e611d69c3

Sorry about that

**Comment by RomarQ** [comment]
Thanks @al3mart! Now I see the blocks being produced.

**Comment by RomarQ** [comment]
Hi @al3mart,

Sorry for disturbing you again.

Yesterday we tried to do a consensus migration from PoA to PoS, which didn't went as planned and the chain got stuck. In the meanwhile we identified the issue and added a fix, which is why I am contacting you, to know if you could do a `paras > forceSetCurrentCode` call with the new wasm. We will use the `codeSubstitutes` field to override the runtime on the collators side.

New wasm:
[acurast-rococo-2239-wasm.zip](https://github.com/paritytech/subport/files/11684852/acurast-rococo-2239-wasm.zip)

Thank you in advance

**Comment by al3mart** [comment]
Wasm set!
