### ISSUE TITLE
Request for a temporary slot on Rococo Testnet

### ISSUE THREAD

**Issue by mohitJukariya** [paritytech/subport#569]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Mohit Jukariya

### Parachain Name

Local Testnet

### ParaID

4256

### Parachain Manager Account

5GeKRGEkEx2oCz5j2e5PodBRq2tUFVTyL6mRrfrcS4baZ4qx

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state)

https://github.com/mohitJukariya/Parachain-Rococo-Polkadot-Local-Testnet/blob/main/para-4105-genesis-state

### Upload your Validation Code (genesis runtime Wasm)

https://github.com/mohitJukariya/Parachain-Rococo-Polkadot-Local-Testnet/blob/main/para-4105-wasm

### (Optional) Upload your Chain Specification

https://github.com/mohitJukariya/Parachain-Rococo-Polkadot-Local-Testnet/blob/main/plain-parachain-chainspec.json

### Anything else we should know?

I want a temporary slot for my "Local Testnet" Parachain on Rococo Testnet. Please assign me the slot as soon as possible.

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Slot has been assigned, you should see your parathread upgrading to parachain shortly
