### ISSUE TITLE
Deriving Polkadot Addresses Based on Bip32-Ed25519

### ISSUE THREAD

**Issue by farukterzioglu** [paritytech/subport#57]
I am trying to implement HD Wallet with C# for polkadot, I already implemented for multiple secp256k1 based crypto currencies. 
I also implemented private key derivation based on Bip32-Ed25519.

With my implementation, anyone can generate Polkadot addresses based on Bip32-Ed25519.

My implementation has the same results with test vectors here;
https://github.com/satoshilabs/slips/blob/master/slip-0010.md#test-vector-1-for-ed25519

I can also confirm that, addresses I generated are same with generated from Subkey with the same private key, if I investigate it with it.

Results from my code;

Address: 5G6tXDeie2KaUgGrwkBfzApKSCm9sE5QvBm1bi1vmBZ4gcCN
Public key: b29b533725c02f6e69d8774c92d8a5a98506c2f09e13a1adbe4db367fbfa512a
Private key: 8bd78fe8b30abf91d3e9474c8927d9874fabc7e31ce2d866cf795378161f954a
Expanded private key: 8bd78fe8b30abf91d3e9474c8927d9874fabc7e31ce2d866cf795378161f954ab29b533725c02f6e69d8774c92d8a5a98506c2f09e13a1adbe4db367fbfa512a

Result from Subkey

subkey inspect 0x8bd78fe8b30abf91d3e9474c8927d9874fabc7e31ce2d866cf795378161f954a --scheme Ed25519
Secret Key URI 0x8bd78fe8b30abf91d3e9474c8927d9874fabc7e31ce2d866cf795378161f954a is account:
Secret seed: 0x8bd78fe8b30abf91d3e9474c8927d9874fabc7e31ce2d866cf795378161f954a
Public key (hex): 0xb29b533725c02f6e69d8774c92d8a5a98506c2f09e13a1adbe4db367fbfa512a
Account ID: 0xb29b533725c02f6e69d8774c92d8a5a98506c2f09e13a1adbe4db367fbfa512a
SS58 Address: 5G6tXDeie2KaUgGrwkBfzApKSCm9sE5QvBm1bi1vmBZ4gcCN
When I investigate the private key from my hd wallet implementation, Subkey prints the same address as I generated.

The problem here that, my implementation is not compatible with official hd wallet implementation which uses path like P//hard//soft (where P is mnemonic)
I rather use a path as m/44/354/0/0/0, to define 0. account's 0. deposit wallet.

The gotcha here is that, from same mnemonic I can't produce the same set of addresses with other available wallets.

I also read that Bip32-Ed25519 may have security flaws. 
I would like to hear your comments about my implementation.

**Comment by farukterzioglu** [comment]
https://github.com/farukterzioglu/HDWallet/blob/master/test/HDWallet.Polkadot.Tests/GeneratePolkadotHDWallet.cs

**Comment by danforbes** [comment]
@farukterzioglu I am shopping this question around internally to see who can help.

**Comment by danforbes** [comment]
A colleague shared this article with me that may shed some light on why we haven't prioritized investigations into Bip32-Ed25519 https://forum.w3f.community/t/key-recovery-attack-on-bip32-ed25519/44

**Comment by farukterzioglu** [comment]
At that article burdges said that,

```
There is no problem because they provide no soft derivation path for ed25519 keys:
“For ed25519 only hardened key generation from Private parent key to private child key is supported.”
```

the library I used, Bip32-Ed25519, also does only hard derivation. I suppose my implementation is also safe to use.

**Comment by joepetrowski** [comment]
> The gotcha here is that, from same mnemonic I can't produce the same set of addresses with other available wallets.

Are you comparing addresses from a root mnemonic in subkey vs. other wallets? Or the problem is with your implementation? Subkey does not use the same mnemonic -> secret key algorithm. See: https://github.com/paritytech/substrate-bip39

**Comment by farukterzioglu** [comment]
I am comparing Subkey derived addresses and my own wallet implementation. 

I can derive private keys from a mnemonic (or from seed) and from those private keys, I am generating addresses. 

If I inspect private keys from Subkey, I see that my privatekey-address pairs are matching with Subkey. 

But since I am using different private key derivation (from mnemonic and path: `m/44'/354'/0'/0'/0'` ) I can't produce same set of  addresses from same mnemonic.

I already used my addresses with Westend and Polkadot and received&spend Dot with those addresses. 
I just wondered what would happen in worse case scenario.

**Comment by NukeManDan** [comment]
@franziskalohl did you ever settle this? If so, please let us know what your solution was. If you do need further support here, please do feel free to re-open this issue! 🙏🏼

**Comment by farukterzioglu** [comment]
Thanks @NukeManDan 
I implemented my own version that not compatible with Subkey.
I am able to generate new addresses and sign transactions but those addresses are not same set with Subkey's
