### ISSUE TITLE
Rococo Contracts faucet not working

### ISSUE THREAD

**Issue by forgetso** [paritytech/subport#572]
Not sure where to put this but the Rococo faucet for the contracts parachain is not working in every location

- element channel
- https://paritytech.github.io/polkadot-testnet-faucet/
- https://use.ink/faucet/

The faucet does work when sending coins to the Rococo relay chain. Have raised this on [stackexchange](https://substrate.stackexchange.com/questions/8805/is-the-rococo-contracts-faucet-broken) as well.

**Comment by al3mart** [comment]
True, it looks like the contracts parachain might need a tweak on its Barriers
![image](https://github.com/paritytech/subport/assets/11448715/54be0dbb-c767-4e72-a4e9-317748fbb42f)

**Comment by forgetso** [comment]
Seems like it's working again.
