### ISSUE TITLE
Request temporary slot for 4273

### ISSUE THREAD

**Issue by evg1605** [paritytech/subport#575]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Radikal-ltd

### Parachain Name

Local Testnet

### ParaID

4273

### Parachain Manager Account

5FBywadDQR9pY172Q5tQxFfh1G7gyst3usS63incfHw11M7j

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[rcc-genstate.txt](https://github.com/paritytech/subport/files/11932174/rcc-genstate.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[rcc-wasm.txt](https://github.com/paritytech/subport/files/11932188/rcc-wasm.txt)

### (Optional) Upload your Chain Specification

[rcc-spec.json.txt](https://github.com/paritytech/subport/files/11932190/rcc-spec.json.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Slot assigned, onboarding should happen in the next rotation
