### ISSUE TITLE
Manta parachain 2104

### ISSUE THREAD

**Issue by ghzlatarev** [paritytech/subport#577]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Manta Network

### Parachain Name

Manta

### ParaID

2104

### Parachain Manager Account

5EFHTWLstvwzuMZmZarpQxHGARDkma8zYCyssp1HXQEJKRYi

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[staging-gensis-state.txt](https://github.com/paritytech/subport/files/11997550/staging-gensis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[staging-genesis-wasm.txt](https://github.com/paritytech/subport/files/11997551/staging-genesis-wasm.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Onboarding parathread

**Comment by al3mart** [comment]
Slot assigned
