### ISSUE TITLE
Polkadex Testnet Onboarding

### ISSUE THREAD

**Issue by zktony** [paritytech/subport#578]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Polkadex

### Parachain Name

kaizen

### ParaID

2040

### Parachain Manager Account

5DqcH6NhjhVKgHRLLUwKrexGu5BHnL5q71LKvD7ZX68bD8fJ

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[para-genesis-2040.zip](https://github.com/paritytech/subport/files/11999114/para-genesis-2040.zip)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[para-wasm-2040.zip](https://github.com/paritytech/subport/files/11999119/para-wasm-2040.zip)

### Anything else we should know?

Could you please offboard and onboard our para chain again with a new genesis file? Also open channel with AssetHub. Thanks

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
Assigned!

**Comment by zktony** [comment]
Hey @al3mart, our collators are not producing blocks:-
```
ul 11 08:08:41 ip-10-211-27-118 parachain-polkadex-node[904512]: 2023-07-11 08:08:41.474  WARN tokio-runtime-worker peerset: [Relaychain] Trying to disconnect unknown peer 12D3KooWKMFQsE9WrFRzjE6p5NLA1zLAUA5s5RFa3CbTesCBdxrG from SetId(3).
Jul 11 08:08:41 ip-10-211-27-118 parachain-polkadex-node[904512]: 2023-07-11 08:08:41.474  WARN tokio-runtime-worker peerset: [Relaychain] Ignoring request to disconnect reserved peer 12D3KooWKMFQsE9WrFRzjE6p5NLA1zLAUA5s5RFa3CbTesCBdxrG from SetId(4).
Jul 11 08:08:42 ip-10-211-27-118 parachain-polkadex-node[904512]: 2023-07-11 08:08:42.487  INFO tokio-runtime-worker substrate: [Relaychain] ✨ Imported #6190303 (0x8141…c5be)
Jul 11 08:08:42 ip-10-211-27-118 parachain-polkadex-node[904512]: 2023-07-11 08:08:42.489  INFO tokio-runtime-worker cumulus-collator: [Parachain] Starting collation. relay_parent=0x814142b5aed697e56aa5d5cfe9c6a5f069b78e69975bd8b2feb0017f049bc5be at=0x094964d84469e64f42c46dac95e6f9e433d2760215ae0f3c796db7c400f06b6d
Jul 11 08:08:46 ip-10-211-27-118 parachain-polkadex-node[904512]: 2023-07-11 08:08:46.217  INFO tokio-runtime-worker substrate: [Relaychain] 💤 Idle (13 peers), best: #6190303 (0x8141…c5be), finalized #6190300 (0x8be6…6131), ⬇ 113.0kiB/s ⬆ 110.2kiB/s
Jul 11 08:08:46 ip-10-211-27-118 parachain-polkadex-node[904512]: 2023-07-11 08:08:46.226  INFO tokio-runtime-worker substrate: [Parachain] 💤 Idle (0 peers), best: #0 (0x0949…6b6d), finalized #0 (0x0949…6b6d), ⬇ 0 ⬆ 0
```
ids of our collator nodes are:-
```
0x4e7b7f176f8778a2dbef829f50466170634e747ab5c5e64cb131c9c5a01d975f
0x325a628e7d7cc3bc98e2e25bd0de7d82eb7126ff7ce7f74978d78f714664fc02
```

**Comment by pavankanteti** [comment]
hey @al3mart - Any updates on the above?

**Comment by al3mart** [comment]
Interesting! It doesn't really seem like any error. We might want to  see logs for longer periods of time, plus those disconnection logs are from the relay side, not your collators.
Review please that you are using the correct chain spec, that your collators have the proper keys set, and that you are running at least two collators if they don't have `--force-authoring` option set.

**Comment by NM2146** [comment]
Hey @pavankanteti @zktony Following up on what @al3mart  said please review your chain spec. We recommend you override it with the latest rococo chainspec. By using `-- --chain chainspec.json` and using this file https://raw.githubusercontent.com/paritytech/polkadot/master/node/service/chain-specs/rococo.json

**Comment by pavankanteti** [comment]
Thanks for the recommendations @al3mart @NM2146. We will try these and get back to you if there are any questions.
