### ISSUE TITLE
Snapshot of Polkadot Node Data

### ISSUE THREAD

**Issue by farukterzioglu** [paritytech/subport#58]
Is there any snapshot of blockchain data for mainnet and Westend, and is it possible to run polkadot node from this snapshots.

Even syncing with Westend takes too much time, I will need to get synced to mainnet too.

**Comment by danforbes** [comment]
Hi @farukterzioglu I wanted to check in on this since I believe you got some guidance from Shawn in our technical chat. Do you have any remaining questions on this topic? Would you care to share any of your findings here so that others may benefit from them?

**Comment by farukterzioglu** [comment]
As I have been told in "Polkadot Validator Lounge",  new bootstrap options are coming. 
But right now only option, I can get the blockchain data from a validator or I can try to sync from scratch with option `--wasm-execution compiled`

Tomorrow I will try to setup and start to sync for mainnet, I will share the time when it got synced.

**Comment by BenWhiteJam** [comment]
also, maybe of interest, there is an open Grant up for providing snapshots:
https://github.com/w3f/Open-Grants-Program/pull/75

**Comment by kianenigma** [comment]
have you looked at substrate-archive? Might be related. cc @insipx

**Comment by NukeManDan** [comment]
https://dotleap.com/how-to-import-a-pre-synced-kusama-database/

Bruno Skvorc of the Web3 Foundation has made something akin to what you need here. He _might_ have further comment on this (will pass him this to look at). Please re-open if you still need support 🙏🏼

**Comment by Swader** [comment]
Hey, yeah, there's a ~40 day old snapshot of Polkadot here: https://app.subsocial.network/@snaps/snapshot-jan-03-2020-572

I recommend just letting it sync in `--wasm-execution compiled` mode if possible though, it's done in like a day. Unless you're using WSL/WSL2, then it's not going to work.
