### ISSUE TITLE
Humidefi-parachain slot request. ParaId 4278

### ISSUE THREAD

**Issue by sankar-boro-zeeve** [paritytech/subport#580]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Humidefi

### Parachain Name

Humidefi

### ParaID

4278

### Parachain Manager Account

5HTnQh3bdaewBsXdKnCpBB5icJQwdFQ1uTaLiipcPH1zVCGD

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

https://drive.google.com/file/d/1IWxQO8oo4tKJHPaNS8V31pctBQaQcU9K/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

https://drive.google.com/file/d/1frn1vFkCndvuUJ_II2_coyNXrLjGqolH/view?usp=sharing

### (Optional) Upload your Chain Specification

https://drive.google.com/file/d/1BJxGB_QSWwC5PBHC9ED7zFQUoa42KH5x/view?usp=sharing

### Anything else we should know?

Humidefi-parachain slot request. ParaId 4278.

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
I have just assigned your slot, onboarding should happen on LP#439 (that would be 21st/7/2023)

**Comment by sankar-boro-zeeve** [comment]
Hi @al3mart We made a genesis file for paraId 4278 using Alice and bob key as collator. But this time we want custom keys on genesis file. Is there any way I can update genesis file from the relay chain? A help would be much appreciated.

I know that we can update genesis using force_set_current_head and force_set_current_code.
