### ISSUE TITLE
Reset Humidefi parachain, ParaId 4278

### ISSUE THREAD

**Issue by sankar-boro-zeeve** [paritytech/subport#581]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Humidefi

### Parachain Name

Humidefi

### ParaID

4278

### Parachain Manager Account

5HBNfF5BWWEfNSzdYeuxcMRM5FmQ7Hx7nKUt9N37jA2v5nSR

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

https://drive.google.com/file/d/19a2DmIyOGiyejsbpf60i2VycWOa6Y4Z9/view?usp=sharing

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

https://drive.google.com/file/d/1ZTgRftLYg5Hsm0NoJsaKqrMNeXO8RrFS/view?usp=sharing

### (Optional) Upload your Chain Specification

https://drive.google.com/file/d/1ix3DqpkrtPvawWckEGfh6S775avyoZGs/view?usp=sharing

### Anything else we should know?

We have an active parachain on rococo with paraId 4278. But that parachain was ran using Alice and bob keys. So now we want to reset our genesis with custom private keys using the rococo apis "force_set_current_code" and "force_set_current_head"

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by al3mart** [comment]
New wasm and state set! If there is anything else to be done, please feel free to drop a comment here.
