### ISSUE TITLE
xcav parachain slots

### ISSUE THREAD

**Issue by ganesh1233456** [paritytech/subport#582]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

xcav

### Parachain Name

xcav-parachain

### ParaID

4285

### Parachain Manager Account

5EcKtQoUJAJc6Ekz3XNaR9LRsDWrqCMVnZNAa7N21JzuZL7e

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[para-4285-genesis-state.txt](https://github.com/paritytech/subport/files/12274209/para-4285-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[para-4285-wasm.txt](https://github.com/paritytech/subport/files/12274212/para-4285-wasm.txt)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by ganesh1233456** [comment]
I am running my collator node and I can see that slots is assigned. But what now? How to processed further steps?
Can you recommend me some resources?

<img width="1424" alt="Screenshot 2023-08-08 at 09 37 42" src="https://github.com/paritytech/subport/assets/42571338/69398057-ce32-482f-8d59-27c62ae0f62c">
<img width="1424" alt="Screenshot 2023-08-08 at 09 39 01" src="https://github.com/paritytech/subport/assets/42571338/47e07a7c-176f-4c4a-b804-24ab4269c2bb">

**Comment by AlexD10S** [comment]
I am going to leave this Issue opened for now, but let's keep the discussion and troubleshooting in your [StackExchange question](https://substrate.stackexchange.com/questions/9541/what-after-slot-assigned)

**Comment by AlexD10S** [comment]
I am offboarding it, to make the onboard again. Something went wrong with the first onboarding. 
My apologies.

**Comment by ganesh1233456** [comment]
ok @AlexD10S  should I have to send request for slots once again?

**Comment by AlexD10S** [comment]
No, no need of it. Just be sure they are the correct ones

**Comment by ganesh1233456** [comment]
hey @AlexD10S now it is in `Parathread` section, still do I have to wait?

<img width="1424" alt="Screenshot 2023-08-09 at 08 58 42" src="https://github.com/paritytech/subport/assets/42571338/156d397d-f447-4813-a0d1-93513105178d">

**Comment by AlexD10S** [comment]
I can see it in the Parachains list: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/parachains
