### ISSUE TITLE
BFG

### ISSUE THREAD

**Issue by ddorgan** [paritytech/subport#583]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

BFG

### Parachain Name

bfg

### ParaID

2013

### Parachain Manager Account

5DWwL6TBA7tur8Mnh5m74t6RtX6t6FBV1X5EfQ3GSh4SK1KT

### Is this for a short or long term slot?

Long-term: we have a matching paraID in use on Polkadot or Kusama.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

0x0000000000000000000000000000000000000000000000000000000000000000007317ac302036250828069d96d26b1ce8ef19f0afa1347ac0e3b120e7df885a9a03170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[bfg.wasm.txt](https://github.com/paritytech/subport/files/12291440/bfg.wasm.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by AlexD10S** [comment]
Onboarding!

**Comment by AlexD10S** [comment]
Onboarded!
