### ISSUE TITLE
Rococo Slot Request for paraID 4290

### ISSUE THREAD

**Issue by vivaldinetwork** [paritytech/subport#587]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

vivaldi network

### Parachain Name

vivaldi network

### ParaID

4290

### Parachain Manager Account

5GuVaEbEn93YNscfd85fedTxV1da2AXwJuNjTe8MabfMUQFr

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[para-4290-genesis-state.txt](https://github.com/paritytech/subport/files/12466672/para-4290-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[para-4290-wasm.txt](https://github.com/paritytech/subport/files/12466676/para-4290-wasm.txt)

### Anything else we should know?

we want to test our app with rococo parachain  with para-id 4290. 

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by AlexD10S** [comment]
Onboarding!
