### ISSUE TITLE
Snowbridge Fork of BridgeHub

### ISSUE THREAD

**Issue by alistair-singh** [paritytech/subport#588]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Snowfork

### Parachain Name

Rococo Snowbridge BridgeHub

### ParaID

3016

### Parachain Manager Account

5EZNJsLRLkJe27evZRgtFALDFgG1Y2cKEY9nexc97tT52fg5

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

https://snowbridge-rococo-demo.s3.eu-central-1.amazonaws.com/para_info/bridge-hub-genesis.state

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

https://snowbridge-rococo-demo.s3.eu-central-1.amazonaws.com/para_info/bridge-hub-genesis.wasm

### (Optional) Upload your Chain Specification

https://snowbridge-rococo-demo.s3.eu-central-1.amazonaws.com/para_info/bridge-hub-rococo-local.json

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed - https://github.com/polkadot-js/apps/pull/7630

**Comment by AlexD10S** [comment]
Done!
