### ISSUE TITLE
Test RSS Connection to Riot Chat

### ISSUE THREAD

**Issue by shawntabrizi** [paritytech/subport#59]
I set up a riot bot to listen to new Subport issues. It should ping the riot chat.

**Comment by danforbes** [comment]
Thanks, Shawn :pray:

**Comment by shawntabrizi** [comment]
confirmed 
<img width="829" alt="image" src="https://user-images.githubusercontent.com/1860335/101099662-f274fc00-3579-11eb-9476-48e2f9b0fbc4.png">
