### ISSUE TITLE
Hyperbridge Testnet

### ISSUE THREAD

**Issue by seunlanlege** [paritytech/subport#595]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Polytope Labs

### Parachain Name

Hyperbridge (Gargantuan)

### ParaID

4296

### Parachain Manager Account

5E4kXkguH9JAVqymJZGkJHi5se2grgR1ZKhhkNUmxqMTSP7g

### Is this for a short or long term slot?

Long-term: we have secured a slot on Polkadot or Kusama.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[head.txt](https://github.com/paritytech/subport/files/12708628/head.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[wasm.txt](https://github.com/paritytech/subport/files/12708630/wasm.txt)

### (Optional) Upload your Chain Specification

[gargantuan-raw.txt](https://github.com/paritytech/subport/files/12708637/gargantuan-raw.txt)

### Anything else we should know?

Spoken to @al3mart already about the perma-slot

**Comment by al3mart** [comment]
onboarding will happen in ~1h 15' from now

**Comment by seunlanlege** [comment]
Humbly requesting a regenesis of Gargantua, as we've now upgraded to async backing.
[wasm.txt](https://github.com/paritytech/subport/files/14209989/wasm.txt)
[head.txt](https://github.com/paritytech/subport/files/14209991/head.txt)

**Comment by SBalaguer** [comment]
@seunlanlege both of these are set now. Also the parachain is now `unlocked` so that you can set the wasm and head directly next time from the parachain manager account.

**Comment by seunlanlege** [comment]
Unfortunately we're bricked again. This time we're disabled async backing until it stabilizes. Here's our new genesis files. Shamelessly requesting a regenesis, hopefully for the last time.

[gargantua.head.txt](https://github.com/paritytech/subport/files/14220315/gargantua.head.txt)
[gargantua.wasm.txt](https://github.com/paritytech/subport/files/14220314/gargantua.wasm.txt)

**Comment by SBalaguer** [comment]
@seunlanlege this is done! To note again, I unlocked your chain yesterday so that you could do this freely yourself, so feel free to keep on bricking your testnet, and then set the wasm and genesis you'd like. That's part of the fun :))

**Comment by seunlanlege** [comment]
Hey guys, don't know how but i can no longer change the parachain code for 4296 on rococo. I keep getting an error that there's a pending code upgrade. But it's for a past relay chain block.

![Screenshot 2024-02-13 at 1 15 35 PM](https://github.com/paritytech/subport/assets/16494314/ae915ddb-06f3-4448-8324-e344d7b76c8f)

Attaching my new genesis header and wasm here for regenesis through forceRegister.

[gargantua.head.txt](https://github.com/paritytech/subport/files/14261456/gargantua.head.txt)
[gargantua.wasm.txt](https://github.com/paritytech/subport/files/14261458/gargantua.wasm.txt)

**Comment by seunlanlege** [comment]
Hey guys just following up here, we are still unable to change the code for hyperbridge on our end
![Screenshot 2024-02-13 at 4 50 59 PM](https://github.com/paritytech/subport/assets/16494314/55bda0e6-66b3-49f4-bd28-6af95f499ff8)
