### ISSUE TITLE
Parachain slot for experimental S\C network (yerba network para id 4292)

### ISSUE THREAD

**Issue by pgherveou** [paritytech/subport#598]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Parity Technology

### Parachain Name

Yerba

### ParaID

4292

### Parachain Manager Account

5FGvfLFJ9Xe4sZAwYD9wYh8sKJPCMRS75WSxgrRp5DNsLyDX

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[para-4292-genesis-159cd.txt](https://github.com/paritytech/subport/files/12846079/para-4292-genesis-159cd.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[para-4292-wasm-159cd.txt](https://github.com/paritytech/subport/files/12846100/para-4292-wasm-159cd.txt)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/9908

**Comment by agryaznov** [comment]
> Can you re-upload your Validation Code with the plan file? (or a txt)

done

**Comment by AlexD10S** [comment]
The onboarding looks succesful but I don't see is producing blocks, any logs on your side?

**Comment by agryaznov** [comment]
@AlexD10S I've updated the runtime and genesis files, could you please re-onboard us? Thanks

**Comment by AlexD10S** [comment]
I gave it a permanent slot for better experience and I have just set the new WASM and genesis files!

**Comment by agryaznov** [comment]
@AlexD10S could you please update the genesis and wasm (updated them to the desc)?

**Comment by AlexD10S** [comment]
Updated!

**Comment by agryaznov** [comment]
one more update please 🙏

**Comment by AlexD10S** [comment]
Updated!

**Comment by agryaznov** [comment]
wow finally we're live! many thanks!
