### ISSUE TITLE
Metaquity Network Rococo Slot Request

### ISSUE THREAD

**Issue by khssnv** [paritytech/subport#603]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Metaquity Limited

### Parachain Name

Metaquity Network

### ParaID

4304

### Parachain Manager Account

5GHak7BBdBoRDB4Mhypgn6V9xg4Xx2BsmXG7pRD6xjdp2ih1

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[metaquity-rococo-testnet-para-4304-genesis-state.txt](https://github.com/paritytech/subport/files/13115192/metaquity-rococo-testnet-para-4304-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[metaquity-rococo-testnet-4304-wasm.txt](https://github.com/paritytech/subport/files/13115194/metaquity-rococo-testnet-4304-wasm.txt)

### (Optional) Upload your Chain Specification

[metaquity-rococo-testnet.json](https://github.com/paritytech/subport/files/13115198/metaquity-rococo-testnet.json)

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: https://github.com/polkadot-js/apps/pull/9956
  - At Polkadot/Substrate Portal: https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.rococo-testnet.metaquity.xyz#/explorer

**Comment by khssnv** [comment]
Please reset the chain state.

### New Genesis Head (genesis state)

[metaquity-rococo-testnet-para-4304-genesis-state-2.txt](https://github.com/paritytech/subport/files/13200932/metaquity-rococo-testnet-para-4304-genesis-state-2.txt)

## New Validation Code (genesis runtime Wasm)

[metaquity-rococo-testnet-4304-wasm-2.txt](https://github.com/paritytech/subport/files/13200933/metaquity-rococo-testnet-4304-wasm-2.txt)

**Comment by khssnv** [comment]
@al3mart, @AlexD10S, hello, could you help with the chain state reset and onboard it for the temporary slot again? Thank you!

**Comment by AlexD10S** [comment]
Done!

**Comment by Ekaanth** [comment]
Pinging @AlexD10S and @ascjones  :))

**Comment by AlexD10S** [comment]
I gave again a temporary slot to the parachain, so let's see. But did you see any error in the logs?

**Comment by khssnv** [comment]
Thank you @AlexD10S. There are no errors in the collator logs as well as no message about the block candidate creation. The node is using Polkadot SDK v1.2.0 from crates.io by the way.

**Comment by khssnv** [comment]
The chain started and 8k+ blocks already backed. Thank you!

By the way, is it the expected behavior not to start on the first attempt? And is there documentation to read about what will happen after the lease period ends?

**Comment by AlexD10S** [comment]
No, I am not sure why the onboarding didn't properly work the first time.
After the period ends you will need to apply again for slots because you got a temporary slot. The permanent slots are typically assigned to teams who have completed a successful slot lease auction and have deployed a parachain with a slot on Polkadot but there can be exceptions if you need permanent slot for some reason

**Comment by khssnv** [comment]
Hello @AlexD10S, please re-onboard for a temporary slot with a new genesis state and runtime. Thank you!

### New Genesis Head (genesis state)

[para-4304-genesis-state.txt](https://github.com/paritytech/subport/files/13704241/para-4304-genesis-state.txt)

### New Validation Code (genesis runtime Wasm)

[para-4304-wasm.txt](https://github.com/paritytech/subport/files/13704245/para-4304-wasm.txt)

**Comment by AlexD10S** [comment]
Onboarded!

**Comment by AlexD10S** [comment]
I see the onboarding was successfully but the chain is not producing blocks. Any errors on your side?
