### ISSUE TITLE
rococo slot request

### ISSUE THREAD

**Issue by ganesh1997oli** [paritytech/subport#606]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

xcavate

### Parachain Name

xcavate

### ParaID

4323

### Parachain Manager Account

5EcKtQoUJAJc6Ekz3XNaR9LRsDWrqCMVnZNAa7N21JzuZL7e

### Is this for a short or long term slot?

Long-term: we have secured a slot on Polkadot or Kusama.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[para-4323-genesis-state.txt](https://github.com/paritytech/subport/files/13325001/para-4323-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[para-4323-wasm.txt](https://github.com/paritytech/subport/files/13325002/para-4323-wasm.txt)

### Anything else we should know?

So... We want to start a XCM channel with X parachain with Y paraID...

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by ganesh1997oli** [comment]
but it is still in Parathread section

**Comment by AlexD10S** [comment]
Assigned temporary slots! Will see if the onboarding is fine before close it

**Comment by AlexD10S** [comment]
It is a parachain now!

**Comment by joshuacheong** [comment]
@ganesh1997oli was the parachain producing blocks? I heard Richard mentioned there was difficulty

**Comment by ganesh1997oli** [comment]
> @ganesh1997oli was the parachain producing blocks? I heard Richard mentioned there was difficulty. If so, do let us know of the issues / logs

Hi Joshuacheong, yes I am struggling to produce blocks. ok let me share node log files, [node01_logs](https://drive.google.com/file/d/1Najb-09iKLAEhD0D2HG4GPTl__h1LCJs/view?usp=drive_link) and [node02_logs](https://drive.google.com/file/d/1stach3JxX_cfkRzAHabNRxCbhRRwrqc4/view?usp=drive_link). I run node for more than 10hr but still nothing happening.

**Comment by ganesh1997oli** [comment]
[para-4323-genesis-state.txt](https://github.com/paritytech/subport/files/13435315/para-4323-genesis-state.txt)
[para-4323-wasm.txt](https://github.com/paritytech/subport/files/13435316/para-4323-wasm.txt)

**Comment by AlexD10S** [comment]
Updated!
