### ISSUE TITLE
Reset the t0rn parachain on Rococo

### ISSUE THREAD

**Issue by 3h4x** [paritytech/subport#608]
**You completed the Parachain Tutorials for your parachain and tested locally?**
 Yes, we have successfully tested our chain on rococo-local.

**Team Name**
t3rn

**Parachain Name**
t0rn

**ParaID**
3333

**Is this for a short or long term slot?**
Long-term

**Upload your Genesis Head (genesis state)**
[t0rn-genesis-state.txt](https://github.com/paritytech/subport/files/13335096/t0rn-genesis-state.txt)

**Upload your Validation Code (genesis runtime Wasm)**
[t0rn-genesis-wasm.txt](https://github.com/paritytech/subport/files/13335108/t0rn-genesis-wasm.txt)

**(Optional) Upload your Chain Specification**
[t0rn.raw.json](https://github.com/paritytech/subport/files/13335114/t0rn.raw.json)

**Anything else we should know?**
Is it possible to start a XCM HRMP channel with Rococo and AssetHub?

**Register your Rococo parachain details for polkadot-js/apps**
It's done

**Comment by AlexD10S** [comment]
Done!
