### ISSUE TITLE
Reset the t0rn parachain on Rococo

### ISSUE THREAD

**Issue by 3h4x** [paritytech/subport#610]
**You completed the Parachain Tutorials for your parachain and tested locally?**
Yes, we have successfully tested our chain on rococo-local.

**Team Name**
t3rn

**Parachain Name**
t0rn

**ParaID**
3333

**Is this for a short or long term slot?**
Long-term

**Upload your Genesis Head (genesis state)**
0x000000000000000000000000000000000000000000000000000000000000000000e632ce5ef44484ca7d743fc8e64e4205085f72a28ef276d3ddbe794639135f7303170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400                                             

**Upload your Validation Code (genesis runtime Wasm)**
https://github.com/t3rn/t3rn/releases/download/v1.74.3-rc.0/t0rn-parachain-runtime-v1.74.3-rc.0.compact.compressed.wasm

**(Optional) Upload your Chain Specification**
https://raw.githubusercontent.com/t3rn/t3rn/v1.74.3-rc.0/specs/t0rn.raw.json

**Anything else we should know?**
Is it possible to start a XCM HRMP channel with Rococo and AssetHub?

**Register your Rococo parachain details for polkadot-js/apps**
It's done

**Comment by AlexD10S** [comment]
Done!
