### ISSUE TITLE
ReOnboard t0rn parachain as 3333 on Rococo

### ISSUE THREAD

**Issue by MaciejBaj** [paritytech/subport#612]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

t3rn

### Parachain Name

t0rn

### ParaID

3333

### Parachain Manager Account

5D333eBb5VugHioFoU5nGMbUaR2uYcoyk5qZj9tXRA5ers7A

### Is this for a short or long term slot?

Long-term: we have secured a slot on Polkadot or Kusama.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

0x000000000000000000000000000000000000000000000000000000000000000000e632ce5ef44484ca7d743fc8e64e4205085f72a28ef276d3ddbe794639135f7303170a2e7597b7b7e3d84c05391d139a62b157e78786d8c082f29dcf4c11131400

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[t0rn-parachain-runtime-v1.74.5-rc.0.compact.compressed.wasm.txt](https://github.com/paritytech/subport/files/13416678/t0rn-parachain-runtime-v1.74.5-rc.0.compact.compressed.wasm.txt)

### (Optional) Upload your Chain Specification

[t0rn.raw.json](https://github.com/paritytech/subport/files/13416686/t0rn.raw.json)

### Anything else we should know?

HRMP channel between t0rn <> Rococo + AssetHub @ Rococo 

### Register your Rococo parachain details for `polkadot-js/apps`

https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frpc.t0rn.io#/chainstate

**Comment by AlexD10S** [comment]
It failed the WASM file! `byte index 2 is not a char boundary; it is inside '�' (bytes 1..4) of `R�SvFێ(�/�X|H^�ƺS(��:!�a@b���'�c�3N�z�ǣqT�4�H�-��(���%�y�F��Թ��e��H�wH�Ƽ����J�v�-e�2��RV(�%�p�Ƒ�*�($��GUmq�ERGF5 ��D�>N`[...]` Probably has been corrupted when transforming the file to .txt

**Comment by MaciejBaj** [comment]
[[t0rn-parachain-runtime-v1.74.5-rc.0.compact.compressed.wasm](https://github.com/paritytech/subport/files/13416678/t0rn-parachain-runtime-v1.74.5-rc.0.compact.compressed.wasm.txt)](https://github.com/t3rn/t3rn/releases/download/v1.74.5-rc.0/t0rn-parachain-runtime-v1.74.5-rc.0.compact.compressed.wasm)


Let me attach the release link directly. Hope that helps

**Comment by AlexD10S** [comment]
Reopened in a new Issue (https://github.com/paritytech/subport/issues/613). I was not able to upload a file editing the Issue
