### ISSUE TITLE
Rococo Slot Renewal Request: Frequency Id: 4044

### ISSUE THREAD

**Issue by wilwade** [paritytech/subport#616]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Amplica Labs

### Parachain Name

Frequency

### ParaID

4044

### Parachain Manager Account

5G4ADWnLUEWwDQ5mKQHEB9ASP7JrdXtUdo97RUpuxPeeKWtz

### Is this for a short or long term slot?

Long-term: we have secured a slot on Polkadot or Kusama.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

Renewal

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

Renewal, so I don't think this is needed?

### Anything else we should know?

This is just a renewal of a slot that expired

### Register your Rococo parachain details for `polkadot-js/apps`

- [x] Polkadot-js Apps UI PR completed

**Comment by wilwade** [comment]
Nope. Looks like it is failing due to not having the same ParaId on Polkadot as it does on Rococo.

**Comment by al3mart** [comment]
Your parachain is being onboarded now

**Comment by wilwade** [comment]
All back up. Thank you @al3mart!
