### ISSUE TITLE
Curio: Rococo Slot Request

### ISSUE THREAD

**Issue by alexxxkny** [paritytech/subport#619]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Curio

### Parachain Name

Curio

### ParaID

3339

### Parachain Manager Account

5FFaHNwYDhY5DUBazJqA16Ck1iFY9CmSnXc1r7yDsrjRBLx8

### Is this for a short or long term slot?

Long-term: we have secured a slot on Polkadot or Kusama.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[curio-rococo-genesis-state.txt](https://github.com/paritytech/subport/files/13704634/curio-rococo-genesis-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[curio-rococo-genesis-wasm.txt](https://github.com/paritytech/subport/files/13704637/curio-rococo-genesis-wasm.txt)

### Register your Rococo parachain details for `polkadot-js/apps`

https://github.com/polkadot-js/apps/pull/9183

**Comment by alexxxkny** [comment]
Hello! Can't actually see a parachain with ParaId 3339. Why has not it been unboarded?

**Comment by AlexD10S** [comment]
I am doing the onboarding manually again, in 2h should be onboarded

**Comment by AlexD10S** [comment]
Onboarded!
