### ISSUE TITLE
Substrate Light Client choices and documentation

### ISSUE THREAD

**Issue by BenWhiteJam** [paritytech/subport#62]
This [Feedbackboard: Light Client Choice](https://feedback.parity.io/b/substrate-feedback-board/light-client-choice) got posted a while ago, reached out internally as well, but didn't yet get a great answer. As this might be also very valuable going forward, I think it makes sense to either 1.) gather informations around Substrate Light Clients in the corresponding conversation of this issue or 2.) enhance the current documentation.

**Comment by danforbes** [comment]
I will need some help with this. I think there may still be some questions that need to be answered around our light client implementations. @Stefie can you offer any insight here? Thank you for raising this issue, @BenWhiteJam, this is very important and something that I'm personally looking forward to helping with :nerd_face:

**Comment by Stefie** [comment]
Hey! To my knowledge we don't have any proper documentation on the Light Client yet, but we surely need it!
There just haven't been too many real-life working examples of projects utilizing Substrate Light Clients and no one really took the time to sit down, think about and write down the different use-cases and the pros and cons of the different options.
So there's just no go-to guide for Light Clients yet.

The Light Client is under active development at the moment and will change quite a bit in the coming months.
In addition to the Substrate Light Client there's a new approach by @tomaka of an alternative light client for Polkadot and Substrate which can be found here https://github.com/paritytech/substrate-lite. 

You can follow the progress of Light Client related tasks here:
https://github.com/orgs/paritytech/projects/2

**Regarding the [question on the Feedbackboard:](https://feedback.parity.io/b/substrate-feedback-board/light-client-choice)**
I know that @riusricardo has successfully been running the Light Client  on a Raspberry Pi and @stiiifff was working on a sample app that demonstrates how to embed a Substrate Light Client node within a mobile Android application so both could be of help when it comes to the question to make it work on machines with limited ressources.

I hope that helped a bit to clarify the situation. I added this issue to the Light Client Board so we keep documentation in mind.

**Comment by danforbes** [comment]
Amazing, @Stefie! Thank you for mentioning the work done by Ricardo, Steve, et al., on the Enterprise Sample. I would suggest that we continue to use the Enterprise Sample as a "playground" to help create some "real-life working examples" that can help guide this process.

**Comment by BenWhiteJam** [comment]
I guess @chaosma from deeper.network would have a real-life use-case at hand. He would like to deploy a light-client on the deeper node: https://github.com/e2chain-dev/e2-chain

**Comment by apopiak** [comment]
The enterprise sample for reference: https://github.com/substrate-developer-hub/substrate-enterprise-sample

**Comment by stiiifff** [comment]
and the experimental Android app w/ an embedded light client is over here: https://github.com/stiiifff/substrate-enterprise-sample-app

**Comment by chaosma** [comment]
> I guess @chaosma from deeper.network would have a real-life use-case at hand. He would like to deploy a light-client on the deeper node: https://github.com/e2chain-dev/e2-chain

Yeah, currently, we are just using RPC call from the small device to full substrate nodes. This works well at this stage. In future, it would be nice if we can add light client inside the small device.  It will give the device better security.

**Comment by danforbes** [comment]
@chaosma - can you provide details about the types of requests you would like to send from the small devices? Will they require an archive node? Will you be submitting extrinsics, requesting data from the chain state, or doing something else?

**Comment by chaosma** [comment]
> @chaosma - can you provide details about the types of requests you would like to send from the small devices? Will they require an archive node? Will you be submitting extrinsics, requesting data from the chain state, or doing something else?

@danforbes sorry for late reply. When the device (light client) interacts with the blockchain, it can query the status of blockchain, e.g. the balance of an account, current validator list; it can submit extrinsic calls.  It can also delegate itself to some online validators. It doesn't require the archive node. But probably just the most recent one or two epochs of data. 

At current stage for the testnet, we just use RPC to interact with the full validator node. It works fine. For the mainnet, I am worry about the potential attack such as eclipse attack. In some rare cases, when a device offline for a long time and back online, it might not be able to contact the correct validator nodes. In this case, the light client is a good solution, and it will sync with multiple nodes to make sure it gets the correct history or state of blockchain. Well, that's just my guess of what the light node will do. Let me know if my understanding about the light node is correct.
