### ISSUE TITLE
Curio Parachain

### ISSUE THREAD

**Issue by alexxxkny** [paritytech/subport#622]
Parachain is now being onboarded.

_Originally posted by @paritytech-onboard-rococo-p-chain[bot] in https://github.com/paritytech/subport/issues/619#issuecomment-1860636634_
Hello! It is said that the parachain was onboarded but I can't actually see a parachain with ParaId 3339. Why has not it been onboarded?

**Comment by AlexD10S** [comment]
I reopen the previous Issue: https://github.com/paritytech/subport/issues/619 and closing this
