### ISSUE TITLE
update magnet

### ISSUE THREAD

**Issue by zachary0809** [paritytech/subport#626]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Magport Labs

### Parachain Name

Magnet

### ParaID

4350

### Parachain Manager Account

5FF6Camy3yc6EwV6ye3744VXh8BkgRNTwjpJfTDvbky8W4oC

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[magnet-4350-state.txt](https://github.com/paritytech/subport/files/13984918/magnet-4350-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[magnet-4350-wasm.txt](https://github.com/paritytech/subport/files/13984919/magnet-4350-wasm.txt)

### Anything else we should know?

So... We want to start a XCM channel with magnet with rococo,want to start a evm.

### Register your Rococo parachain details for `polkadot-js/apps`

- [ ] Polkadot-js Apps UI PR completed
  - Available here: {FIX ME!!!!}

**Comment by zachary0809** [comment]
hello, magnet is still in Parathread section @AlexD10S @al3mart

**Comment by al3mart** [comment]
The onboarding process checks that the paraid provided is a parachain holding a slot in production (this won't work with coretime, but yes at this point in time).

I'd say your para has been assigned a temp slot and it will be onboarded during the following LPs.

Also, note that on demand coretime is available in Rococo already.
