### ISSUE TITLE
Reset Magnet(4350)

### ISSUE THREAD

**Issue by zachary0809** [paritytech/subport#629]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Magport Labs

### Parachain Name

Magnet

### ParaID

4350

### Parachain Manager Account

5FF6Camy3yc6EwV6ye3744VXh8BkgRNTwjpJfTDvbky8W4oC

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[magnet-4350-state.txt](https://github.com/paritytech/subport/files/14057038/magnet-4350-state.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[magnet-4350-wasm.txt](https://github.com/paritytech/subport/files/14057043/magnet-4350-wasm.txt)

### (Optional) Upload your Chain Specification

[raw-magnet-4350.json](https://github.com/paritytech/subport/files/14057080/raw-magnet-4350.json)

### Anything else we should know?

 We want to start a XCM channel with magnet with rococo,want to start a evm.

### Register your Rococo parachain details for `polkadot-js/apps`

We want to reset specification.

**Comment by zachary0809** [comment]
@AlexD10S @al3mart we want to reset specification, Can you help us restart parachain with new specification?

**Comment by al3mart** [comment]
@zachary0809 absolutely! Feel free to update the issue with the new relevant information. Ping me again when that is ready.

**Comment by zachary0809** [comment]
@al3mart The above specification is the latest, and magnet is a parachain now,how to do to reset? and 
what do we need to do?
