### ISSUE TITLE
1002: Verification Error: Runtime error: Execution failed: ApiError("Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress"): RuntimeApi, Execution failed: ApiError, \"Could not convert parameter `tx` between node and runtime: No such variant in enum MultiAddress

### ISSUE THREAD

**Issue by JDawg287** [paritytech/subport#63]
This is happening when trying to submit any extrinsic on the `node-template`. 

Steps to reproduce:
```
$ git clone https://github.com/paritytech/substrate.git
$ cd substrate
$ cargo build
.
.
.
$ ./target/debug/node-template --dev --tmp
```

version:
```
$ ./target/debug/node-template --version
node-template 2.0.0-2a7a985d3-x86_64-linux-gnu
```

![image](https://user-images.githubusercontent.com/38837406/101885123-0d301c00-3bdd-11eb-9fa8-4d0a1d5b26a2.png)

I have verified that this does not happen while running `substrate`.
```
$ ./target/debug/substrate --dev --tmp
```

**Comment by danforbes** [comment]
You need to add some types https://polkadot.js.org/docs/api/FAQ#the-node-returns-a-could-not-convert-error-on-send In particular, I think you need to add this type https://crates.parity.io/sp_runtime/enum.MultiAddress.html This error should not occur if you are using the [Node Template](https://github.com/substrate-developer-hub/substrate-node-template) and have not made any changes to it. It sounds like you may be running a node built off the tip of `master` as opposed to the Node Template, which is built off the `v2.0.0` tag. Is there a reason you need to use that version?

**Comment by JDawg287** [comment]
@danforbes No reason in particular, I just wanted an updated version of the Node Template to work with.
I thought everything was included in the updated Node Template. Thanks for the clarification, I will try out the fix!

**Comment by danforbes** [comment]
@JDawg287 - I'm going to close this Issue since I haven't heard back, but please feel free to reopen it if you're still having problems.

**Comment by JDawg287** [comment]
@danforbes Actually one last thing, I would like to read more documentation on how and where to add different types so that the API and the Node have 100% matching types. Can you provide some links to find more information on this topic. Thanks 👍

**Comment by danforbes** [comment]
Apologies for the delayed response, @JDawg287. You can find some docs for the API here https://polkadot.js.org/docs/api/start/types.basics To add types to the UI, you can go here to add all the types as a JSON object https://polkadot.js.org/apps/#/settings/developer
