### ISSUE TITLE
Open HRMP Channel between Para ID 3344 and Rococo Asset Hub

### ISSUE THREAD

**Issue by lrazovic** [paritytech/subport#632]
This request is for the establishment an HRMP channel between the Rococo Asset Hub and the Parachain with Para ID 3344 (and vice versa), aiming to facilitate the testing of reserve-backed transfers of rTether USD (Asset ID 1984)

**Comment by al3mart** [comment]
You want someone to dispatch this call with SUDO :)
https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Frococo-rpc.polkadot.io#/extrinsics/decode/0x180208fa05e8030000100d0000e803000000900100fa05100d0000e8030000e803000000900100
 
 @helloitsbirdo  :point_up:

**Comment by lrazovic** [comment]
Done! Thanks :D 

![image](https://github.com/paritytech/subport/assets/4128940/3d7e2f95-58aa-47b1-9ac6-edb8068e31af)
