### ISSUE TITLE
Open HRMP Channel between Bifrost Para ID 2030 and Rococo Asset Hub

### ISSUE THREAD

**Issue by hqwangningbo** [paritytech/subport#639]
@al3mart We need to do some experimental cross-chain testing, please help us.

**Comment by al3mart** [comment]
Hello! These days I'm working on getting Paseo ready regarding testnets.
- https://forum.polkadot.network/t/the-new-polkadot-community-testnet/4956

I believe @SBalaguer  should be able to get you guys going :)

**Comment by hqwangningbo** [comment]
> Hello! These days I'm working on getting Paseo ready regarding testnets.
> 
> * https://forum.polkadot.network/t/the-new-polkadot-community-testnet/4956
> 
> I believe @SBalaguer should be able to get you guys going :)

It's great. I'm looking forward to it. 
@SBalaguer Can you help us?

**Comment by SBalaguer** [comment]
Done! Please re-open this issue if anything.
