### ISSUE TITLE
Debug loggers not working, but Info loggers are, despite log level being set to trace

### ISSUE THREAD

**Issue by kylezs** [paritytech/subport#64]
Logging from a pallet, and I'm setting `lruntime=trace` when running, and logging with:
```
frame_support::debug::native::info!("The info data on a native logger is: {:?}", data);
frame_support::debug::native::debug!("The debug data on the native logger is: {:?}", data);
frame_support::debug::RuntimeLogger::init();
frame_support::debug::info!("the data is: {:?}", data);
frame_support::debug::debug!("the data is: {:?}", data);
```

Only the info logger is working for each of the logger types. Seems like a bug?

**Comment by kianenigma** [comment]
what is the command that you are running? and which version?

**Comment by danforbes** [comment]
Chiming in to keep things moving. In Element, @kylezs said
> I'm setting` lruntime=trace` when running

Ref: https://matrix.to/#/!HzySYSaIhtyWrwiwEV:matrix.org/$160807530535244McIUc:matrix.org?via=matrix.parity.io&via=matrix.org&via=corepaper.org

**Comment by kylezs** [comment]
I'm running version 2.0.0 and the command I'm running is:
```
./target/debug/state-chain-node --base-path /tmp/node1 --chain customSpecRaw.json --port 30333 --ws-port 9944 --rpc-port 9933 --validator --rpc-methods=Unsafe --name Node1  -lruntime=trace
```

**Comment by NukeManDan** [comment]
Hey all - I wanted to check in if this is still an open issue? If not, let's close this one?

**Comment by NukeManDan** [comment]
One note: AFAIK [the executor](https://substrate.dev/docs/en/knowledgebase/advanced/executor#native-execution) needs to be given the `Native` flag for logs to work, WASM don't do logging (as well yet) 

you must add the `--execution Native` flag when starting your node to do this.
