### ISSUE TITLE
Upgrade Sora Parachain to parachain and set Management Account

### ISSUE THREAD

**Issue by N1ghtStorm** [paritytech/subport#646]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Soramitsu

### Parachain Name

Sora Parachain

### ParaID

2011

### Parachain Manager Account

5Dz955QNnt16mgj6TWDdKdoahQvXDJVfujoYWVs7LFEHRspX

### Is this for a short or long term slot?

Long-term: we have secured a slot on Polkadot or Kusama.

Need to update sora parachain from parathread to parachain and set management account to 5Dz955QNnt16mgj6TWDdKdoahQvXDJVfujoYWVs7LFEHRspX

Thank you!

**Comment by pg-vlad** [comment]
Hello, i am QA from Soramitsu team
@al3mart @NM2146 
Please help us

**Comment by SBalaguer** [comment]
HEy @pg-vlad, since Coretime is already live on Rococo, there's no need to forcefully add any chains anymore. You can go ahead and register your wasm and head as on any other network, get a core on the Rococo Coretime Chain and assign it to your parachain.

Do let us know if anything!

**Comment by ntn-x2** [comment]
@SBalaguer sorry if I use this issue for my own interest, but I am not aware of another way to reach out to you. We do require sudo action to reset our head and WASM, before being able to go ahead with acquiring coretime. Would you be able to help us? https://github.com/paritytech/subport/issues/650.
