### ISSUE TITLE
how to generate polkadot address over my dot node

### ISSUE THREAD

**Issue by sollover** [paritytech/subport#65]
Hi everyone,

I would like to generate a polkadot address over my dot node with rpc methods ways or like this. Is it available? I didn't found any info about with this way. polkadot documentions only has Polkadot{.js} Browser Plugin or like this way.

thank you

**Comment by Swader** [comment]
You don't need your node to generate a dot address, it's all just math. [Subkey](https://substrate.dev/docs/en/knowledgebase/integrate/subkey) is one recommended approach, but any of [these](https://wiki.polkadot.network/docs/en/learn-account-generation) will do just fine too.
