### ISSUE TITLE
Reset RILT parachain on Rococo

### ISSUE THREAD

**Issue by Ad96el** [paritytech/subport#650]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

KILT Protocol

### Parachain Name

RILT

### ParaID

2086

### Parachain Manager Account

5EUJcZ28VHU2GqQEvt6SzJwciQcGEm6EGddSv74HoRV3yY2M

### Is this for a short or long term slot?

Long-term: we have secured a slot on Polkadot or Kusama.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

[geneis.hex.txt](https://github.com/paritytech/subport/files/15345637/geneis.hex.txt)

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

[rilt.wasm.txt](https://github.com/paritytech/subport/files/15345646/rilt.wasm.txt)

### (Optional) Upload your Chain Specification

[rilt.json](https://github.com/paritytech/subport/files/15345684/rilt.json)

### Anything else we should know?

We would like to completely reset our parachain, including pruning the existing state.

Before onboarding, the extrinsic `paraSudoWrapper.scheduleParaCleanup` must be called.

Thanks a lot!

### Register your Rococo parachain details for `polkadot-js/apps`

RILT is already listed on polkadot-js: https://github.com/polkadot-js/apps/pull/10583

**Comment by Ad96el** [comment]
@al3mart I think something did not work  

RILT is still a para thread and the latest head is indicating that the cleanup was not executed

**Comment by al3mart** [comment]
@SBalaguer Could we get the manager lock removed from this para in Rococo ? :pray:

**Comment by SBalaguer** [comment]
> @SBalaguer Could we get the manager lock removed from this para in Rococo ? 🙏

Not effective because the owner is the SUDO account. I will come back between today and Monday with a plan on how to do this so that the Kilt team can work autonomously.

**Comment by ntn-x2** [comment]
Ho @SBalaguer! Thanks for looking into this. You have any updates on the matter yet? At the very least we would need our head and WASM updated. How to changed that in the future can be tackled at a later time, while having a running Rococo chain is higher priority right now.

**Comment by Ad96el** [comment]
Hello @SBalaguer,

Sorry to bother you, but have you found some time to tackle this issue?

**Comment by SBalaguer** [comment]
Hey @Ad96el @ntn-x2, sorry for the late reply here. Unfortunately I won't be able to do it just now, as Rococo was updated to include the new CheckMetadata SignedExtension, so we need all wallets to update to be able to sign transactions. As soon as I can do this, I'll get you up and running.

My plan for now is to just force the wasm and the head listed on the issue.

**Comment by ntn-x2** [comment]
@SBalaguer I believe that would be sufficient. Once the head and WASM have been written, we can purchase coretime and start the chain. The lock on the parachain, AFAIAC, is not important right now.

**Comment by SBalaguer** [comment]
Did this now: https://rococo.subscan.io/block/10959569. Let me know if anything!
