### ISSUE TITLE
Sudo Account Needed

### ISSUE THREAD

**Issue by webguru9178** [paritytech/subport#655]
### You completed the Parachain Tutorials for your parachain and tested locally?

- [X] Yes, we have successfully tested our chain on `rococo-local`.

### Team Name

Earthshepards

### Parachain Name

Shear

### ParaID

4441

### Parachain Manager Account

5CeSoXAd16hWW7eNQb97qtaf6gd7ez2qFszjWDWVk2L14H76

### Is this for a short or long term slot?

Short-term: we registered a parathread with the paraID above.

### Upload your Genesis Head (genesis state) - Do not submit a compressed file.

file:///home/dev/Downloads/SubstrateTestnet/substrate-parachain-template/target/release/para-4441-genesis-state.txt

### Upload your Validation Code (genesis runtime Wasm) - Do not submit a compressed file.

file:///home/dev/Downloads/SubstrateTestnet/substrate-parachain-template/target/release/para-4441-wasm.txt

### Anything else we should know?

I need Sudo Account for assigning a slot

### Register your Rococo parachain details for `polkadot-js/apps`

I need Sudo Account for assigning a slot

**Comment by SBalaguer** [comment]
@Chrisgvelt you don't need a sudo account to assign a slot, you can just access a core on the coretime chain. Feel free to check it out on lastic.xyz and/or regionx.tech

**Comment by webguru9178** [comment]
Hi, @SBalaguer 

Could you please share with me some references for updating my parathread
to parachain?
I purchased the core and assigned a task.
And it's Active Parachain now.
But there isn't a Para Name in my parachain
Could you please share with me some guides?
Best Regards,
Chris
