### ISSUE TITLE
Subkey docker image default port

### ISSUE THREAD

**Issue by sollover** [paritytech/subport#66]
hi everyone,

what is the default port of Subkey image? I couldn't find this: 

`docker pull parity/subkey`

can you help me?

thank you

**Comment by al3mart** [comment]
I am not very familiar with that image, but you should be able to get that kind of information running `docker inspect <image>`

**Comment by danforbes** [comment]
I don't think Subkey needs to expose any ports. Can you explain what you're trying to do, @sollover?

**Comment by BenWhiteJam** [comment]
Maybe one of the following commands might help?
- `docker run -it parity/subkey`
- `docker run -it parity/subkey generate`
- `docker run parity/subkey generate >> /tmp/test`

Please be aware that the last command stores all the secrets on the host machine and in general, the key generation should get done with great security considerations!

**Comment by sollover** [comment]
Hi, actually I would like to expose / publish  this image because the address generation request will be from a service, I won't do it manually. how can I do that?

thank you

**Comment by BenWhiteJam** [comment]
Maybe `polkadot.js` might be a better fit to look into?
https://polkadot.js.org/docs/util-crypto/examples/create-mnemonic

**Comment by danforbes** [comment]
If you're looking for Rust APIs you can try inspecting the implementation Subkey uses for key generation https://github.com/paritytech/substrate/blob/v2.0.0/client/cli/src/commands/generate.rs

**Comment by danforbes** [comment]
If you wanted to use Subkey in a Docker container to do this, you could just use something like `docker exec` to execute the `generate` subcommand and parse the command line output.

**Comment by sollover** [comment]
Before I must run docker run command for the use docker exec command you know, but when I run the docker run command for this image, it stops immediately. For mnemonic phase suggestion: can I generate the polkadot address from this mnemonic phase?
