### ISSUE TITLE
how to convert an address balance to string or human readable?

### ISSUE THREAD

**Issue by sollover** [paritytech/subport#67]
hi, I would like to read an balance for an polkadot address. 

I ran this code snippets:

```
  const polkaProvider = new HttpProvider("http://xxx.xx.xx.xxxx:9933")
  const api = await ApiPromise.create({ provider : polkaProvider})

  const ADDR = "12xtAYsRUrmbniiWQqJtECiBQrMn8AypQcXhnQAc6RB6XkLW";
  const now = await api.query.timestamp.now();
  const { nonce, data: balance } = await api.query.system.account(ADDR)
 console.log(${now}: balance of ${balance.free} and a nonce of ${nonce});
```

and I got this result:

`1599399426000: balance of 450531834908280914 and a nonce of 2905`

what's wrong or how  can I convert this balance parameter to human readable format?

actually the address balance is  **6,165,835.797436886 DOT**

how do i get this and  what is the type of balance.free?

**Comment by shawntabrizi** [comment]
Balances should provide the `.toHuman()` function, which should do what you want.

Otherwise you can do things manually like this: https://github.com/shawntabrizi/substrate-balance-graph/blob/master/substratebalancegraph.js#L35

Feel free to reopen if this is not clear enough or you have other questions.

**Comment by sollover** [comment]
hi @shawntabrizi  thank you your support, I have one question again.

when I run the` balance.free.toHuman()`not the this balance shown in polkascan. Polkascan says the free balance `5,503,149.121639378`
` balance.free.toHuman()` result :  balance of 46.5050 MDOT and a nonce of 2994... Also what is MDOT?  my mind is very confused :(

thank you
