### ISSUE TITLE
how to convert an address balance to string or human readable?

### ISSUE THREAD

**Issue by sollover** [paritytech/subport#68]
hi

when I run the` balance.free.toHuman()`not the this balance shown in polkascan. Polkascan says the free balance `5,503,149.121639378`
` balance.free.toHuman()` result :  balance of 46.5050 MDOT and a nonce of 2994... Also what is MDOT?  my mind is very confused :(

thank you

_Originally posted by @sollover in https://github.com/paritytech/subport/issues/67#issuecomment-751457828_

**Comment by shawntabrizi** [comment]
`toHuman` uses Metric Prefixes: https://www.nanotech-now.com/metric-prefix-table.htm

So `MDOT` is Mega-DOT, which is a million DOTs.

As for the difference in the value, you need to provide more data. It seems to me you are querying two different blocks, two different users, two different chains, etc...

**Comment by sollover** [comment]
hey thank you,

you said " It seems to me you are querying two different blocks, two different users, two different chains, etc..." what do you mean? I am really confused :) actually I would like to see the correct balance only for an address...

**Comment by shawntabrizi** [comment]
You showed that polkascan and your Polkadot js query have different values.

This can only really be the case if you are doing different queries between the two. So clarification here will help.

**Comment by sollover** [comment]
okey, my codes snippets are below: 

```
`
const polkaProvider = new HttpProvider("http://xxx.xxx.xxx.xx:9933")
 const api = await ApiPromise.create({ provider : polkaProvider})

  const ADDR = "11Q7ismkHUbbUexpQc4DgTvedfsh8jKMDV7jZZoQwv57NLS";

  const now = await api.query.timestamp.now();

  const { nonce, data: balance } = await api.query.system.account(ADDR)

  decimals = api.registry.chainDecimals;
  base = new BN(10).pow(new BN(decimals))
  const mybal = ("${balance.free}")
  console.log("BN Result *****",mybal)
  dm = new BN(mybal).divmod(base);
  console.log(parseFloat(dm.div.toString() + "." + dm.mod.toString()))

  console.log("All balance ${balance}");

 console.log("${now}: free balance of ${balance.free.toHuman()} and a nonce of ${nonce}`);"

```

and console results are:
```

BN Result ***** 80332389567289449
8033238.956728945
All balance {"free":"0x0000000000000000011d65e1f81dd869","reserved":50660000000,"miscFrozen":"0x0000000000000000011d5cd5753d7969","feeFrozen":"0x0000000000000000011d5cd5753d7969"}
1600137978000: free balance of 8.0332 MDOT and a nonce of 0

```

and polkadot subscan result for this address: `Transferrable 1,000 DOT`

https://polkadot.subscan.io/account/11Q7ismkHUbbUexpQc4DgTvedfsh8jKMDV7jZZoQwv57NLS

now, my questions are:

1- what is real DOT balance for this address (11Q7ismkHUbbUexpQc4DgTvedfsh8jKMDV7jZZoQwv57NLS) ?
2- how do i get this balance? (or to real)

thanks for your patience reallyyy I am confused :)

**Comment by shawntabrizi** [comment]
@sollover it looks like you are running a local node. Is it fully done syncing?

What does our official nodes say about the balance? (Polkadot JS)

**Comment by sollover** [comment]
@shawntabrizi  polkadot.js gives the code examples for an address balance, I shared above, that's all :( also yes I ran node as locally. How do I check the sync status? (I used docker image for run local node)

**Comment by emostov** [comment]
> How do I check the sync status? (I used docker image for run local node)

Here is an RPC exposed by polkadot.js that should tell you if your node is currently doing a major sync:

```javascript
const { isSyncing } = await api.rpc.system.health()
```

(Corresponds to this RPC in Substrate https://github.com/paritytech/substrate/blob/0dfdc328fa2b9514847b354e6968553a9e29d61e/client/rpc-api/src/system/mod.rs#L56-L62)

**Comment by sollover** [comment]
thank you for info @emostov ! 
my node seems sync,  api.rpc.system.health command result :
`isSyncing {"peers":8,"isSyncing":true,"shouldHavePeers":true}`

why the address balance doesn't look right still... Is there a solution? what's wrong?

**Comment by emostov** [comment]
I think you need to wait for `"isSyncing":false` before you can rely on queries to the node. If I understand correctly, `"isSyncing":true` means your node is currently executing a major sync.

While you are waiting for your node to finish its major sync you can query a public node, such as the one parity offers: `wss://cc1-1.polkadot.network`. 

I would also recommend taking a look at the `.at` syntax for queries so you can get state at a specific block. Here are some docs: https://polkadot.js.org/docs/api/start/api.query.other#state-at-a-specific-block

**Comment by sollover** [comment]
hmm okey, I got it wrong "isSyncing":true, synchronization continues, it's not complete... I'm waiting until it's sync : false. Any your idea how long the estimate will take?

**Comment by sollover** [comment]
After the node was synchronized, the balances of the accounts getting properly!
