### ISSUE TITLE
how to transfer a dot from dot address to another??

### ISSUE THREAD

**Issue by sollover** [paritytech/subport#69]
hi everyone,

I would like a lot of DOT from an address to another over my node. I examined the example on polkadot.js documentation: 

```
 // Import the API, Keyring and some utility functions
const { ApiPromise } = require('@polkadot/api');
const { Keyring } = require('@polkadot/keyring');

const BOB = '5FHneW46xGXgs5mUiveU4sbTyGBzmstUspZC92UhjJM694ty';

async function main () {
  // Instantiate the API
  const api = await ApiPromise.create();

  // Constuct the keying after the API (crypto has an async init)
  const keyring = new Keyring({ type: 'sr25519' });

  // Add Alice to our keyring with a hard-deived path (empty phrase, so uses dev)
  const alice = keyring.addFromUri('//Alice');

  // Create a extrinsic, transferring 12345 units to Bob
  const transfer = api.tx.balances.transfer(BOB, 12345);

  // Sign and send the transaction using our account
  const hash = await transfer.signAndSend(alice);

  console.log('Transfer sent with hash', hash.toHex());
}

main().catch(console.error).finally(() => process.exit());

```

But this example not clearly for this reasons:

1- how to sign the transaction?

2- What does Keyring object include?`  ( const alice = keyring.addFromUri('//Alice');)`

3- where is the private key or likely object for transaction signing?

4- Is` signAndSend `function enough for transaction publish to network?

can you help me?

thank you

**Comment by al3mart** [comment]
Hello @sollover ,

I will try to give a big picture explanaition of your questions, and will attach some doucmentation that you may find interesting.

When you use `.signAndSend()` this method prepare the payload for the transaction created beforehand, includes data like account's nonce, genesisHash, blockHash, and so. And yes, then the transaction is sent to the node. Afterwards, with some networking magic it will be gossiped over the rest of the nodes and eventually they will reach consensus.

Keyring is a good piece of software in charge of managing key pairs, and taking care of not revealing the secrets. Using polkadot.js you will find yourself adding new key pairs to KeyRing and using it to sign or verify.
If you prefer to manage keypairs by yourself you always can use subkey https://substrate.dev/docs/en/knowledgebase/integrate/subkey

I will really recomend reading and understanding this piece of documentation, https://polkadot.js.org/docs/api/start/api.tx And coming back for any further doubt :) We will always be happy to help.

**Comment by danforbes** [comment]
@al3mart has done a great job so far but I just want to chime in with a little more info and answer your questions very directly @sollover 

1. The transaction is signed by the `signAndSend` function. There should also be an API to sign the transaction without sending it if you would like.
2. The keyring is a library that can be used to generate and manage key pairs. In the example above, the keyring is being used to generate the [well-known Alice development account](https://substrate.dev/docs/en/knowledgebase/integrate/subkey#well-known-keys), and then that account is used to sign the transaction.
3. The private key for Alice is generated from the URI `bottom drive obey lake curtain smoke basket hold race lonely fit walk//Alice`. See the link above to understand why.
4. Yes, `signAndSend` sends the transaction to the node and the node's networking capabilities will gossip the transaction from there.

Please let us know if you have any additional questions or close this Issue if you're all set for now.

**Comment by sollover** [comment]
thank you your explations I am soo clearly now :) I will proceed with these info
