### ISSUE TITLE
Is substrate-archive the only way to read transactions in a block or is there else?

### ISSUE THREAD

**Issue by sollover** [paritytech/subport#70]
Hi everyone,

How to get an polkadot transaction info from an block with txhash or an address?

how can I do this? I found called "substrate archive" indexing engine. Is solution only this? 

thank you

**Comment by kianenigma** [comment]
if you only have tx-hash or an account address, I think that is the only way. If you know at which block number/hash your transaction of interest happened, then any full node with `--prunning=archive` can respond to you through the javascript api and give you all the details of that block, including the transactions. 

A similar tool that might be helpful in this regard is `substrate-api-sidecar`. It attaches to an archive node (archive-node != substrate-archive) and exposes a REST API for common queries. But in essence, (almost) anything that it does is a wrapper around polkadot-js-api.

**Comment by sollover** [comment]
Can I set `--prunning=archive` when I setup the node? or how can I run the --prunning=archive command? I have a sync local node but I couldn't setup with  `--prunning=archive`.

I tried in node like this: `polkadot --prunning=archive` I guess, is not true... It's give me this error:
`Error:
   0: Backend error: IO error: While lock file: /polkadot/.local/share/polkadot/chains/polkadot/db/LOCK: Resource temporarily unavailable
`

thank you

**Comment by kianenigma** [comment]
Error seems to indicate that you have another node process running, make sure to close all your existing nodes and then re-run with `--prunning=archive`. 

As for the `--prunning=archive`, I think you need to wipe your database first and re-sync in archive mode. For both operations, you can use the `--help` and look for `pruning` and `purche-chain` options in there.

**Comment by sollover** [comment]
hi, can I tried re-setup with `--pruning=archive` , I got this error: 

```
Error:
   0: State database error: Expected pruning mode: constrained
```

how do I fix this error?

**Comment by kianenigma** [comment]
can you paste your full command? also, are you sure that you purged the old chain database?

**Comment by sollover** [comment]
I can try this: 

`docker run -d --name polka -v /data/polkadot:/polkadot parity/polkadot --rpc-external --rpc-cors '*' --pruning=archive`

also I didn't remove old container...

**Comment by kianenigma** [comment]
> also I didn't remove old container...

You should, I think the rest would work fine. 

I am not 100% sure if `0: State database error: Expected pruning mode: constrained` is related, but my best guess is that you can't switch a database mode on the fly (which makes sense). So you need to `purge-chain` and then run again, or simply delete your docker volume.

**Comment by sollover** [comment]
I started to on another server, and it's worked, The node, syncronizing now,I am waiting and I ran getBlock command for an txHash value  and I got this snippet:

`getBlock {"block":{"header":{"parentHash":"0x712379ca0045176254dde98162f827910ed9041c9050c365f1cd367103652fa7","number":5849,"stateRoot":"0x74c74405cce1dde086223e1a11082e1c7796a3110ea38377daa8fbd93317d2d7","extrinsicsRoot":"0x01212e21c8fd1baa9a7b057f123ebee2d430ac7c5c7a3690eee15bec4a6d395f","digest":{"logs":[{"PreRuntime":[1161969986,"0x030400000074f5cc0f00000000beb55c94db97253d2c8c2fc1bb8b0b0eece7b355127254cec22d05b798cc9f43b1f288e789829dae1f8320fbd7f55026f8fdf1c3d134b1b557c5f0a49089310a2b44ed1a5470d4162c01fa27340d1f4b05fdd03ecb35c9564d83816254ecd008"]},{"Seal":[1161969986,"0xf20d0e23b3ac9f4bc8aecb902ee002d617589efe219b154b78e06f2bcbdfd77b9f7c9a900c161cd24c00471575f46bc08cf2e960314698b300e1fbc418bdee85"]}]}},"extrinsics":["0x280403000bc0ceb8537201","0x1004140000"]},"justification":"0x"}

`

where is the transactions of this block?

**Comment by kianenigma** [comment]
The extrinsics field is the encoded transactions. If you want an easy way to get a human readable format, you need to use sidecar or polkadot-js-api. 

- sidecar apis: https://paritytech.github.io/substrate-api-sidecar/dist/ ,you would need `/blocks/{block}`
- polkadot js api example: https://polkadot.js.org/docs/api/cookbook/blocks/#how-do-i-view-extrinsic-information

**Comment by danforbes** [comment]
@sollover please close this Issue if you don't have any follow-up questions. Thanks for the great explanations, @kianenigma 🙏🏻

**Comment by sollover** [comment]
hi @kianenigma , I tried decode the getBlock result with "signedBlock.block.extrinsics " on polkadot.js (and like your example)

```
const signedBlock = await api.rpc.chain.getBlock("0xb6ab12822f68e22acec68d37dd0e79a142e99db380a892b997f2c2608560b45a")

console.log(signedBlock.block.extrinsics)
```

and I got this results:
`Vec(2) [
  Type {
    registry: TypeRegistry {},
    _raw: Type [Map] {
      'signature' => [Type [Map]],
      'method' => [Type [Map]],
      registry: TypeRegistry {}
    }
  },
  Type {
    registry: TypeRegistry {},
    _raw: Type [Map] {
      'signature' => [Type [Map]],
      'method' => [Type [Map]],
      registry: TypeRegistry {}
    }
  },
  registry: TypeRegistry {},
  _Type: [class Type extends GenericExtrinsic]
]`

I did not expect that :( 

And I tried this too:

`console.log(signedBlock.block.extrinsics[1].method)`

and Its give me that:

`Type [Map] {
  'callIndex' => GenericCallIndex(2) [Uint8Array] [ 20, 0, registry: TypeRegistry {} ],
  'args' => Struct [Map] {
    'heads' => Vec(0) [ registry: TypeRegistry {}, _Type: [class Type] ],
    registry: TypeRegistry {},
    heads: [Getter]
  },
  registry: TypeRegistry {},
  _meta: Type [Map] {
    'name' => [String (Text): 'set_heads'] { registry: TypeRegistry {} },
    'args' => Vec(1) [
      [Type [Map]],
      registry: TypeRegistry {},
      _Type: [class Type]
    ],
    'documentation' => Vec(1) [
      [Text],
      registry: TypeRegistry {},
      _Type: [class Text extends String]
    ],
    registry: TypeRegistry {},
    name: [Getter],
    args: [Getter],
    documentation: [Getter]
  }
}`

what's my fault?

thank you

**Comment by al3mart** [comment]
Hey @sollover keep up! There is no better way for learning than trying to solve this little problems you encounter on the way :nerd_face:  

I could not be 100% rigth about this, but I expect those extrinsics you want to decode to be SCALE encoded, information about SCALE here https://substrate.dev/docs/en/knowledgebase/advanced/codec
So I guess you could just deserialize that info with something like https://github.com/polkadot-js/api/tree/master/packages/types

I hope @kianenigma can confirm or correct me here :)

If that doesn't work for you, there is an awesome list of resources that @danforbes curated, that could led you to other libraries or implementations of SCALE codecs https://github.com/polkadot-js/api/tree/master/packages/types

**Comment by kianenigma** [comment]
@sollover try printing the same things but add a `.toHuman` to them ;)

**Comment by sollover** [comment]
Thank You, solved 👍
