### ISSUE TITLE
contracts.instantiate 1010

### ISSUE THREAD

**Issue by LayNath242** [paritytech/subport#71]
when i deploy smart contract error 
contracts.instantiate 1010: Invalid Transaction: Transaction would exhaust the block limits

**Comment by NukeManDan** [comment]
Hey @LayNath242 😁 
I assume you are trying to use the `contracts` pallet? Are you working with `ink!`?
Can you provide the contract code you are trying to upload (a link to the repo where it is stored)?

**Comment by danforbes** [comment]
If you were using recent versions of Substrate and Polkadot{JS} Apps UI it's possible there was a recent change that will address this problem. Ref https://matrix.to/#/!tYUCYdSvSYPMjWNDDD:matrix.parity.io/$160927657914394Lsopj:matrix.parity.io?via=matrix.parity.io&via=matrix.org&via=corepaper.org

**Comment by LayNath242** [comment]
Thank you @NukeManDan i use flipper contract.

**Comment by NukeManDan** [comment]
@LayNath242 are you following this tutorial? https://substrate.dev/substrate-contracts-workshop/#/

And the error comes from interacting with your running node with this UI? https://paritytech.github.io/canvas-ui

**Comment by LayNath242** [comment]
Thank you @NukeManDan i use new Polkadot{Js} uiSo maby because of Polkadot{js} ui that @danforbes mention before.

**Comment by NukeManDan** [comment]
Ok - let us know if you get past this point @LayNath242, and if so we can close this issue

I encourage you to come ask more questions in the [matrix group for contracts and ink!](https://matrix.to/#/!tYUCYdSvSYPMjWNDDD:matrix.parity.io) 😀 as well as you continue to experiment!

**Comment by LayNath242** [comment]
Thank you very much it work now in Polkadot{js} ui it error because of gas limit.
