### ISSUE TITLE
websocket connection error 

### ISSUE THREAD

**Issue by sollover** [paritytech/subport#72]
hi everyone,

I'm trying connect to my polkadot node over rpc websocket pipe like this: 

`
const run = async() =>{

const { ApiPromise, WsProvider } = require('@polkadot/api')
 const wsProv = new WsProvider('ws://x.x.x.x:9944')
const api = await ApiPromise.create({ provider:wsProv })
const signedBlock = (await api.rpc.chain.getBlock()).toHuman()
console.log(signedBlock)
}

run()
`

but I got this error when I ran:

`2021-01-02 18:28:22          API-WS: disconnected from ws://x.x.x.x:9944: 1006:: connection failed
`

also I gave permission remote connections for my node

what should I do?

thank you

**Comment by Wangmmx** [comment]
I have also been encountering this error, how did you solve it? thank you!

**Comment by sollover** [comment]
Hi @Wangmmx I'm running with polkadot docker image, and I re-up it, with ` --ws-external  ` command.

you can use like this: 

docker run -d -p x.x.x.x:9944:9944 -p x.x.x.x:9933:9933 parity/polkadot --rpc-external --ws-external --rpc-cors '*' --pruning=archive
