### ISSUE TITLE
Cannot import Lunie Wallet using seed 

### ISSUE THREAD

**Issue by Cryptomainly** [paritytech/subport#75]
Complaint: Cannot import an original KSM address from Lunie extension/wallet to any new wallet as the generated address differs.  Lunie support cannot help.
Cause: Combination of seed phrase, derivation HD path and curve do not match original identity
Cure: Please can anyone help with the "Standard" HD Derivation Path for Kasuma and the Derivation path if it was done through Ledger?  🙏

**Comment by NukeManDan** [comment]
Sorry you are having issues @Cryptomainly ! I have not used the Lunie wallet, can you post a link to their software and ideally source code? In any case, I think the following can help. 

### Public Address Prefix

First, there may simply be an issue with the [network prefix](https://wiki.polkadot.network/docs/en/learn-accounts#for-the-curious-how-prefixes-work) that the wallet is using. **you can convert the _public keys_ in question with [this tool](https://wiki.polkadot.network/docs/en/learn-accounts#address-conversion-tools)**. It could be that the keys are being generated correctly, and just formatted differently for each wallet.

### Ledger

Specifically for the Ledger, the default path seems to be defined [here](https://github.com/Zondax/ledger-polkadot/blob/e749a7f19ca91fb147447980df47a9b42614d889/app/src/coin.h#L24-L26) as:
```
#define HDPATH_LEN_DEFAULT   5
#define HDPATH_0_DEFAULT     (0x80000000 | 0x2c)
#define HDPATH_1_DEFAULT     (0x80000000 | 0x162)       // 354
```

I have not inspected the code further, but it seems that BIP44 and SLIP44 (see references) imply that the path on the ledger for Polkadot is set correctly.

### Subkey

The best tool to try iterations on the paths to recover this is [subkey](https://substrate.dev/docs/en/knowledgebase/integrate/subkey).

**Note**: When generating new keys, the Polkadot.js App, Subkey, and Polkadot.js Extension by default will have _no derivation path_ (the root key). Signer will default to a path _based on the network you specify to use_ (`//polkadot` for Polkadot, and `//kusama` for Kusama). To recover an account to/from Signer, you must _set a custom derivation path_ specifically to nothing/empty.

Checkout this how-to [recover accounts from seeds on other tools](https://github.com/paritytech/parity-signer/blob/master/docs/tutorials/Recover-Account-Polkadotjs.md) as well, it should be useful. 

## Related Resources

- [Subscan Address Format Transformation (ss58 Accounts)](https://polkadot.subscan.io/tools/ss58_transform)
    - Convert a ss58 public key with any network prefix to all other networks
- [SLIP44 listings](https://github.com/satoshilabs/slips/blob/master/slip-0044.md)
    - Registered coin types for BIP-0044
- [BIP44 specification](https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki)
- [BIP32 specification](https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki)

**Comment by Cryptomainly** [comment]
Thank you very much for the detailed reply.  I was aware of the document regarding "create custom path" and leaving it blank in Signer but I still could not access my funds that were on my original Lumie wallet.  The Lumie wallet has now ceased.  I am stuck!

**Comment by NukeManDan** [comment]
@Cryptomainly Do you mean https://lunie.io ?

Have you looked at their guides: http://help.lunie.io/en/articles/4599473-how-to-migrate-your-polkadot-and-kusama-addresses

**Comment by laboon** [comment]
I'm talking with Lunie about this now. They said there's a derivation path issue and will post documentation on how to migrate soon.

**Comment by Cryptomainly** [comment]
> I'm talking with Lunie about this now. They said there's a derivation path issue and will post documentation on how to migrate soon.

Thank you for letting me know.... it is driving me mad.... would you mind posting a link here when you have one please?

Thanks everyone, very helpful responses indeed

**Comment by laboon** [comment]
http://help.lunie.io/en/articles/4599473-how-to-migrate-your-polkadot-and-kusama-addresses

**Comment by NukeManDan** [comment]
Thanks @laboon - @Cryptomainly reopen this issue if you can't get the support you need from that and the team there.
