### ISSUE TITLE
[Question] Charge fee from Smart Contract native balance for any execution instead of the account who submit transaciton

### ISSUE THREAD

**Issue by evgeny-s** [paritytech/subport#76]
Hello, here.
We use [substrate-node-template](https://github.com/substrate-developer-hub/substrate-node-template).
We have a specific business case for the Blockchain Network where we don't want to charge fees from the account who submit the transaction, but we want to charge fees from Smart Contract native balance. 
Could you please share if this doable and share some directions?
So we want to override this module: [transation-payment](https://github.com/paritytech/substrate/tree/master/frame/transaction-payment).
So the idea is the following:
* Add change [here](https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/src/lib.rs#L531)
* Extract Smart Contract from the `call` parameter
* Create an instance of `Self::AccountId`
* Substitute `who` with this new instance

Please share your thoughts, thanks!

**Comment by thiolliere** [comment]
In "fees" you also include the gas cost of the execution of the smart contract call ?

Also do you mean every call to a smart contract are payed by the smart contract or just specific ones ?

Maybe something doable can be to have another pallet with one dispatchable `call_as_from_contract`:
```
		pub fn call_as_from_contract(
			origin,
			dest: <T::Lookup as StaticLookup>::Source,
			#[compact] value: BalanceOf<T>,
			#[compact] gas_limit: Gas,
			data: Vec<u8>
		) -> DispatchResultWithPostInfo {
		// maybe check some logic here
			// call pallet_contract::Module::call(dest, dest value, gas_limit, data);
			// make dest pay for the fee or maybe only when call is successful
			// return Pays::No
		}
```
This would still require caller to pay  the fee, but he would be refund in some cases.

If you don't want caller to even pay for any fee, you should rather use ValidateUnsigned logic and have this extrinsic `call_as_from_contract` have no origin.

**Comment by evgeny-s** [comment]
Thanks for your reply, @thiolliere!!
Here some answers to your questions:
> In "fees" you also include the gas cost of the execution of the smart contract call?

Yes, we want all fees related to Smart Contract execution should be charged from the Smart Contract native balance, which we can deposit with some amount of native tokens.

> Also do you mean every call to a smart contract are payed by the smart contract or just specific ones?

For now, we need every call should be paid, of course, it doesn't include "read" calls like `balanceOf` for example.

> Maybe something doable can be to have another pallet with one dispatchable call_as_from_contract:

Where we can put this pallet?
From what we found, we can fork `transaction-payment` pallet and modify it. We also don't want the caller to pay the fee at all.

> If you don't want caller to even pay for any fee, you should rather use ValidateUnsigned logic and have this extrinsic call_as_from_contract have no origin.

Could you please add more details on this? Where should we use it and how? We're new in Rust and Substrate, so would be great to have more specifics.

-------------------------
What we have so far, in [this](https://github.com/paritytech/substrate/blob/master/frame/transaction-payment/src/lib.rs#L524) "validate" function we can do something like this:
```
fn validate(
		&self,
		who: &Self::AccountId, // We no longer need this parameter
		_call: &Self::Call,
		info: &DispatchInfoOf<Self::Call>,
		len: usize,
	) -> TransactionValidity {
		let data = [1, 2, 3, ...]; // We should take this byte array from _call somehow, because we have info about Smart Contract address there.
                let mut slice = &data[..];
                let new_who = &Self::AccountId::decode(&mut slice).unwrap();

		let (fee, _) = self.withdraw_fee(&new_who, info, len)?;
		Ok(ValidTransaction {
			priority: Self::get_priority(len, info, fee),
			..Default::default()
		})
	}
	```


Any help would be appreciated. 
Thanks again, @thiolliere!!

**Comment by thiolliere** [comment]
> Where we can put this pallet?
From what we found, we can fork transaction-payment pallet and modify it. We also don't want the caller to pay the fee at all.

just create a new pallet an insert it in your runtime, I guess when completing most tutorial on substrate you should be able to do this without much difficulty.

> Could you please add more details on this? Where should we use it and how? We're new in Rust and Substrate, so would be great to have more specifics.

Without changing transaction-payment you can do:
* if your transaction doesn't need any signature, then you should use unsigned transaction. But then you have really nothing, like no nonce for example. But you can provide your own unsigned validation and assert whatever signature in the call.

* or you can use signed transaction, and make the caller pay for the fees and refunded, the condition for refund is up to you

If you want to modify transaction-payment: then I guess you can make it aware of pallet_contracts. convert T::Call to pallet_contracts::Call using `IsSubType` trait. as runtime Call (i.e. `<T as frame_system::Config>::Call`) implement `IsSubType` for every pallets call. Once you have converted your call to pallet call you have the information you want.

I'm not sure I can say more without more understanding of the usecase.

**Comment by evgeny-s** [comment]
Hey, @thiolliere .
Thanks for all explanations.

Regarding the use case. 
We want to build a private blockchain that provides a possibility for applications to:
* Deploy Smart Contract which gives a possibility to issue assets and transfer assets (custom application tokens) between application Main Wallet (Smart Contract Owner) and application users wallets.
* We want application users don't care about any fees, so we want fees for all transactions sent from application user wallets to be charged from the Smart Contract address. Since we can specify the `endowment` parameter and send some native tokens to the Smart Contract, or we can even send some native tokens later to the Smart Contract address.

In other words:
* I am the application owner and I want to have internal application points (tokens/assets) let's say.
* I should be able to deploy Smart Contract to the network/blockchain, which we are building.
* I should be able to supply let's say 1M tokens for my application.
* Once the user finished some application task, I want to encourage my app users and send them 10 tokens, let's say. 
* Application users should be able to redeem some in-app items by spending earned tokens, but in order to do this, they should have some native tokens on their wallets. But we want to get rid of this requirement and we want Smart Contract to pay for any fees when the application user sends tokens back to the application's main wallet.

Is it clear enough?
Maybe you can suggest something else in terms of how we can approach it?

Thanks in advance!

**Comment by NukeManDan** [comment]
Hey all - is this still an open issue? If so, let's reopen it.
Thanks for the details, this well be good for the community to reference latter in any case 🙇🏼

**Comment by thiolliere** [comment]
Sorry I can't really find time to dive into it.

from:

> We want application users don't care about any fees, so we want fees for all transactions sent from application user wallets to be charged from the Smart Contract address. Since we can specify the endowment parameter and send some native tokens to the Smart Contract, or we can even send some native tokens later to the Smart Contract address.

So it seems only one contract interaction is free, so maybe a special case in transaction-payment pallet is the way to go.
You'll probably need to fork it to make it aware of contract and stuff like this.
But there can be other good implementation
