### ISSUE TITLE
MIME Type

### ISSUE THREAD

**Issue by olanod** [paritytech/subport#78]
I was thinking of creating an endpoint that "prepares" a blockchain transaction to be signed and thought it would be nicer if the endpoint returns a binary blob with a specific content type that my application or a different user specified application can open for the signature.  
It would be nice if the content type is not an arbitrary MIME type. `application/scale` for generic scale encoded types and `application/scale+my-custom-tx` for specific type of scale encoded data?

**Comment by NukeManDan** [comment]
Hey all - is this still an open issue? If so, let's reopen it.
Thanks for the details, this well be good for the community to reference latter in any case 🙇🏼
