### ISSUE TITLE
Contract never stops deploying

### ISSUE THREAD

**Issue by noahsalvadordenjo** [paritytech/subport#8]
Dear substrate,

I just added the contracts module, and it never stops sending.
Am I missing some flag in the startline?
Because blocks are being produced.
I start the node with cargo build --release -- --dev

**Comment by JoshOrndorff** [comment]
We need some more clarity on this.

If you added the contracts pallet, what did you add it to a node template? What do you mean by "it never stops sending"? What is it sending?

`cargo build --release -- --dev` is not what you should be running. Did you mean `cargo run --release -- --dev`
