### ISSUE TITLE
Supporting cosmos-like keypair and importing them in Substrate pallet

### ISSUE THREAD

**Issue by jimmychu0807** [paritytech/subport#80]
## Can we generate cosmos-like keypair (with subkey?) and importing them in Substrate pallet?

Moving the discussion from Element to here:

```
mnemonic: main kingdom matter topple sleep piece agent dawn island cactus cry trip soldier belt gaze card one spirit stay kingdom certain quote total chunk
hd path: m/44'/118'/0'/0/0
priv key hex: d275ef7cde3e71a2a9d5ff1284ce5180fe8f9281b132a8acacc0d14cf8ac9d98
pub key hex: 03288fe36bfc263c2121f4e2cc78908377b2da4ecff1e332d7493bd4ea59630ca5
```

maggie (@hammeWang)
> one more question, why do we need hd path here? From my knowledge, we only need to know the mnemonic or the private key with the KeyType, that is enough to generate an app specific key to sign the data.

vbstreetz
> basically, hd path allows creation of multiple private keys with the same mnemonic phrase. that's why in metamask, for example, you only need 1 mnemonic phrase to create as many accounts as possible.
>
> bip44
> here's handy tool to use https://iancoleman.io/bip39/
> for cosmos/tendermint/bluzelle will need to use this one https://github.com/iancoleman/bip39/pull/452 and ran it in your local machine

maggie
> This seems seperate to me. On cosmos side, we know the hdpath(unchange) and the mnemonic to derive the privatekey, and on the substrate offchain worker side, we need the private key, public key and keytype to insert the key into keystore for signing

vbstreetz
> yeah, so we are hoping to import this same mnemonic+hd path as an app subkey
i.e. https://substrate.dev/docs/en/knowledgebase/runtime/off-chain-workers#option-2-add-an-app-subkey-via-cli
an alternate import option is using subkey tool https://substrate.dev/docs/en/knowledgebase/integrate/subkey#inserting-keys-to-a-nodes-keystore
>
> btw, specifying the scheme doesn't work as well: --scheme Ecdsa
>
> ```
> subkey inspect "main kingdom matter topple sleep piece agent dawn island cactus cry trip soldier belt gaze card > one spirit stay kingdom certain quote total chunk//44'//118'//0'//0'//0" --scheme Ecdsa 
> ```

**Comment by vbstreetz** [comment]
I just realized the raw private key can be imported as well? so I think we can work with this for now:
```
➜ ~  subkey inspect 0xd275ef7cde3e71a2a9d5ff1284ce5180fe8f9281b132a8acacc0d14cf8ac9d98 --scheme Ecdsa
Secret Key URI `0xd275ef7cde3e71a2a9d5ff1284ce5180fe8f9281b132a8acacc0d14cf8ac9d98` is account:
  Secret seed:      0xd275ef7cde3e71a2a9d5ff1284ce5180fe8f9281b132a8acacc0d14cf8ac9d98
  Public key (hex): 0x03288fe36bfc263c2121f4e2cc78908377b2da4ecff1e332d7493bd4ea59630ca5
  Account ID:       0x0c1697aca4283154655359e055f7d02deda9f096ac9168866103ddb41486ddf5
  SS58 Address:     5CLZ9FnuDFA6n4H2tgub3G1dB3Kn5iMaG8m36SNa9R6H1gm6
```

Now the next problem we're having is signing, here's an example:

```
echo -n 85f5fb9cfe86b6db6eb957e0a6d6cbfcc32e971aa8d84ca352c49980c2408bbf | subkey verify 5333edae0432585087f7f21874ccd39deb68db2febc6028242d816c9f46d2dd61df8a453698086469af0ceea26361e9abeab9d7d4e471e0004578efd1fa422bf 5CLZ9FnuDFA6n4H2tgub3G1dB3Kn5iMaG8m36SNa9R6H1gm6 --scheme Ecdsa --hex

Error: SignatureInvalidLength { read: 64, expected: 65 }

```

Will share more info in a few...

**Comment by NukeManDan** [comment]
Any update here @jimmychu0807 @vbstreetz ? would be curious to know more 😁 but I think this repo is not meant to be a depository for feature requests... just triaging problems in development. 
If no update, let's close this issue 🙏🏼 - but where should we continue this kind of thing @jimmychu0807 ?
