### ISSUE TITLE
Block Reorgs running local Substrate devnet with three nodes

### ISSUE THREAD

**Issue by jimmychu0807** [paritytech/subport#81]
I am running on [this Substrate version](https://github.com/paritytech/substrate/tree/5215cd71aed415465e4d25926d426900a0b1f29a). After I compile a release version of Substrate, I run with three nodes as followed:

```bash
./substrate \
  --base-path /tmp/alice \
  --chain local \
  --alice \
  --port 30333 \
  --ws-port 9944 \
  --node-key 0000000000000000000000000000000000000000000000000000000000000001 \
  --validator

./substrate \
  --base-path /tmp/bob \
  --chain local \
  --bob \
  --port 30335 \
  --ws-port 9945 \
  --node-key 0000000000000000000000000000000000000000000000000000000000000002 \
  --validator

./substrate \
  --base-path /tmp/charlie \
  --chain local \
  --charlie \
  --port 30336 \
  --ws-port 9946 \
  --node-key 0000000000000000000000000000000000000000000000000000000000000003 \
  --validator
```

But all 3 nodes happen to have reorg (forking) frequently. This is [the console log for alice](https://gist.github.com/jimmychu0807/67ce340db624cda7012269931b01a06e) (search for the word `Reorg` in the log). Am I missing something on running multi-node substrate?

Would you know what's wrong? @danforbes @NukeManDan @kaichaosun @juniuszhou @hammeWang

Thank you 🙏

**Comment by danforbes** [comment]
It looks like maybe you are not specifying bootnodes.

**Comment by NukeManDan** [comment]
Hey I am testing Rococo locally (the [cumulus workshop](https://substrate.dev/cumulus-workshop/)) and seeing this behavior as well (reorgs). `--discover-local` is suggested, but it doesn't seem to matter as my nodes peer anyhow. AFAIK you do not need to set bootnodes. Who would be best to diagnose this?

**Comment by NukeManDan** [comment]
Andre and Basti helped on an internal chat: [This wiki](https://wiki.polkadot.network/docs/en/learn-consensus#multiple-validators-per-slot) on how BABE works suggest that this is indeed expected behavior.
> the frequency [of block reorgs] should be the same on your local network as polkadot/kusama
> every time there is a primary slot block there is potential for a re-org (since someone else authored using a secondary slot)

**Comment by jimmychu0807** [comment]
@NukeManDan Thanks for followup on this issue.
