### ISSUE TITLE
Scale Encode and Custom RPC error - JavaScript & Polkadot{JS}

### ISSUE THREAD

**Issue by RainFallsSilent** [paritytech/subport#82]
I am here again，I need help 😀

### What I want to do
first: Hash a task1( JavaScript Object), and send the task detail to substrate node by a transaction.
second: Create task2 (Rust struct) by details of task1 in the 'method' of substrate node.
third: Compare the first hash with the second hash

### Difficulties
Substrate uses 'scale encodes', but I don't know how to get Scale Encoded data of task1 by JavaScript.
From doc of Polkadot-JS,  I can only use task.encode() if the task is the result of the API call.
(https://polkadot.js.org/docs/api/start/types.basics)
But what can I do to get the Scale encoded data of task1( JavaScript Object) and let task1.hash be equal to task2.hash?

### I tried to add an RPC to encode the task but failed
the RPC is:
RPC in substrate pallet:
```rust
    fn encode_task(&self,
        n: u32,
        k: u32, 
        key_ype: Vec<u8>,
        nonce_hash: Vec<u8>) -> Result<Vec<u8>>;
```
RPC type in JavaScript for polkadot js api:
``` javascript
rpc: {
    encodeTask: {
      description: 'encode data',
      params: [
       {
          name: 'n',
          type: 'u32'
        },
        {
          name: 'k',
          type: 'u32'
        },
        {
          name: 'keyType',
          type: 'Vec<u8>'
        },
        {
          name: 'nonceHash',
          type: 'Vec<u8>'
        }
      ],
      type: 'Vec<u8>'
    }
} 
```
or
``` javascript
rpc: {
    encodeTask: {
      description: 'encode data',
      params: [
       {
          name: 'n',
          type: 'u32'
        },
        {
          name: 'k',
          type: 'u32'
        },
        {
          name: 'keyType',
          type: 'Bytes'
        },
        {
          name: 'nonceHash',
          type: 'Bytes'
        }
      ],
      type: 'Bytes'
    }
} 
```
the RPC is only succeeded by using 'curl', sample :
``` shell
curl http://localhost:9933 -H "Content-Type:application/json;charset=utf-8" -d '{"jsonrpc":"2.0","id":1,"method":"pallet_encodeTask","params": [3,2,[1,2,3],[4,5,6]]}'
```

when I use 'api.rpc', there will be some error: 
```
(node:14839) UnhandledPromiseRejectionWarning: Error: createType(Bytes):: Bytes: required length less than remainder, expected at least 1629468, found 3
```
or
```
(node:56526) UnhandledPromiseRejectionWarning: Error: createType(Vec<u8>):: Bytes length 504728836 exceeds 10485760
```
I want to call custom RPC by 'api.rpc',  but it is only succeeded by using 'curl'.(the port is different, default api port is 9944, the curl port is 9933)

### There is no good way to solve the problem, I need help

How can I use polkadot js api to get scale encoded data of task1?

**Comment by NukeManDan** [comment]
Can you clarify what specifically you mean by "task" and "submitting" that task?
Are you talking about [dispatching extrinsics](https://substrate.dev/docs/en/knowledgebase/getting-started/glossary#dispatch) via RPC calls or something else?

**Comment by RainFallsSilent** [comment]
@NukeManDan  
task1( JavaScript):
```javascript
const task1 = {
    n: n,
    k: k,
    keyType: testKeyType,
    nonceHash: testHash
}
// how to get scale data of task1 and get the task1_hash?
const task1_hash = ''; // todo get task1 hash
await api.query.pallet.sendTask(n, k, keyType, nonceHash, task1_hash);
```
"submitting" the task means call api.query.[pallet].[method] using details of task1, sample:
```rust
// pallet code
pub struct Task {
    pub n: u32,
    pub k: u32,
    pub key_type: Vec<u8>,
    pub nonce_hash: Vec<u8>,
}
...
// pallet mothod code
#[weight = 100]
pub fn send_task(
            origin,
            n: u32,
            k: u32,
            key_type: Vec<u8>,
            nonce_hash: Vec<u8>,
            task1_hash: Vec<u8>,
        ) -> dispatch::DispatchResult {
     let task = Task {
         n: n,
         k: k,
         key_type: key_type,
         nonce_hash: nonce_hash,
     }
     let task_data = task.encode();
     // this is the data of task2, i will hash it and compare with task1_hash.   
}
```

**Comment by RainFallsSilent** [comment]
@NukeManDan your second question, I wrote a simple example too.
task1( JavaScript):
```javascript
const task1 = {
    n: n,
    k: k,
    keyType: testKeyType,
    nonceHash: testHash
}
// how to get scale data of task1 and get the task1_hash?
// get the scale data by rpc
const task1_data = await api.rpc.pallet.encode_task(n, k, key_type, nonce_hash);
const task1_hash = hash(task1_data);
await api.query.pallet.sendTask(n, k, keyType, nonceHash, task1_hash);
```
"submitting" the task means call api.query.[pallet].[method] using details of task1, sample:
```rust
// pallet code
pub struct Task {
    pub n: u32,
    pub k: u32,
    pub key_type: Vec<u8>,
    pub nonce_hash: Vec<u8>,
}
...
// pallet rpc
pub fn send_task(
            n: u32,
            k: u32,
            key_type: Vec<u8>,
            nonce_hash: Vec<u8>,
        ) -> dispatch::DispatchResult {
     let task2 = Task {
         n: n,
         k: k,
         key_type: key_type,
         nonce_hash: nonce_hash,
     }
     let task2_data = task2.encode();
     return task2_data
}
```
The difficulity is that I can't get the scale data of task1 ( need be equal task2_data).

**Comment by NukeManDan** [comment]
@RainFallsSilent forgive my late reply here, is this still an issue? Please let me know how you remedied it for others searching if you solved it 🙏🏼 

I also wonder if you discovered these tools:
Community maintained API client: https://github.com/scs/substrate-api-client
Parity owned tx formation and submission: https://github.com/paritytech/substrate-subxt 

If you still need support, please reopen this issue! 😁
