### ISSUE TITLE
Howto inject custom development accounts to keyring

### ISSUE THREAD

**Issue by shamb0** [paritytech/subport#83]
Looking for some help in injecting extra accounts in addition to **"well-known development accounts"**

* Accounts injected via util script "substrate-enterprise-sample/scripts/src/init.js"
are not visible in frontend UI, for example accounts like "betty | clarice | daisy | francis "

![](https://i.imgur.com/CTCwZ6O.png)

![](https://i.imgur.com/N3iodqS.png)

* Observed env config option 'REACT_APP_DEVELOPMENT_KEYRING' part of "substrate-enterprise-sample/ui/src/config/index.js", Wondering is it possible to use this config option to 
inject the address.

```
// Accepting React env vars and aggregating them into `config` object.
const envVarNames = [
  'REACT_APP_PROVIDER_SOCKET',
  'REACT_APP_DEVELOPMENT_KEYRING'
];
```

* With Polkadot.js extn able to inject, but behaviour is not always consistent. sometimes address is not getting injected or listed via UI app

![](https://i.imgur.com/ew09NRC.png)

**Comment by NukeManDan** [comment]
@shamb0 - this issue has not been address, but (I hope) it is now stale. I am unclear on the root cause here, If you still want assistance please let me know here, we will repoen this issue and _promptly_ address it.
