### ISSUE TITLE
no link to the existing desktop wallet

### ISSUE THREAD

**Issue by dchmelik** [paritytech/subport#84]
Seems polkadot.network and this GitHub area don't link to the existing desktop (or other device) wallet, which if I recall correctly is an Electron program.  I need to install it again and am having an extremely difficult time finding it, which shouldn't be the case if someone is new to a cryptocurrency and just wants to find out how to use a desktop wallet.

**Comment by laboon** [comment]
There is a list of wallet software on the wiki - https://wiki.polkadot.network/docs/en/build-wallets

**Comment by al3mart** [comment]
Please @dchmelik let us know if the wallet you were talking about is in the list :)

**Comment by dchmelik** [comment]
It's not on any list on polkadot.network & github.com/paritytech/polkadot front pages which it should be like every other major cryptocurrency project, more than some of the other things that fewer people will look for (such as setup of an entire node when they haven't even seen how to run a wallet first.)  Not everyone will look at the wiki (thinking it's about more advanced stuff) rather than 'technology' or 'GitHub,' if there's not a list to a beginner/basic documentation page that goes to the wiki... and that's how the wiki seems.  Wallets aren't on it's front table of contents either rather than in development guide.  They should be in a _**USER GUIDE**_. The wiki link on github.com/paritytech/polkadot goes to a page that in Chrome/Chromium is a 404 reloading with a pop-up over & over until I have to kill Chromium, restart, and close that page before it happens again (opens in Firefox though.)  Your desktop wallet is on an obscure page on one of your projects here (I'd never have found it without help) and if I recall correctly is the JS one but isn't listed, in the wiki, as being desktop (which is probably why it took me much longer to try Polkadot.)  A percentage of people will end up thinking there isn't a Free/Libre/Opensource Software (FLOSS) one except for portable PCs they may not use for such things.  I only learned there is a desktop one by asking to your watercooler chat room and taking considerable time paying attention...

**Comment by Swader** [comment]
Thanks for letting us know, we've got plans to add a much simpler section to the wiki which should prevent such issues in the future.
