### ISSUE TITLE
How can I query a extrinsic only by txhash?

### ISSUE THREAD

**Issue by readygo586** [paritytech/subport#85]
In Ethereum, a submitted Transaction's detail information can be queried out by eth_getTransactionByHash method, I have not find similar RPC method in polka. 
However, in polkadot.subscan.io, I can easily find the transaction using just the txHash (https://polkadot.subscan.io/extrinsic/0x55fed9bea66baefc0481fdc29a29ee56c2203e972101b9c726e0c788d0564b79)

Any Idea on how I can implement such function?

**Comment by jacogr** [comment]
See https://wiki.polkadot.network/docs/en/build-protocol-info#unique-identifiers-for-extrinsics

**Comment by NukeManDan** [comment]
@readygo586 I was going to post the same link 😁 ☝🏼  Please reopen this if you need further clarifications!

And if you have not already, please join us in our [support channel on element](https://matrix.to/#/#substrate-technical:matrix.org) and/or the [Polkadot Discord](https://discord.gg/rWfUw2WRF7) to get further help as you get deeper into development with substrate 🥳

**Comment by readygo586** [comment]
thanks for the information.
