### ISSUE TITLE
Update validators' weights

### ISSUE THREAD

**Issue by Mar-Alex** [paritytech/subport#86]
Hello.
In our project, we are building a pallet that, among other things, has its own logic of validator updates. We’ve implemented `pallet_session::SessionManager` for our pallet and added a custom logic into `new_session`, so now it returns the list of validators according to our requirements. 
Both GRANDPA and BABE work with authorities and their weights (GRANDPA- https://github.com/paritytech/substrate/blob/master/frame/grandpa/src/lib.rs#L376 , BABE - https://github.com/paritytech/substrate/blob/master/frame/babe/src/lib.rs#L166 ), but according to the idea of NPoS all these weights are equal. Our pallet uses not a NPoS approach, so the voting powers (weights) of validators are important. `new_session` returns only the list of ValidatorId. 
How can I inform BABE and GRANDPA about the weights of chosen validators? 
Is it possible not to write directly to the storage fields they work with, but make it more universally, something like the implementation of `SessionManager`?

**Comment by andresilva** [comment]
We do have support for assigning different weights in BABE and GRANDPA, but currently the support ends there. As you said, in our NPoS implementation all validators are considered equal, therefore neither the `staking` or `session` modules support weights. If you are assigning weights to validators I am assuming that you are already using your own staking logic, therefore my suggestion would be to create your own session interface which passes along the weight information along with validator keys.

On another note, you will probably be the first user of weighted BABE and GRANDPA, so let us know if you find something wrong 😊.

**Comment by Mar-Alex** [comment]
Thanks a lot
