### ISSUE TITLE
Node with upgraded native runtime cannot connect to network due to difference in genesis block

### ISSUE THREAD

**Issue by parall4x** [paritytech/subport#87]
I'm running into the following issue.
* I've got a network running runtime spec_version 1.
* I build a new runtime version with spec_version 2.
* I perform a runtime upgrade to the network to version 2 of the runtime.
* I purge the chain on my local box
* I compile the new node, now with version 2.
* -- I purge the chain of the local node --
* Now, the local node cannot connect, because the genesis block is different from the of the network.

This problem does not occur when doing the following:
* Run network with spec version 1
* Run local node with spec version one. ( This generates the genesis block and puts it on the FS)
* Perform runtime upgrade to network
* Compile version 2
* Run local node with version 1. This connects without problems, as the chain is already setup.

I've done some digging, and I believe what's happening is that when there's no chain on the FS yet, the v2 runtime is put
in its genesis block. The line that does this is in chain_spec.rs (WASM_BINARY). However, when I replace this with a v1 runtime, the problem persists. It appears the genesis hash that is calculated use for comparison with the network does not take this into account.

I've come up with the following workaround.
* I have let v1 create  a genesis block. 
* I've put the resulting db on the FS in a tarball, which is published with the source code.
* I instruct the users to untar the tarbal to where substrate looks for the DB
* As far as subtrate is concerned, the correct genesis block is now present on the system
* Nodes now run fine, regardless of spec_version

See readme.MD on https://github.com/opentensor/subtensor

**Comment by al3mart** [comment]
I would say that in the first scenario you should provide the proper v2 chain_spec when running the node with `--chain`

**Comment by NukeManDan** [comment]
@parall4x is this still an issue? If so please reopen this one.
