### ISSUE TITLE
Ink! based ERC20 contract to use native token, not it's own. 

### ISSUE THREAD

**Issue by puffanddmx** [paritytech/subport#91]
After deploying erc20 using ink, when a new contract address is created, deposit the money used in the substrate mainnet there. For example, after depositing native 100 dots to the created contract address, what tranfer logic should be put in the ink contract to withdraw native 100 dots rather than erc20 from the contract address again?

**Comment by NukeManDan** [comment]
I think you may be misunderstanding the ERC20 standard: it is mean to be a completely isolated unit of account unto itself. There is no direct logic to convert between some other token and an arbitrary deployed ERC20. Thus you are trying to do something strange and likely wrong.

Please let me know if I am misunderstanding your problem and feel free to clarify.

**Comment by puffanddmx** [comment]
Thank you for answer. What I want to know is that when a contract is issued, it is usually used by depositing a certain amount to prevent it from becoming a tombstone address. I wanted to know if the contract could do the logic to re-withdraw the deposited amount which was in the contract address. The link below is erc20 transfer logic. Unlike this, I wanted to know how to withdraw the deposited amount to prevent it from becoming a tombstone address. Am I misunderstanding?


https://github.com/paritytech/ink/blob/master/examples/erc20/lib.rs#L437

**Comment by al3mart** [comment]
In the ink_env documentation you can see the [functions](https://paritytech.github.io/ink/ink_env/index.html#functions) available.
Indeed `[transfer](https://paritytech.github.io/ink/ink_env/fn.transfer.html)` function exists, but I am not certain if you would be able to reduce the contract balance to 0.
Anyway, you can find a lot of functions there that I guess can help you with you purpose

**Comment by puffanddmx** [comment]
Thank you for answer. I looked at the data you gave, but I saw that there is a transfer function inside. However, the transfer function used here is seen as an internal function used to send erc20 assets made in ink. For example, if you create a contract on Ethereum, you can deposit eth as well as erc20 in the contract. Conversely, withdrawals can also be done in both eth/erc20 contracts. In ink, the transfer function shown above can be used like erc20, but I want to know the transfer logic that sends native coins such as eth to a certain account in the ink contract.

**Comment by NukeManDan** [comment]
@puffanddmx can you join [the ink matrix channel](https://matrix.to/#/#ink:matrix.parity.org) to get further support? Assuming this is still an issue
