### ISSUE TITLE
Email Signup Form (the polkadot way)

### ISSUE THREAD

**Issue by unclehowell** [paritytech/subport#92]
Say we take a traditional email signup form on a website. 
How would that same concept work in the polkadot universe ?
Surely the website visitor wouldn't hand over any data to begin with. 
But instead the website visitor would grant the website a key in order to be able to signal them. 
Which the website visitor can invalidate/revoke at will.

**Comment by bkchr** [comment]
@danforbes I don't know a better place for this issue.

**Comment by NukeManDan** [comment]
@unclehowell If you are looking at how to do user account management & validation by using a ss58 keypair, this is possible but using the same keys to hold funds and manage accounts is (very) poor privacy and security practice, and not advisable.

As an example of what could be possible with the polkadot extension, [this blog](https://www.toptal.com/ethereum/one-click-login-flows-a-metamask-tutorial) shows a patter for metamask that could be used with the extention instead.
