### ISSUE TITLE
How to split inflation as 50% to validators and 50% to other accounts

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#95]
We have a scenario where we have to split inflation as 50% to validators and 50% to other accounts. We are exploring staking pallet but couldn't find a way to control flow of inflation. 

Can anyone help us to locate that code?

**Comment by shawntabrizi** [comment]
What does it mean to split inflation 50% to "other accounts"? Who specifically are the other accounts?

As for inflation:

* Inflation Curve is Defined here: https://github.com/paritytech/substrate/blob/master/frame/staking/src/inflation.rs
* Payout logic is here: https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L2333
* Ultimately, new tokens are minted here: https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L2452

**Comment by ayushmishra2005** [comment]
> What does it mean to split inflation 50% to "other accounts"? Who specifically are the other accounts?
> 
> As for inflation:
> 
> * Inflation Curve is Defined here: https://github.com/paritytech/substrate/blob/master/frame/staking/src/inflation.rs
> * Payout logic is here: https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L2333
> * Ultimately, new tokens are minted here: https://github.com/paritytech/substrate/blob/master/frame/staking/src/lib.rs#L2452

@shawntabrizi By other accounts, I mean some predefined accounts.

**Comment by shawntabrizi** [comment]
Seems like you will need to write your own pallet for such scenarios, it is not supported by staking pallet.
