### ISSUE TITLE
Unable transfer all balance from controller acount

### ISSUE THREAD

**Issue by yuzmemak** [paritytech/subport#96]
Dear Sirs,

I have no enough feedbacks from other platform. But I couldn't solve the issue even after analyze chain data.

I am migrating another projects with my servers for running validation nodes. I send all my dots from stash account without problem. But I am not able to send from controller account. I receive this yellow warning:

"There is an existing reference count on the sender account. As such the account cannot be reaped from the state."

Will told me that may be I need to change controller account of stash account.

When I check staking tab for my stash account. It was disappeared from staking tab. 

I just want to remind that this accounts were using for validation that's why there is key on the controller account as well. (could be reason?)

How can I remove this limitation from my controller account?

Best Regards

**Comment by kianenigma** [comment]
> "There is an existing reference count on the sender account. As such the account cannot be reaped from the state."

Have you called `withdraw_unbonded`, so you'd have no unlocking-chunck left? 

Please post these values for your controller: `Balances:Locks`, `Staking:Ledger`.

You can get both from the chain-state section under developer tab of the UI. 

<img width="1680" alt="Screenshot 2021-02-18 at 16 24 30" src="https://user-images.githubusercontent.com/5588131/108387745-ca567a00-7205-11eb-9fd1-7896328efd2f.png">

**Comment by yuzmemak** [comment]
Hi,

Thanks for your kidnly message. 

Balance locks output as follows:

balances.locks: Vec<BalanceLock>
[]

I think issue is not bound locking. What I suspect is validator key sign. Because this controller should be free from stash side as well. May be not.

Best Regards

**Comment by kianenigma** [comment]
and the `staking.ledger`? 

> I just want to remind that this accounts were using for validation that's why there is key on the controller account as well. (could be reason?)

You mean a session key? then you need to call `purge_keys` to remove it, and if you are still validating, then you just cannot withdraw everything out of that account yet.

**Comment by yuzmemak** [comment]
Hi again,

some how  staking.ledger: Option result is not seen on the previous message. Here is the output:

staking.ledger: Option<StakingLedger>
<none>

Best regards

**Comment by yuzmemak** [comment]
Hi,

Any news? Is there any development? Any clue how this dots stacked?

Best Regards

**Comment by thiolliere** [comment]
just to be sure you did call `purge_keys` with the controller account isn't it?
And you had a successful `purge_keys` call
(the image you sent show a failing one, maybe because you use the stash account)

**Comment by yuzmemak** [comment]
Hi,

Yes I call purge_keys with controller account which is not transfering all dots.

Pur_keys call failed. I do not see any clue on the failed action report.

**Comment by thiolliere** [comment]
the NoAssociatedValidator means there is no stash associated to the controller.
Thus the stash is probably correctly removed, and the controller has no ledger anymore.

My theory is that you need to call `purge_keys` before removing the stash/controller stuff.
If I'm correct you did unbond all stash funds, the stash/controller relation has been removed.
Thus `purge_keys` is failing.

So if I'm correct you need to bond the stash to the controller again, do `purge_keys` and then unbond + withdraw_unbonded later.

Maybe we can improve the process though by not allowing to remove stash/controller bonding while session still have keys.

**Comment by yuzmemak** [comment]
Hi,

I try to change controller of the stash account back. Last 5 minutes, I am waiting broadcasting. 

Recently, subscan and polkastats are down

When I check Polkascan, I do not see any new action.

Is there any cancellation method for this action? Or I need to wait broadcastin?

**Comment by thiolliere** [comment]
ah there is a runtime upgrade happening, I guess some nodes can be busy importing the block, should resolve soon I think

**Comment by yuzmemak** [comment]
Hi,

This kind of breaks needs to be mentioned to the users. They can think that chain is not working. If I have receive a message before submitting the action, I can trust the network. But after 5 minutes, still broadcasting, I can leave polkadot foreever.

I think you needs better UI designs such as ADA

**Comment by yuzmemak** [comment]
Another suprize! I need to wait unbounding time 24 days, to pay controller change fees. 

You may ask why, I have bound on this stash account. The reason is "validator lounge". To release controller account they suggest me bound stash account it self.

I don't know what you think you guys needs to make simple process. These are to Swiss.

After 24 days, I will change controller back to stash. Than I will try to release key.

Lets see, please keep this issue open. I will let you know.

**Comment by NukeManDan** [comment]
@yuzmemak sorry for your frustrating experience.
I think enough time has passed? Is this now resolved for you? 

Further DOT specific support you can get here: https://support.polkadot.network/support/home - please seek further support as needed there 🙏🏼 

As this is not a substrate specific issue, I am closing this one out.

**Comment by yuzmemak** [comment]
Hi,

Thanks for interest. Time is up. And I change controller, back to original one, as you guys advised.

I called "purge key" without error and my dots are free from controlling account. Before any other trap, I just transfer all of them to Exhange for swap with ADA, immediately. I don't want to see any more surprise from polkadot.

And bingo! another surprise on the stash account.

What I have now:

27 days passed and my dots still locked, there is no auto release by polkadot algo. There is a key symbol which I need to click to release my dots.

I did and another transaction fee (of course), lets pay to validator who is my exchange company, not poor miners. 

Surprise message says there is no enough balance to pay transaction fee. I have many dost which are locked and only 0.95 dots are free. Before pay fee, system checks live limit which is 1 dot. But there is no option to stop checking and pay this fee. Because I want to escape from hell.

Why there is no option to stop minimum live limit, when unlocking like transferring all dots?

**Comment by polkadotbabe** [comment]
Following all these steps, burning gas trying everything and anything, I have the same can't-reap problem on an old control account....  ...and a huge thanks to @Paradoxxx on discord for spending a lot of time trying to figure it out.

Will post in the dev part on discord and follow up here if I find a solution.

**Comment by yuzmemak** [comment]
> Following all these steps, burning gas trying everything and anything, I have the same can't-reap problem on an old control account.... ...and a huge thanks to @paradoxxx on discord for spending a lot of time trying to figure it out.
> 
> Will post in the dev part on discord and follow up here if I find a solution.

Hi,

They closed this post without my approvel. I think you need to open another subject. No body will follow here.

Enjoy!

**Comment by polkadotbabe** [comment]
On 2021-03-21 10:26, yuzmemak wrote:

I was able to post to it, I thought that meant it was open?

Were you ever able to withdraw down to zero/"reap" the account?

Thanks for responding, I appreciate it! :-)

--Anna

**Comment by thiolliere** [comment]
> 27 days passed and my dots still locked, there is no auto release by polkadot algo. There is a key symbol which I need to click to release my dots.
> 
> I did and another transaction fee (of course), lets pay to validator who is my exchange company, not poor miners.
> 
> Surprise message says there is no enough balance to pay transaction fee. I have many dost which are locked and only 0.95 dots are free. Before pay fee, system checks live limit which is 1 dot. But there is no option to stop checking and pay this fee. Because I want to escape from hell.

Indeed the controller account must send the transaction `withdraw_unbonded` to decrease or remove the lock on the stash.
The "many dost which are locked" are not part of the balance of the controller account, but on the stash account. Those are 2 different accounts (in your case).
If an account has 0.95 not locked dots and 0.1 locked dot in its balance, then it can pay for transaction with 0.05 fees.

> Why there is no option to stop minimum live limit, when unlocking like transferring all dots? After unlocking I will have many dots free.

After calling withdraw_unbonded your controller has no new dot. The only difference is that the lock in your stash account is decreased or removed.
In your case if we didn't enforce the controller to be kept alive when paying for fees. It would have die and 0.95 dot would have been burned.

**Comment by yuzmemak** [comment]
Hi,

I think main problem here is "**die**" verb. If you read all documents, you will se that "**may die**". 

In computer since there is **1 or 0**. There is no "**may**"

Controller account is useless; to keep a 1 dot in it useless. These are just 18th centuries bankers trick.

Just give me an option, I am ready to take **dying** risk. 

If there is a "**may**" in a blockchain, there would be a change that you may lose all assets.

Sorry, but I don't see any advantage in polkadot projects, nearby other POS projects. Just traps and tricks to increase staking APY.

**Comment by thiolliere** [comment]
> Controller account is useless; to keep a 1 dot in it useless.

well, the chain did prevent you from burning 0.95 dot of yours, because your controller would have died after paying the fee.
Not everybody does consider 1 dot as useless.
Prefering burning 0.95 dot in order to pay 0.05 fees is a bit unexpected to me.

> If there is a "may" in a blockchain, there would be a change that you may lose all assets.

this doesn't make any sense
