### ISSUE TITLE
Why do we need to mock duration starting at 0 in millisecond for timestamp inherent to implement instant seal

### ISSUE THREAD

**Issue by ayushmishra2005** [paritytech/subport#97]
hello,

I am trying to implement https://substrate.dev/recipes/kitchen-node.html#instant-seal-consensus. I was following https://github.com/paritytech/frontier/blob/master/template/node/src/service.rs for implementation steps.

I am not able to understand the purpose of below code:

```

/// Provide a mock duration starting at 0 in millisecond for timestamp inherent.
/// Each call will increment timestamp by slot_duration making block importer
/// think time has passed.
pub struct MockTimestampInherentDataProvider;

pub const INHERENT_IDENTIFIER: InherentIdentifier = *b"timstap0";

thread_local!(static TIMESTAMP: RefCell<u64> = RefCell::new(0));

impl ProvideInherentData for MockTimestampInherentDataProvider {
    fn inherent_identifier(&self) -> &'static InherentIdentifier {
        &INHERENT_IDENTIFIER
    }

    fn provide_inherent_data(&self, inherent_data: &mut InherentData) -> Result<(), sp_inherents::Error> {
        TIMESTAMP.with(|x| {
            *x.borrow_mut() += SLOT_DURATION;
            inherent_data.put_data(INHERENT_IDENTIFIER, &*x.borrow())
        })
    }

    fn error_to_string(&self, error: &[u8]) -> Option<String> {
        InherentError::try_from(&INHERENT_IDENTIFIER, error).map(|e| format!("{:?}", e))
    }
}

```
It is being used here https://github.com/paritytech/frontier/blob/master/template/node/src/service.rs#L105. 

Can someone please explain this?

**Comment by thiolliere** [comment]
I think the inherent data needs to be provided so that pallet-timestamp can work.

the time will increase the time by SLOT_DURATION so that pallet-babe can also work.
Pallet babe checks that the current time is valid in regards to the current slot (given through pre-runtime digest).

**Comment by NukeManDan** [comment]
(kinda) a duplicate #102 - let's continue the help there.
